### ISSUE TITLE
Problems about context ha and job jar manage

### ISSUE THREAD

**Issue by permanentstar** [spark-jobserver/spark-jobserver#1000]
Hi,
We use sjs in yarn cluster mode and I have two questions, thanks for any suggestion.
1. Is there any update for #353 ? I think the **context ha** is a very import feature.
2.Is it possible to save **main job jar** on hdfs instead of in jobDao like rmdb, so we can unify to manage all the user files in our metasystem?

**Comment by bsikander** [comment]
Both features are implemented. Closing.
