### ISSUE TITLE
Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient

### ISSUE THREAD

**Issue by ssmolen2018** [spark-jobserver/spark-jobserver#1002]
**Used Spark version**
2.2.0 (spark-2.2.0-bin-2.7.3.tgz) 
**Used Spark Job Server version**
jobServer-master 0.8.0

**Deployed mode**
localhost and docker

**Actual (wrong) behavior**
* When I run job-server locally using sbt, I can create multiple sql contexts, using the following command:
curl -i -d "" 'http://localhost:8090/contexts/sql-context-1?num-cpu-cores=2&memory-per-node=512M&context-factory=spark.jobserver.context.SessionContextFactory'
(different contexts names)

* When I run job-server in docker container, Im able to create just one context, creating second context is failing with the following error:
"status": "CONTEXT INIT ERROR",
  "result": {
    "errorClass": "java.lang.IllegalArgumentException",
    "cause": "java.lang.RuntimeException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient;",
    "stack": ["org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:106)", "org.apache.spark.sql.hive.HiveExternalCatalog.databaseExists(HiveExternalCatalog.scala:193)", "org.apache.spark.sql.internal.SharedState.externalCatalog$lzycompute(SharedState.scala:105)", "org.apache.spark.sql.internal.SharedState.externalCatalog(SharedState.scala:93)", "org.apache.spark.sql.hive.HiveSessionStateBuilder.externalCatalog(HiveSessionStateBuilder.scala:39)", "org.apache.spark.sql.hive.HiveSessionStateBuilder.catalog$lzycompute(HiveSessionStateBuilder.scala:54)", "org.apache.spark.sql.hive.HiveSessionStateBuilder.catalog(HiveSessionStateBuilder.scala:52)", "org.apache.spark.sql.hive.HiveSessionStateBuilder.catalog(HiveSessionStateBuilder.scala:35)", "org.apache.spark.sql.internal.BaseSessionStateBuilder.build(BaseSessionStateBuilder.scala:289)", "org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1050)", "org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:130)", "org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:130)", "scala.Option.getOrElse(Option.scala:121)", "org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:129)", "org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:126)", "org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:938)", "org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:938)", "scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)", "scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)", "scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)", "scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)", "scala.collection.mutable.HashMap.foreach(HashMap.scala:99)", "org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:938)", "spark.jobserver.context.SessionContextFactory.makeContext(SessionContextFactory.scala:30)", "spark.jobserver.context.SessionContextFactory.makeContext(SessionContextFactory.scala:17)", "spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:64)", "spark.jobserver.context.SessionContextFactory.makeContext(SessionContextFactory.scala:17)", "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:148)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)", "spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)", "spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)", "akka.actor.Actor$class.aroundReceive(Actor.scala:484)", "spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)", "akka.actor.ActorCell.invoke(ActorCell.scala:495)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)", "akka.dispatch.Mailbox.run(Mailbox.scala:224)", "akka.dispatch.Mailbox.exec(Mailbox.scala:234)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"],
    "causingClass": "org.apache.spark.sql.AnalysisException",
    "message": "Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':"
**Steps to reproduce**
Create one sql-context using context-factory=spark.jobserver.context.SessionContextFactory
When u try to create a second context, u receive mentioned above error.

**Comment by cubean** [comment]
+ 1 Same problem

**Comment by velvia** [comment]
Is the docker container running the same version?

Could it be that the docker container contains a different version of Spark?

**Comment by ssmolen2018** [comment]
Container is running Spark v 2.2.0 (spark-2.2.0-bin-2.7.3.tgz).

**Comment by ssmolen2018** [comment]
I switched to this image: codegerm/spark-jobserver and do not have this problem anymore. @velvia could you please build new image with Spark v 2.2.0 and jobServer-master 0.8.0 and upload it to the Docker hub? The latest version was uploaded 2 years ago and uses Spark v 1.6.1.

One more question, unrelated to this issue - could you please give examples of using Hive to get data?

**Comment by ssmolen2018** [comment]
Master branch does not have examples of using Hive.
