### ISSUE TITLE
SJS querying Hive

### ISSUE THREAD

**Issue by ssmolen2018** [spark-jobserver/spark-jobserver#1004]
**Used Spark version**
2.2.0
**Used Spark Job Server version**
0.8.1
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
client, local with local Hadoop/Hive and MySql metastore for Hive
**Actual (wrong) behavior**
SJS gives an error - "Invalid Job type for this context", when HiveContextFactory used to get list of Hive tables. It shows an empty list if SessionContextFactory is used to get list of Hive tables.
**Steps to reproduce**:
1. Create hive table using hive shell:
hive> create table ......
hive> show tables; <-- shows list of tables
Same using SJS:
1. Upload jar:
curl --data-binary @target/scala-2.11/job-server-extras_2.11-0.8.1-SNAPSHOT.jar localhost:8090/jars/hiveTest
2. Create HiveContext:
curl -i -d "" 'http://localhost:8090/contexts/sql?num-cpu-cores=2&memory-per-node=512M&context-factory=spark.jobserver.context.HiveContextFactory'
3. Get list of Hive tables:
curl -d "sql:\"show tables\"" "localhost:8090/jobs?appName=hiveTest&classPath=spark.jobserver.SessionTestJob&context=sql&sync=true"
Response:
{
"status": "ERROR",
"result": "Invalid job type for this context"
}
4. Create sql context:
curl -i -d "" 'http://localhost:8090/contexts/session-context?num-cpu-cores=2&memory-per-node=512M&context-factory=spark.jobserver.context.SessionContextFactory'

5. curl d "sql:\"show tables\"" "localhost:8090/jobs?appName=hiveTest&classPath=spark.jobserver.SessionTestJob&context=session-context&sync=true"
Im getting empty result, even though I have created tables in Hive.

I can query Hive from spark-shell>

**Comment by ssmolen2018** [comment]
Configuration issue - resolved.

**Comment by linsimiao** [comment]
i have a similar problem to yours. which configuration had you modified to resolve the problem? Thanks. @ssmolen2018
