### ISSUE TITLE
spark.jobserver.context.HiveContextFactory ClassNotFoundException

### ISSUE THREAD

**Issue by ssmolen2018** [spark-jobserver/spark-jobserver#1005]
**Used Spark version**
2.2.0
**Used Spark Job Server version**
0.8.1-SNAPSHOT ( latest from Master)
**Deployed mode**
local
**Actual (wrong) behavior**
running: curl -d "" '127.0.0.1:8090/contexts/hive-cntx?context-factory=spark.jobserver.context.HiveContextFactory' - getting exception:

**Steps to reproduce**
started SJS
build job-server-extras:  sbt job-server-extras/assembly
uploaded extras jar:
curl --data-binary @job-server-extras_2.11-0.8.1-SNAPSHOT.jar localhost:8090/jars/extras
run:
curl -d "" '127.0.0.1:8090/contexts/hive-cntx?context-factory=spark.jobserver.context.HiveContextFactory'

Received an exception:

{
  "status": "CONTEXT INIT ERROR",
  "result": {
    "message": "spark.jobserver.context.HiveContextFactory",
    "errorClass": "java.lang.ClassNotFoundException",
    "stack": "java.lang.ClassNotFoundException: spark.jobserver.context.HiveContextFactory\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:381)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:424)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\n\tat spark.jobserver.JobManagerActor.getContextFactory(JobManagerActor.scala:426)\n\tat spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:168)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)\n\tat spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)\n\tat spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)\n\tat akka.actor.Actor$class.aroundReceive(Actor.scala:484)\n\tat spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:495)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n

**Comment by ssmolen2018** [comment]
It appears that spark.jobserver.context.HiveContextFactory is deprecated as of SJS v 0.8.0. 
It would be nice if all examples related to the deprecated features are updated.

**Comment by ericraymond** [comment]
Is there a replacement for HiveContextFactory?

**Comment by ruVic101** [comment]
Hi,
I am getting the same error when I try to create a HiveContextFactory/ SQLContextFactory

  `curl -d "" 'localhost:8090/contexts/TestHiveContext?context-factory=spark.jobserver.context.HiveContextFactory'`

Error:
`{
  "status": "CONTEXT INIT ERROR",
  "result": {
    "message": "spark.jobserver.context.HiveContextFactory",
    "errorClass": "java.lang.ClassNotFoundException",
    "stack": "java.lang.ClassNotFoundException: spark.jobserver.context.HiveContextFactory\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:381)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:424)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\n\tat spark.jobserver.JobManagerActor.getContextFactory(JobManagerActor.scala:458)\n\tat spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:200)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)\n\tat spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)\n\tat spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)\n\tat akka.actor.Actor$class.aroundReceive(Actor.scala:484)\n\tat spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:495)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"
  }
}
`
Is there any other way to create HiveContextFactory? @velvia @noorul
