### ISSUE TITLE
GET /contexts/<contextname> does not work with context-per-jvm = true

### ISSUE THREAD

**Issue by pk-work** [spark-jobserver/spark-jobserver#1007]
**Used Spark version**
2.1.0

**Used Spark Job Server version**
current master branch

**Deployed mode**
Standalone with context-per-jvm set to true

**Actual (wrong) behavior**
Get 500 timeout when trying to get response from GET /contexts/<contextname>

**Steps to reproduce**
1. Start SJS with context-per-jvm = true
2. Create context
3. GET /contexts/<contextname>

**Logs**

{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/context-supervisor#1787303926]] after [10000 ms]. Sender[null] sent message of type \"spark.jobserver.ContextSupervisor$GetSparkWebUI\".",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": "akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/context-supervisor#1787303926]] after [10000 ms]. Sender[null] sent message of type \"spark.jobserver.ContextSupervisor$GetSparkWebUI\".\n\tat akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)\n\tat akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)\n\tat scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)\n\tat scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)\n\tat scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)\n\tat akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)\n\tat akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)\n\tat akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)\n\tat akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)\n\tat java.lang.Thread.run(Thread.java:808)\n"
  }
}

**Comment by velvia** [comment]
Thanks for PR. Will have a look.

**Comment by permanentstar** [comment]
@pk-work @velvia 
it should be a bug in current version
see #985 

@velvia 
by the way, can u have a look at #1000 ? Thanks.

**Comment by pk-work** [comment]
@velvia Thanks for merging.
