### ISSUE TITLE
Dependencies on PySpark not being picked up

### ISSUE THREAD

**Issue by dvaldivia** [spark-jobserver/spark-jobserver#1009]
I'm trying to use `dependent-jar-uris = ["file:///myjars/aws-java-sdk-1.7.4.jar", "file:///myjars/hadoop-aws-2.7.3.jar"]` but I'm still getting `java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found` as if the jars were not loaded at all.

I can see if the `py-context` is created, I can see them being loaded successfully
(the file location is valid in my local, I only used myjars for simplicity purpose)
I even see the artifacts in the spark environment

```
spark://192.168.1.140:61826/jars/aws-java-sdk-1.7.4.jar    Added By User
spark://192.168.1.140:61826/jars/hadoop-aws-2.7.3.jar    Added By User
```

any idea, what I could be doing wrong?

I'm submitting pyspark so I cannot go with the fat jar approach

**Used Spark version**
2.2.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
master head
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
spark stand alone
**Actual (wrong) behavior**
depdencies are not show or being used

**Comment by maharshibhavsar** [comment]
Hey, I'm facing the same issue, did you find any solutions?
