### ISSUE TITLE
BUG: all submitted apps are named as `spark.jobserver.JobManager` with yarn-cluster mode

### ISSUE THREAD

**Issue by zenglian** [spark-jobserver/spark-jobserver#1010]
When job server runs with cluster mode,  all submitted apps are named as `spark.jobserver.JobManager`.

<img width="646" alt="qq 20180124095929" src="https://user-images.githubusercontent.com/5268434/35310651-5cf9ac16-00ed-11e8-9245-0b4d22a253a1.png">

**Comment by velvia** [comment]
This should be an easy one for somebody to tackle.

**Comment by permanentstar** [comment]
I have noticed this too, can it be parameterized?

**Comment by zenglian** [comment]
@velvia Could you help to fix it?  I'm not familiar with scala.

**Comment by bsikander** [comment]
This issue was fixed in https://github.com/spark-jobserver/spark-jobserver/pull/1156 . Closing.
