### ISSUE TITLE
DELETE binaries does not work

### ISSUE THREAD

**Issue by ssmolen2018** [spark-jobserver/spark-jobserver#1012]
**Used Spark version**
2.2.1

**Used Spark Job Server version**
0.8.1-SNAPSHOT ( the latest from MASTER)

**Deployed mode**
local
with spark.jobserver.io.JobFileDAO

**Actual (wrong) behavior**
curl  localhost:8090/binaries <- shows all uploaded binaries
curl -X POST "localhost:8090/binaries/preview?_method=DELETE" <- - used to delete binary called 'preview'
Receive response = 'OK'

curl  localhost:8090/binaries <-- binary 'preview' is still there

**Steps to reproduce**
See above

**Comment by bsikander** [comment]
Why are you using FileDAO? It is deprecated and has performance + memory issues. Use SqlDao.

**Comment by noorul** [comment]
@ssmolen2018 Are you successful with SqlDao? Can we close this issue?

**Comment by aceteam-dfs** [comment]
It does work with SQLDao.
