### ISSUE TITLE
Setup in eclipse

### ISSUE THREAD

**Issue by dynastykaiserlord123** [spark-jobserver/spark-jobserver#1016]
**Used Spark version**

**Used Spark Job Server version**
(Released version, git branch or docker image version)

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)

**Actual (wrong) behavior**

**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).
Is there a setup guide for this project?

**Comment by bsikander** [comment]
You need to do the following steps to setup SJS in eclipse
- Install scala perspective in your eclipse
- Install sbt
- Add `addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.1.0")` to this file ->`~/.sbt/0.13/plugins/plugins.sbt`
- Add `transitiveClassifiers in Global := Seq(Artifact.SourceClassifier, Artifact.DocClassifier)` in `~/.sbt/0.13/global.sbt`
- Download latest SJS and in the root folder of SJS execute `sbt 'eclipse execution-environment=JavaSE-1.8'`, this will create .project and .classpath files
- Open eclipse and import SJS.
- Sometimes you need to change the version of scala inside eclipse to avoid errors. If you see errors after import, select all the SJS projects -> right click -> Scala -> Set scala installation -> select version.

**Comment by hntd187** [comment]
Or you could just use intelliJ, it doesn't need all this setup.
