### ISSUE TITLE
CONTEXT INIT ERROR setting up SQL context

### ISSUE THREAD

**Issue by calebcrawdad110** [spark-jobserver/spark-jobserver#1017]
I am trying to create an SQL context using SJS running in development mode via SBT (macOS 10.13 with sbt@0.13.16 installed via Homebrew).  I followed the instructions on the [Contexts](https://github.com/spark-jobserver/spark-jobserver/blob/v0.8.0/doc/contexts.md) page but am receiving a `CONTEXT INIT ERROR`. I realize this is covered in the Troubleshooting guide but that did not help me.

I have no experience with Scala so I am sure I am missing an obvious step but I haven't been able to figure it out for some time now. I found a few related issues but could not glean a clear answer from them ([example](https://github.com/spark-jobserver/spark-jobserver/issues/562#issuecomment-238531626), [example 2](https://github.com/spark-jobserver/spark-jobserver/issues/499), [example 3](https://stackoverflow.com/a/35803957/378638)). 

Can you please let me know what step I'm missing? Thank you very much.

**Used Spark Job Server version**
v0.8.0

**Deployed mode**
Development mode (sbt)

**Actual (wrong) behavior**
CONTEXT INIT ERROR trying to create SQLContext

**Steps to reproduce**

*1. Clone SJS version 0.8.0:*
$ git clone https://github.com/spark-jobserver/spark-jobserver.git
$ cd spark-jobserver
$ git checkout v0.8.0

*2. Run server in development mode:*
$ sbt
\> project job-server-extras
\> reStart

*3. Attempt to create SQL context*
My attempt to create SQL context [using curl as described in the docs](https://github.com/spark-jobserver/spark-jobserver/blob/v0.8.0/doc/contexts.md) fails even though I followed [the troubleshooting guide](https://github.com/spark-jobserver/spark-jobserver/blob/v0.8.0/doc/troubleshooting.md#javalangclassnotfoundexception-when-staring-spark-jobserver-from-sbt):
```
$ curl -d "" '127.0.0.1:8090/contexts/sql-context?context-factory=spark.jobserver.context.SQLContextFactory'
{
  "status": "CONTEXT INIT ERROR",
  "result": {
    "message": "spark.jobserver.context.SQLContextFactory",
    "errorClass": "java.lang.ClassNotFoundException",
    "stack": "java.lang.ClassNotFoundException: spark.jobserver.context.SQLContextFactory\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:381)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:424)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\n\tat spark.jobserver.JobManagerActor.getContextFactory(JobManagerActor.scala:426)\n\tat spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:168)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)\n\tat spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)\n\tat spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)\n\tat akka.actor.Actor$class.aroundReceive(Actor.scala:484)\n\tat spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:495)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"
  }
}
```

**Logs**

[SBT logs](https://github.com/spark-jobserver/spark-jobserver/files/1688159/sbt.txt)
[job-server-local.log](https://github.com/spark-jobserver/spark-jobserver/files/1688165/job-server-local.log)

**Comment by calebcrawdad110** [comment]
Quick update: I tried the exact same steps above, but checked out the `v0.7.0` branch instead, and it worked. I am still looking for help with `v0.8.0` but I thought this was worth mentioning.

**Comment by linsimiao** [comment]
have u worked rightly with `v0.8.0`? I red through the page you mentioned, and I did create the right session. However, when I tried to run the class that extends `JSessionJob<Row[]>`, a `java.lang.ClassCastException` was thrown with msg `<my-calz-name>cannot be cast to spark.jobserver.api.SparkJobBase`
