### ISSUE TITLE
sbt package .  get below error, can anyone give some hints?

### ISSUE THREAD

**Issue by xiaods** [spark-jobserver/spark-jobserver#102]
```bash
[info] Packaging /Users/xiaods/Downloads/spark-jobserver-0.5.0/job-server/target/job-server-0.5.0.jar ...
[info] Done packaging.
[success] Total time: 364 s, completed 2015-3-23 14:58:35
[error] Expected letter
[error] Expected symbol
[error] Expected '!'
[error] Expected '+'
[error] Expected '++'
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected ';'
[error] Expected end of input.
[error] Expected '--'
[error] Expected 'show'
[error] Expected 'all'
[error] Expected '*'
[error] Expected '{'
[error] Expected project ID
[error] Expected configuration
[error] Expected key
[error] Expected '-'
[error] .
[error] ^
```

**Comment by velvia** [comment]
Are you sure you didn't feed in extra input to STDIN while running the
command?

On Mon, Mar 23, 2015 at 12:02 AM, Deshi Xiao <notifications@github.com>
wrote:

> [info] Packaging
> /Users/xiaods/Downloads/spark-jobserver-0.5.0/job-server/target/job-server-0.5.0.jar
> ...
> [info] Done packaging.
> [success] Total time: 364 s, completed 2015-3-23 14:58:35
> [error] Expected letter
> [error] Expected symbol
> [error] Expected '!'
> [error] Expected '+'
> [error] Expected '++'
> [error] Expected 'debug'
> [error] Expected 'info'
> [error] Expected 'warn'
> [error] Expected 'error'
> [error] Expected ';'
> [error] Expected end of input.
> [error] Expected '--'
> [error] Expected 'show'
> [error] Expected 'all'
> [error] Expected '*'
> [error] Expected '{'
> [error] Expected project ID
> [error] Expected configuration
> [error] Expected key
> [error] Expected '-'
> [error] .
> [error] ^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/102>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by sayden** [comment]
I had this same problem and, as @velvia pointed, it was because I was running `sbt about .` (with a trailing period). 

Just using `sbt about` or `sbt [command]` solved the problem for me
