### ISSUE TITLE
Forever RUNNING tasks after job server restarting

### ISSUE THREAD

**Issue by iatsukanov** [spark-jobserver/spark-jobserver#1023]
**Used Spark version** 2.2.0

**Used Spark Job Server version** v0.8.0 

**Deployed mode** Spark Standalone

**Actual (wrong) behavior**
If we
1. run a long task 
2. while it is RUNNING we stop job-server
3. start job-server

the task will be forever RUNNING.

**Steps to reproduce**
1. run a long task 
2. stop job-server
3. start job-server

**Comment by noorul** [comment]
I think https://github.com/spark-jobserver/spark-jobserver/commit/65a80c733a9e14b8db52e8226d282681b5c8e02d might have fixed this issue. Can you try master?

**Comment by bsikander** [comment]
Yes, the change mentioned by noorul is correct. You should enable it in your config and it should kill the long running task.

**Comment by iatsukanov** [comment]
https://github.com/spark-jobserver/spark-jobserver/commit/65a80c733a9e14b8db52e8226d282681b5c8e02d doesn't solve the problem. Logic from this commit stops context if the master/supervisor actor is not reachable.

My problem - tasks that have RUNNING status after job-server was started.

For example:
1. we have a started job-severer with context-per-jvm = true and https://github.com/spark-jobserver/spark-jobserver/commit/65a80c733a9e14b8db52e8226d282681b5c8e02d
2. then we start a long task
3. then we do "kill -9" for both processes: job-server and forked process with spark context
4. JobManagerActor will not have time to catch that context-supervisor was Terminated. JobStatusActor will not have time to do postStop() and mark the job with "Context  ... for this job was terminated"

So, after we start job-server again we will have the RUNNING job and it will never be finished.

Instead of "kill -9" we can experience:
1. oom killer
2. if we use job-server inside a container we can stop the container immediately without waiting until job-server finishes writing "Context  ... for this job was terminated"
3. electricity on a server can be turned off
4. etc

In my opinion, job-server needs logic that will search RUNNING tasks after launching and mark them stopped with a special status/message.

**Comment by bsikander** [comment]
Well, yes, it you use kill -9 to immediately kill both master and Driver then the state will not be changed in DB. On startup, currently, SJS master won't check the DB to change the status to UNKNOWN or something similar.

**Comment by iatsukanov** [comment]
Do you plan to fix it in the near future?

If not what do you think if I will try to make a pull request? (maybe you think that job-server doesn't need this logic at all)

**Comment by noorul** [comment]
PRs are most welcome

**Comment by bsikander** [comment]
It would be good if we can handle this corner case also. So, PRs are welcome as noorul mentioned.

**Comment by zenglian** [comment]
I think you should not kill it, but after restarting, SJS should be able to show it's running.

**Comment by bsikander** [comment]
This issue should be fixed after [this](https://github.com/spark-jobserver/spark-jobserver/pull/1047). At SJS startup, RUNNING contexts/jobs are cleaned up. Please reopen if you think that problem still exists.
