### ISSUE TITLE
Java example

### ISSUE THREAD

**Issue by sakinapitalwala** [spark-jobserver/spark-jobserver#1024]
**Used Spark version**
2.2.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
Latest using Maven dependency 
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
client

Issue
We are trying to use the SparkSessionBuilder with java and trying to run the job
**following is the code**

public class PamAggregatorNew implements SparkSessionJob   {
	
	public static void main (String[] args){
		SparkSession sparkSession = SparkSession
				.builder()
				.appName("PamPreprocessor")
				.config("spark.master","local")
				//.config("spark.cassandra.connection.host", "127.0.0.1")
				//.config("spark.cassandra.connection.port", "9042")
				.getOrCreate();
        
        Config config=ConfigFactory.parseString("");
        JobEnvironment r=null;
        //String str=args[0]+","+args[1];
        PamAggregatorNew sp=new PamAggregatorNew();
        Object ret= sp.runJob(sparkSession,r,"abc,afsdf");
        
   
	}
	 public Object runJob(SparkSession sparkSession, JobEnvironment runtime, Object data) {
		 String s1=(String) data;
		 s1="asdasdasdlkaslkd";
		 List<Character> sp1=createLabeledPoints(s1);
		 JavaSparkContext j=JavaSparkContext.fromSparkContext(sparkSession.sparkContext());
		 return j.parallelize(sp1).countByValue();;
	       
	    }
	public Object runJob(Object arg0, JobEnvironment arg1, Object arg2) {
		// TODO Auto-generated method stub
		return null;
	}
	public Or<Object, Every<ValidationProblem>> validate(Object arg0, JobEnvironment arg1, Config arg2) {
		// TODO Auto-generated method stub
		return null;
	}
	public Object runJob(SparkSessionContextLikeWrapper arg0, JobEnvironment arg1, Object arg2) {
		// TODO Auto-generated method stub
		return null;
	}
	public Or<Object, Every<ValidationProblem>> validate(SparkSession arg0, JobEnvironment arg1, Config arg2) {
		// TODO Auto-generated method stub
		return null;
	}
	public Or<Object, Every<ValidationProblem>> validate(SparkSessionContextLikeWrapper arg0, JobEnvironment arg1,
			Config arg2) {
		// TODO Auto-generated method stub
		return null;
	}
	public List<Character> createLabeledPoints(String records) {
	    List<Character> points=new ArrayList<>();
	    for(int i = 0, n = records.length() ; i < n ; i++) { 
	    	Character c = records.charAt(i); 
	        points.add(c);
	    }
	    return points;
	}
}

we are getting this following **error while running the job on the server**

"status": "ERROR",
  "result": {
    "message": "scala.MatchError: null",
    "errorClass": "java.lang.RuntimeException",
    "stack": "java.lang.RuntimeException: scala.MatchError: null\n\tat spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:376)\n\tat scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)\n\tat scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
  }
}

**Comment by noorul** [comment]
Look at https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server-tests/src/main/java/spark/jobserver/JavaHelloWorldJob.java

**Comment by zenglian** [comment]
Do not forget to mention that java job must use contextfactory.
