### ISSUE TITLE
sbt test error akka.pattern.AskTimeoutException: Timed out

### ISSUE THREAD

**Issue by noorul** [spark-jobserver/spark-jobserver#103]
I am using 0.4.1 and I get this error when I run "sbt test"

[info] JobManagerActorAdHocSpec:
[info] error conditions 
[info] - should return errors if appName does not match
[info] - should return error message if classPath does not match *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class spark.jobserver.JobManagerActor$Initialized
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:412)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass(TestKit.scala:399)
[info]   at akka.testkit.TestKit.expectMsgClass(TestKit.scala:707)
[info]   at spark.jobserver.JobManagerSpec$$anonfun$2$$anonfun$apply$mcV$sp$7.apply$mcV$sp(JobManagerSpec.scala:76)
[info]   at spark.jobserver.JobManagerSpec$$anonfun$2$$anonfun$apply$mcV$sp$7.apply(JobManagerSpec.scala:73)
[info]   at spark.jobserver.JobManagerSpec$$anonfun$2$$anonfun$apply$mcV$sp$7.apply(JobManagerSpec.scala:73)
[info]   at org.scalatest.FunSpec$$anon$1.apply(FunSpec.scala:1600)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
[info]   at spark.jobserver.JobManagerSpec.withFixture(JobManagerSpec.scala:36)
[info]   ...
[info] Exception encountered when attempting to run suite spark.jobserver.JobManagerActorAdHocSpec: Timed out *** ABORTED ***
[info]   akka.pattern.AskTimeoutException: Timed out
[info]   at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
[info]   at akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
[info]   at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
[info]   at java.lang.Thread.run(Thread.java:745)
[info]   ...
[info] LocalContextSupervisorSpec:
[info] context management 
[info] - should list empty contexts at startup
[info] - can add contexts from jobConfig *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected List(olap-demo), found ArrayBuffer()
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:328)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:314)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:707)
[info]   at spark.jobserver.LocalContextSupervisorSpec$$anonfun$3$$anonfun$apply$mcV$sp$2.apply$mcV$sp(LocalContextSupervisorSpec.scala:77)
[info]   at spark.jobserver.LocalContextSupervisorSpec$$anonfun$3$$anonfun$apply$mcV$sp$2.apply(LocalContextSupervisorSpec.scala:73)
[info]   at spark.jobserver.LocalContextSupervisorSpec$$anonfun$3$$anonfun$apply$mcV$sp$2.apply(LocalContextSupervisorSpec.scala:73)
[info]   at org.scalatest.FunSpec$$anon$1.apply(FunSpec.scala:1600)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
[info]   at spark.jobserver.LocalContextSupervisorSpec.withFixture(LocalContextSupervisorSpec.scala:41)
[info]   ...
[info] Exception encountered when attempting to run suite spark.jobserver.LocalContextSupervisorSpec: Timed out *** ABORTED ***
[info]   akka.pattern.AskTimeoutException: Timed out
[info]   at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
[info]   at akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
[info]   at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
[info]   at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)
[info]   at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
[info]   at java.lang.Thread.run(Thread.java:745)
[info]   ...
[error] Failed: Total 81, Failed 6, Errors 0, Passed 75
[error] Failed tests:
[error] 	spark.jobserver.JobManagerActorAdHocSpec
[error] 	spark.jobserver.JobManagerActorSpec
[error] 	spark.jobserver.LocalContextSupervisorSpec
[error] (job-server/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 162 s, completed 24 Mar, 2015 11:47:08 AM

**Comment by noorul** [comment]
Some more information about the environment. I am using Mac OS X. This worked yesterday but today it is not. I don't remember changing anything. Even if I remove everything, extract from the tar ball and repeat everything. The tar ball used is https://github.com/spark-jobserver/spark-jobserver/archive/v0.4.1.tar.gz

**Comment by zeitos** [comment]
@noorul should we close this one?

**Comment by noorul** [comment]
Closing!
