### ISSUE TITLE
AkkaClusterSupervisor test failing randomly

### ISSUE THREAD

**Issue by bsikander** [spark-jobserver/spark-jobserver#1030]
**Actual (wrong) behavior**
In the testcase, I was expecting a `ContextInitialized` message but I was receiving `ContextAlreadyExists`. The reason is that when you stop a JobManagerActor, you receive `Terminated` message back and in the code of this message we remove the context from hashmap. 

So in my case, it happened that Terminated event was not processed fully and the next testcase was triggered which also created an actor with same name, which causes `ContextAlreadyExists`.

I will push the fix shortly. There are 2 options:
1- Add 1s sleep after receiving the Terminated event.
2- Don't use the same name again in the testcase.

Option#2 seems better.

**Comment by bsikander** [comment]
@all,
Actually, it seems that the behavior of AkkaClusterSupervisor is wrong. Testcase seems to be correct.

When `StopContext` is called for a context, `StopContext` is sent back to the user and if the user tries to create the same context again, he gets a `ContextAlreadyExists`. This behavior is incorrect.

I think the hashmap should be cleared within `StopContext` message.

**Comment by velvia** [comment]
Behroz, you are probably right.

**Comment by bsikander** [comment]
I have created a temporary fix to make the master branch testcases stable.
https://github.com/spark-jobserver/spark-jobserver/pull/1032/files

I will do the proper fix in an upcoming change.

**Comment by bsikander** [comment]
Closing this issue for now.
