### ISSUE TITLE
could not call curl -d "input.string = a b c a b see" "localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample&context=test-context&sync=true"

### ISSUE THREAD

**Issue by I348773** [spark-jobserver/spark-jobserver#1035]
After I start the server and then run command as below:
curl localhost:8090/contexts/test-context  this links is ok, the result is 
{
  "context": "test-context",
  "applicationId": "local-1519962820517"
}

However when I run this command:
curl -d "input.string = a b c a b see" "localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample&context=test-context&sync=true"
The result says that:
{
  "status": "ERROR",
  "result": "appName test not found"
}

Do you know why?

**Comment by I348773** [comment]
Yes, I see the install dir has already had spark-job-server.jar, I just use this as the sample to test.
So how I do like this?

**Comment by linsimiao** [comment]
your appName should be the dir name that you have installed, but not alway `test`.
