### ISSUE TITLE
Question: is the jobserver compatible with PostgreSQL ?

### ISSUE THREAD

**Issue by nibbio84** [spark-jobserver/spark-jobserver#104]
I have read about compatibility with H2 and MySQL and I know that it uses Slick under the hood as data access layer but... has it been tested with a PostgreSQL database ?

Do you foresee any issue with PostgreSQL ?

**Comment by velvia** [comment]
I don't foresee any issues, but just haven't had time to test it out.

-Evan

On Fri, Mar 27, 2015 at 10:12 AM, Nicola Ferraro <notifications@github.com>
wrote:

> I have read about compatibility with H2 and MySQL and I know that it uses
> Slick under the hood as data access layer but... has it been tested with a
> PostgreSQL database ?
>
> Do you foresee any issue with PostgreSQL ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/104>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
@nibbio84 Try it out now on master.  There are definitely people using it with MySQL, PostGres should work too.  Some changes have been merged to make this possible and easier.  We are lacking directions, but you should be able to change the configuration of SJS to make this work.
