### ISSUE TITLE
Restart of Jobserver

### ISSUE THREAD

**Issue by bsikander** [spark-jobserver/spark-jobserver#1040]
Currently, if we restart the jobserver, it loses all the connections to the context JVMs and there is no way to connect to them. We believe that with the following changes in jobserver, we can achieve basic restart of Jobserver and jobs.
 
1- Persistence of Context in DB
2- Removal of in-memory data structures from master
3- Reconnection to context JVMs if Jobserver restarts (https://github.com/spark-jobserver/spark-jobserver/issues/353)
4- Restart of context JVMs through supervise mode
 
Since these changes will be done in multiple steps, this issue is an initial announcement of upcoming changes.

**Used Spark version**
2.2.1

**Comment by zenglian** [comment]
Pls provide a rest API for restarting a job by the way.

**Comment by thoHeinze** [comment]
@zenglian  What is your scenario? We will enable the Spark supervise mode, there will be no need  to manually restart the job.

**Comment by thoHeinze** [comment]
@bsikander can you please update this issue? Most of the work is done imho.

**Comment by bsikander** [comment]
@thoHeinze yes, all the tasks are done.
