### ISSUE TITLE
HeapSpace while running performance test

### ISSUE THREAD

**Issue by diegocolombo** [spark-jobserver/spark-jobserver#1042]
**Used Spark version**
2.2.1

**Used Spark Job Server version**
0.8.0

**Deployed mode**
cluster

**Actual (wrong) behavior**
Scenario:
- A performance test of 500 request for 12 minutes, over a job that returns a payload of 3.4Mb each
- After each request, the jobserver memory consume grows, and looks like the GC is not happening, causing a HeapSpace issue

Here is the memory consume during the execution of the test:
![screenshot from 2018-03-07 09-17-42](https://user-images.githubusercontent.com/16367212/37092947-65a28fca-21ec-11e8-9a63-a4eb7d8ad5e1.png)

**Comment by bsikander** [comment]
Umm interesting. We have seen this behavior with FileSqlDao. Are you using SqlDao?

**Comment by bsikander** [comment]
Maybe generate a heap dump and analyze which class/object is the culprit.

Following was helpful for me.
You can use the following command to generate the dump of a running JVM.
`<Your java installation>/java/bin/jcmd <pid> GC.heap_dump /tmp/dump`

Maybe use the following tool to analyze
https://www.eclipse.org/mat/

**Comment by velvia** [comment]
I also highly suggest using SJK
https://github.com/aragozin/jvm-tools

**Comment by diegocolombo** [comment]
@bsikander yes, I'm using the follow config:
`jobdao = spark.jobserver.io.JobSqlDAO`

@velvia I'm going to have a look at this tool

**Comment by thoHeinze** [comment]
@diegocolombo  Which mode of the jobserver are using? Did you set `context-per-jvm=true` ?

**Comment by thoHeinze** [comment]
@diegocolombo  Do I understand your initial description correctly, that your job creates responses of 3.4 MB each?

**Comment by diegocolombo** [comment]
@thoHeinze Yes, you did. It does a query based on the given parameter and returns the dataframe as a json:
`df.toJSON.collect().mkString("[", ",", "]")`

**Comment by thoHeinze** [comment]
@diegocolombo Ok, so your results are no surprise. The jobserver caches internally all job results in a cache. Per default it will keep up to 5000 results https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/resources/application.conf#L20
You might want to reduce this number for your scenario.

**Comment by diegocolombo** [comment]
@thoHeinze Worked as a charm! Thank you.
