### ISSUE TITLE
Why do we need application.conf and local.conf and dev.conf?

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#1049]
**Used Spark version**
3.2.1-SNAPSHOT

**Used Spark Job Server version**
tip of 0.8.1-SNAPSHOT

**Deployed mode**
Spark Standalone

I'm very confused by all the different .conf files.
I thought there was only one local.conf file that would have all the settings, but I often find that if I do not also change the same settings in application.conf, there is no effect.

The README also refers to dev.conf. Is that the same as local.conf? There is no file called dev.conf in the job-server repo.

I'm trying to configure the JobSqlDao for mySql. At first I had the configuration set in local.conf only, but then I was getting mySql errors because it was trying to apply h2 upgrades because application.conf had flyway.locations set to h2.

It seems that spark.jobserver.sqldao.rootdir needs to be set in application.conf but not local.conf.
I'm not sure why its needed because sqldao.rootdir should not be need for mysql (only needed for h2).
 
It's almost working, but now it complains about"akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/binary-manager#-1982728063]] after [3000 ms]
I think this is because our jar is large (around 40m) and I need to increase some timeout somewhere.

In any case, the main question is: Why do we need all these different *.conf files and how do we know which one to change? Does one take precedence over the other? Do we need to repeat settings?

**Comment by bsikander** [comment]
Sorry for the confusion. I hope your confusion is resolved, if not, then this might help.

application.conf is the main config of spark-jobserver. It contains all the default configurations for SJS.
You can override the configurations in `application.conf` using `<environment>.conf` files. As mentioned in the [deployment section](https://github.com/spark-jobserver/spark-jobserver#deployment).

There is no file named local.conf in SJS itself but normally you create one. See point 3 in [here](https://github.com/spark-jobserver/spark-jobserver#deployment). If you are running SJS on local machine then you can copy the local.conf.template file to local.conf. If you are running SJS on aws then you can copy local.conf.template to aws.conf or something totally different 123.conf or dev.conf.

For example, on your local machine you might want to run SJS with MySql sometimes and sometimes with Postgres DB. Then you can create a mysql.conf with MySql configurations and postgres.conf with Postgres configurations. Now, when you want to deploy SJS with postgres, you can execute the following
```
./bin/server_deploy.sh postgres
```
For mysql, something like
```
./bin/server_deploy.sh mysql
```

> I'm trying to configure the JobSqlDao for mySql. At first I had the configuration set in local.conf only, but then I was getting mySql errors because it was trying to apply h2 upgrades because application.conf had flyway.locations set to h2.

If your configurations are according to this [documentation section](https://github.com/spark-jobserver/spark-jobserver#configuring-spark-jobserver-mysql-database-backend) then it should not pick up the application.conf flyway.locations. If your configurations seem ok then please post your config here.

> Do we need to repeat settings?

No, repeat settings if you want to override the default value.

**Comment by barrybecker4** [comment]
Thanks for the clarification.
