### ISSUE TITLE
NamedRDD is not working on 0.5.0

### ISSUE THREAD

**Issue by maihung** [spark-jobserver/spark-jobserver#105]
I just upgraded to 0.5.0 from 0.4.1 without any other changes, the RDDs are no longer cached.

I did a test where within the same job, I did an update and a get.  The get failed to get any cached RDD even through the update went through without any errors.

How can I cache the RDDs like in the previous release?

Thank you,
Hung

**Comment by velvia** [comment]
Have you tried recompiling your jobs?   The API changed so it is not binary
compatible.

On Sat, Mar 28, 2015 at 3:53 PM, maihung <notifications@github.com> wrote:

> I just upgraded to 0.5.0 from 0.4.1 without any other changes, the RDDs
> are no longer cached.
>
> I did a test where within the same job, I did an update and a get. The get
> failed to get any cached RDD even through the update went through without
> any errors.
>
> How can I cache the RDDs like in the previous release?
>
> Thank you,
> Hung
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/105>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by maihung** [comment]
Thank you for your response.  Do you have an example on how to do an update and a get for the new API?

**Comment by velvia** [comment]
The API hasn't changed.... have a look at the tests, but you should still
be able to do

namedRdds.getOrElseCreate("rdd", myRddFunc)

On Mon, Mar 30, 2015 at 1:29 PM, maihung <notifications@github.com> wrote:

> Thank you for your response. Do you have an example on how to do an update
> and a get for the new API?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/105#issuecomment-87822793>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
Quite an old ticket, we are now at 0.6.0 and things should be working now...
