### ISSUE TITLE
using spark2.1 and jobserver 0.8 code results in error Wrong classloader for job object

### ISSUE THREAD

**Issue by preetbawa** [spark-jobserver/spark-jobserver#1053]
**Used Spark version**
2.1

**Used Spark Job Server version**
jobserver 0.8 

(Released version, git branch or docker image version)
compiled spark-jobserver.jar and deployed in ec2 standalone cluster

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
client mode 

**Actual (wrong) behavior**
log entries: EUSEESparkJob class extends SparkSessionJob with NamedObjectSupport 

2018-04-03 16:47:28,714] INFO  k.jobserver.util.JarUtils$ [] [akka://JobServer/user/context-supervisor/sql-context-1] - Loading object spark.jobserver.EUSEESparkJob$ using loader spark.jobserver.util.ContextURLClassLoader@20ac90c0

[2018-04-03 16:47:28,714] ERROR k.jobserver.util.JarUtils$ [] [akka://JobServer/user/context-supervisor/sql-context-1] - ****Wrong ClassLoader for object spark.jobserver.EUSEESparkJob$: Expected spark.jobserver.util.ContextURLClassLoader@20ac90c0 but got org.apache.spark.util.MutableURLClassLoader@76908cc0****

****
**Steps to reproduce**
1. setup spark 2.1 cluster
2. setup spark job server with compiled jar (sbt assembly in my git branch and copied to ec2 master)
3. run the command 
curl "localhost:8090/jobs?appName=sql&classPath=spark.jobserver.EUSEESparkJob&context=sql-context" -d '{
   "resourceId": "daas_system_test",
   "sourceApplication": "CDI",
   "engine": "CEREBRO",
   "tables": "`qaws_chat_lake_vldtd.chat_trfr_detls_rpt_dly_ovral_card_vw`",
   "script": "select * from `qaws_chat_lake_vldtd.chat_trfr_detls_rpt_dly_ovral_card_vw`",
   "snowFlakeOutput": "testCerebro",
   "destinationWriteMode": "overwrite",
   "eid":"suj741",
   "executionDetail": {
             "jobExecutionId": "test",
             "topic": "test",
             "exitMessage": "",
             "status": "not started"
    }
}'

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by preetbawa** [comment]
any help would be greatly appreciated.

**Comment by valan4ik** [comment]
Sorry for the late reply, but we currently on Jobserver 0.10.x and Spark 2.4.
A lot of changes were introduced, also class loader was refactored. 
I will close the issue as it seems to be outdated now. Please reopen it, if the issue happens with the latest Jobserver version as well.
