### ISSUE TITLE
jobserver benefits with cluster mode 

### ISSUE THREAD

**Issue by preetbawa** [spark-jobserver/spark-jobserver#1070]
**Used Spark version**
2.2.0

**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8 

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
cluster 
I am looking into fact to change deploy mode to cluster for the fact if u have too many job requests on single jobserver driver, it may become bottleneck in terms of performance even though meat of processing is happening on spark cluster. In cluster mode since driver for each job is deployed on some assigned worker by master, i think it scales better. But then my question is how jobserver benefits in terms of cluster mode ? another question is that if cluster mode is supported in standalone mode. 

please let me know. 
**Actual (wrong) behavior**

**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by bsikander** [comment]
>> another question is that if cluster mode is supported in standalone mode.

Yes

>> But then my question is how jobserver benefits in terms of cluster mode 

Jobserver VM has less load and avoids noisy neighbor problem.
