### ISSUE TITLE
The context is not being display in SJS UI

### ISSUE THREAD

**Issue by Joslt** [spark-jobserver/spark-jobserver#1071]
**Used Spark version**
Spark 2.2.0

**Used Spark Job Server version**
SJS 0.8

**Deployed mode**
client on Spark Standalone YARN

**Actual (wrong) behavior**
Not displaying the running context in the SJS UI

**Steps to reproduce**
Just configure SJS to use spark 2.2.0 with scala 2.11. Start the server script
and when you go to the SJS UI there is not display about a running context.
But if you curl the context you will get the active context.

Unused parts of this template should be removed (including this line).

**Comment by pracucci** [comment]
This issue should have already been fixed by https://github.com/spark-jobserver/spark-jobserver/pull/1008 (after `0.8.0` release).
