### ISSUE TITLE
"errorClass": "scala.MatchError"

### ISSUE THREAD

**Issue by yabola** [spark-jobserver/spark-jobserver#1074]
Used Spark version
2.2.0
Used Spark Job Server version
master

Deployed mode
local[4]

I use scala 2.11.8
I can upload my jar ,but when I 
curl -d "input.string = a b c a b see" "localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample"
It has error：
my error log:
`"errorClass": "scala.MatchError",
    "stack": "scala.MatchError: (Actor[akka://JobServer/user/context-supervisor/effb7cdb-TestServer1#595244498],Actor[akka://JobServer/user/context-supervisor/global-result-actor#-2104837566]) (of class scala.Tuple2)\n\tat spark.jobserver.WebApi.spark$jobserver$WebApi$$getJobManagerForContext(WebApi.scala:728)\n\tat spark.jobserver.WebApi$$anonfun$jobRoutes$1$$anonfun$apply$75$$anonfun$apply$76.apply(WebApi.scala:640)\n\tat spark.jobserver.WebApi$$anonfun$jobRoutes$1$$anonfun$apply$75$$anonfun$apply$76.apply(WebApi.scala:630)\n\tat spray.routing.ApplyConverterInstances$$anon$17$$anonfun$apply$6.apply(ApplyConverterInstances.scala:60)\n
............`

**Comment by bsikander** [comment]
Could you please format the error correctly? It is unreadable.

**Comment by yabola** [comment]
@bsikander Thanks for your reply.
My error log:
`{
  "status": "ERROR",
  "result": {
    "message": "(Actor[akka://JobServer/user/context-supervisor/f1a6a8e8-TestServer#-1105897149],Actor[akka://JobServer/user/context-supervisor/global-result-actor#-2104837566]) (of class scala.Tuple2)",
    "errorClass": "scala.MatchError",
    "stack": "scala.MatchError: (Actor[akka://JobServer/user/context-supervisor/f1a6a8e8-TestServer#-1105897149],Actor[akka://JobServer/user/context-supervisor/global-result-actor#-2104837566]) (of class scala.Tuple2)
	spark.jobserver.WebApi.spark$jobserver$WebApi$$getJobManagerForContext(WebApi.scala:728)
	spark.jobserver.WebApi$$anonfun$jobRoutes$1$$anonfun$apply$75$$anonfun$apply$76.apply(WebApi.scala:640)
	spark.jobserver.WebApi$$anonfun$jobRoutes$1$$anonfun$apply$75$$anonfun$apply$76.apply(WebApi.scala:630)
	spray.routing.ApplyConverterInstances$$anon$17$$anonfun$apply$6.apply(ApplyConverterInstances.scala:60)
	spray.routing.ApplyConverterInstances$$anon$17$$anonfun$apply$6.apply(ApplyConverterInstances.scala:59)
	spray.routing.ConjunctionMagnet$$anon$3$$anon$4$$anonfun$happly$1$$anonfun$apply$1.apply(Directive.scala:38)
	spray.routing.ConjunctionMagnet$$anon$3$$anon$4$$anonfun$happly$1$$anonfun$apply$1.apply(Directive.scala:37)
	 spray.routing.directives.BasicDirectives$$anon$2.happly(BasicDirectives.scala:79)
	 spray.routing.Directive$$anon$7$$anonfun$happly$4.apply(Directive.scala:86)
	 spray.routing.Directive$$anon$7$$anonfun$happly$4.apply(Directive.scala:86)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) 
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
	spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
	scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
	akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
	akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	spray.routing.RequestContext.reject(RequestContext.scala:202)
	spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:35)
	spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:34)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
	spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
	scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
	akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
	akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	spray.routing.RequestContext.reject(RequestContext.scala:202)
	spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:35)
	spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:34)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
	$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
	scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
	akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
	akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	spray.routing.RequestContext.reject(RequestContext.scala:202)
	spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:35)
	spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:34)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
	spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
	scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
	akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
	spray.routing.RequestContext.reject(RequestContext.scala:202)
	spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:35)
	spray.routing.directives.RouteDirectives$$anon$1.apply(RouteDirectives.scala:34)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	spray.routing.directives.OnSuccessFutureMagnet$$anon$2$$anonfun$happly$2$$anonfun$apply$2.apply(FutureDirectives.scala:81)
	spray.routing.directives.OnSuccessFutureMagnet$$anon$2$$anonfun$happly$2$$anonfun$apply$2.apply(FutureDirectives.scala:79)
	scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"
  }
}`

**Comment by yabola** [comment]
my local.conf  and local.sh:
 
**local.conf**

# Template for a Spark Job Server configuration file
# When deployed these settings are loaded when job server starts
#
# Spark Cluster / Job Server configuration
spark {
  # spark.master will be passed to each job's JobContext
  # local[...], yarn, mesos://... or spark://...
  master = "local[4]"

  # client or cluster deployment
  submit.deployMode = "client"

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 4

  jobserver {
    port = 8090

    context-per-jvm = false

    # Note: JobFileDAO is deprecated from v0.7.0 because of issues in
    # production and will be removed in future, now defaults to H2 file.
    jobdao = spark.jobserver.io.JobSqlDAO

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    datadao {
      # storage directory for files that are uploaded to the server
      # via POST/data commands
      rootdir = /tmp/spark-jobserver/upload
    }

    sqldao {
      # Slick database driver, full classpath
      slick-driver = slick.driver.H2Driver

      # JDBC driver, full classpath
      jdbc-driver = org.h2.Driver

      # Directory where default H2 driver stores its data. Only needed for H2.
      rootdir = /tmp/spark-jobserver/sqldao/data

      # Full JDBC URL / init string, along with username and password.  Sorry, needs to match above.
      # Substitutions may be used to launch job-server, but leave it out here in the default or tests won't pass
      jdbc {
        url = "jdbc:h2:file:/tmp/spark-jobserver/sqldao/data/h2-db"
        user = ""
        password = ""
      }

      # DB connection pool settings
      dbcp {
        enabled = false
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
    # When using chunked transfer encoding with scala Stream job results, this is the size of each chunk
    result-chunk-size = 1m
  }

  # Predefined Spark contexts
  # contexts {
  #   my-low-latency-context {
  #     num-cpu-cores = 1           # Number of cores to allocate.  Required.
  #     memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
  #   }
  #   # define additional contexts here
  # }

  # Universal context configuration.  These settings can be overridden, see README.md
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

    # In case spark distribution should be accessed from HDFS (as opposed to being installed on every Mesos slave)
    # spark.executor.uri = "hdfs://namenode:8020/apps/spark/spark.tgz"

    # URIs of Jars to be loaded into the classpath for this context.
    # Uris is a string list, or a string separated by commas ','
    # dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]

    # Add settings you wish to pass directly to the sparkConf as-is such as Hadoop connection
    # settings that don't use the "spark." prefix
    passthrough {
      #es.nodes = "192.1.1.1"
    }
  }

  # This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
  # home = "/home/spark/spark"
  
  short-timeout = 60s
}

# check the reference.conf in spray-can/src/main/resources for all defined settings
spray.can.server {
  # uncomment the next lines for making this an HTTPS example
  # ssl-encryption = on
  # path to keystore
  #keystore = "/some/path/sjs.jks"
  #keystorePW = "changeit"

  # see http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#SSLContext for more examples
  # typical are either SSL or TLS
  encryptionType = "SSL"
  keystoreType = "JKS"
  # key manager factory provider
  provider = "SunX509"
  # ssl engine provider protocols
  enabledProtocols = ["SSLv3", "TLSv1"]
  idle-timeout = 60 s
  request-timeout = 40 s
  pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
  # Needed for HTTP/1.0 requests with missing Host headers
  default-host-header = "spray.io:8765"

  # Increase this in order to upload bigger job jars
  parsing.max-content-length = 300m
}
 
# Note that you can use this file to define settings not only for job server,
# but for your Spark jobs as well.  Spark job configuration merges with this configuration file as defaults.

akka {
  remote.netty.tcp {
    # This controls the maximum message size, including job results, that can be sent
    # maximum-frame-size = 10 MiB
	hostname = "dsdc81"
     maximum-frame-size = 100 MiB
  }
}

**Comment by yabola** [comment]
my local.conf:
spark {
  # spark.master will be passed to each job's JobContext
  # local[...], yarn, mesos://... or spark://...
  master = "local[4]"

  # client or cluster deployment
  submit.deployMode = "client"

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 4

  jobserver {
    port = 8090

    context-per-jvm = false

    # Note: JobFileDAO is deprecated from v0.7.0 because of issues in
    # production and will be removed in future, now defaults to H2 file.
    jobdao = spark.jobserver.io.JobSqlDAO

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    datadao {
      # storage directory for files that are uploaded to the server
      # via POST/data commands
      rootdir = /tmp/spark-jobserver/upload
    }

    sqldao {
      # Slick database driver, full classpath
      slick-driver = slick.driver.H2Driver

      # JDBC driver, full classpath
      jdbc-driver = org.h2.Driver

      # Directory where default H2 driver stores its data. Only needed for H2.
      rootdir = /tmp/spark-jobserver/sqldao/data

      # Full JDBC URL / init string, along with username and password.  Sorry, needs to match above.
      # Substitutions may be used to launch job-server, but leave it out here in the default or tests won't pass
      jdbc {
        url = "jdbc:h2:file:/tmp/spark-jobserver/sqldao/data/h2-db"
        user = ""
        password = ""
      }

      # DB connection pool settings
      dbcp {
        enabled = false
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
    # When using chunked transfer encoding with scala Stream job results, this is the size of each chunk
    result-chunk-size = 1m
  }

  # Predefined Spark contexts
  # contexts {
  #   my-low-latency-context {
  #     num-cpu-cores = 1           # Number of cores to allocate.  Required.
  #     memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
  #   }
  #   # define additional contexts here
  # }

  # Universal context configuration.  These settings can be overridden, see README.md
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

    # In case spark distribution should be accessed from HDFS (as opposed to being installed on every Mesos slave)
    # spark.executor.uri = "hdfs://namenode:8020/apps/spark/spark.tgz"

    # URIs of Jars to be loaded into the classpath for this context.
    # Uris is a string list, or a string separated by commas ','
    # dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]

    # Add settings you wish to pass directly to the sparkConf as-is such as Hadoop connection
    # settings that don't use the "spark." prefix
    passthrough {
      #es.nodes = "192.1.1.1"
    }
  }

  # This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
  # home = "/home/spark/spark"
  
  short-timeout = 60s
}

# check the reference.conf in spray-can/src/main/resources for all defined settings
spray.can.server {
  # uncomment the next lines for making this an HTTPS example
  # ssl-encryption = on
  # path to keystore
  #keystore = "/some/path/sjs.jks"
  #keystorePW = "changeit"

  # see http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#SSLContext for more examples
  # typical are either SSL or TLS
  encryptionType = "SSL"
  keystoreType = "JKS"
  # key manager factory provider
  provider = "SunX509"
  # ssl engine provider protocols
  enabledProtocols = ["SSLv3", "TLSv1"]
  idle-timeout = 60 s
  request-timeout = 40 s
  pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
  # Needed for HTTP/1.0 requests with missing Host headers
  default-host-header = "spray.io:8765"

  # Increase this in order to upload bigger job jars
  parsing.max-content-length = 300m
}
 
# Note that you can use this file to define settings not only for job server,
# but for your Spark jobs as well.  Spark job configuration merges with this configuration file as defaults.

akka {
  remote.netty.tcp {
    # This controls the maximum message size, including job results, that can be sent
    # maximum-frame-size = 10 MiB
	hostname = "dsdc81"
     maximum-frame-size = 100 MiB
  }
}

**Comment by yabola** [comment]
@bsikander  I am really sorry for wasting your time.I found the problem.It will work only when I create the context first("curl -d "" 'localhost:8090/contexts/jcontext?context-factory=spark.jobserver.context.JavaSparkContextFactory'") and then  ("curl -d "" 'localhost:8090/jobs?appName=test4&classPath=TestServer&context=jcontext&sync=true&context-factory=spark.jobserver.context.JavaSparkContextFactory'").It dosen't work when I use ("curl -d "" 'localhost:8090/jobs?appName=test4&classPath=TestServer'").

**Comment by bsikander** [comment]
@yabola no problem. Yes, job can only be submitted in a running context.

**Comment by fracTyler** [comment]
Please consider revisiting this issue.  The problem occurs when attempting to run a job with an adhoc context.  All that is needed to fix this is to append `._1` to `originator ! contexts(contextName)` in the `StartAdHocContext` receive case for `LocalContextSupervisorActor`

**Comment by linsimiao** [comment]
what's more, if u want to run a java class, create a java context by specifying 
`context-factory=spark.jobserver.context.JavaSparkContextFactory`.
However, if u wanna run a scala class, create a common context is ok.

**Comment by bsikander** [comment]
@fuqiliang yes, seems to be a bug.

@fracTyler already proposed a solution. Contributions are welcomed. @fuqiliang would you like to take a shot at this?

**Comment by iamtheuserofthis** [comment]
On creating a context first I get the following result:
`{
   "status":"JOB LOADING FAILED",
   "result":{
      "message":"spark.jobserver.WordCountExample$ cannot be cast to spark.jobserver.japi.BaseJavaJob",
      "errorClass":"java.lang.ClassCastException",
      "stack":"java.lang.ClassCastException: spark.jobserver.WordCountExample$ cannot be cast to spark.jobserver.japi.BaseJavaJob\n\tat spark.jobserver.JobCacheImpl$$anonfun$getJavaJob$1.apply(JobCache.scala:67)\n\tat spark.jobserver.JobCacheImpl$$anonfun$getJavaJob$1.apply(JobCache.scala:59)\n\tat spark.jobserver.util.LRUCache.get(LRUCache.scala:35)\n\tat spark.jobserver.JobCacheImpl.getJavaJob(JobCache.scala:59)\n\tat spark.jobserver.context.JavaContextFactory$class.loadAndValidateJob(SparkContextFactory.scala:118)\n\tat spark.jobserver.context.JavaSparkContextFactory.loadAndValidateJob(JavaSparkContextFactory.scala:9)\n\tat spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:532)\n\tat spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:377)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.JobManagerActor$$anonfun$5.applyOrElse(JobManagerActor.scala:279)\n\tat scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)\n\tat spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)\n\tat spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)\n\tat spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)\n\tat scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)\n\tat spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)\n\tat akka.actor.Actor$class.aroundReceive(Actor.scala:484)\n\tat spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:495)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n"
   }
`}`
