### ISSUE TITLE
how to pass in java.library.path per context [question]

### ISSUE THREAD

**Issue by tropicalpb** [spark-jobserver/spark-jobserver#1076]
I need to pass in -Djava.library.path to invoke native libraries for a context.  How to achieve this in contexts { } section of settings.conf?

Thanks

**Comment by bsikander** [comment]
Have you tried [this](https://github.com/spark-jobserver/spark-jobserver#dependency-jars) ?

**Comment by tropicalpb** [comment]
native libraries are not dependent jars, they are .so files on linux and passed in differently

**Comment by bsikander** [comment]
ok I understand. I think through `context` config section it is not possible right now.

But have your tried adding `-Djava.library.path` [here](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/config/local.sh.template#L38)?

**Comment by tropicalpb** [comment]
No, it doesn't work.  I also tried SPARK_SUBMIT_OPTS and that didn't work either.  None of the options get propagated to the Spark executors.  I had to manually edit the settings in the spark-default.conf regarding the library paths of the executors to make it work.  

I'd hate to muck around with global settings though.  It'd be great if it can be supported.

**Comment by bsikander** [comment]
The property that I mentioned is for driver.

The following environment variable is used for both driver and executors. It should work. Could you please try to pass your setting [here](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/config/local.sh.template#L40)?

**Comment by bsikander** [comment]
I am assuming that it worked. Please reopen if you still have problems.

**Comment by bsikander** [comment]
umm, strange. I thought that the last one should have worked. 

Your goal is to pass some custom arguments to each executor JVM?
