### ISSUE TITLE
java.io.NotSerializableException

### ISSUE THREAD

**Issue by yabola** [spark-jobserver/spark-jobserver#1078]
**Used Spark version**
spark 2.2
**Used Spark Job Server version**
(Released version, git branch or docker image version)
master(0.8)
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
cluster on Spark Standalone

I create Jcontext by ("curl -d "" 'localhost:8090/contexts/jcontext?context-factory=spark.jobserver.context.JavaSparkContextFactory'")
and I can upload my jar.I use ("curl -d "" 'localhost:8090/jobs?appName=test-job&classPath=TestServer&context=jcontext&sync=false&context-factory=spark.jobserver.context.JavaSparkContextFactory'")
It has error

{
  "duration": "0.008 secs",
  "classPath": "TestServer",
  "startTime": "2018-06-25T23:32:20.903+08:00",
  "context": "jcontext",
  "result": {
    "message": "java.io.NotSerializableException: TestServer
Serialization stack:
- object not serializable (class: TestServer, value: TestServer@33d830ba)
- field (class: TestServer$1, name: this$0, type: class TestServer)\n\t- object (class TestServer$1, TestServer$1@1413524a)
- field (class: org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1, name: f$3, type: interface org.apache.spark.api.java.function.FlatMapFunction)
- object (class org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1, <function1>)",
    "errorClass": "java.lang.RuntimeException",
    "stack": "java.lang.RuntimeException: java.io.NotSerializableException: TestServer\nSerialization stack:\n\t- object not serializable (class: TestServer, value: TestServer@33d830ba)\n\t- field (class: TestServer$1, name: this$0, type: class TestServer)
- object (class TestServer$1, TestServer$1@1413524a)
- field (class: org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1, name: f$3, type: interface org.apache.spark.api.java.function.FlatMapFunction)
- object (class org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1, <function1>)
 org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
 org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
 org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
 org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
org.apache.spark.SparkContext.clean(SparkContext.scala:2287)
 org.apache.spark.rdd.RDD$$anonfun$flatMap$1.apply(RDD.scala:379)
org.apache.spark.rdd.RDD$$anonfun$flatMap$1.apply(RDD.scala:378)
 org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
org.apache.spark.rdd.RDD.flatMap(RDD.scala:378)
org.apache.spark.api.java.JavaRDDLike$class.flatMap(JavaRDDLike.scala:126)
org.apache.spark.api.java.AbstractJavaRDDLike.flatMap(JavaRDDLike.scala:45)
TestServer.run(TestServer.java:38)\n\tat TestServer.run(TestServer.java:22)
spark.jobserver.japi.JavaJob.runJob(JavaJob.scala:20)
spark.jobserver.japi.JavaJob.runJob(JavaJob.scala:11)
spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:447)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
 scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)\n"
  },
  "status": "ERROR",
  "jobId": "12f94b76-74e2-4955-a900-fdd107d42a96",
  "contextId": "036c0c00-4862-41aa-b9c5-2f3a5228a457"
}

This is my code:

import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;
import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.api.java.function.FlatMapFunction;
import org.apache.spark.api.java.function.Function2;
import org.apache.spark.api.java.function.PairFunction;
import org.apache.spark.api.java.function.VoidFunction;
import scala.Tuple2;
import spark.jobserver.api.JobEnvironment;
import spark.jobserver.japi.JSparkJob;

import java.util.Arrays;
import java.util.Iterator;

public class TestServer implements JSparkJob<String> {

    @Override
    public String run(JavaSparkContext sc, JobEnvironment runtime, Config data) {
        JavaRDD<String> lines=sc.textFile("hdfs://dsdc81:9000/demo.data");
        JavaRDD<String> words = lines.flatMap(new FlatMapFunction<String,String>(){
            @Override
            public Iterator<String> call(String line) throws Exception {
                return Arrays.asList(line.split(" ")).iterator();
            }
        });
        JavaPairRDD<String,Integer> pairs =words.mapToPair(new PairFunction<String,String,Integer>(){
            @Override
            public Tuple2<String, Integer> call(String word) throws Exception {
                return new Tuple2<String,Integer>(word,1);
            }

        });
        JavaPairRDD<String,Integer> wordCounts =pairs.reduceByKey(new Function2<Integer,Integer,Integer>(){
            @Override
            public Integer call(Integer v1, Integer v2) throws Exception {
                return v1+v2;
            }
        });
        wordCounts.foreach(new VoidFunction<Tuple2<String,Integer>>(){
            @Override
            public void call(Tuple2<String, Integer> wordcount) throws Exception {
                System.out.println(wordcount._1+" appeared "+wordcount._2+"times");
            }
        });
        return "Hi!";
    }
    @Override
    public Config verify(JavaSparkContext sc, JobEnvironment runtime, Config config) {
        return ConfigFactory.empty();
    }
}

**Comment by bsikander** [comment]
Please format the exception and code properly, it is not readable.

**Comment by yabola** [comment]
@bsikander Thanks for your instant reply.This is my code addreess.
[https://github.com/yabola/project/blob/master/TestServer.java](url)
My error log.
[https://github.com/yabola/project/blob/master/ErrorLog.txt](url)

**Comment by yabola** [comment]
@bsikander Thanks for your instant reply.This is my code addreess.
https://github.com/yabola/project/blob/master/TestServer.java
My error log.
https://github.com/yabola/project/blob/master/ErrorLog.txt
