### ISSUE TITLE
Context mode Jobs logging

### ISSUE THREAD

**Issue by bittu2009** [spark-jobserver/spark-jobserver#1079]
**Used Spark version**
2.3.1
**Used Spark Job Server version**
Master Branch

**Deployed mode**
Client

**Actual (wrong) behavior**
When we are submitting jobs parallel in context mode the logs are written in spark-job-server.out and the logs are messed up means jubmbled with each other job. How do we make for each job logs in different file.
**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by thoHeinze** [comment]
If you set the configuration ``context-per-jvm=True``, each context will be started inside an individual JVM and write into a separate log file.

**Comment by bsikander** [comment]
The logs are jumbled because your SJS configurations are not correct.

Have you already solved the problem? If no, then please post your configurations *.sh & *.conf file.

**Comment by bsikander** [comment]
closing issue, due to inactivity.
