### ISSUE TITLE
What is the recommended size of the return data set

### ISSUE THREAD

**Issue by manasdebashiskar** [spark-jobserver/spark-jobserver#108]
Hi, 
 I have a jobserver process that takes a bunch of filter parameters and returns the filtered dataset.
However my return dataset is of the order of multiple GB.
Can I send the result as a map?(With out choking the job-server with OOM)
or a better way is to save it to HDFS and just send the path of the saved files?

Thanks
Manas

**Comment by velvia** [comment]
I think HDFS or other persistent storage is def the way to go, for something that big.  JSON/HTTP is not a good medium for that size.  :)

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
