### ISSUE TITLE
Can not find `JSqlJob<T>` in java api of SJS.

### ISSUE THREAD

**Issue by linsimiao** [spark-jobserver/spark-jobserver#1080]
**Used Spark version**
2.2.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8.0
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
 client
**Actual (wrong) behavior**

I added dependency
 ` <dependency>

         <groupId>spark.jobserver</groupId>

         <artifactId>job-server_2.11</artifactId>

         <version>0.8.0</version>

     </dependency>`

in my java project. 

When  I tried to implements `JSqlJob<T>` which @hntd187 declared in [https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/javaapi.md](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/javaapi.md),  `JSqlJob<T>` was not recognized.
I wonder how can I build a sql job.
Thanks in advance.

**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by linsimiao** [comment]
@hntd187

**Comment by linsimiao** [comment]
or should I implements `BaseJavaJob<R,C>`？

**Comment by hntd187** [comment]
Don’t implement ‘BaseJavaJob’ did you also include the extras dependency?

**Comment by linsimiao** [comment]
I add dependency on extras of version `0.8.0` right now, and it still doesn't work.

**Comment by linsimiao** [comment]
well, I had a look into the extras jar, and I found there are two classes inside package `japi`, which are `JSessionJob` and `JStreamingJob`. Should I extends  `JSessionJob` to solve my problem?

Thx in advance. @hntd187

**Comment by linsimiao** [comment]
the class that suits me  is exactly `JSessionJob`.
