### ISSUE TITLE
can spark job server support a context start automatically If the context quit due to exceptions?

### ISSUE THREAD

**Issue by lxhao** [spark-jobserver/spark-jobserver#1084]
**Used Spark version**
2.2

**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.7.7

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
client

**Actual (wrong) behavior**

**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by noorul** [comment]
What we are doing today is that before submitting a job check whether the context exists or not. If not create and submit, otherwise submit.

**Comment by bsikander** [comment]
Jobserver now supports supervise mode. If a context has supervise mode enabled and it gets killed with exit code of non-zero, spark will restart it and jobserver will get initialized again.
