### ISSUE TITLE
can support to save result field in database?

### ISSUE THREAD

**Issue by lxhao** [spark-jobserver/spark-jobserver#1093]
**Used Spark version**
2.2
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
yarn client and cluster
**Actual (wrong) behavior**
the returned result of job status has no result field when restart context.
**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by bsikander** [comment]
The size of result could vary between jobs. So, putting it in DB is not a good option.

You should write your result externally e.g. HDFS/s3/local disk etc

**Comment by lxhao** [comment]
What you say is reasonable. But sometimes  results are very small, maybe just a HDFS path. I think it is reasonable for users to configure the result to be stored in the database, or if the result exceeds a certain size, it can not be saved to the database.
