### ISSUE TITLE
Support Spark 2.3 with k8s

### ISSUE THREAD

**Issue by ejthsiao** [spark-jobserver/spark-jobserver#1096]
We have been using spark-jobserver for Spark 2.2 and have a question in regards to Spark 2.3 with k8s support (preview).  

The following is a spark-submit for k8s.  Note the --master is a k8s URL instead of either spark or yarn.  This command works fine for Spark 2.3.0/2.3.1 distribution with k8s. The question we have is whether JobServer needs to be extended to support k8s or does JobServer rely on the underlying Spark bits (e.g. 2.3.1 which contains support for Kubernetes) so this should just work for JobServer.  Currently Job Server certifies with Standalone Spark as well on cluster, Mesos, YARN client with Spark 2.2.0 only but I do not see 2.3.x certification nor k8s.  Can the community pls comment if anyone is looking into this space and whether it's a certification effort or additional development is required on jobserver to support k8s.

$ bin/spark-submit \
    --master k8s://https://<k8s-apiserver-host>:<k8s-apiserver-port> \
    --deploy-mode cluster \
    --name spark-pi \
    --class org.apache.spark.examples.SparkPi \
    --conf spark.executor.instances=5 \
    --conf spark.kubernetes.container.image=<spark-image> \
    local:///path/to/examples.jar

**Comment by ejthsiao** [comment]
fix the example -

$ bin/spark-submit \
    --master k8s://https://<k8s-apiserver-host>:<k8s-apiserver-port> \
    --deploy-mode cluster \
    --name spark-pi \
    --class org.apache.spark.examples.SparkPi \
    --conf spark.executor.instances=5 \
    --conf spark.kubernetes.container.image=<spark-image> \
    local:///path/to/examples.jar

**Comment by ejthsiao** [comment]
See https://spark.apache.org/docs/2.3.0/running-on-kubernetes.html

**Comment by bsikander** [comment]
Related: https://github.com/spark-jobserver/spark-jobserver/issues/1046

**Comment by bsikander** [comment]
Closing. Support for k8s can be tracked in https://github.com/spark-jobserver/spark-jobserver/issues/1038
