### ISSUE TITLE
can support to save result field in database?

### ISSUE THREAD

**Issue by lxhao** [spark-jobserver/spark-jobserver#1098]
**Used Spark version**
2.2
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
client 
**Actual (wrong) behavior**
 Sometimes results are very small, maybe just a HDFS path. I think it is reasonable for users to configure whether the result to be stored in the database, or if the result exceeds a certain size, it can not be saved to the database.
**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by velvia** [comment]
Sure, this is not a bad idea

**Comment by Nibooor** [comment]
See https://github.com/spark-jobserver/spark-jobserver/pull/1375
