### ISSUE TITLE
Recommended way to pass main class arguments

### ISSUE THREAD

**Issue by DatPhanTien** [spark-jobserver/spark-jobserver#1100]
** Spark version 2.3.1**

**Spark Job Server 0.8.1**
(Released version, git branch or docker image version)

**Deployed mode: Cluster**

Dear 

We are not able to find any where a dedicated documentation for passing arguments to main class of an application via SJS API.
Could you please enlighten us regarding this aspect?

Best

**Comment by bsikander** [comment]
umm, what is your usecase?

Generally, you can do the following. Notice `-d` flag and `input.string`.

```
curl -d "input.string = a b c a b see" "localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample&context=test-context&sync=true"
```

Then within your code, you can access the input using `config.getString("input.string")` and then use it to initialize whatever you want.

**Comment by velvia** [comment]
The input to a job is typically JSON or Typesafe Config/HOCON, or .properties. You use the Typesafe COnfig library to parse the input.

**Comment by DatPhanTien** [comment]
Dear velvia,

Thanks for the advice.
Btw, are there any available examples (in the code of Spark Job Server project) of how to parse the input in different formats (JSON, .properties or TypeSafe)?

**Comment by velvia** [comment]
WordCountExample.scala and LongPiJob.scala have super simple examples of parsing config/JSON (should work for both) for one string or Int variable.

SessionTestJob shows an example of using SJS as a query server where the query is a single config line starting with sql =

**Comment by DatPhanTien** [comment]
Thanks
Just test it quickly. In JSON format, it works like a charm.

Shall we close the issue?

**Comment by velvia** [comment]
yes please, glad you found out how :)
