### ISSUE TITLE
Missing implementation while extending SparkJob.scala

### ISSUE THREAD

**Issue by DatPhanTien** [spark-jobserver/spark-jobserver#1104]
**Used Spark version: 2.3.1**

**Used Spark Job Server version: 0.8.0**

**Deployed mode: Cluster**

We are implementing our own applications to use Spark Job Server.
Here is very simple example of our code:

>  package com.test
> 
> import com.typesafe.config.{Config}
> import org.apache.spark._
> import spark.jobserver._
> import spark.jobserver.SparkJob
> 
> trait TestSjs extends SparkJob {
>   def validate(sc: SparkContext, config: Config): SparkJobValidation = SparkJobValid
> }
> 
> object TestParam extends TestSjs {
> 
>   override def validate(sc: SparkContext, config: Config): SparkJobValidation = super.validate(sc, config)
> 
>   override def runJob(sc: SparkContext, jobConfig: Config): Any = {
>     "Hello world!"
>   }
> }

We used Intellij for developing these codes. In side the pom file, we declare the dependency on Spark Job server version 0.8.0

Steps to reproduce:
1) Build the project -> get a jar file (the build finished successfully)
2) Upload jar to Spark Job Server API
3) Run job

Here is the response:
`{
  "jobId": "38ee225f-2f70-46de-b40a-eed4e3cd88d5",
  "status": "ERROR",
  "result": {
    "message": "scala.NotImplementedError: an implementation is missing",
    "errorClass": "java.lang.RuntimeException",
    "stack": "java.lang.RuntimeException: scala.NotImplementedError: an implementation is missing\n\tat scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)\n\tat com.test.TestParam$.validate(TestParam.scala:86)\n\tat com.test.TestParam$.validate(TestParam.scala:16)\n\tat spark.jobserver.SparkJobBase$class.validate(SparkJob.scala:35)\n\tat com.test.TestParam$.validate(TestParam.scala:16)\n\tat spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:438)\n\tat scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)\n\tat scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:748)\n"
  }
}`

Clearly, there is a missing implementation that our code did not cover, or at least, that is how we deduce from the response.

Could you please help us to better understand what is missing?

Best regards
Tien Dat

**Comment by valan4ik** [comment]
The issue probably occurs due to the following line:
```
override def validate(sc: SparkContext, config: Config): SparkJobValidation = super.validate(sc, config)
```

If you want to skip validation the it may make sense just to always return `SparkJobValid`:
```
override def validate(sc: SparkContext, config: Config): SparkJobValidation = SparkJobValid
```

You can check WordCount examples for a bit more clarity: https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server-tests/src/main/scala/spark/jobserver/WordCountExample.scala
