### ISSUE TITLE
Using local jar files to run jobs in cluster mode

### ISSUE THREAD

**Issue by DatPhanTien** [spark-jobserver/spark-jobserver#1105]
**Used Spark version: 2.3.1**

**Used Spark Job Server version: 0.8.0**

**Deployed mode: Cluster**

Dear

We are using SJS for running our jobs in cluster mode.
For handling application jar files, SJS requires to use JobSqlDAO (since we want to have a context per JVM).
Our question is: **Is it possible to run our application with only local jars (accessible on each Spark node)?** In other words, is there any possible way to not involve using any database just for storing jar file? I mean, if we have local jar file on each node, just pass a valid jar path to the configuration.

Best
Tien Dat

**Comment by valan4ik** [comment]
It's impossible to run jobserver without any DB set up. Main application jar will be always taken from DB in current Jobserver implementation. Jobserver also keeps a lot of metadata information in DB (so you will have to set up one in any case).
What is possible, as @gao634209276 mentioned, you can make your main jar very minimal and put all the rest into dependency jars. They can be kept locally and added as a dependency, when you start the job.
