### ISSUE TITLE
How to run Spark Job Server on EMR 5.15.0 (Spark 2.3.0)

### ISSUE THREAD

**Issue by BourneYu** [spark-jobserver/spark-jobserver#1107]
**Used Spark version**
2.3.0

**Used Spark Job Server version**
git branch: master (up-to-date as of August 15, 2018)

**Deployed mode**
cluster on Spark EMR-5.15.0

**Actual (wrong) behavior**
Follow the manual:https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/EMR.md (EMR 4.2.0). 

I found the manual to increase the MANAGER_* parameter when creating config/emr.sh:
MANAGER_JAR_FILE="$appdir/spark-job-server.jar"
MANAGER_CONF_FILE="$(basename $conffile)"
MANAGER_EXTRA_JAVA_OPTIONS=
MANAGER_EXTRA_SPARK_CONFS="spark.yarn.submit.waitAppCompletion=false|spark.files=$appdir/log4jcluster.properties,$conffile"
MANAGER_LOGGING_OPTS="-Dlog4j.configuration=log4j-cluster.properties"

When run 'bin/server_package.sh emr' output:
/mnt/work/spark-jobserver/config/emr.sh: line 13: appdir: unbound variable

Anyone plz guide me how should I set $appdir $(basename $conffile) $conffile?

**Comment by BourneYu** [comment]
@bsikander ，help me please，thank you！

**Comment by bsikander** [comment]
I am not an expert in EMR related deployment but here is an example, [how appdir should be set](https://github.com/spark-jobserver/spark-jobserver/blob/master/bin/setenv.sh#L8)

**Comment by bsikander** [comment]
did it help? Can we close the issue?
