### ISSUE TITLE
Database connection pooling for multiple concurrent jobs

### ISSUE THREAD

**Issue by kavuri** [spark-jobserver/spark-jobserver#112]
We have a case that we will have to run concurrent jobs (for the same algorithm) on different data sets. And these jobs can run in parallel and each one of them would be fetching the data from the database.
We would like to optimize the database connections by making use of connection pooling. Is there any facility available in job server to enable such a feature? If not, any suggestions on how we can enable such a feature either in the algorithm code or job server?

**Comment by velvia** [comment]
Hi Sateesh,

One idea is that you can have these different jobs run in parallel (using
the fair scheduler) in a single, custom spark context.  You can just extend
the SparkContextBase -- see how this is done with the SQLContext.  This
custom context would hold a shared connection pool, which can be accessed
by all the different jobs.   What do you think?

On Thu, Apr 2, 2015 at 4:36 AM, Sateesh Kavuri <notifications@github.com>
wrote:

> We have a case that we will have to run concurrent jobs (for the same
> algorithm) on different data sets. And these jobs can run in parallel and
> each one of them would be fetching the data from the database.
> We would like to optimize the database connections by making use of
> connection pooling. Is there any facility available in job server to enable
> such a feature? If not, any suggestions on how we can enable such a feature
> either in the algorithm code or job server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/112>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by kavuri** [comment]
@velvia Makes sense.
Question then is, can I use the this new context the same way I use SparkContext?

**Comment by velvia** [comment]
You will have access to this new context (passed in as the first arg of
startJob), and assuming you subclass SparkContext or point to it, should
have easy direct access to the SparkContext.

On Fri, Apr 3, 2015 at 1:42 AM, Sateesh Kavuri <notifications@github.com>
wrote:

> @velvia <https://github.com/velvia> Makes sense.
> Question then is, can I use the this new context the same way I use
> SparkContext?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/112#issuecomment-89223509>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by kavuri** [comment]
What is the way then to pass the connection pool to the algorithm? Since
connection objects are not serializable

**Comment by velvia** [comment]
Sateesh, how about writing a custom SparkContext (like SQLContext, for
example, it wraps SparkContext and has the connection pool state....

class MyCustomSparkContext(context: SparkContext) {
  val connectionPool = ....

}

Then you create a CustomSparkContextJob, which is passed the
MyCustomSparkContext with the connection pool already set up....


On Sun, Apr 5, 2015 at 8:16 PM, Sateesh Kavuri <notifications@github.com>
wrote:

> What is the way then to pass the connection pool to the algorithm? Since
> connection objects are not serializable
> On 5 Apr 2015 13:58, "Evan Chan" <notifications@github.com> wrote:
>
> > You will have access to this new context (passed in as the first arg of
> > startJob), and assuming you subclass SparkContext or point to it, should
> > have easy direct access to the SparkContext.
> >
> > On Fri, Apr 3, 2015 at 1:42 AM, Sateesh Kavuri <notifications@github.com
> >
> > wrote:
> >
> > > @velvia <https://github.com/velvia> Makes sense.
> > > Question then is, can I use the this new context the same way I use
> > > SparkContext?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/spark-jobserver/spark-jobserver/issues/112#issuecomment-89223509
> > >
> > > .
> > >
> >
> >
> >
> > --
> > If you are free, you need to free somebody else.
> > If you have some power, then your job is to empower somebody else.
> > --- Toni Morrison
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/spark-jobserver/spark-jobserver/issues/112#issuecomment-89734877
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/112#issuecomment-89901524>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by noorul** [comment]
Is this really a spark-jobserver related issue?

**Comment by kavuri** [comment]
@noorul depends on how you look at it. The job server is expected to manage multiple contexts and jobs in Spark, in which case, connection pooling would become a critical issue

**Comment by hntd187** [comment]
Yes @kavuri, but the connection to that DB is part of your job, so you manage it. SJS sits a level above that managing the overall Spark state, so if you wanted a connection pool you should have it in your actual job. Otherwise we'd be basically creating pools/managers for everything under the sun, which I don't believe is the intent.

**Comment by kavuri** [comment]
@hntd187 agreed that it falls into the job purview, but this becomes relevant if we have to implement a context that needs to access a connection pool. @velvia inputs are helpful and relevant here

**Comment by velvia** [comment]
If you mean that you want multiple jobs executing on a shared context and you want a connection pool to be shared amongst the jobs - that is something you can implement yourself by implementing a custom context that extends, for example, SQLContext, and implementing a custom SparkContextFactory.   This is why Job Server allows you to extend the context factories, for scenarios like this.

If you have any issues with this approach, be sure to let us know and we’d love to improve it.

-Evan

**Comment by kavuri** [comment]
@velvia Yes, we ended up doing something like that. Thanks

**Comment by noorul** [comment]
Closing this
