### ISSUE TITLE
unable to access "akka.remote.netty.tcp.hostname" from outside; unable to map random ports

### ISSUE THREAD

**Issue by zenglian** [spark-jobserver/spark-jobserver#1122]
When clients and job server are in different networks,  clients cannot connect to ` akka.remote.netty.tcp.hostname` as it's an internal host/ip.

So there should be another property for clients to connect to, e.g.,

    akka.remote.netty.tcp.bindAddress=0.0.0.0:12345   //used by server
    akka.remote.netty.tcp.externalAccessAddress=external_ip:mapped_port    //used by clients

Besides, the server port must be static otherwise you are not able to create the port mapping (for,e.g,  docker/k8s network). And if server is restarted, clients could not resume the connection.  Services should not use random ports.

**Comment by bsikander** [comment]
Setting `akka.remote.netty.tcp.hostname` to an externally accessible IP doesn't work?

**Comment by zenglian** [comment]
The server can't start up with external name/IP.
