### ISSUE TITLE
Bug: Some property may be lost using com.typesafe.config

### ISSUE THREAD

**Issue by gao634209276** [spark-jobserver/spark-jobserver#1128]
**Used Spark version**
ALL
**Used Spark Job Server version**
(Released version, git branch or docker image version)
ALL
**Deployed mode**
ALL

**Actual (wrong) behavior**
When set some property in  SJS config file，
such as：
```
spark.speculation = true
spark.speculation.interval = 10s
spark.speculation.multiplier = 3
spark.speculation.quantile = 0.8
```
But I found SJS use com.typesafe.config parse the config file. finally,The configuration is converted into the following：
```
{
    "context-settings" : {
        "spark" : {
            "speculation" : {
                "interval" : "10s",
                "multiplier" : 3,
                "quantile" : 0.8
            },
}
```
It lost the property `spark.speculation`！
The configuration of this situation is a lot in the spark， How to solve this problem？

**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).
@bsikander

**Comment by bsikander** [comment]
I didn't understand that correctly, where do you set configurations in HOCON format? Why don't you directly set configurations in JSON format?

**Comment by gao634209276** [comment]
I set these configurations  in SJS config file, I just wrote this part of the configuration，
The overall configuration is HOCON format：
```
spark {
   // ...
   context-settings {
       // ...
       spark.speculation = true
       spark.speculation.interval = 10s
       spark.speculation.multiplier = 3
       spark.speculation.quantile = 0.8
   }
// ...
}
```

**Comment by gao634209276** [comment]
The problems is com.typesafe.config parse this to a Object, but the config path :  `spark/context-settings/spark/speculation` have to value, one is a Boolean value and the other is configObject.
The latter will cover the front

**Comment by bsikander** [comment]
Ok, this seems to be a general problem and not directly related to jobserver?
Is there a solution to this problem in typesafe community?

As a workaround, try to set your spark configurations directly under `launcher` [section](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/resources/application.conf#L181). All configurations specified in this section will be passed to driver in JVM arguments.

**Comment by gao634209276** [comment]
Yes, It is caused by typesafe parsing, I don't know if there is a solution.
Thanks,  I will try it

**Comment by gao634209276** [comment]
the launcher [section](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/resources/application.conf#L181) which you recommend also use typesafe parsing in [src](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/scala/spark/jobserver/util/ManagerLauncher.scala#L67), and the property `spark.speculation` still lost.
@bsikander

**Comment by gao634209276** [comment]
But I thought of a compromise：
set `spark.speculation = true` at `launcher`, and others under `context-settings`

**Comment by bsikander** [comment]
@gao634209276 did it work?
