### ISSUE TITLE
Can the JobServer have different config/log4j.properties Or update the config without restart the JobServer

### ISSUE THREAD

**Issue by togoon** [spark-jobserver/spark-jobserver#113]
we deployed the jobserver in the develop environment. After run the test jar, i have some questions about the jobserver.

i: the config paramter in validate and runJob function is immutable, can i update or reload it?
ii: the log only append into one file(spark-job-server.log), based on the log4j-server.properties,can i support different config with different job/jar, Or update the config without restart the JobServer.
Such as A.jar with A.config,log4j.A.properties and B.jar with B.config,log4j.B.properties

**Comment by velvia** [comment]
i.  Yes the config parameter is immutable, cannot be updated.
ii.   I'm not a log4j expert, I don't believe log4j supports updating log
configuration.,  You can probably change settings on the fly using JMX
though.

Honestly I'm thinking of switching to logback.  It's a much better logging
library and you can change config on the fly.

On Fri, Apr 3, 2015 at 12:55 AM, togoon <notifications@github.com> wrote:

> we deployed the jobserver in the develop environment. After run the test
> jar, i have some questions about the jobserver.
>
> i: the config paramter in validate and runJob function is immutable, can i
> update or reload it?
> ii: the log only append into one file(spark-job-server.log), based on the
> log4j-server.properties,can i support different config with different
> job/jar, Or update the config without restart the JobServer.
> Such as A.jar with A.config,log4j.A.properties and B.jar with
> B.config,log4j.B.properties
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/113>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by togoon** [comment]
How do I use the logback for JobServer ? copy the logback-server.xml file to the project root directory?

**Comment by velvia** [comment]
It's more involved than that.  There are some dependencies which pull in
log4j, we need to exclude the log4j, and then put in log4j-over-slf4j jar.
The dependency tree can be printed using the "dependencyGraph" command in
sbt.  Once the deps are satisfied then use the -Dlogback.configurationFile
JVM switch (check the bottom of Build.scala).

I'm hoping to switch over to logback.  I'm tired of log4j.

On Wed, Apr 8, 2015 at 1:16 AM, togoon <notifications@github.com> wrote:

> How do I use the logback for JobServer ? copy the logback-server.xml file
> to the project root directory?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/113#issuecomment-90838899>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by togoon** [comment]
oh,yes I found the following code in Build.scala

**Comment by togoon** [comment]
oh , yes ,I found the following code in Build.scala
```java
lazy val jobServerLogbackLogging = "-Dlogback.configurationFile=config/logback-local.xml"
lazy val jobServerLogging = "-Dlog4j.configuration=config/log4j-local.properties"
```

Does that mean I can't use the logback now?

**Comment by velvia** [comment]
Yeah, more build changes are needed.

On Thu, Apr 9, 2015 at 12:59 AM, togoon <notifications@github.com> wrote:

> oh , yes ,I found the following code in Build.scala
>
> lazy val jobServerLogbackLogging = "-Dlogback.configurationFile=config/logback-local.xml"
> lazy val jobServerLogging = "-Dlog4j.configuration=config/log4j-local.properties"
>
> Does that mean I can't use the logback now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/113#issuecomment-91144249>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison
