### ISSUE TITLE
SparkContext

### ISSUE THREAD

**Issue by stalins** [spark-jobserver/spark-jobserver#115]
How job server handles multiple sparkcontext? Is it creating new process when user calls create context REST?.

**Comment by velvia** [comment]
Not right now, but there is something in the works.

On Mon, Apr 6, 2015 at 8:12 PM, stalins <notifications@github.com> wrote:

> How job server handles multiple sparkcontext? Is it creating new process
> when user calls create context REST?.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/115>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by stalins** [comment]
apache spark says we cannot maintain multiple sparkcontext in single JVM instance, how its working in job server?

**Comment by velvia** [comment]
Some folks have gotten it to work.  In the meantime there is a new PR open to tackle this problem.
