### ISSUE TITLE
Please provide a Dockerfile and instructions for building and running locally

### ISSUE THREAD

**Issue by eschizoid** [spark-jobserver/spark-jobserver#1155]
Currently, there is a `Dockerfile.env` that the whole purpose is just running the tests. Is there a similar file for building locally using docker?

**Comment by noorul** [comment]
Did you try sbt-docker? It will generate Dockerfile.

**Comment by eschizoid** [comment]
@noorul thanks for your suggestion, I tried that but I keep getting the following error:

```
sbt docker
...
[info] --2019-02-04 23:56:50--  http://d3kbcqa49mib13.cloudfront.net/spark-2.3.2.tgz
[info] Resolving d3kbcqa49mib13.cloudfront.net (d3kbcqa49mib13.cloudfront.net)... 13.249.26.199, 13.249.26.68, 13.249.26.6, ...
[info] Connecting to d3kbcqa49mib13.cloudfront.net (d3kbcqa49mib13.cloudfront.net)|13.249.26.199|:80... connected.
[info] HTTP request sent, awaiting response... 404 Not Found
[info] 2019-02-04 23:56:50 ERROR 404: Not Found.
[info] The command '/bin/sh -c wget http://d3kbcqa49mib13.cloudfront.net/spark-2.3.2.tgz && tar -xvf spark-2.3.2.tgz && cd spark-2.3.2 && ./dev/make-distribution.sh -Dscala-2.11 -Phadoop-2.7 -Phive && cd .. && mv spark-2.3.2/dist /spark && rm spark-2.3.2.tgz && rm -r spark-2.3.2' returned a non-zero code: 8
[info]
[error] java.lang.RuntimeException: Nonzero exit code: 8
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at scala.sys.process.BasicIO$Streamed$.next$1(BasicIO.scala:49)
[error] 	at scala.sys.process.BasicIO$Streamed$.$anonfun$apply$1(BasicIO.scala:50)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
[error] 	at scala.collection.immutable.Stream.foreach(Stream.scala:531)
[error] 	at sbtdocker.DockerBuild$.build(DockerBuild.scala:87)
[error] 	at sbtdocker.DockerBuild$.buildAndTag(DockerBuild.scala:72)
[error] 	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:45)
[error] 	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:24)
[error] 	at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$1(DockerSettings.scala:17)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (docker) Nonzero exit code: 8
[error] Total time: 75 s, completed Feb 4, 2019 5:56:52 PM
```

**Comment by eschizoid** [comment]
@noorul Any chance that you can push `spark-2.3.2` binaries?

**Comment by noorul** [comment]
@eschizoid  There is an issue with the URL. I will push a fix.  Attached is the dockerfile that for generated for me with the fix.

`
FROM openjdk:8-jdk
EXPOSE 8090
EXPOSE 9999
ENV MESOS_VERSION="1.0.0-2.0.89.ubuntu1404"
RUN echo "deb http://repos.mesosphere.io/ubuntu/ trusty main" > /etc/apt/sources.list.d/mesosphere.list && \
                apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF && \
                apt-get -y update && \
                apt-get -y install mesos=${MESOS_VERSION} && \
                apt-get clean
        
ENV MAVEN_VERSION="3.3.9"
RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
          && curl -fsSL http://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz \
          | tar -xzC /usr/share/maven --strip-components=1 \
          && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
        
ENV MAVEN_HOME="/usr/share/maven"
ENV MAVEN_CONFIG="/.m2"
COPY 0/spark-job-server.jar /app/spark-job-server.jar
COPY 1/server_start.sh app/server_start.sh
COPY 2/server_stop.sh app/server_stop.sh
COPY 3/setenv.sh app/setenv.sh
COPY 4/log4j-stdout.properties app/log4j-server.properties
COPY 5/docker.conf app/docker.conf
COPY 6/docker.sh app/settings.sh
ENV JOBSERVER_MEMORY="1G"
ENV SPARK_HOME="/spark"
RUN ["mkdir", "-p", "\/database"]
RUN wget http://apache.lauf-forum.at/spark/spark-2.3.2/spark-2.3.2.tgz && \
tar -xvf spark-2.3.2.tgz && \
cd spark-2.3.2 && \
./dev/make-distribution.sh -Dscala-2.11 -Phadoop-2.7 -Phive && \
cd .. && \
mv spark-2.3.2/dist /spark && \
rm spark-2.3.2.tgz && \
rm -r spark-2.3.2
VOLUME ["\/database"]
ENTRYPOINT ["app\/server_start.sh"]
`

**Comment by eschizoid** [comment]
@noorul thanks for the fix! I just tried it and is working as expected. Feel free to close the issue.
