### ISSUE TITLE
is ad hoc context created single thread or multiple thread?

### ISSUE THREAD

**Issue by fengxucn** [spark-jobserver/spark-jobserver#1164]
**Used Spark version**
2.2.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8.0
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
YARN

**Actual (wrong) behavior**
I did a load test for spark job server, which send 10 requests (all ad hoc context) at same time, and I found the 10 ad hoc context was created one by one, not parallel

context-per-jvm = true

**Steps to reproduce**
use jmeter to do load test and using ad hoc 

**Questions**
is it possible to let it run in parallel?
```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by bsikander** [comment]
So, does it work in parallel or doesn't ?

**Comment by fengxucn** [comment]
yes, they run parallel
