### ISSUE TITLE
about JobResultActor

### ISSUE THREAD

**Issue by gao634209276** [spark-jobserver/spark-jobserver#1165]
**Used Spark version**
spark 2.2
**Used Spark Job Server version**
Master

**Deployed mode**
(cluster on Spark Standalone/Mesos)

**Actual (wrong) behavior**
When I read the src：[JobResultActor](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/scala/spark/jobserver/JobResultActor.scala), I found it was initialized at [AkkaClusterSupervisor](https://github.com/spark-jobserver/spark-jobserver/blob/819afe5901d98dc89d1ef6b1c06b9c6acd8e9b1b/job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala#L411),
Since I have not deployed these two modes(cluster on Spark Standalone/Mesos), so I do not understand how it work in supervise mode:
When JobServer restart and reconnect to old akka cluster in which still has running contexts([JobServer](https://github.com/spark-jobserver/spark-jobserver/blob/819afe5901d98dc89d1ef6b1c06b9c6acd8e9b1b/job-server/src/main/scala/spark/jobserver/JobServer.scala#L139)), how can JobResultActor work after user submit a job

I begging to know. Thanks !
@bsikander @bsikander @velvia

**Comment by bsikander** [comment]
I don't understand the question fully. Maybe you can clarify a bit.

 JobResultActor is not persisted anywhere, all data is in cache. This means that when Jobserver restarts, we loose all the data stored in cache of JobResultActor. Everything else is persisted.

**Comment by gao634209276** [comment]
JobResultActor is created in JobServer's actorSystem，when Jobserver is restarts, the running context's JobResultActor also will be down, and how can context use the old Jobserver's JobResultActor to cache data?

**Comment by bsikander** [comment]
Yes, it cannot. You are right.

As I was saying that currently, JobResultActor is not cached anywhere and on Jobserver restart it is also not repopulated. So, the context cannot use it to cache data.

This was never too high priority because people generally put the results of their jobs to some external storage like HDFS/C*.

**Comment by gao634209276** [comment]
ok

**Comment by bsikander** [comment]
Btw if you are interested, feel free to contribute. We are here to help. Thanks.

Closing the issue.
