### ISSUE TITLE
how to use Apache Bench to post requests to spark jobserver to running jobs parrally

### ISSUE THREAD

**Issue by taxuefeihong** [spark-jobserver/spark-jobserver#1166]
**Used Spark version**
2.2.1
**Used Spark Job Server version**
(Released version, git branch or docker image version)
master branch
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
cluster on Spark Standalone
**Actual (wrong) behavior**
I have deployed jobserver and try the wordcount example walkthrough success. 
```
curl -d "input.string = test cluster mode" 'Master:8090/jobs?appName=test-cluster&classPath=spark.jobserver.WordCountExample'
```
then how to use Apache Bench to post request to spark jobserver? The aim is to make spark cluster execute jobs parrally to test the reliability of the cluster. 
the command I use now is 
```
ab -n 100 -c 10 -p paras.txt -T ‘application/json’ http://Master:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample   
```
but it didn't make sense, when I 
```
curlMaster:8090/jobs
```
there didn't appear corresponding jobs
then which command shall I use? how can we link apache bench(ab) with spark jobserver restFul api?

**Comment by valan4ik** [comment]
Worked for me:
```
ab -p post.data -n 5 -c 5  -T "application/json" "http://127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample"
```

**Comment by taxuefeihong** [comment]
when I user your command, the result turns to be different compared to the result after running command I first raised。
it seems work, but occurs another Exception
```
Benchmarking 127.0.0.1 (be patient)...apr_pollset_poll: The timeout specified has expired (70007)
```
the content of my post.data is 
```
{
    "input" : {
        "string" : "test apache bench"
    }
}
```
Have you encountered this problem before?

**Comment by taxuefeihong** [comment]
Thanks for your advice!
When I use your command, it seems work. But I encounter another Exception as described in https://github.com/spark-jobserver/spark-jobserver/issues/1166
Have you encountered this problem before?


| |
田亚真
|
|
yzhentian@126.com
|
签名由网易邮箱大师定制


On 03/5/2019 20:36，Valentina<notifications@github.com> wrote：

Worked for me:

ab -p post.data -n 5 -c 5  -T "application/json" "http://127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample"

**Comment by taxuefeihong** [comment]
when I add (-s timeout), it turns out the right answer:
```
ab -p post.data -n 5 -c 5 -s 5000 -T "application/json" "http://127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample"
```
but it didn't make sense, when I run ```curl Master:8090/jobs```
there appeared corresponding jobs
Thanks for your advice!

**Comment by valan4ik** [comment]
@taxuefeihong 
Sorry, can't help you more here, I think it's a bit more about Apache Bench than Jobserver.
That the jobs were here, when you checked `curl Master:8090/jobs` makes perfect, because you just got a timeout exception waiting for the response probably (request was already sent to Jobserver).

Although default timeout for Apache Bench is 30 seconds, it's maybe worth checking out how long does it take you to create one job. Not sure what else comes into play when you use parallel requests with Jobserver API.

**Comment by taxuefeihong** [comment]
The problem has been solved when I add -s 5000 in the command 
Thank you very much!


| |
田亚真
|
|
yzhentian@126.com
|
签名由网易邮箱大师定制


On 03/5/2019 22:55，Valentina<notifications@github.com> wrote：

@taxuefeihong
Sorry, can't help you more here, I think it's a bit more about Apache Bench than Jobserver.
That the jobs were here, when you checked curl Master:8090/jobs makes perfect, because you just got a timeout exception waiting for the response probably (request was already sent to Jobserver).

Although default timeout for Apache Bench is 30 seconds, it's maybe worth checking out how long does it take you to create one job. Not sure what else comes into play when you use parallel requests with Jobserver API.
