### ISSUE TITLE
Jobserver allows to delete binaries for running jobs

### ISSUE THREAD

**Issue by valan4ik** [spark-jobserver/spark-jobserver#1167]
**Actual (wrong) behavior**

User can start a long running job and delete binary during that time. Jobserver allows to delete the binary, but once the binary is deleted there is no way to get information about this job.

For JobSQLDao the Job status is also not getting updated during that time (JobSQLDao always checks existence of the binary before updating status)

**Steps to reproduce**
1. Start LongPiJob from tests
2. Delete binary while the job is running
3. It's not possible to get info through job API anymore and in H2 database Job will always have status "RUNNING"

**Wished behavior**

Before deleting a binary, make a check, that there are no running jobs for this binary.

**Comment by Nibooor** [comment]
This behavior has been fixed with PR: 
https://github.com/spark-jobserver/spark-jobserver/pull/1209
