### ISSUE TITLE
How to access the JobID of a job from with in my spark application

### ISSUE THREAD

**Issue by manasdebashiskar** [spark-jobserver/spark-jobserver#117]
Hi, 
 I would like to store certain intermediate data in a temp folder and delete them when user send's a REST call.
I am thinking /tmp/<JobID>files... will suit my need. 
Hence the question: How can I access the Job ID from with in the spark application?

Thanks
Manas

**Comment by velvia** [comment]
Manas, would you mind asking the question on the google group instead and
closing the issue?  Thanks.

On Tue, Apr 7, 2015 at 12:34 PM, manas <notifications@github.com> wrote:

> Hi,
> I would like to store certain intermediate data in a temp folder and
> delete them when user send's a REST call.
> I am thinking /tmp/files... will suit my need.
> Hence the question: How can I access the Job ID from with in the spark
> application?
>
> Thanks
> Manas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/117>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
Right now there is no way to access the JobID, but this is a good idea.

On Thu, Apr 9, 2015 at 12:48 AM, Evan Chan <velvia@gmail.com> wrote:

> Manas, would you mind asking the question on the google group instead and
> closing the issue?  Thanks.
>
> On Tue, Apr 7, 2015 at 12:34 PM, manas <notifications@github.com> wrote:
>
>> Hi,
>> I would like to store certain intermediate data in a temp folder and
>> delete them when user send's a REST call.
>> I am thinking /tmp/files... will suit my need.
>> Hence the question: How can I access the Job ID from with in the spark
>> application?
>>
>> Thanks
>> Manas
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spark-jobserver/spark-jobserver/issues/117>.
>>
>
>
>
> --
> If you are free, you need to free somebody else.
> If you have some power, then your job is to empower somebody else.
>    --- Toni Morrison
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by manasdebashiskar** [comment]
Hi Evan, 
 Thanks for the info. I would search for the google group for job-server and post my questions there.
