### ISSUE TITLE
Why are there allowed up to two contexts in jobserver?

### ISSUE THREAD

**Issue by taxuefeihong** [spark-jobserver/spark-jobserver#1175]
**Used Spark version**
2.2.1
**Deployed mode**
cluster on Spark Standalone

**Actual (wrong) behavior**
how many context can I curl to Master:8090/contexts?
In practice, I the max number of contexts I can make is 2.
is there any configure needs to be done responding to this?

**Comment by bsikander** [comment]
The number of contexts that you can launch depends on the size of your spark cluster. 

e.g. If you have 50 cores and 100 GB RAM in your cluster and your first context uses all of them then you can only launch 1 but if you configure your context to only use 1 core for driver and 1 for executor then you can launch around 25.

**Comment by taxuefeihong** [comment]
the cores contexts used? is that configured in <environment>.conf?
```
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc
  }
```

**Comment by bsikander** [comment]
This is the default. You can also configure them when you create a context. Documentation can be found [here](https://github.com/spark-jobserver/spark-jobserver#context-configuration)

**Comment by bsikander** [comment]
Closing the issue due to inactivity. Please reopen if the problem is not solved.
