### ISSUE TITLE
CONTEXT INIT ERROR

### ISSUE THREAD

**Issue by sushanth-hi** [spark-jobserver/spark-jobserver#1181]
**Used Spark version**
2.2.0

**Used Spark Job Server version**
0.8.0
**Deployed mode**
Cluster
YARN

**Actual (wrong) behavior**
- Create a context using curl command.
- Delete the same context.
- Again create the context. This will fail with a message "**Context failed to connect back within initialization time**" 

**Steps to reproduce**
- Deploy the SJS jar to master with YARN-Cluster settings.
- Start SJS.
- Use curl or use Insomnia request to create context. 
- Now delete the context and try to re-create.

**Logs**
[2019-03-26 08:15:13,501] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - **Starting context with actor name jobManager-a217888a-de4b-4c1e-af63-a6b6a0a8c1e9**
[2019-03-26 08:15:13,501] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - **Created working directory /opt/user/spark-job-server/logs/jobserver-spark-context5065055417856614958 for context spark-context**
[2019-03-26 08:15:13,530] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - **Initializing spark launcher**
[2019-03-26 08:15:13,530] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - **Adding custom arguments to launcher**
[2019-03-26 08:15:13,531] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - **Start launcher application**
[2019-03-26 08:15:13,534] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - **Scheduling a time out message for forked JVM**
[2019-03-26 08:15:43,551] WARN  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - **Context forked JVM failed to initialize for actor jobManager-a217888a-de4b-4c1e-af63-a6b6a0a8c1e9**

**Comment by bsikander** [comment]
Can you please share your driver logs and also logs from the spark-submit folder?

**Comment by sushanth-hi** [comment]
Attaching the logs

[logs.txt](https://github.com/spark-jobserver/spark-jobserver/files/3007456/logs.txt)

[containerLogs.txt](https://github.com/spark-jobserver/spark-jobserver/files/3007458/containerLogs.txt)

[spark-job-server.txt](https://github.com/spark-jobserver/spark-jobserver/files/3007460/spark-job-server.txt)

**Comment by bsikander** [comment]
Can you also share you logs from the following folder?
/opt/user/spark-job-server/logs/jobserver-spark-context5065055417856614958

Also, your configuration file and .sh file e.g. local.conf and local.sh file

**Comment by sushanth-hi** [comment]
**prod.conf**

```
# Spark Cluster / Job Server configuration
spark {
  master = "yarn"

  submit.deployMode = "cluster"

  job-number-cpus = 4

  jobserver {
    port = 8090

    context-per-jvm = true

    # Note: JobFileDAO is deprecated from v0.7.0 because of issues in
    # production and will be removed in future, now defaults to H2 file.
    jobdao = spark.jobserver.io.JobSqlDAO

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    datadao {
      # storage directory for files that are uploaded to the server
      # via POST/data commands
      rootdir = /tmp/spark-jobserver/upload
    }

    sqldao {
      # Slick database driver, full classpath
      slick-driver = slick.driver.H2Driver

      # JDBC driver, full classpath
      jdbc-driver = org.h2.Driver

      # Directory where default H2 driver stores its data. Only needed for H2.
      rootdir = /tmp/spark-jobserver/sqldao/data

      jdbc {
        url = "jdbc:h2:tcp://xx.xx.xx.xxx:9092/~/spark-job-h2-db/h2-db;AUTO_RECONNECT=TRUE"
      }

      # DB connection pool settings
      dbcp {
        enabled = false
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
    startH2Server = false
    
    result-chunk-size = 1m
  }



  # Universal context configuration. 
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.


    passthrough {
      #es.nodes = "192.1.1.1"
    }
  }

}

akka {
  remote.netty.tcp {
    hostname = "xx.xx.xx.xxx"
    # This controls the maximum message size, including job results, that can be sent
    maximum-frame-size = 100 MiB
  }
}

```

**prod.sh**
```
#!/usr/bin/env bash

DEPLOY_HOSTS="xx-xx-xx-xxx"

APP_USER=user
APP_GROUP=spark
JMX_PORT=9999
# optional SSH Key to login to deploy server
#SSH_KEY=/path/to/keyfile.pem
INSTALL_DIR=/opt/user/spark-job-server
LOG_DIR=/opt/user/spark-job-server/logs
PIDFILE=/opt/user/spark-job-server/spark-jobserver.pid
JOBSERVER_MEMORY=1G
SPARK_VERSION=2.2.0
MAX_DIRECT_MEMORY=512M
SPARK_HOME=/opt/lib/spark2
SPARK_CONF_DIR=/opt/lib/spark2/conf

SCALA_VERSION=2.11.6 # or 2.11.6


MANAGER_JAR_FILE="$appdir/spark-job-server.jar"
MANAGER_CONF_FILE="$conffile"
MANAGER_EXTRA_JAVA_OPTIONS=
MANAGER_EXTRA_SPARK_CONFS=
MANAGER_LOGGING_OPTS="-Dlog4j.configuration=file:$appdir/log4j-server.properties"
SPARK_LAUNCHER_VERBOSE=0

```

The above attachment has the logs from "**/opt/user/spark-job-server/logs/jobserver-spark-context5065055417856614958**" with name "**spark-job-server.txt**"

**Comment by bsikander** [comment]
If you set SPARK_LAUNCHER_VERBOSE=1 in prod.sh, then you can see more information inside spark-job-server.txt.

The problem seems to be 
```
19/03/26 07:49:25 ERROR HadoopFSFacade: File /opt/user/spark-job-server/prod.conf does not exist
```

Basically, when you the driver starts, it needs to load the configuration file of jobserver. The path to configuration is passed in JVM arguments. `MANAGER_CONF_FILE` variable inside prod.sh is actually the path of configuration file.

Since you are using cluster mode, you have 2 options
- Either the prod.conf should be available to all containers at path `/opt/user/spark-job-server/prod.conf`
- Or you put the prod.conf in HDFS/s3 and put the path in `MANAGER_CONF_FILE` e.g. 
```
MANAGER_CONF_FILE="hdfs://<IP>:<Port>/path/to/prod.conf"
```

**Comment by sushanth-hi** [comment]
I tried with the first option and even added SPARK_LAUNCHER_VERBOSE=1.  It did provide logs about spark configuration, 

but issue still persists i.e 
```
ERROR HadoopFSFacade: File /opt/user/spark-job-server/prod.conf does not exist
```
Attaching the logs. 

[spark-job-server.txt](https://github.com/spark-jobserver/spark-jobserver/files/3008626/spark-job-server.txt)
[logs_sc.txt](https://github.com/spark-jobserver/spark-jobserver/files/3008627/logs_sc.txt)


I have just added the prod.conf file in that location. Is that enough?

Thank you for your support.

**Comment by bsikander** [comment]
The issue still remains the same. The container cannot find the prod.conf file.

How did you provide the container with prod.conf file?
Since in your setup you have hadoop, please also try to put the conf file in hadoop and try to use option#2 and see if that works.

**Comment by sushanth-hi** [comment]
@bsikander Thanks a lot :+1:  . HDFS approach worked and I'm able to create context.
