### ISSUE TITLE
Possible quick releasing of 0.9.1?

### ISSUE THREAD

**Issue by smiklosovic** [spark-jobserver/spark-jobserver#1182]
@noorul , all 

Is there any will to release quick 0.9.1 with this commit?

https://github.com/spark-jobserver/spark-jobserver/commit/be00f0ef2aa81bef2226f7fdfb7934d26caae411

We would like to use it in our releases exactly with this commit included and it is quite unfortunate we have to reference to 0.9.1-SNAPSHOT and not to official build.

**Comment by bsikander** [comment]
@noorul @velvia should we do a quick release?

**Comment by TharinduAmila** [comment]
Any updates on this, I would also like to have a release including fixes for dependencies of cassandra connector

**Comment by valan4ik** [comment]
Release 0.10.0 was recently released. I will close the issue as it seems to be outdated now.
