### ISSUE TITLE
Persist job results

### ISSUE THREAD

**Issue by ffarozan** [spark-jobserver/spark-jobserver#119]
RESTEndpoint .../jobs works from persisted result. But the .../jobs/{jobId} fails across job server restarts. Is this an issue or is this a pending feature to be implemented?

**Comment by velvia** [comment]
Can you describe in more detail what you are seeing?   It should work
across restarts, assuming that job server is configured to talk to a real
database.

On Wed, Apr 8, 2015 at 8:17 AM, Firdousi Farozan Zackariya <
notifications@github.com> wrote:

> RESTEndpoint .../jobs works from persisted result. But the
> .../jobs/{jobId} fails across job server restarts. Is this an issue or is
> this a pending feature to be implemented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/119>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ffarozan** [comment]
I did not configure job server with an external DB, but used the default fileDao as well as the embedded H2 SqlDao.

What I see, across restarts is:
1. <url>/jobs is able to show the jobs executed in the previous starts
2. <url>/jobs/<jobid> returns NoSuchJobID error for a jobid from an earlier start. It works fine for a jobid from the current start

**Comment by ffarozan** [comment]
After discussion with Evan on this topic on the mailing list, I will file new issues for supporting these features.
1. Expose JobId to jobs
2. Asynchronous notification to callers, once job completes.

**Comment by nemccarthy** [comment]
We would be interested in having the SJS persist the Job Result in the database. I think this would also be a step in the right direction to HA. We are running in a dockerized environment (on Mesos). If the SJS container goes down and any Async jobs were running but the application on the other end hadn't polled for the job result, it would be lost.

**Comment by velvia** [comment]
Ok.  This is a good idea.  

There are two approaches:

- save the result of a job that the job outputs
- save an RDD somehow

You are talking about #1, where the result size is not huge right?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by nemccarthy** [comment]
Thanks Evan. 

Yes I'm thinking about option 1. I think it would be awesome if we could make a pluggable API for result storage. The default is the LRU cache. For jobs where there isn't a large result set we could have the SQL backed implementation.

In the case of 'huge' results, I would assume the common pattern people are using is that they are not sending those results through the SJS, but rather they are persisting the RDD as part of the job some where (HDFS/S3 etc) and the SJS job result is just a path to the result file. The actual result retrieval is then left as an exercise for the client. I don't think we'd want to be streaming large results through the SJS. I guess if we had a decent storage implementation this might be possible...

In our specific use case we probably have result objects in the 10s of MB range max. Storing these a LOBs in the DB should be ok. 

Thoughts? 

Should I create a new issue for this one? Happy to work on it!

**Comment by velvia** [comment]
Nathan,

I think I agree with your premise.  Yes, go ahead and work on it, and feel
free to reach out for help!

On Wed, Sep 23, 2015 at 6:54 PM, Nathan <notifications@github.com> wrote:

> Thanks Evan.
>
> Yes I'm thinking about option 1. I think it would be awesome if we could
> make a pluggable API for result storage. The default is the LRU cache. For
> jobs where there isn't a large result set we could have the SQL backed
> implementation.
>
> In the case of 'huge' results, I would assume the common pattern people
> are using is that they are not sending those results through the SJS, but
> rather they are persisting the RDD as part of the job some where (HDFS/S3
> etc) and the SJS job result is just a path to the result file. The actual
> result retrieval is then left as an exercise for the client. I don't think
> we'd want to be streaming large results through the SJS. I guess if we had
> a decent storage implementation this might be possible...
>
> In our specific use case we probably have result objects in the 10s of MB
> range max. Storing these a LOBs in the DB should be ok.
>
> Thoughts?
>
> Should I create a new issue for this one? Happy to work on it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/119#issuecomment-142781331>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison
