### ISSUE TITLE
NameRdd loses rdd when the jobserver has runned for a long time

### ISSUE THREAD

**Issue by pharosa** [spark-jobserver/spark-jobserver#121]
I established a spark-jobserver to store rdd for reusing among different jobs. But laterly the NameRdd will lose the registered rdd when the spark-jobserver has runned for a relative long time. In the Spark log I found that the rdd has been removed when no remove action is called. I look into the job-server code and find out that in RddManagerActor the rdd is stored in 
private val namesToRDDs = new mutable.HashMap[String, RDD[_]]()
. Theoretically that is definitely right becasue the rdd reference is store with a StrongReference. But the rdd will disappear in practice, So I reassign the rdd reference to a static variable in addition to putting the reference in the namesToRDDS. The code is somehow like blow:
object ReferenceHolder{
val rdd:RDD =....
}
Then the rdd stop disappearing.
Even if adding a strong reference fixes it, I still cannot figure out the real reason why the namesToRDDS failed to retain rdd reference.

**Comment by velvia** [comment]
Spark naturally removes stale RDDs after a certain time.  See the
spark.cleaner.ttl
property.

Details please?  (version of Spark, job server, environment, ow you're
running, logs, etc.)

On Thu, Apr 9, 2015 at 9:13 PM, Aphid <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/121>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by hntd187** [comment]
Since this is almost a year old please try the latest version of the code if you are still having issues please open a new issue. Thanks.
