### ISSUE TITLE
Memory leak with JobResultActor

### ISSUE THREAD

**Issue by bklostermann** [spark-jobserver/spark-jobserver#1227]
**Used Spark version**
2.2.0

**Used Spark Job Server version**
0.9.0

**Deployed mode**
EMR
context-per-jvm = true

**Actual (wrong) behavior**
We create 3 Spark Contexts and run jobs against those contexts.  After awhile those Spark Contexts will be deleted, and new ones created in its place.  SJS will eventually run out of memory.  When inspecting the heap dump, all JobResultActors remain in memory permanently (even for the Spark Contexts that were deleted).  Consequently those JobResultActors also retain their LRU cache.  Is there any way to have those old JobResultActors released?

**Steps to reproduce**
Create Spark Contexts, run jobs, and then delete contexts. Repeat.

**Comment by Nibooor** [comment]
Hi,

you are right, it seems like the jobserver (or jobmanager) never terminates any result actor after the contexts are stopped.

Probably most SJS users don't encounter this problem as 
  a) job results are often written to a database directly (so resultActors typically have a minor load)
  b) a restart of the spark slave will free the memory eventually.

So unless you want to circumvent the issue by persisting job results in a database, I think a code modification would be necessary to address this leak.
Contributions are of course always welcome.

**Comment by Nibooor** [comment]
See https://github.com/spark-jobserver/spark-jobserver/pull/1375
