### ISSUE TITLE
is there a deamon to do job (jar files) clean up?

### ISSUE THREAD

**Issue by liu-hongwei** [spark-jobserver/spark-jobserver#124]
hi, 

day after day, there will be tons of jar files uploaded to the spark job server, is there an existed way to automatically clean up the old jobs , jar files ?

Thanks

**Comment by velvia** [comment]
Hi Liu,

Not currently, but it would be pretty easy to run a cron script on your
database to clean up the old jars.  At Ooyala we did not release new
version of jars more frequently than every week and under the same name, so
it wasn't a problem.

-Evan

On Mon, Apr 13, 2015 at 9:23 AM, liu-hongwei <notifications@github.com>
wrote:

> hi,
>
> day after day, there will be tons of jar files uploaded to the spark job
> server, is there an existed way to automatically clean up the old jobs ,
> jar files ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/124>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by noorul** [comment]
I think the answer is pretty clean. Closing this.
