### ISSUE TITLE
Is it possible to enable CORS for spark-jobserver (Access-Control-Allow-Origin)

### ISSUE THREAD

**Issue by parer800** [spark-jobserver/spark-jobserver#125]
Hi,

I'm developing an app that will make http request to the spark-jobserver (through the browser), and I'm getting trouble with "Access-Control-Allow-Origin". Is it possible to define something like "Access-Control-Allow-Origin: *" ?
Or will I have to patch the urls with a CORS proxy server?

**Comment by parer800** [comment]
Probably should mention that I'm using this: https://github.com/gr2m/CORS-Proxy as a workaround. And calling the url below from the web client.
``` javascript
url: "http://127.0.0.1:9292/localhost:8090/jobs?appName=..."
```

**Comment by velvia** [comment]
This should not be hard to enable at all.   I found this:

https://gist.github.com/ayosec/4324747
https://coderwall.com/p/0izzta/cors-directive-for-spray

Of course if a PR is submitted that will speed things up  :)

On Tue, Apr 14, 2015 at 6:57 AM, Pär Eriksson <notifications@github.com>
wrote:

> Probably should mention that I'm using this:
> https://github.com/gr2m/CORS-Proxy as a workaround. And calling the url
> below from the web client.
>
> url: "http://127.0.0.1:9292/localhost:8090/jobs?appName=..."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/125#issuecomment-92860602>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by hntd187** [comment]
Closing this since the latest code has CORs support.
