### ISSUE TITLE
Support for Spark 2.4

### ISSUE THREAD

**Issue by jeynesrya** [spark-jobserver/spark-jobserver#1253]
Is there a plan to add support for Apache Spark 2.4?

**Comment by valan4ik** [comment]
@bsikander @Nibooor and I have it on our TODO list. But we won't probably contribute it soon.

If you are interested in the topic, contributions are very welcome :)

**Comment by murraytodd** [comment]
Are there any known issues that need to be addressed, or is this simply a matter of updating various dependency versions and testing? If the latter, I may be able to contribute time & effort.

**Comment by bsikander** [comment]
@murraytodd actually I have already implemented 2.4 upgrade. It will be pushed soon. Stay tuned :)

**Comment by murraytodd** [comment]
> @murraytodd actually I have already implemented 2.4 upgrade. It will be pushed soon. Stay tuned :)

Brilliant! I'll relay that to my team!

**Comment by jeynesrya** [comment]
> @murraytodd actually I have already implemented 2.4 upgrade. It will be pushed soon. Stay tuned :)

That's brilliant news! That release will be a game changer for us - thanks!

**Comment by bsikander** [comment]
@murraytodd @jeynesrya great that it helps you but please note that k8s support is still not there.

**Comment by murraytodd** [comment]
> @murraytodd @jeynesrya great that it helps you but please note that k8s support is still not there.

That's fine. It's the improved Spark Structured Streaming in 2.4 that we've been waiting for. (And being able to support general Spark 2.4 environments. SJS is our application's bridge (and is very important based on some of our just-in-time computational functionality) so it dictates our Spark version dependencies.

**Comment by bsikander** [comment]
@jeynesrya @murraytodd 2.4.4 change is merged in master. Next release of jobserver (coming soon) will also support 2.4.4.

**Comment by jeynesrya** [comment]
That's excellent news. Will the release include a docker image pushed in Dockerhub or is that for each person to do individually?

**Comment by bsikander** [comment]
Regarding automatic publishing of docker, i am not sure. I will get back to you.

**Comment by bsikander** [comment]
@jeynesrya currently, we have not pusblished to docker. The machinery is not ready. For now, you have to go indivually. In future, we plan to add this to the automatic publishing.

Feel free to contribute here.

**Comment by jeynesrya** [comment]
> @jeynesrya currently, we have not pusblished to docker. The machinery is not ready. For now, you have to go indivually. In future, we plan to add this to the automatic publishing.
> 
> 
> 
> Feel free to contribute here.

Thanks for the update! If I manage to get the job server running in Docker, I’ll contribute as mentioned 😊

**Comment by bsikander** [comment]
You can find an example here. I did this some time ago but it needs to be updated and improved.
https://hub.docker.com/repository/docker/bsikander/sjs

**Comment by bsikander** [comment]
Closing issue since jobserver has been release with this version.
