### ISSUE TITLE
Docker Image for JobServer 0.9.0-SNAPSHOT

### ISSUE THREAD

**Issue by KhanhTrinh1703** [spark-jobserver/spark-jobserver#1259]
I'm using **SparkSessionJob** to connect Database with **JobServer version 0.9.0-SNAPSHOT**. Is there any **docker image** support for version 0.9.0-SNAPSHOT? 
Current docker image just supports for **0.7.0**

**Comment by valan4ik** [comment]
You can build your own docker image by cloning jobserver repository and running `sbt docker`.
Note: Don't forget to use `export SCALA_VERSION=2.11.x` if you are using Scala 2.11.

I will close the ticket, please reopen it if there are any questions left.
