### ISSUE TITLE
Unable to run spark-jobserver with CDH yarn-client mode

### ISSUE THREAD

**Issue by josealvarezmuguerza** [spark-jobserver/spark-jobserver#126]
I've set a mini cluster with 8 nodes CDH 5.3.2. Load spark-job server in one of them(10.10.10.101). From my remote machine I send the curl command for trigger a spark job. (ctx and jar already created) and I get a ClassNotFoundException when spark job is running in one data nodes, 10.10.10.107:

Stdoutput {
  Stdoutput   "status": "ERROR",
  Stdoutput   "result": {
  Stdoutput     "message": "Job aborted due to stage failure: Task 3 in stage 3.0 failed 4 times, most recent failure: Lost task 3.3 in stage 3.0 (TID 38, *10.10.10.107*): java.lang.NoClassDefFoundError: spark/jobserver/SparkJob\n\tat java.lang.ClassLoader.defineClass1(Native Method)\n\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)\n\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)\n\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)\n\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)\n\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)\n\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)\n\tat xxx.xxx.xxxxx.xxxxxMyScalaclass$$anonfun$3.apply(Myscalaclass.scala:68)\n\tat xxx.xxx.xxxxx.xxxxxMyScalaclass$$anonfun$3.apply(Myscalaclass.scala:68)\n\tat scala.collection.Iterator$$anon$11.next(Iterator.scala:328)\n\tat org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:249)\n\tat org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:163)\n\tat org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:70)\n\tat org.apache.spark.rdd.RDD.iterator(RDD.scala:228)\n\tat org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)\n\tat org.apache.spark.scheduler.Task.run(Task.scala:56)\n\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.ClassNotFoundException: spark.jobserver.SparkJob\n\t at java.net.URLClassLoader$1.run(URLClassLoader.java:366)\n\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)\n\t... 24 more\n\nDriver stacktrace:",
  Stdoutput     "errorClass": "org.apache.spark.SparkException",
  Stdoutput     "stack": ["org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1214)", "org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1203)", "org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1202)", "scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)", "scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)", "org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1202)", "org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)", "org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)", "scala.Option.foreach(Option.scala:236)", "org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:696)", "org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1420)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)", "akka.actor.ActorCell.invoke(ActorCell.scala:456)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)", "akka.dispatch.Mailbox.run(Mailbox.scala:219)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"]
  Stdoutput   }

**Comment by josealvarezmuguerza** [comment]
So far, I've solved the issue by creating a fat jar with server api dependency included. My jar turned from less than 100kb to 9.3Mb weight. If somebody have a more elegant solution please let me know.

**Comment by velvia** [comment]
@josealvarezmuguerza  Try my newest PR, #164, which uses spark-submit instead.  May solve your issue.

**Comment by zeitos** [comment]
Closing this one for inactivity
