### ISSUE TITLE
Uploading a new binary file creted clone in BINARIES and grow table to lock issue.

### ISSUE THREAD

**Issue by vassav-nn** [spark-jobserver/spark-jobserver#1268]
**Used Spark version**
2.4.0.3.1.2.1-1 and less

**Used Spark Job Server version**
(Released version, git branch or docker image version)

**Deployed mode**
cluster on Spark Standalone + mysql Current version of schema *** : 0.7.10

**Actual (wrong) behavior**
curl POST of jar of sjs-test creates clone task in BINARIES and BINARIES_CONTENTS instead of update it.

After 150+ rows any delete commund was stuck in TO and affect any other tasks with:
ERROR ark.jobserver.io.JobSqlDAO [] [akka://JobServer/user/dao-manager] - Lock wait timeout exceeded; try restarting transaction

**Steps to reproduce**
used sbt sjs/assembly for build sjs-assembly-0.1-SNAPSHOT.jar 

curl -k -X POST -H "Content-Type: application/java-archive" --basic --user "$(cat /proxyuser):$(cat /proxypassword)" --data-binary @sjs/target/scala-2.11/sjs-assembly-0.1-SNAPSHOT.jar https://***/jars/sjs-test

curl -k -d '' -X PUT --basic --user <same> https://***/contexts?reset=reboot

Got 150+ clones in DB

Can stuck local testing like:
delete from `BINARIES_CONTENTS` where `BINARIES_CONTENTS`.`BIN_HASH` in (select `BIN_HASH` from `BINARIES` where `APP_NAME` = 'sjs-test');

**Logs**

```
[2019-12-04 15:34:18,241] INFO  rk.jobserver.BinaryManager [] [akka://JobServer/user/binary-manager] - Deleting binary pysj-***
[2019-12-04 15:35:09,697] ERROR ark.jobserver.io.JobSqlDAO [] [akka://JobServer/user/dao-manager] - Lock wait timeout exceeded; try restarting transaction
com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
...
```

**Comment by vassav-nn** [comment]
For info if smb got same problems: just save critical info and truncate tables.

**Comment by valan4ik** [comment]
Hi @vassav-nn ,

It's kind of a "feature", that the binary information is not overwritten. I think it had some historical design reasons. In general, you can see in DB all the versions of the binary under the same name.
You are right, we can check if it can be changed now (I think anyways only the latest binary is used if you restart the job), but so far all DAOs act like this.

One of the ways to avoid it is to use different binary names and delete binaries from time to time.

**Comment by vassav-nn** [comment]
> Hi @vassav-nn ,
> One of the ways to avoid it is to use different binary names and delete binaries from time to time.
I think is better to refactor primary key in table BINARIES_CONTENTS from | BIN_HASH | varbinary(32) | to normal index (BIN_ID from BINARIES for example). 
With BIN_HASH is primary key the deleting one of 200 rows in BINARIES_CONTENTS takes 15+ mins

**Comment by vassav-nn** [comment]
I can close issue if you want, just left it for google.
