### ISSUE TITLE
Support HDFS paths in jar loader?

### ISSUE THREAD

**Issue by vishalvibhandik** [spark-jobserver/spark-jobserver#127]
HI,
we are running spark 1.1.0 in standalone cluster mode.
Job server 0.4.1
whenever the job server starts a new job it copies the application jar to /var/run/work/<app id>/jars on each executor.
1. is there a way to stop copying these jars to above path on each executor? can the application jar be copied only once on each node of the cluster and that classpath can be used for each job run?
2. is there a way to delete these jars after the job is completed?

**Comment by velvia** [comment]
Hi,

The executor class loader loads the jar through an HTTP service that the
Spark Context itself runs.  It's part of Spark's own mechanism for
distributing jars.  The only way to really overcome it would be to
implement an option to put the jar on HDFS or some other shared file system
visible to every Spark node, and thus would not need to be downloaded to
every node.  This jar could then be managed by the job server.

Does the above sound useful?

On Fri, Apr 17, 2015 at 10:37 AM, vishalvibhandik <notifications@github.com>
wrote:

> HI,
> we are running spark 1.1.0 in standalone cluster mode.
> Job server 0.4.1
> whenever the job server starts a new job it copies the application jar to
> /var/run/work//jars on each executor.
> 1. is there a way to stop copying these jars to above path on each
> executor? can the application jar be copied only once on each node of the
> cluster and that classpath can be used for each job run?
> 2. is there a way to delete these jars after the job is completed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/127>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by vishalvibhandik** [comment]
thank you Evan.
this is helpful.
In can upload the jar to hdfs which is visible to all the nodes.
But what settings do I need to make while starting the job using the job server?
I mean how does the job server and the workers know where the jar is located?
are there any settings that i need to apply while creating the context?

**Comment by velvia** [comment]
Vishal,

I was saying we would need to modify job server so it saves jars in HDFS
instead of locally in your file system.

However, for dependent jars (say you are using Cassandra Connector etc.),
you can store those in HDFS to make job startup faster.   Just put your
dependent jar in HDFS and then set dependent-jar-uris = ["hdfs://......."]


On Tue, Apr 21, 2015 at 10:19 AM, vishalvibhandik <notifications@github.com>
wrote:

> thank you Evan.
> this is helpful.
> In can upload the jar to hdfs which is visible to all the nodes.
> But what settings do I need to make while starting the job using the job
> server?
> I mean how does the job server and the workers know where the jar is
> located?
> are there any settings that i need to apply while creating the context?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/127#issuecomment-94878168>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by vishalvibhandik** [comment]
thanks Evan.

**Comment by v-gerasimov** [comment]
Hi!
When I set dependent-jar-uris like ["hdfs://......."], I got the error:
```
    "message": "unknown protocol: hdfs",
    "errorClass": "java.net.MalformedURLException"
```
How can I solve this problem? Use java protocol.handler?

**Comment by velvia** [comment]
Ah, hm, that is a bug, probably because we are using the default java
UriClassLoader, which doesn't understand hdfs.

On Fri, Apr 24, 2015 at 4:25 AM, v-gerasimov <notifications@github.com>
wrote:

> Hi!
> When I set dependent-jar-uris like ["hdfs://......."], I got the error:
>
>     "message": "unknown protocol: hdfs",
>     "errorClass": "java.net.MalformedURLException"
>
> How can I solve this problem? Use java protocol.handler?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/127#issuecomment-95904088>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by zeitos** [comment]
@velvia I didn't read the whole thread, is this still a bug or was it fixed?

**Comment by velvia** [comment]
@zeitos I don't think this is fixed.  We should probably rename the title though.

**Comment by noorul** [comment]
@zeitos @velvia  Is this really a bug? Isn' t this enhancement?

**Comment by hntd187** [comment]
We should just use the Hadoop API to read files then we'd be able to support a wide array of file locations. But technically right now it does seem to be more of an enhancement.

**Comment by velvia** [comment]
Sure.  It’s because we just directly use URLClassLoader which of course doesn’t support HDFS.   The possible solution is just not to use our own class loader.  Spark has evolved enough that we might not need to use our own anymore.

**Comment by DatPhanTien** [comment]
Dear all, do you have any update on this enhancement? Is it closed now or on-going?

**Comment by bsikander** [comment]
Using HDFS implementation of new BinaryDAO, we can store and read the jar files from Hadoop. Jobserver is also able to read the config and jar file of jobserver itself from hadoop. The relevant changes are
https://github.com/spark-jobserver/spark-jobserver/pull/1169
https://github.com/spark-jobserver/spark-jobserver/pull/1136

Closing.
