### ISSUE TITLE
Recive Json File 

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [spark-jobserver/spark-jobserver#129]
hi, team
its possibile to recive a json file ?

**Comment by velvia** [comment]
Sorry can you explain more?   The configuration passed into a job can be
JSON, yes.

On Thu, Apr 23, 2015 at 10:41 AM, Benkhaoua <notifications@github.com>
wrote:

> hi, team
> its possibile to recive a json file ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/129>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by sidahmedbenkhaoua** [comment]
non is possible send to job a file json as 
data{
"id":"1",
"name":"aaa"
}

**Comment by sidahmedbenkhaoua** [comment]
and how i get it in job

**Comment by velvia** [comment]
So let me understand: data.name is the name of the json file you wish to
ingest?

Where is this file located?

In the current implementation, it's guaranteed that the spark job would get
executed on the same host as the job server itself, so your job could
simply read the json file directly in its code (but be careful to not do
this within RDD transformation code, which would get run on each Spark
executor instead).

If this file is located say on HDFS or somewhere shared, and you want to
process it in Spark, then you can simply use the sc.textFile(....) (or
sqlContext.jsonFile(...)) to process the files in parallel.


On Fri, Apr 24, 2015 at 2:29 AM, Benkhaoua <notifications@github.com> wrote:

> and how i get it in job
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/129#issuecomment-95868705>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by petro-rudenko** [comment]
If the file is local you can just use next syntax for curl:
```
curl -H "Content-Type: application/json" --data @myfile.json -X POST ...
```

**Comment by velvia** [comment]
@sidahmedbenkhaoua is the comment from @petro-rudenko good enough?

**Comment by velvia** [comment]
Closing, feel free to reopen if still an issue
