### ISSUE TITLE
Google groups for spark-jobserver is not accessible

### ISSUE THREAD

**Issue by ap-osd** [spark-jobserver/spark-jobserver#1294]
There wasn't any way to reach out to the administrator of the spark-jobserver Google groups for dev questions. So I'm using this channel. I hope someone here can address it.

The groups mentioned in the contact section [https://groups.google.com/forum/#!forum/spark-jobserver]( https://groups.google.com/forum/#!forum/spark-jobserver) cannot be accessed by non members. There is no option to join the group too.

Some recent changes to Google groups could be the issue.

> Go to your  group setting  https://groups.google.com/forum/#!groupsettings/YourGroups Name 
> then    Manage Group > Information > Directory - "Group directory" - the setting to be set to "Anyone on the web" or else users who aren't members won't be able to discover the group at all as result of recent changes.

**Comment by velvia** [comment]
@ap-osd  I have fixed the permissions.... please try again, thanks!

**Comment by velvia** [comment]
and feel free to reopen if it still has a problem.
