### ISSUE TITLE
Need a way to configure H2 DB port 

### ISSUE THREAD

**Issue by pgouda89** [spark-jobserver/spark-jobserver#1302]
**Used Spark version**
2.4

**Used Spark Job Server version**
0.9
**Deployed mode**
Yarn Cluster
**Actual (wrong) behavior**
Currently, it uses hardcoded port 9092 to start H2DB port. We have an issue where D2 DB port is not available on the job-server machine
**Steps to reproduce**
1. Create Spark-job server to talk to CDH cluster on a machine. 
2. Execute spark tasks against CDH cluster.
3. Create Spark job-server to submit the jobs to HDP cluster on the same machine
4. Try to execute the job.
5. Both the spark job server will use the same H2DB instance as the port is 9092 always

**Comment by valan4ik** [comment]
Hi @pgouda89,

As far as I know, it's up to you how to configure H2, you just let Jobserver know which connection string to use, e.g.:
``` 
    sqldao {
      jdbc {
        url = "jdbc:h2:tcp://CLUSTER-IP:9092/h2-db;AUTO_RECONNECT=TRUE"
      } 
    }
```
Did you try putting another port in this connection string? Or do you face some other issue?

**Comment by pgouda89** [comment]
Hi @valan4ik,
Using different port in sqldao.jdbc.url didn't help. The issue is with the way Spark job-server creates the H2 DB server. We were not passing the port details to start H2 DB server in the createTcpServer() function call.
` if (config.getBoolean("spark.jobserver.startH2Server")) {
      val rootDir = config.getString("spark.jobserver.sqldao.rootdir")
      val h2 = org.h2.tools.Server.createTcpServer("-tcpAllowOthers", "-baseDir", rootDir).start();
      logger.info("Embeded H2 server started with base dir {} and URL {}", rootDir, h2.getURL: Any)
    }`

I have used the following code in my local setup to bypass the issue:
`  if (config.getBoolean("spark.jobserver.startH2Server")) {
      val rootDir = config.getString("spark.jobserver.sqldao.rootdir")
      var h2ServerPort = config.getInt("spark.jobserver.h2ServerPort")
      if ( h2ServerPort == 0 ) {
         h2ServerPort = 9092
      }
      val h2 = org.h2.tools.Server.createTcpServer(
                           "-tcpPort", h2ServerPort.toString, "-tcpAllowOthers", "-baseDir", rootDir).start();
      logger.info("Embeded H2 server started with base dir {} and URL {}", rootDir, h2.getURL: Any)
    }`
I have perameterized H2 DB server port "h2ServerPort" and spark job-server uses the default port(9092) if the env.conf does not contain "spark.jobserver.startH2Server".

**Comment by bsikander** [comment]
Property `spark.jobserver.startH2Server` is optional. If you don't want to start H2 on your own then you can use this property as jobserver will quickly spin up an embedded H2.

You can just set this property to false and start H2 on your own and pass the connection string. This should work.

**Comment by pgouda89** [comment]
Hi @bsikander,

I agree, spark.jobserver.startH2Server is an optional configuration. I feel SJS should take optional port details as well to start the H2 Db server. Managing H2 DB outside SJS will be additional overhead for the user. In our use case, we had to start and configure multiple SJS on a single machine to talk to different Hadoop clusters. To be honest fixing SJS code was the best solution compare to create and manage the external H2 DB servers.
 
Thanks,
Prabhakar

**Comment by bsikander** [comment]
>>  I feel SJS should take optional port details as well to start the H2 Db server
sure, you should contribute the code back to sjs :). We can help you also.

>> In our use case, we had to start and configure multiple SJS on a single machine to talk to different Hadoop clusters
Just an FYI, you can use single jobserver to deploy jobs on many clusters. While spinning up the context, you can pass the master address :).

**Comment by bsikander** [comment]
btw H2 is not a production DB and should be used carefully. It is not stable. For production scenarios, mysql/postgres are recommended.

**Comment by bsikander** [comment]
Closing the ticket. If you need more help then please reopen.
