### ISSUE TITLE
Need a way to set custom spark-context name(Yarn application name)

### ISSUE THREAD

**Issue by pgouda89** [spark-jobserver/spark-jobserver#1303]
**Used Spark version**
2.4.0
**Used Spark Job Server version**
0.9
**Deployed mode**
Yarn cluster
**Actual (wrong) behavior**
Spark context name is hard-coded to "spark.jobserver.JobManager"
**Steps to reproduce**
1. Start spark job-server
2. Create a spark context.
Currently, we don't have a mechanism to change spark context name(appName)
![Untitled](https://user-images.githubusercontent.com/45407645/81489577-d8fe1280-922b-11ea-8609-f1edde60cdb8.png)

Unused parts of this template should be removed (including this line).

**Comment by valan4ik** [comment]
Hi @pgouda89,

I don't use YARN, but I think there was a fix for Jobserver exactly for this issue:
https://github.com/spark-jobserver/spark-jobserver/pull/1156

The thing is that it was pushed couple commits after release `0.9.0` was made.
You may need to cherry-pick this change or use newly released Jobserver `0.10.0`.

**Comment by pgouda89** [comment]
Awesome, This seems duplicate of #1156
