### ISSUE TITLE
Can we submit a SparkSessionJob without pre-defined context? 

### ISSUE THREAD

**Issue by vishnuchelle** [spark-jobserver/spark-jobserver#1304]
**Used Spark version**
2.2.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8.0
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)
cluster
**Actual (wrong) behavior**
wrong
**Steps to reproduce**
- Write a new Spark application extending the SparkSessionJob. Below I have provided the worksbount example I used from the docs. 
```
object WordCountExampleSparkSession extends SparkSessionJob {
  type JobData = Seq[String]
  type JobOutput = collection.Map[String, Long]

  override def runJob(sparkSession: SparkSession, runtime: JobEnvironment, data: JobData): JobOutput =
    sparkSession.sparkContext.parallelize(data).countByValue

  override def validate(sparkSession: SparkSession, runtime: JobEnvironment, config: Config):
  JobData Or Every[ValidationProblem] = {
    Try(config.getString("input.string").split(" ").toSeq)
      .map(words => Good(words))
      .getOrElse(Bad(One(SingleProblem("No input.string param"))))
  }
}
```
- Try submitting the job using POST something like below without a context. - THIS FAILS
curl -d "input.string = a b c a b see" "<HOSTNAME>:8095/jobs?appName=giter8-wc-2&classPath=com.example.wordcount.WordCountExampleSparkSession"
This failing with below exception mentioned in the log.

- The same will work if a context is already created an the Job is submitted using the context. - THIS WORKS. 
curl -d "" "https://hostname:8095/contexts/vc-context-1?num-cpu-cores=2&memory-per-node=1G&context-factory=spark.jobserver.context.SessionContextFactory"
curl -d "input.string = a b c a b see" "https://hostname:8095/jobs?appName=giter8-wc-4&classPath=com.example.wordcount.WordCountExampleSparkSession&context=vc-context-1&sync=true"

How can we do this without a pre-defined context? 

Ref: https://github.com/spark-jobserver/spark-jobserver#new-sparkjob-api-with-spark-v21 

**Logs**

```
< HTTP/1.1 400 Bad Request
< Server: spray-can/1.3.4
< Date: Thu, 28 May 2020 01:52:47 GMT
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=UTF-8
< Content-Length: 72
<
{
  "status": "ERROR",
  "result": "Invalid job type for this context"
}
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by parisni** [comment]
hi. I am having the same issue. 

spark 2.4.3
jobserver 0.10.0

I am investigating

**Comment by valan4ik** [comment]
If there is no context specified, then Jobserver creates ad-hoc a plain SparkContext.
Jobserver doesn't know in advance, which job is going to be posted, so if you use Session or Streaming context, you need to create it in advance.
