### ISSUE TITLE
Postgres Migration from 0.9.0 to 0.10.0 is broken

### ISSUE THREAD

**Issue by Ennosigaeon** [spark-jobserver/spark-jobserver#1306]
**Used Spark version**
2.3.1

**Used Spark Job Server version**
0.10.0

**Deployed mode**
default

**Actual (wrong) behavior**
The flyway migration for Postgres from schema V0.7.8 to V0.7.9 is completly broken. Namely:

1. Alter table statement to add new columns uses wrong syntax.
2. The content of "JOB"."BIN_ID" is not migrated to "JOB"."BIN_IDS". Instead the new "BIN_IDS" field is always empty and "BIN_ID" is droped.
3. The new "JOB"."URIS" column defaults to NULL for old records breaking the loading of those jobs.

**Steps to reproduce**
Use Spark Job Server 0.9.0, execute some jobs, update to Spark Job Server 0.10.0

I already fixed this issue on my local fork and would be happy to provide a pull request. Yet, I am not sure how to reference the release tag.

**Comment by valan4ik** [comment]
I think we can't fix it in master branch.
The whole last year we were going in direction of splitting DAO into 2 components: for metadata and for binaries. This split changes DAO quite a lot and current master already doesn't have migration code you had problems with (basically, from the next version of Jobserver, internal DAO structure will change a lot).

I am not sure we faced such kind of a problem before.
@bsikander @noorul did you ever do such hotfixes? is there documented process? :)

I guess we would need to create additional "hotfix" branch based on release tag: https://github.com/spark-jobserver/spark-jobserver/tree/v0.10.0

**Comment by valan4ik** [comment]
Hi @Ennosigaeon ,
I just created new branch `jobserver-0.10.x`, could you please open PRs with your fixes for this branch?

**Comment by Ennosigaeon** [comment]
@valan4ik I have created two PR (#1312 for #1306 and #1311 for #1307). Please let me know if you need anything else from me.

**Comment by valan4ik** [comment]
Hi @Ennosigaeon ,
All your fixes are now released with a new hotfix release `0.10.1`: https://github.com/spark-jobserver/spark-jobserver/releases/tag/v0.10.1
I will close the ticket then.
Thank you for your contribution!
