### ISSUE TITLE
Jobs are sorted by start time in ascending order

### ISSUE THREAD

**Issue by Ennosigaeon** [spark-jobserver/spark-jobserver#1307]
**Used Spark version**
2.3.1

**Used Spark Job Server version**
0.10.0

**Deployed mode**
default

**Actual (wrong) behavior**
With the new release the list of jobs is sorted by start time is ascending order instead of descending order. This way always the oldest jobs are loaded and just finished/crashed jobs are never shown.

I already fixed this issue on my local fork and would be happy to provide a pull request. Yet, I am not sure how to reference the release tag.

**Comment by noorul** [comment]
@Ennosigaeon Please create PR
