### ISSUE TITLE
Spark 3.0 support

### ISSUE THREAD

**Issue by ravi-unifi** [spark-jobserver/spark-jobserver#1315]
Support spark 3.0 and scala 2.12.

**Comment by sivasai-quartic** [comment]
Can we expect this anytime soon

**Comment by kjdoyle** [comment]
Any news on support for Spark 3.0?

**Comment by valan4ik** [comment]
Closing as duplicate of https://github.com/spark-jobserver/spark-jobserver/issues/1269
