### ISSUE TITLE
Same class name and another app name

### ISSUE THREAD

**Issue by v-gerasimov** [spark-jobserver/spark-jobserver#132]
Hi,
I have one context and two uploaded jars which have same class, but different ```appName```. For example, first jar has old version class and ```appName``` "app-old", and second jar has new version class and ```appName``` "app-new". When I start job with: 
```
spark-jobserver.host:8090/jobs?appName=app-old&classPath=com.host.my.Job&context=test-context'
```
It works correctly. But if I post another job (not restart context) with:
```
spark-jobserver.host:8090/jobs?appName=app-new&classPath=com.host.my.Job&context=test-context'
```
It works like app-old. I think this problem with classloader. But how ```appName``` works  and why does it need?

**Comment by velvia** [comment]
Spark jobserver cannot reload the same class path twice in the same context, because of shared class loader.  This is JVM and Spark limitation. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by v-gerasimov** [comment]
Evan,
but why do I need ```appName``` parameter?
