### ISSUE TITLE
Can you change code without restarting jobserver?

### ISSUE THREAD

**Issue by cacti77** [spark-jobserver/spark-jobserver#133]
I've noticed that if I change my code and upload a new jar then the changes have no effect unless I type reStart in the SBT shell prompt.  On https://github.com/spark-jobserver/spark-jobserver/tree/master it says: *If you make a code change, simply type reStart again at the SBT shell prompt, it will compile your changes and restart the jobserver.*

This is fine, except when I reStart then my context is lost - and all the named RDDs I created in it! Then I have to go through multiple steps to create my context and named RDDs again. This is very tiresome when debugging my code!

Are you planning to allow hot-code changes without restarting jobserver please? I'm using 0.5.1 on Windows 7.  Or maybe I'm misunderstanding how to use this framework (I am new to it) and perhaps I should be [persisting my RDDs](http://spark.apache.org/docs/1.3.0/programming-guide.html#rdd-persistence) instead.

**Comment by velvia** [comment]
cacti, the README was talking about "reStart" for hot development of the
job server itself, not jobs.   Hot code changes without restarting the
jobserver:

1) Run your job as an ad-hoc job (don't create a context manually)
2) Reload your job jar
3) Rerun your job.  It should use the new code now.

On Mon, Apr 27, 2015 at 6:59 AM, cacti77 <notifications@github.com> wrote:

> I've noticed that if I change my code and upload a new jar then the
> changes have no effect unless I type reStart in the SBT shell prompt. On
> https://github.com/spark-jobserver/spark-jobserver/tree/master it says: *If
> you make a code change, simply type reStart again at the SBT shell prompt,
> it will compile your changes and restart the jobserver.*
>
> This is fine, except when I reStart then all my contexts are lost - and
> all the RDDs I created in them! Then I have to go through multiple steps to
> create my contexts and RDDs again. This is very tiresome when debugging my
> code!
>
> Are you planning to allow hot-code changes without restarting jobserver
> please? I'm using 0.5.1 on Windows 7. Or maybe I'm misunderstanding how to
> use this framework (I am new to it) and perhaps I should be persisting my
> RDDs
> <http://spark.apache.org/docs/1.3.0/programming-guide.html#rdd-persistence>
> instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/133>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
Alternatively, if you pre-created the context, delete it and create another
one.

Each context has its own classloader.  The JVM does not really support
hot-loading of classes.

On Wed, Apr 29, 2015 at 10:41 PM, Evan Chan <velvia@gmail.com> wrote:

> cacti, the README was talking about "reStart" for hot development of the
> job server itself, not jobs.   Hot code changes without restarting the
> jobserver:
>
> 1) Run your job as an ad-hoc job (don't create a context manually)
> 2) Reload your job jar
> 3) Rerun your job.  It should use the new code now.
>
> On Mon, Apr 27, 2015 at 6:59 AM, cacti77 <notifications@github.com> wrote:
>
>> I've noticed that if I change my code and upload a new jar then the
>> changes have no effect unless I type reStart in the SBT shell prompt. On
>> https://github.com/spark-jobserver/spark-jobserver/tree/master it says: *If
>> you make a code change, simply type reStart again at the SBT shell prompt,
>> it will compile your changes and restart the jobserver.*
>>
>> This is fine, except when I reStart then all my contexts are lost - and
>> all the RDDs I created in them! Then I have to go through multiple steps to
>> create my contexts and RDDs again. This is very tiresome when debugging my
>> code!
>>
>> Are you planning to allow hot-code changes without restarting jobserver
>> please? I'm using 0.5.1 on Windows 7. Or maybe I'm misunderstanding how to
>> use this framework (I am new to it) and perhaps I should be persisting
>> my RDDs
>> <http://spark.apache.org/docs/1.3.0/programming-guide.html#rdd-persistence>
>> instead.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spark-jobserver/spark-jobserver/issues/133>.
>>
>
>
>
> --
> If you are free, you need to free somebody else.
> If you have some power, then your job is to empower somebody else.
>    --- Toni Morrison
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by cacti77** [comment]
OK, thanks velvia; I hadn't realised it was referring to job-server code (maybe add that in the readme?).  That explains why it said "it will compile your changes"!

Yes, I was creating the context in advance and I had different jars for different jobs.  I was sharing named RDDs between the jobs running in the same context.  And I wanted to debug a job that wasn't working as expected.  So, based on what you said, if I modify the code for that job it looks like I have to start all over again with a new context. I guess I'll just have to create a temporary script to create the context and run all the jobs up to the one that's not behaving.  Or save the job output at various points and resume from those points later on.
