### ISSUE TITLE
Can the project provide Maven compilation

### ISSUE THREAD

**Issue by kelvin-qin** [spark-jobserver/spark-jobserver#1346]
There seems to be some trouble compiling with SBT, mostly because some packages cannot be downloaded, so the project cannot be compiled.
eg:
```shell
[info] Updating ProjectRef(uri("file:/root/spark-jobserver-0.11.0/project/"), "spark-jobserver-0-11-0-build")...
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.timushev.sbt#sbt-updates;0.3.4: Resolution failed several times for dependency: com.timushev.sbt#sbt-updates;0.3.4 {compile=[default(compile)]}:: 
[error] 	typesafe-ivy-releases: unable to get resource for com.timushev.sbt#sbt-updates;0.3.4: res=https://repo.typesafe.com/typesafe/ivy-releases/com.timushev.sbt/sbt-updates/scala_2.12/sbt_1.0/0.3.4/ivys/ivy.xml: java.net.UnknownHostException: repo.typesafe.com: Name or service not known
[error] 	sbt-plugin-releases: unable to get resource for com.timushev.sbt#sbt-updates;0.3.4: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.timushev.sbt/sbt-updates/scala_2.12/sbt_1.0/0.3.4/ivys/ivy.xml: java.net.UnknownHostException: dl.bintray.com: Name or service not known
```

I think Maven pom might be more friendly.

**Comment by valan4ik** [comment]
Hi @kelvin-qin ,

I am not sure wether Maven is really more friendly and better than SBT, it probably depends on a project and personal preferences:

https://stackoverflow.com/questions/11277967/pros-and-cons-of-using-sbt-vs-maven-in-scala-project
https://www.scala-lang.org/old/node/11935

SBT has many nice features (e.g. cross-publishing is super easy).

**Comment by velvia** [comment]
It might be a matter of that particular SBT plugin, ie set-updates, rather than SBT itself.  
This project does depend on a large number of SBT plugins, and porting would be very nontrivial.

**Comment by kelvin-qin** [comment]
All right, thank you very much. It's not about whether Maven is really good or not, it's just about having trouble compiling the project. My goal is to compile successfully so that I can use it. I don't know if there are any packages that have been compiled to try.

**Comment by velvia** [comment]
Sorry, there are some old Docker images lying around.

**Comment by kelvin-qin** [comment]
```shell
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.apache.logging.log4j#log4j-core;2.8.1: configuration not found in org.apache.logging.log4j#log4j-core;2.8.1: 'master(compile)'. Missing configuration: 'compile'. It was required from org.apache.logging.log4j#log4j-slf4j-impl;2.8.1 runtime
[error] unresolved dependency: com.squareup.okio#okio;1.12.0: configuration not found in com.squareup.okio#okio;1.12.0: 'master(compile)'. Missing configuration: 'compile'. It was required from com.squareup.okhttp3#okhttp;3.7.0 compile
```
Has anyone encountered this error?
I encountered this error while executing bin/server_deploy.sh.
@velvia @valan4ik

**Comment by kelvin-qin** [comment]
Can someone tell me exactly what it takes to build successfully?
I installed sbt1.4.7.

**Comment by valan4ik** [comment]
Hi @kelvin-qin ,
I am using sbt 1.2.6.
Just cleaned the cache and build the project again, don't see any exceptions.

**Comment by bsikander** [comment]
I am not sure if we even have this dependency `com.squareup.okio#okio`, are you sure you are using the correct version? Have you tried to build the master branch?

**Comment by kelvin-qin** [comment]
i will try again.thanks

**Comment by kelvin-qin** [comment]
@valan4ik thanks. Build success finally! o(╥﹏╥)o
Using sbt 1.4.7,but change repo with huaweicloud.
