### ISSUE TITLE
Run Job Server Infinitely

### ISSUE THREAD

**Issue by anandvijay619** [spark-jobserver/spark-jobserver#135]
sbt
reStart

These commands above starts my jobServer. But if my machine goes to sleep then the pipe breaks to ec2 and hence this process gets closed.

How can i run this as a background task?

**Comment by velvia** [comment]
I would recommend deploying or at least creating an assembly jar and actually running it as a real background process on a server somewhere instead of your laptop. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by anandvijay619** [comment]
Yup I am doing same... running on EC2 Ubuntu instance. I have a SSH terminal which executes the JOB Server.

I connect it using SSH and then create a package of my app and upload the same to the job server. But when my SSH connection drops then this JOB Server also gets interrupted.

**Comment by velvia** [comment]
Again, recommendation is to run the job server in a background process
instead of directly in SSH.  :)

On Tue, Apr 28, 2015 at 10:58 PM, anandvijay619 <notifications@github.com>
wrote:

> Yup I am doing same... running on EC2 Ubuntu instance. I have a SSH
> terminal which executes the JOB Server.
>
> I connect it using SSH and then create a package of my app and upload the
> same to the job server. But when my SSH connection drops then this JOB
> Server also gets interrupted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/135#issuecomment-97315734>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by mikee123** [comment]
Hi anandvijay619, did you fine a solution for this problem. How to run spark in the background ?I have got same problem recently .thanks
