### ISSUE TITLE
server crashed using mllib (java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by villafana1981** [spark-jobserver/spark-jobserver#138]
hi,
we have the spark job server run together with the standalone spark cluster on one machine, 
we tried to run jobs that uses mllib, but we got a error(in the server).

job-server[ERROR] Uncaught error from thread [JobServer-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
job-server[ERROR] java.lang.NoClassDefFoundError: org/apache/spark/mllib/stat/Statistics$
job-server[ERROR] 	at SparkCorrelation$.getCorrelation(SparkCorrelation.scala:50)
job-server[ERROR] 	at SparkCorrelation$.runJob(SparkCorrelation.scala:28)
job-server[ERROR] 	at SparkCorrelation$.runJob(SparkCorrelation.scala:11)
job-server[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:234)

do you have any idea about it?
-using spark 1.2 and jobserver 0.5.0

thanks

**Comment by velvia** [comment]
Are you running job server alone, and with the start_server.sh script with
SPARK_HOME etc. properly set?

On Wed, Apr 29, 2015 at 1:16 PM, villafana1981 <notifications@github.com>
wrote:

> hi,
> we have the spark job server run together with the standalone spark
> cluster on one machine,
> we tried to run jobs that uses mllib, but we got a error(in the server).
>
> job-server[ERROR] Uncaught error from thread
> [JobServer-akka.actor.default-dispatcher-3] shutting down JVM since
> 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
> job-server[ERROR] java.lang.NoClassDefFoundError:
> org/apache/spark/mllib/stat/Statistics$
> job-server[ERROR] at
> SparkCorrelation$.getCorrelation(SparkCorrelation.scala:50)
> job-server[ERROR] at SparkCorrelation$.runJob(SparkCorrelation.scala:28)
> job-server[ERROR] at SparkCorrelation$.runJob(SparkCorrelation.scala:11)
> job-server[ERROR] at
> spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:234)
>
> do you have any idea about it?
> -using spark 1.2 and jobserver 0.5.0
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/138>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by villafana1981** [comment]
Spark job server works fine (running the test), but when i use mllib it crashes.
i run the jobserver using :
sbt reStart

I create the fat jar for the job and the job works correctly (the fat jar its big)

is there another way to correct this situation?

i running job server alone.
start_server,sh?

**Comment by velvia** [comment]
Hmmm.  Do you mean you packaged MLLib in the fat jar?  That should not be
necessary, since the Spark distro already has MLLib in it.

I'm sensing that there needs to be more guidance and easier process in
general around dependencies.

On Wed, May 20, 2015 at 9:03 AM, villafana1981 <notifications@github.com>
wrote:

> Spark job server works fine (running the test), but when i use mllib it
> crashes.
> i run the jobserver using :
> sbt reStart
>
> I create the fat jar for the job and the job works correctly (the fat jar
> its big)
>
> is there another way to correct this situation?
>
> i running job server alone.
> start_server,sh?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/138#issuecomment-103940106>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by villafana1981** [comment]
Yeah, it would be helpful, a little more documentation about the external libraries would be great.

I think putting a fat-jar with all libraries that i need in the EXTRA_JAR solve the situation, it could be a workaround, ill going to try it.

Do you have other idea to solve this situation?
Sorry for my poor english

great job with this rest framework :)

**Comment by velvia** [comment]
Hi, many thanks.    EXTRA_JAR only works when you run it locally with sbt,
but won't work in production.  For a prod deployment I recommend putting
the extra jars in the spark-env.sh SPARK_CLASSPATH, or to use the
dependent-jar-uris parameter (search for that in the README).

How can I help make the classpath stuff easier?  One thought is perhaps to
have a separate classpath section in the docs.   Also I know Spark UI has a
helpful section on classpaths, but perhaps having a REST interface for that
would be helpful.

On Wed, Jun 10, 2015 at 8:14 AM, villafana1981 <notifications@github.com>
wrote:

> Yeah, it would be helpful, a little more documentation about the external
> libraries would be great.
>
> I think putting a fat-jar with all libraries that i need in the EXTRA_JAR
> solve the situation, it could be a workaround, ill going to try it.
>
> Do you have other idea to solve this situation?
> Sorry for my poor english
>
> great job with this rest framework :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/138#issuecomment-110791349>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by zeitos** [comment]
Closing for innactivity
