### ISSUE TITLE
Postgresql driver usage in job

### ISSUE THREAD

**Issue by nickpoorman** [spark-jobserver/spark-jobserver#139]
Is there a trick to loading the [postgresql driver](http://mvnrepository.com/artifact/postgresql/postgresql/9.1-901-1.jdbc4) for a job? I can't figure out if I need to package it with the job, or the jobserver, or spark...

```
{
  "status": "ERROR",
  "result": {
    "message": "No suitable driver found for jdbc:postgresql://dburi?user=foo&password=bar&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory",
    "errorClass": "java.sql.SQLException",
    "stack": ["java.sql.DriverManager.getConnection(DriverManager.java:596)", "java.sql.DriverManager.getConnection(DriverManager.java:233)", "org.apache.spark.sql.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:94)", "org.apache.spark.sql.jdbc.JDBCRelation.<init>(JDBCRelation.scala:125)", "org.apache.spark.sql.jdbc.DefaultSource.createRelation(JDBCRelation.scala:114)", "org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:290)", "org.apache.spark.sql.SQLContext.load(SQLContext.scala:679)", "cf.Train$.getRatings(Train.scala:77)", "cf.Train$.runJob(Train.scala:22)", "cf.Train$.runJob(Train.scala:17)", "spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:235)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)", "java.lang.Thread.run(Thread.java:745)"]
  }
```

I tried setting the location of the jar in my .conf file:

```
dependent-jar-uris = ["file:///Users/nick/projects/ml/postgresql-9.4-1201.jdbc41.jar"]
```

Didn't work. I also tried adding to my build.sbt for the job:

```
libraryDependencies += "postgresql" % "postgresql" % "9.1-901-1.jdbc4"
```

Didn't work. The only thing I can think to do is compile it straight into Spark.

Edit: Compiling with Spark works. I feel like there has to be a better way / should be done on the job side of things.

**Comment by velvia** [comment]
I believe you would need to package it with the Spark distribution at the
very least, and to be safe on every node (try using dependent-jar-uris).

On Fri, May 1, 2015 at 7:18 AM, Nicholas Poorman <notifications@github.com>
wrote:

> Is there a trick to loading the postgresql driver
> <http://mvnrepository.com/artifact/postgresql/postgresql/9.1-901-1.jdbc4>
> for a job? I can't figure out if I need to package it with the job, or the
> jobserver, or spark...
>
> {
>   "status": "ERROR",
>   "result": {
>     "message": "No suitable driver found for jdbc:postgresql://dburi?user=foo&password=bar&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory",
>     "errorClass": "java.sql.SQLException",
>     "stack": ["java.sql.DriverManager.getConnection(DriverManager.java:596)", "java.sql.DriverManager.getConnection(DriverManager.java:233)", "org.apache.spark.sql.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:94)", "org.apache.spark.sql.jdbc.JDBCRelation.<init>(JDBCRelation.scala:125)", "org.apache.spark.sql.jdbc.DefaultSource.createRelation(JDBCRelation.scala:114)", "org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:290)", "org.apache.spark.sql.SQLContext.load(SQLContext.scala:679)", "cf.Train$.getRatings(Train.scala:77)", "cf.Train$.runJob(Train.scala:22)", "cf.Train$.runJob(Train.scala:17)", "spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:235)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)", "ja
>  va.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)", "java.lang.Thread.run(Thread.java:745)"]
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/139>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ssoto** [comment]
Could be related with https://github.com/spark-jobserver/spark-jobserver/issues/197?

**Comment by velvia** [comment]
@nickpoorman One way, instead of compiling with Spark, would be to put the postgresql jar in Spark's class path, by editing your spark-env.sh and the SPARK_CLASSPATH.   An alternative, not as elegant, is to edit spark job server's start script and include it in the --jars argument.  Actually you could try using `server_start.sh` as is and appending the argument `--package` and give the Maven coordinates of the postgresql jar.  That's probably the easiest for new folks. 

If this works, let us know, we'd be happy to post instructions.

**Comment by LHaferkamp** [comment]
In development mode (sbt -> reStart) do
`export EXTRA_JAR="<path to jars>/postgresql-9.4-1204-jdbc42.jar"`
before

**Comment by dmalaescu** [comment]
I had the same problem regarding the postresql driver and starting the spark job server with _--jars_ argument worked.

**Comment by zeitos** [comment]
@nickpoorman did any of the options worked? can we close this issue?

**Comment by nickpoorman** [comment]
@zeitos - I abandoned spark a few months ago and so have not tested the suggestions. Feel free to close this.
