### ISSUE TITLE
Use jobId within the job

### ISSUE THREAD

**Issue by ffarozan** [spark-jobserver/spark-jobserver#140]
In order for apps to persist the job result, the jobId should be known from within the job.

Job itself can store the result by storing in some place of its choice - could be redis, s3, or via another API call, etc. But what must be needed is the job id. Job itself should know what its id is, so that can be used as a key

**Comment by zeitos** [comment]
You can do `sc.getLocalProperty("spark.jobGroup.id") `

**Comment by zeitos** [comment]
@ffarozan closing this issue.

**Comment by ffarozan** [comment]
Sure, Thanks.
