### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by RandSaleh** [spark-jobserver/spark-jobserver#1401]
**Used Spark version**
What is the official status for last 0.11.1/0.11.0 Spark job Server compatibility with spark 3 ? 
**Used Spark Job Server version**
(Released version, git branch or docker image version)

**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)

**Actual (wrong) behavior**

**Steps to reproduce**

**Logs**

```
some log
```

or as attached file (see below)

Unused parts of this template should be removed (including this line).

**Comment by vglagoleva** [comment]
Jobserver is not supporting Spark 3 officially, feature request and PRs are still open: https://github.com/spark-jobserver/spark-jobserver/issues/1269
However, some users report that it is working for them: https://github.com/spark-jobserver/spark-jobserver/issues/1391
