### ISSUE TITLE
0.5.1 not on Maven

### ISSUE THREAD

**Issue by jeffsteinmetz** [spark-jobserver/spark-jobserver#141]
Developers may try to add the 0.5.1 dependency to the``` job-server-api```

  http://dl.bintray.com/spark-jobserver/maven

... even though 0.5.0 will work as well (doesn't look like the scala Traits have changed).

**Comment by velvia** [comment]
Yeah, we'll publish very soon, then devs will have the 0.5.1 jar.

On Mon, May 4, 2015 at 11:41 AM, Jeff Steinmetz <notifications@github.com>
wrote:

> Developers may want to add the 0.5.1 dependency to thejob-server-api
>
> http://dl.bintray.com/spark-jobserver/maven
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/141>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by nickpoorman** [comment]
+1

**Comment by fwang7** [comment]
+1

**Comment by corrius** [comment]
+1

**Comment by velvia** [comment]
@jeffsteinmetz and others: 0.5.1 has been published to Bintray.
