### ISSUE TITLE
JobServer call with Javascript

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [spark-jobserver/spark-jobserver#143]
hi, i would like call job with javascript code it is possible ?

**Comment by velvia** [comment]
What do you mean, you mean interact with a job through some browser JS
code?   So you need something other than the REST API for launching and
managing jobs?

On Thu, May 7, 2015 at 1:25 AM, Benkhaoua <notifications@github.com> wrote:

> hi, i would like call job with javascript code it is possible ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/143>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by sidahmedbenkhaoua** [comment]
yes i would like call job server with $.ajax request for example

**Comment by jeffsteinmetz** [comment]
A REST call is agnostic to what calls it.  The main issue you may have is exposing the REST API endpoint of the job server to (what sounds like) a client web browser, which sounds like a public endpoint - which could be dangerous.  You may want a proxy with some type of auth.
