### ISSUE TITLE
spark streaming job with Kafka

### ISSUE THREAD

**Issue by fwang7** [spark-jobserver/spark-jobserver#144]
hi,

i didn't see "org.apache.spark.streaming" in the dependencies so I will have to upload a "fat jar" including the streaming jar to the job-server if i want to play it with Kafka to do some streaming calculation, is that correct?  Thanks!

**Comment by sidahmedbenkhaoua** [comment]
you add dependencies in SPARK CLASS PATH all dependencies

2015-05-07 18:03 GMT+02:00 Feng Wang <notifications@github.com>:

> hi,
>
> i didn't see "org.apache.spark.streaming" in the dependencies so I will
> have to upload a "fat jar" including the streaming jar to the job-server if
> i want to play it with Kafka to do some streaming calculation, is that
> correct? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/144>.
>



-- 

*BENKHAOUA Sidahmed*
*software developer at iconsoftware <http://www.iconsoftware.dz/>*
Phone:+213 (0) 668 98 10 63
e-mail: *s.benkhaoua@iconsoftware.dz <s.benkhaoua@iconsoftware.dz> *
*Skype:  *sbenkhaoua
*Twitter: **@sBenkhaoua <https://twitter.com/sBenkhaoua>*
︵﻿ ¯\(ツ)/¯ ︵C'est le devoir de chaque homme de rendre au monde au moins
autant qu'il en a reçue︵﻿ ¯\(ツ)/¯ ︵

**Comment by velvia** [comment]
Spark streaming should be park of your Spark distribution.

On Thu, May 7, 2015 at 12:01 PM, Benkhaoua <notifications@github.com> wrote:

> you add dependencies in SPARK CLASS PATH all dependencies
>
>
> 2015-05-07 18:03 GMT+02:00 Feng Wang <notifications@github.com>:
>
> > hi,
> >
> > i didn't see "org.apache.spark.streaming" in the dependencies so I will
> > have to upload a "fat jar" including the streaming jar to the job-server
> if
> > i want to play it with Kafka to do some streaming calculation, is that
> > correct? Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/spark-jobserver/spark-jobserver/issues/144>.
> >
>
>
>
> --
>
> *BENKHAOUA Sidahmed*
> *software developer at iconsoftware <http://www.iconsoftware.dz/>*
> Phone:+213 (0) 668 98 10 63
> e-mail: *s.benkhaoua@iconsoftware.dz <s.benkhaoua@iconsoftware.dz> *
> *Skype: *sbenkhaoua
> *Twitter: **@sBenkhaoua <https://twitter.com/sBenkhaoua>*
> ︵﻿ ¯\(ツ)/¯ ︵C'est le devoir de chaque homme de rendre au monde au moins
> autant qu'il en a reçue︵﻿ ¯\(ツ)/¯ ︵
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/144#issuecomment-99980850>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by zeitos** [comment]
Since spark streaming has been added, I'm closing this one
