### ISSUE TITLE
How to force JobServer to execute the main function ?

### ISSUE THREAD

**Issue by richiesgr** [spark-jobserver/spark-jobserver#145]
Hi
Working with 0.5.1
I can't enable to call the main JobServer automatically skip my def main and call the runJob with his own context. 
my job is like this

package spark.jobserver
object SparkFileToDBJob extends SparkJob {

  def main(args: Array[String]) {
    println("IN MAIN ==============================")

    val jobConfig = ConfigFactory.parseString("")
    jobConfig.withFallback(ConfigFactory.parseFile(new File(jobConfig.getString("configFile"))))

    val sparkClusterHost = jobConfig.getString("spark.host")
    val sparkConf = new SparkConf().setMaster(sparkClusterHost)
      .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
      .set("spark.kryo.registrator", "com.inneractive.fortknox.kafka.AggregationKryoRegistrator")

    DataSource(jobConfig)

    val sc = new SparkContext(sparkConf)

It's in package spark.jobserver

**Comment by velvia** [comment]
Sorry, what is the issue?  You want to work with this code and cannot
change it to use the SparkJob API?

On Thu, May 7, 2015 at 10:09 AM, richiesgr <notifications@github.com> wrote:

> Hi
> Working with 0.5.1
> I can't enable to call the main JobServer automatically skip my def main
> and call the runJob with his own context.
> my job is like this
>
> package spark.jobserver
> object SparkFileToDBJob extends SparkJob {
>
> def main(args: Array[String]) {
> println("IN MAIN ==============================")
>
> val jobConfig = ConfigFactory.parseString("")
> jobConfig.withFallback(ConfigFactory.parseFile(new File(jobConfig.getString("configFile"))))
>
> val sparkClusterHost = jobConfig.getString("spark.host")
> val sparkConf = new SparkConf().setMaster(sparkClusterHost)
>   .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
>   .set("spark.kryo.registrator", "com.inneractive.fortknox.kafka.AggregationKryoRegistrator")
>
> DataSource(jobConfig)
>
> val sc = new SparkContext(sparkConf)
>
> It's in package spark.jobserver
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/145>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by richiesgr** [comment]
Hi

No This object extends SparkJob but have main function. Is the JobServer
call the main function or do I need to move all the main in the runjob
method ?
Thanks

**Comment by velvia** [comment]
The main will not be executed by job server, you need to have code in the
runJob method.

On Thu, May 7, 2015 at 2:24 PM, richiesgr <notifications@github.com> wrote:

> Hi
>
> No This object extends SparkJob but have main function. Is the JobServer
> call the main function or do I need to move all the main in the runjob
> method ?
> Thanks
>
> On Thu, May 7, 2015 at 10:01 PM, Evan Chan <notifications@github.com>
> wrote:
>
> > Sorry, what is the issue? You want to work with this code and cannot
> > change it to use the SparkJob API?
> >
> > On Thu, May 7, 2015 at 10:09 AM, richiesgr <notifications@github.com>
> > wrote:
> >
> > > Hi
> > > Working with 0.5.1
> > > I can't enable to call the main JobServer automatically skip my def
> main
> > > and call the runJob with his own context.
> > > my job is like this
> > >
> > > package spark.jobserver
> > > object SparkFileToDBJob extends SparkJob {
> > >
> > > def main(args: Array[String]) {
> > > println("IN MAIN ==============================")
> > >
> > > val jobConfig = ConfigFactory.parseString("")
> > > jobConfig.withFallback(ConfigFactory.parseFile(new
> > File(jobConfig.getString("configFile"))))
> > >
> > > val sparkClusterHost = jobConfig.getString("spark.host")
> > > val sparkConf = new SparkConf().setMaster(sparkClusterHost)
> > > .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
> > > .set("spark.kryo.registrator",
> > "com.inneractive.fortknox.kafka.AggregationKryoRegistrator")
> > >
> > > DataSource(jobConfig)
> > >
> > > val sc = new SparkContext(sparkConf)
> > >
> > > It's in package spark.jobserver
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/spark-jobserver/spark-jobserver/issues/145>.
> > >
> >
> >
> >
> > --
> > If you are free, you need to free somebody else.
> > If you have some power, then your job is to empower somebody else.
> > --- Toni Morrison
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/spark-jobserver/spark-jobserver/issues/145#issuecomment-99980822
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/145#issuecomment-100023483>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison
