### ISSUE TITLE
Expecting end of input or a comma, got ':'

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [spark-jobserver/spark-jobserver#146]
hi, i have error when i send parametre with carecter  : 
example Tue May 05 22:29:35 CEST 2015
Expecting end of input or a comma, got ':'

**Comment by velvia** [comment]
Sorry, can you post the full example, what is the URL, logs, etc.?

On Fri, May 8, 2015 at 3:14 AM, Benkhaoua <notifications@github.com> wrote:

> hi, i have error when i send parametre with carecter :
> example Tue May 05 22:29:35 CEST 2015
> Expecting end of input or a comma, got ':'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/146>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison
