### ISSUE TITLE
Long running jobs fill up disk

### ISSUE THREAD

**Issue by nickpoorman** [spark-jobserver/spark-jobserver#151]
This might be more of a spark configuration issue, however maybe someone here who has long running jobserver context might know the answer.

I'm running a train job on mllib ALS continuously over and over again on the same context, with `spark.mesos.coarse = true`. The idea is to keep the model as up-to-date as possible, while still being able to call the prediction job on the context with the trained model. I simply save the user and product features as Named RDDs in the train job and load them up on the the predict jobs to be used.

Every time the training occurs, (about every three minutes) the amount of disk space being used keeps increasing. I've narrowed it down to files like these that are not being removed and thus causing the problem:

```
$ find /tmp -name \* | xargs du -hs

1.4G  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/09
745M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/3b
317M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/05
856M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/1a
797M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26
2.0M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_65_29_0.data
2.1M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_61_47_0.data
4.0K  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_17_31_0.index
2.2M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_49_5_0.data
4.0K  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_82_17_0.index
```

I'll end up with a few thousand of those, which quickly eats up a few hundred GBs of disk space until the disk is completely full.

This didn't help:

```
 --gc_delay=20mins --gc_disk_headroom=0.6
```

This didn't help, was thinking maybe I could disable the spilling for the shuffle and not create those files. It still created those files on the slaves... `production.conf`:

```
spark.shuffle.spill = false
```

This didn't help... `production.conf`:

```
spark.cleaner.ttl = 600
```

I'm at a complete loss here. I don't understand how anyone could use the jobserver and leave a context running for any extended period of time. Is there some setting I'm completely overlooking?

PS: This is how the model is saved on each training iteration:

```scala
  def saveModel(sc: SparkContext, model: MatrixFactorizationModel): String = {
    // Save model as a named RDD
    // MatrixFactorizationModel keeps two RDDs: productFeatures & userFeatures
    // we'll save those, the rank, and a timestamp pointer

    // create a timestamp
    val currentTime = System.currentTimeMillis.toString

    // get the current timestamp
    val oldTimestamp = getTimestamp

    // wrap them in an RDD so we can save the to the jobserver
    val rank: RDD[Int] = sc.parallelize(Seq(model.rank))
    val timestamp: RDD[String] = sc.parallelize(Seq(currentTime))

    this.namedRdds.update("user_features" + currentTime, model.userFeatures)
    this.namedRdds.update("product_features" + currentTime, model.productFeatures)
    this.namedRdds.update("rank" + currentTime, rank)
    this.namedRdds.update("model_timestamp", timestamp)

    // remove the old data
    if(oldTimestamp.isDefined){
      this.namedRdds.destroy("user_features" + oldTimestamp)
      this.namedRdds.destroy("product_features" + oldTimestamp)
      this.namedRdds.destroy("rank" + oldTimestamp)
    }

    currentTime
  }

  def getTimestamp: Option[String] = {
    val oldTimestamp = this.namedRdds.get[String]("model_timestamp")
    if(oldTimestamp.isDefined) Some(oldTimestamp.get.collect()(0))
    else None
  }
```

**Comment by velvia** [comment]
I don't think this is a job-server specific issue ...  I ran into this with
a much older version of Spark, where Spark does not clean up the temp files
on disk.  I actually submitted a PR, so there is a config you can set, but
later I think they disabled it by default or something.  I'll have to dig
up the config again.

One solution, which kinda sucks frankly, is to have a cron job clean up
these files.  I agree it would be much better for Spark itself to do the
cleanup.



On Tue, May 12, 2015 at 8:16 PM, Nicholas Poorman <notifications@github.com>
wrote:

> This might be more of a spark configuration issue, however maybe someone
> here who has long running jobserver context might know the answer.
>
> I'm running a train job on mllib ALS continuously over and over again on
> the same context, with spark.mesos.coarse = true. The idea is to keep the
> model as up-to-date as possible, while still being able to call the
> prediction job on the context with the trained model. I simply save the
> user and product features as Named RDDs in the train job and load them up
> on the the predict jobs to be used.
>
> Every time the training occurs, (about every three minutes) the amount of
> disk space being used keeps increasing. I've narrowed it down to files like
> these that are not being removed and thus causing the problem:
>
> $ find /tmp -name \* | xargs du -hs
>
> 1.4G  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/09
> 745M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/3b
> 317M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/05
> 856M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/1a
> 797M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26
> 2.0M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_65_29_0.data
> 2.1M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_61_47_0.data
> 4.0K  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_17_31_0.index
> 2.2M  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_49_5_0.data
> 4.0K  /tmp/spark-e6844d42-6950-494a-bb59-95ebca0f93bb/blockmgr-1cd15ddf-def9-48c5-8e89-bfe1d81d1352/26/shuffle_82_17_0.index
>
> I'll end up with a few thousand of those, which quickly eats up a few
> hundred GBs of disk space until the disk is completely full.
>
> This didn't help:
>
>  --gc_delay=20mins --gc_disk_headroom=0.6
>
> This didn't help, was thinking maybe I could disable the spilling for the
> shuffle and not create those files. It still created those files on the
> slaves... production.conf:
>
> spark.shuffle.spill = false
>
> This didn't help... production.conf:
>
> spark.cleaner.ttl = 600
>
> I'm at a complete loss here. I don't understand how anyone could use the
> jobserver and leave a context running for any extended period of time. Is
> there some setting I'm completely overlooking?
>
> PS: This is how the model is saved on each training iteration:
>
>   def saveModel(sc: SparkContext, model: MatrixFactorizationModel): String = {
>     // Save model as a named RDD
>     // MatrixFactorizationModel keeps two RDDs: productFeatures & userFeatures
>     // we'll save those, the rank, and a timestamp pointer
>
>     // create a timestamp
>     val currentTime = System.currentTimeMillis.toString
>
>     // get the current timestamp
>     val oldTimestamp = getTimestamp
>
>     // wrap them in an RDD so we can save the to the jobserver
>     val rank: RDD[Int] = sc.parallelize(Seq(model.rank))
>     val timestamp: RDD[String] = sc.parallelize(Seq(currentTime))
>
>     this.namedRdds.update("user_features" + currentTime, model.userFeatures)
>     this.namedRdds.update("product_features" + currentTime, model.productFeatures)
>     this.namedRdds.update("rank" + currentTime, rank)
>     this.namedRdds.update("model_timestamp", timestamp)
>
>     // remove the old data
>     if(oldTimestamp.isDefined){
>       this.namedRdds.destroy("user_features" + oldTimestamp)
>       this.namedRdds.destroy("product_features" + oldTimestamp)
>       this.namedRdds.destroy("rank" + oldTimestamp)
>     }
>
>     currentTime
>   }
>
>   def getTimestamp: Option[String] = {
>     val oldTimestamp = this.namedRdds.get[String]("model_timestamp")
>     if(oldTimestamp.isDefined) Some(oldTimestamp.get.collect()(0))
>     else None
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/151>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
@nickpoorman  the config values in Spark to tweak are:

spark.worker.cleanup.enabled = true
spark.worker.cleanup.interval

Try it out and if it works, please close  :)

**Comment by nickpoorman** [comment]
I don't think `spark.worker.cleanup.enabled = true` works for mesos, only appears to be in the Spark Standalone code.

I've abandoned trying to get this to work for now, so I'll close the issue. Would love if someone finds a solution to this.

**Comment by velvia** [comment]
If you want to contribute to Spark, I can help you with the change, as I submitted the original PR. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
