### ISSUE TITLE
No configuration setting found for key 

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [spark-jobserver/spark-jobserver#152]
i have create json file to send in job server 
curl -H "Content-Type: application/json" --data @file.json -X POST 'localhost:8090/jobs?appName=roadtraffic7&classPath=LuncherCarRoadCountStream
whene i lunche methode i found this error 
{
  "status": "ERROR",
  "result": {
    "message": "No configuration setting found for key 'data'",
    "errorClass": "com.typesafe.config.ConfigException$Missing",
    "stack": ["com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)", "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)", "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)", "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)", "com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)", "LuncherCarRoadCountStream$.validate(LuncherCarRoadCountStream.scala:19)", "LuncherCarRoadCountStream$.validate(LuncherCarRoadCountStream.scala:11)", "spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:225)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)", "java.lang.Thread.run(Thread.java:745)"]
  }

**Comment by velvia** [comment]
From the stack trace, sounds like your code in the validate() method is
trying to pull a key from the JSON config which doesn't exist.  I would
debug print out the job config (or use the API to retrieve what job server
thinks is the config)..  which you can do using config.root.render(), I
believe.

On Thu, May 14, 2015 at 7:22 AM, Benkhaoua <notifications@github.com> wrote:

> i have create json file to send in job server
> curl -H "Content-Type: application/json" --data @file.json -X POST
> 'localhost:8090/jobs?appName=roadtraffic7&classPath=LuncherCarRoadCountStream
> whene i lunche methode i found this error
> {
> "status": "ERROR",
> "result": {
> "message": "No configuration setting found for key 'data'",
> "errorClass": "com.typesafe.config.ConfigException$Missing",
> "stack":
> ["com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)",
> "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)",
> "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)",
> "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)",
> "com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)",
> "LuncherCarRoadCountStream$.validate(LuncherCarRoadCountStream.scala:19)",
> "LuncherCarRoadCountStream$.validate(LuncherCarRoadCountStream.scala:11)",
> "spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:225)",
> "scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)",
> "scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)",
> "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)",
> "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)",
> "java.lang.Thr ead.run( Thread.java:745)"]
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/152>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
@sidahmedbenkhaoua can we close this one?

**Comment by zeitos** [comment]
Closing since we got no response for months
