### ISSUE TITLE
Support Spark 1.4.0

### ISSUE THREAD

**Issue by ejono** [spark-jobserver/spark-jobserver#155]
Spark 1.4.0 has removed the compute-classpath.sh script that is currently being used by spark-jobserver's server_start.sh script.  (See https://issues.apache.org/jira/browse/SPARK-4924 for the JIRA that removed compute-classpath.sh.)  I'm not sure if there are any other issues that would block spark-jobserver from using Spark 1.4.0 once it is released, but this one thing that needs to be fixed.

**Comment by velvia** [comment]
@ejono have a look at https://github.com/spark-jobserver/spark-jobserver/pull/164

**Comment by punya** [comment]
Is any additional work needed to support 1.4.0 or is it just a question of changing the dependency?

**Comment by velvia** [comment]
Just changing the dependency should work.  You could in fact change
SPARK_VERSION environment variable, then rebuild..... or as of master right
now, you could put SPARK_VERSION in your local.sh to build for deployment.

On Thu, Jun 18, 2015 at 5:53 AM, Punyashloka Biswal <
notifications@github.com> wrote:

> Is any additional work needed to support 1.4.0 or is it just a question of
> changing the dependency?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/155#issuecomment-113146925>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
BTW just to make it clear on master `server_start.sh` no longer uses `compute_classpath`.

**Comment by emmekappa** [comment]
Any ETA about Spark 1.4 support?

**Comment by velvia** [comment]
If you are blocked you can try 1.4.0 without any code change by setting the SPARK_VERSION env variable.  

As for making 1.4.0 the default, some other issues to get to first. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ishepherd** [comment]
Please check anything needed for Spark 1.5 also. Thanks.

**Comment by nemccarthy** [comment]
master seems to work on 1.4, going to try 1.5 now unless someone else has?

**Comment by velvia** [comment]
Everyone, master has been switched to 1.4 officially.  Closing.
