### ISSUE TITLE
Use spray-json on spark-jobserver

### ISSUE THREAD

**Issue by v-gerasimov** [spark-jobserver/spark-jobserver#156]
Hi!

When I try to use spray-json library in my spark-jobserver job, I catch this exception:
```
java.lang.NoClassDefFoundError: spark/jobserver/SparkSqlJob
```
My code:
```
object UserJob extends SparkSqlJob {
import spray.json._

  override def runJob(sc: SQLContext, jobConfig: Config) = {
    val jsonStrings = sc.sparkContext.textFile("1.json")
    jsonStrings.map(_.parseJson.asJsObject.fields("user")).map(_.convertTo[User]).collect()
  }

  override def validate(sc: SQLContext, config: Config): SparkJobValidation = SparkJobValid
}
```

I upload "fat-jar" to spark-jobserver.
Could I use spray-json library on spark-jobserver?

**Comment by v-gerasimov** [comment]
If I remove provided from: 
```
"spark.jobserver" % "job-server-api" % "0.5.0" % "provided"
```
it will work. But I haven't idea why it works.

**Comment by velvia** [comment]
Is that line you removed in your job itself?

What if you put jobserver in the classpath of every Spark executor/worker,
but put back the provided?

On Tue, May 26, 2015 at 1:08 AM, v-gerasimov <notifications@github.com>
wrote:

> If I remove provided from:
>
> "spark.jobserver" % "job-server-api" % "0.5.0" % "provided"
>
> it will work. But I haven't idea why it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/156#issuecomment-105436218>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by v-gerasimov** [comment]
No, that line is removed from sbt library dependencies.

I put jobserver.jar in the dependent-jar-uris of job-server config and put back the ```provided``` in the project. It works.

**Comment by noorul** [comment]
@v-gerasimov Can you close this issue if it is not an issue anymore?

**Comment by velvia** [comment]
Going to close, feel free to reopen if you still have issues.   Note that we are going to create a starter project to help folks get dependencies right; there is a new ticket for that.
