### ISSUE TITLE
Multiple spark-jobserver's with the same spark cluster

### ISSUE THREAD

**Issue by kavuri** [spark-jobserver/spark-jobserver#158]
I would like to run multiple spark-jobserver behind a load balancer (to enable high availability), but with the same spark cluster. Each of the jobserver's will have its own context created (with the REST API call). Each of the incoming trigger for the algorithm can go to either of the jobservers. I have setup a spark cluster of 5 nodes (1 Master and 4 workers). Is this configuration something that is possible? What will happen if the two jobservers get the requests at the same time? Will the requests be queued at the spark cluster?
Any inputs are appreciated

**Comment by PierreVincent** [comment]
If you're running Spark in Standalone mode, the Spark cluster will schedule the jobs on a FIFO basis, whenever the required resources are available. See [Resource Scheduling](https://spark.apache.org/docs/1.3.0/spark-standalone.html#resource-scheduling).

One thing maybe to be careful of with your set up is that you need to make sure your Application JARs are being uploaded to each of the Job Servers, because it stores them locally. Also if you're not using ad-hoc contexts (i.e. context created on the fly with the job), you will need to make sure that the multiple calls (1. create context, 2. run job with context, and 3. stop the context) will be sent to the same job server instance. All this might also make context sharing a bit tricky, if you wanted to start a context and run multiple apps that would share RDDs between them in that same context.

**Comment by velvia** [comment]
In theory you could point each job server to the same database via a JDBC
URL, in which case you would not need to upload jars to each job
server.     I have not personally tried this setup however.

On Wed, May 27, 2015 at 8:33 AM, Pierre Vincent <notifications@github.com>
wrote:

> If you're running Spark in Standalone mode, the Spark cluster will
> schedule the jobs on a FIFO basis, whenever the required resources are
> available. See Resource Scheduling
> <https://spark.apache.org/docs/1.3.0/spark-standalone.html#resource-scheduling>
> .
>
> One thing maybe to be careful of with your set up is that you need to make
> sure your Application JARs are being uploaded to each of the Job Servers,
> because it stores them locally. Also if you're not using ad-hoc contexts
> (i.e. context created on the fly with the job), you will need to make sure
> that the multiple calls (1. create context, 2. run job with context, and 3.
> stop the context) will be sent to the same job server instance. All this
> might also make context sharing a bit tricky, if you wanted to start a
> context and run multiple apps that would share RDDs between them in that
> same context.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/158#issuecomment-105961970>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by kavuri** [comment]
@PierreVincent We would be creating the context, but are never going to tear it down. Also, we do not have a case of sharing of the RDD's across contexts. The main usecase for us to create a context is to reduce the time taken to create the context (we have seen that in loaded conditions, context creation itself takes anywhere between 10secs-7mins). Some of the folks have mentioned that when one jobserver creates a context and when the next job server creates another context with another name, then there have been cases that the new context creation goes into waiting state. Is this the expected scenario?

@velvia If the algo jar is not uploaded to each of the job-servers, how will they get the reference to the jar? Can you help explain this in a bit more detail. Thanks

**Comment by velvia** [comment]
@kavuri  you might want to see #120 which is one step towards true job server HA.

Job server uploads the jar and stores it in the database.  When it's time to load the app it retrieves it from the database, saving the jar bytes in a local file.   Therefore if multiple job servers point to the same database they can retrieve the same jar and it only has to be loaded once.

**Comment by velvia** [comment]
Hope your question is answered.  Going to use #190 as the official HA / Failover thread.
