### ISSUE TITLE
Application logging doesn't work

### ISSUE THREAD

**Issue by aviemzur** [spark-jobserver/spark-jobserver#159]
Hi,

I'm trying to see my own application logs when using jobserver but they don't seem to show up anywhere,
Looks like it ignores my app's log4j.xml completely since the files I configured aren't being created,
So I assumed the logs would appear in jobserver's log but they aren't there either.

I'm using the trait org.apache.spark.Logging which gets the loggers using slf4j:

import org.slf4j.{Logger, LoggerFactory}
log_ = LoggerFactory.getLogger(logName)

How can I see my own application's logs using jobserver?

Thanks.

**Comment by velvia** [comment]
I assume you solved the problem?   If you use slf4j it should redirect
properly.

On Thu, May 28, 2015 at 12:04 AM, aviemzur <notifications@github.com> wrote:

> Closed #159
> <https://github.com/spark-jobserver/spark-jobserver/issues/159>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/159#event-315695006>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by aviemzur** [comment]
Yes. Couldn't find a way to delete the issue
