### ISSUE TITLE
Include Spark program jar file inside JobServer

### ISSUE THREAD

**Issue by ChenYanting** [spark-jobserver/spark-jobserver#161]
I would like to execute my Spark program through Spark JobServer. However, I don't want to put my Spark program directly into Spark JobServer's folder, like job-server-tests. As a result, is it possible to compile my Spark program to a jar file, and include this classpath inside the JobServer so that the SparkJob is able to call my Spark program?

If this is doable, where do I put the jar file that has my own Spark program?

**Comment by velvia** [comment]
Hi Yanting,

The standard procedure is to compile to a jar file and upload via POSTing
to the /jars route, not to include the jar in the classpath.   Sorry if
this is not clear from the README!

On Mon, Jun 1, 2015 at 8:44 PM, Yanting Chen <notifications@github.com>
wrote:

> I would like to execute my Spark program through Spark JobServer. However,
> I don't want to put my Spark program directly into Spark JobServer's
> folder, like job-server-tests. As a result, is it possible to compile my
> Spark program to a jar file, and include this classpath inside the
> JobServer so that the SparkJob is able to call my Spark program?
>
> If this is doable, where do I put the jar file that has my own Spark
> program?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/161>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ChenYanting** [comment]
@velvia 

So what you said is that I have to include my own business Spark codes with JobServer. Then, compile all of these codes into a single jar. Finally, upload this jar file using REST API. Is it right?

If there are some dependencies inside my business logic, which JobServer configuration files are required to modify? According to my experiment, the files that need to be changed are Dependencies.scala and Build.scala. Is it correct?

From here https://github.com/spark-jobserver/spark-jobserver#create-a-job-server-project,
Do I really need to create build.sbt in order to have my own project?

**Comment by velvia** [comment]
Hi, no you don't need to include your own business logic inside the job server project. If you are looking for a sample project for Scala jobs, that can compile a jar by itself... I have a sample project generator but it's a bit out of date.  It would be pretty unreasonable to ask you to build a jar that is part of the job server project. 

Let me update the sample project then point you at it.  I'll also update the README so it's more clear.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ChenYanting** [comment]
@velvia 
You said that I do not need to include business logic inside the job server project. So, there would be two jars, right? One is for SparkJob. The other includes my business.

However, how do I use SparkJob to launch my business logic which is in another different jar file from JobServer's?

p.s. My business logic is developed in Java rather than Scala.

**Comment by velvia** [comment]
So what I recommend is to put the java and Scala code all in one single
project, but that is independent of the job server project itself.

Perhaps an example would be easiest?

I have really old code here, which needs to be updated:

https://github.com/velvia/spark-jobserver-template.g8/tree/master/src/main/g8


On Wed, Jun 3, 2015 at 5:49 PM, Yanting Chen <notifications@github.com>
wrote:

> @velvia <https://github.com/velvia>
> You said that I do not need to include business logic inside the job
> server project. So, there would be two jars, right? One is for SparkJob.
> The other includes my business.
>
> However, how do I use SparkJob to launch my business logic which is in
> another different jar file from JobServer's?
>
> p.s. My business logic is developed in Java rather than Scala.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/161#issuecomment-108660868>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ChenYanting** [comment]
Yes, this is also what my current situation is. But, there would be some dependencies that I have to deal with. It is what I mentioned in the beginning.

In fact, I would like to run a Spark application which reads data from Cassandra. As a result, which file is used to control the dependencies? project/Dependencies.scala?

**Comment by velvia** [comment]
So, let me understand.  You have your Spark job, which is in one jar.
Then, you have some dependencies, which you do not want to package into
your job jar, is that right?

There are several options.  The easiest is to use the "dependent-jar-uris"
config param, which is documented in the README.   This is configured per
context, then you submit your job jar as usual using the REST API, and the
other dependent jar uses the config.

On Wed, Jun 3, 2015 at 6:10 PM, Yanting Chen <notifications@github.com>
wrote:

> Yes, this is also what my current situation is. But, there would be some
> dependencies that I have to deal with. It is what I mentioned in the
> beginning.
>
> In fact, I would like to run a Spark application which reads data from
> Cassandra. As a result, which file is used to control the dependencies?
> project/Dependencies.scala?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/161#issuecomment-108668781>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ChenYanting** [comment]
@velvia 
There is also a method called setJars in the class of SparkConf. Is using "dependent-jar-uris" the same as SparkConf.setJars?

**Comment by velvia** [comment]
More or less.  Since job server jobs don't control SparkConf directly it does this for you. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ChenYanting** [comment]
So, which method do you suggest? Use "dependent-jar-uris" or SparkConf.setJars?

Another question is that if I use "dependent-jar-uris", would jobServer fetch the jars located in this path in its node and copy jars to all Spark cluster workers?

**Comment by velvia** [comment]
If you use file:// or absolute path then the jars will be copied, just like with setJars. 

With job server you do not control SparkConf so calling setJars directly is not an option. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ChenYanting** [comment]
Oh, I see. Let me clarify that when using JobServer, I do not need to create a SparkConf object to pass it as a parameter of SparkContext. Is it right?

**Comment by velvia** [comment]
That's right.  If you implement SparkJob you will see that you are given the SparkContext already initialized.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ChenYanting** [comment]
So, if we want to make a similar action as what SparkConf does, we need to modify the file "local.conf" located inside the folder of job-server without declaring a SparkConf in SparkJob. Correct?

**Comment by velvia** [comment]
Right.  Declaring SparkConf won't do anything because by then SparkConf is already created. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ChenYanting** [comment]
However, since I am going to use Cassandra with JobServer, I need to set the Cassandra host. How do I set this value inside SparkConf object without declaring a new one?

**Comment by ChenYanting** [comment]
I have some more questions. For example, there are two JobServers, A and B. Then, there is one dependency jar file, X

1. If I put X to A and set JobServer A's dependent-jar-uris as X, then I send a request to A, would A copy X to all of workers? If Yes, is there any limitation on the jar size or anything else? Then, where does each worker save this jar file?

2. Since I do not put X to B, there would be something wrong while sending request to B. Is this correct?

3. I found that I can put setting, like "spark.cassandra.connection.host", in local.conf or just put into the REST url, like curl -d "" 'localhost:8090/contexts/test-context?spark.cassandra.connection.host=10.224.12.32'

For some dynamic setting value, the second one would be better, right? because I can get the correct value at runtime before building the URL.

**Comment by velvia** [comment]
Yanting,

Did you see this section of the README?

To pass settings directly to the sparkConf that do not use the "spark."
prefix "as-is", use the "passthrough" section.

    spark.context-settings {
        spark.cores.max = 10
        passthrough {
          some.custom.hadoop.config = "192.168.1.1"
        }
    }

For the exact context configuration parameters, see JobManagerActor docs as
well as application.conf.


On Thu, Jun 4, 2015 at 9:54 PM, Yanting Chen <notifications@github.com>
wrote:

> However, since I am going to use Cassandra with JobServer, I need to set
> the Cassandra host. How do I set this value inside SparkConf object without
> declaring a new one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/161#issuecomment-109161573>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
For 1 and 2:
 - If you POST your jar to the /jars route, then it will appear on all job
servers (assuming you configure JDBC to point at a shared database), and it
will be copied to all workers too.
  dependent-jar-uris is separate from /jars, if you already POSTed your jar
to /jars then you don't need to use dependent-jar-uris.
  Example: you would compile your Cassandra job using the
cassandra-spark-connector as % "provided", and post your job jar to job
server.  The cassandra-spark-connector and its dependencies should be added
as dependent-jar-uris (please use an assembly jar).

The dependent-jar-uris URI should be an absolute file path, or HDFS URL, if
you want it to be copied to all servers.

Hope this makes things clearer.

For 3.  See my previous response, and make sure you read the entire README!

On Fri, Jun 5, 2015 at 12:01 AM, Yanting Chen <notifications@github.com>
wrote:

> I have some more questions. For example, there are two JobServers, A and
> B. Then, there is one dependency jar file, X
>
>    1.
>
>    If I put X to A and set JobServer A's dependent-jar-uris as X, then I
>    send a request to A, would A copy X to all of workers? If Yes, is there any
>    limitation on the jar size or anything else? Then, where does each worker
>    save this jar file?
>    2.
>
>    Since I do not put X to B, there would be something wrong while
>    sending request to B. Is this correct?
>    3.
>
>    I found that I can put setting, like
>    "spark.cassandra.connection.host", in local.conf or just put into the REST
>    url, like curl -d ""
>    'localhost:8090/contexts/test-context?spark.cassandra.connection.host=10.224.12.32'
>
> For some dynamic setting value, the second one would be better, right?
> because I can get the correct value at runtime before building the URL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/161#issuecomment-109181455>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ChenYanting** [comment]
@velvia 

Thanks for your reply. 
Another situation is that I write a SparkJob inside jobServer. In my SparkJob, I would like to call invoke a class which is in another dependency jar file. However, when I execute "sbt package", it would say that it cannot find the class. As a result, how do I run "sbt package" to compile SparkJob using classes in another jar file?

P.S. in compile time, not run time.

**Comment by velvia** [comment]
Yanting,

If you include the dependency in your build file, or in lib/ or
lib_managed/, then SBT should be able to find it.   You may want to jump on
the SBT Gitter channel for better help.

On Fri, Jun 12, 2015 at 1:07 AM, Yanting Chen <notifications@github.com>
wrote:

> @velvia <https://github.com/velvia>
>
> Thanks for your reply.
> Another situation is that I write a SparkJob inside jobServer. In my
> SparkJob, I would like to call invoke a class which is in another
> dependency jar file. However, when I execute "sbt package", it would say
> that it cannot find the class. As a result, how do I run "sbt package" to
> compile SparkJob using classes in another jar file?
>
> P.S. in compile time, not run time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/161#issuecomment-111403485>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by linsimiao** [comment]
@velvia
 Hi velvia, I found that you recommented above that _The dependent-jar-uris URI should be an absolute file path, or HDFS URL, if
you want it to be copied to all servers. _  However, when I use a HDFS URL, malformedURLException would be thrown. Anyhelp will be greate.

**Comment by velvia** [comment]
I'm not sure an HDFS URL is supported for dependent jar URIs....

**Comment by linsimiao** [comment]
@velvia Then what's the recommended way to add dependent jar uris  when I am running SJS on docker.
