### ISSUE TITLE
Serialize JobConfig as JSON

### ISSUE THREAD

**Issue by olegshirokikh** [spark-jobserver/spark-jobserver#163]
In the route ```GET /jobs/<jobId>/config``` the TypeConfig is serialized as a string and returned as ```text/plain```. Maybe it'd be better and more consistent with other routes to render TypeConfig as a JSON? Something like this may do it, I guess?

```
val renderOptions = ConfigRenderOptions.concise().setJson(true);
...
case cnf: Config =>
            ctx.complete(cnf.root().render(renderOptions))
```

**Comment by velvia** [comment]
Thanks, I agree returning as JSON would be better.

Is there a separate issue for the other /config problem with sync routes?

On Wed, Jun 3, 2015 at 3:12 PM, Oleg Shirokikh <notifications@github.com>
wrote:

> In the route GET /jobs/<jobId>/config the TypeConfig is serialized as a
> string and returned as text/plain. Maybe it'd be better and more
> consistent with other routes to render TypeConfig as a JSON? Something like
> this may do it, I guess?
>
> val renderOptions = ConfigRenderOptions.concise().setJson(true);
>
> case cnf: Config =>
>             ctx.complete(cnf.root().render(renderOptions)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/163>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by olegshirokikh** [comment]
Hi Evan - Yes - please see issue #162

**Comment by fedragon** [comment]
Hello @olegshirokikh I cannot reproduce this issue locally, the configuration is properly returned as a JSON:

```
curl --verbose /jobs/0159b987-0a91-428a-89f5-856265b1ac9a/config

< HTTP/1.1 200 OK
< Server: spray-can/1.3.3
< Date: Sat, 30 Apr 2016 20:21:49 GMT
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=UTF-8
< Content-Length: 46
<
{
    "foo" : {
        "bar" : "baz"
    }
}
```

has this issue already been fixed?

**Comment by hntd187** [comment]
Jobs in the latest code are returned as JSON, please give the latest code a try and if this isn't what you intended please open a new issue. Thanks.
