### ISSUE TITLE
fat jar(Uber) for spark jobserver

### ISSUE THREAD

**Issue by gouravgupta92** [spark-jobserver/spark-jobserver#169]
How can i create fat jar for the spark jobserver i am not able to find anything regarding this.

**Comment by velvia** [comment]
It is created by "sbt assembly" or by one of the packaging scripts --
server_deploy.sh or server_package.sh.

Can close this after you try it?

On Wed, Jun 10, 2015 at 11:14 PM, gouravgupta92 <notifications@github.com>
wrote:

> How can i create fat jar for the spark jobserver i am not able to find
> anything regarding this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/169>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by gouravgupta92** [comment]
thanks
