### ISSUE TITLE
sbt reStart exit kills server.

### ISSUE THREAD

**Issue by mayfield2333** [spark-jobserver/spark-jobserver#171]
running sbt interactively works fine to start the server (i.e. run "sbt", then in the interactive shell type "reStart".

How do you setup the job server to use the server_start.sh and server_stop.sh script?

**Comment by velvia** [comment]
@mayfield2333 Look in the "Deployment" section of the README, it will tell you how to deploy it so you can run it with server_start.sh etc.   You need a Spark distribution for it to work.
