### ISSUE TITLE
I see errors while using spark-submit

### ISSUE THREAD

**Issue by noorul** [spark-jobserver/spark-jobserver#172]
When I use spark-submit script in server_start.sh I get errors but spark-jobserver runs.

http://pastie.org/10242361

**Comment by velvia** [comment]
Did you figure this out btw?   Isn't this due to earlier job server running?

On Tue, Jun 16, 2015 at 12:40 AM, Noorul Islam K M <notifications@github.com
> wrote:

> When I use spark-submit script in server_start.sh I get errors but
> spark-jobserver runs.
>
> http://pastie.org/10242361
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/172>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by noorul** [comment]
I was able to get rid of Address already in use error. But I still get the tput error. I am using chef-spark-jobserver for deployment.

**Comment by velvia** [comment]
Hm, I have no idea about the tput error, but does the job server actually
start, and are you able to execute normal requests?

On Thu, Jun 18, 2015 at 2:23 AM, Noorul Islam K M <notifications@github.com>
wrote:

> I was able to get rid of Address already in use error. But I still get the
> tput error. I am using chef-spark-jobserver for deployment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/172#issuecomment-113086997>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by noorul** [comment]
Yes, job server starts it works properly. Another thing I noticed is that logging is not happening properly. I am using dse submit.

**Comment by velvia** [comment]
Hm.  I would ping Mr. Russell Spitzer at Datastax, who has a prototype of
job server integrated into DSE.  (This is not official, but SJS might be
coming in future version  :)   He would know how to get things to work.

My guess is that dse submit somehow doesn't support all the same options as
spark-submit, in exactly the same way.

On Fri, Jun 19, 2015 at 12:09 AM, Noorul Islam K M <notifications@github.com
> wrote:

> Yes, job server starts it works properly. Another thing I noticed is that
> logging is not happening properly. I am using dse submit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/172#issuecomment-113403279>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by noorul** [comment]
I am actually using his version of server_start.sh https://github.com/RussellSpitzer/spark-jobserver/blob/DSP-47-EAP3/bin/server_start.sh

**Comment by velvia** [comment]
Wait. So you are getting those errors using his version of server_start?  Have you tried the version that's merged into master?  We fixed some logging issues I had seen earlier. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by noorul** [comment]
I think initial testing was with that one. But I think in that also I saw tput error, may be because chef recipe is using runit to launch Spark Job server. Having said that I still remember noticing that log where not going into /var/log/spark-jobserver/spark-jobserver.log but into current file. Did you notice the same?

**Comment by velvia** [comment]
I only tested locally by putting an explicit path into settings.sh.  Have
you tried putting an explicit path?

On Fri, Jun 19, 2015 at 2:23 AM, Noorul Islam K M <notifications@github.com>
wrote:

> I think initial testing was with that one. But I think in that also I saw
> tput error, may be because chef recipe is using runit to launch Spark Job
> server. Having said that I still remember noticing that log where not going
> into /var/log/spark-jobserver/spark-jobserver.log but into current file.
> Did you notice the same?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/172#issuecomment-113444215>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by noorul** [comment]
How do I do that?

**Comment by velvia** [comment]
@noorul when you run either `server_package.sh` or `server_deploy.sh` it creates a local file called `settings.sh`, which you need to modify for your deployment (it comes from local.sh or <env>.sh).  There is a variable LOG_DIR in there, so modify that.   Or a better way is to modify LOG_DIR in your <env>.sh script before you run one of the deploy scripts.

**Comment by zeitos** [comment]
@noorul Should we close this one?

**Comment by noorul** [comment]
Closing as this is not relevant anymore.
