### ISSUE TITLE
No configuration setting found for key 'akka.version'

### ISSUE THREAD

**Issue by ChenYanting** [spark-jobserver/spark-jobserver#173]
Hi

I have a Spark JobServer with dependent-jar-uris setting. dependent-jar-uris points to a dependency jar file. Sometimes, I have to upload a new version of the dependency jar file to the same location in order to replace the old one without stopping the JobServer. 

Then, when I create the context, I always see the error message below.
>
  "status": "CONTEXT INIT ERROR",
  "result": {
    "message": "No configuration setting found for key 'akka.version'",
    "errorClass": "com.typesafe.config.ConfigException$Missing",
    "stack": ["com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)", "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)", "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)", "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)", "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)", "com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)", "akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:168)", "akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:504)", "akka.actor.ActorSystem$.apply(ActorSystem.scala:141)", "akka.actor.ActorSystem$.apply(ActorSystem.scala:118)", "org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:122)", "org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:55)", "org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:54)", "org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1837)", "scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)", "org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1828)", "org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:57)", "org.apache.spark.SparkEnv$.create(SparkEnv.scala:223)", "org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:163)", "org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:269)", "org.apache.spark.SparkContext.<init>(SparkContext.scala:272)", "spark.jobserver.context.DefaultSparkContextFactory$$anon$1.<init>(SparkContextFactory.scala:41)", "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:41)", "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:34)", "spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:268)", "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:106)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:465)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"]

However, if I restart the JobServer, it works well as before. 

As a result, how do I make the JobServer work well after I replace a new dependency file?

**Comment by velvia** [comment]
So let me understand:

 - You upload dependent-jar-uris file, then start a context.
 - Now you upload a new version of dependent-jar-uris to new location.

Before step 2, did you shut down the previous context?  Otherwise it's
dangerous to replace the existing jar, unpredictable consequences will
happen because the jar is pulled from under the classloader.

I would recommend uploading to a new path, and changing the
dependent-jar-uris for new contexts you create.

On Wed, Jun 17, 2015 at 8:32 PM, Yanting Chen <notifications@github.com>
wrote:

> Hi
>
> I have a Spark JobServer with dependent-jar-uris setting.
> dependent-jar-uris points to a dependency jar file. Sometimes, I have to
> upload a new version of the dependency jar file to the same location in
> order to replace the old one without stopping the JobServer.
>
> Then, when I create the context, I always see the error message below.
>
> "status": "CONTEXT INIT ERROR",
> "result": {
> "message": "No configuration setting found for key 'akka.version'",
> "errorClass": "com.typesafe.config.ConfigException$Missing",
> "stack":
> ["com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)",
> "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)",
> "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)",
> "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)",
> "com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)",
> "com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)",
> "akka.actor.ActorSystem$Settings.(ActorSystem.scala:168)",
> "akka.actor.ActorSystemImpl.(ActorSystem.scala:504)",
> "akka.actor.ActorSystem$.apply(ActorSystem.scala:141)",
> "akka.actor.ActorSystem$.apply(ActorSystem.scala:118)",
> "org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:122)",
> "org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:55)",
> "org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:54)",
> "org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Ut
> ils.scal a:1837)",
> "scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)",
> "org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1828)",
> "org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:57)",
> "org.apache.spark.SparkEnv$.create(SparkEnv.scala:223)",
> "org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:163)",
> "org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:269)",
> "org.apache.spark.SparkContext.(SparkContext.scala:272)",
> "spark.jobserver.context.DefaultSparkContextFactory$$anon$1.(SparkContextFactory.scala:41)",
> "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:41)",
> "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:34)",
> "spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:268)",
> "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:106)",
> "scala.runtime.AbstractPartialFunction$mcVL$ sp.apply
> $mcVL$sp(AbstractPartialFunction.scala:33)",
> "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)",
> "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)",
> "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)",
> "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)",
> "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)",
> "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)",
> "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)",
> "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)",
> "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)",
> "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.
> scala:33 )",
> "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)",
> "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)",
> "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)",
> "akka.actor.Actor$class.aroundReceive(Actor.scala:465)",
> "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)",
> "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)",
> "akka.actor.ActorCell.invoke(ActorCell.scala:487)",
> "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)",
> "akka.dispatch.Mailbox.run(Mailbox.scala:220)",
> "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)",
> "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)",
> "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)",
> "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)",
> "scala.concurrent.forkjoin.Fork JoinWork
> erThread.run(ForkJoinWorkerThread.java:107)"]
>
> However, if I restart the JobServer, it works well as before.
>
> As a result, how do I make the JobServer work well after I replace a new
> dependency file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/173>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ChenYanting** [comment]
@velvia 
For current situation, I put dependent-jar to the same location. Besides, I tried to shut down the existing context before uploading a new jar. However, I still get the same error message when creating a new context.

Without uploading to a new path, the only solution to this problem is to restart the jobserver?

**Comment by velvia** [comment]
No, you should not have to restart, though to be honest I have not tested
this.  Each new context creates a new classloader, so in theory it should
work.

On Thu, Jun 18, 2015 at 1:30 AM, Yanting Chen <notifications@github.com>
wrote:

> @velvia <https://github.com/velvia>
> For current situation, I put dependent-jar to the same location. Besides,
> I tried to shut down the existing context before uploading a new jar.
> However, I still get the same error message when creating a new context.
>
> Without uploading to a new path, the only solution to this problem is to
> restart the jobserver?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/173#issuecomment-113075460>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ChenYanting** [comment]
@velvia 
Without restarting the job server, I cannot get the job server come back to normal status. Would you mind testing this scenario?

**Comment by velvia** [comment]
@ChenYanting I'll let you know when I have a chance to try it.

**Comment by ChenYanting** [comment]
@velvia 
Thanks a lot!

**Comment by ChenYanting** [comment]
@velvia 
Do you have any further idea about this issue?

**Comment by velvia** [comment]
@ChenYanting I have not had time to reproduce.   Have you tried to upload to a new path?

**Comment by zeitos** [comment]
Closing since we got no response from @ChenYanting
