### ISSUE TITLE
JobServer returning invalid JSON

### ISSUE THREAD

**Issue by mshanm10** [spark-jobserver/spark-jobserver#176]
Jobserver returned the below json response. The String PRODUCT1 is not enclosed with quotes because of which my client fails with "ValueError: No JSON object could be decoded".
  "status": "OK",
  "result": ["[17799.91015625,null,PRODUCT1]", "[50000.0,null,PRODUCT2]", "[0.0,null,PRODUCT4]"]

I am not sure how to fix this. Please help me.

**Comment by velvia** [comment]
What is the data structure returned by your job?  If you could tell us what
it is we could perhaps help.

On Sat, Jun 20, 2015 at 3:58 PM, mshanm10 <notifications@github.com> wrote:

> Jobserver returned the below json response. The String PRODUCT1 is not
> enclosed with quotes because of which my client fails with "ValueError: No
> JSON object could be decoded".
> "status": "OK",
> "result": ["[17799.91015625,null,PRODUCT1]", "[50000.0,null,PRODUCT2]",
> "[0.0,null,PRODUCT4]"]
>
> I am not sure how to fix this. Please help me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/176>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by mshanm10** [comment]
Basically I am executing a sql and getting its output as JSON.

sql="SELECT SUM(SALES_AMOUNT__180) as SALES_AMOUNT__180, ORDER_DATE__171__YEAR__208, PRODUCT_ID__172__PRODUCT_NAME__199 from TABLE__7057512925467189369 GROUP BY ORDER_DATE__171__YEAR__208, PRODUCT_ID__172__PRODUCT_NAME__199 LIMIT 10

I convert it to pandas dataframe in my client. It was working fine with older spark versions. I just upgraded it to Spark 1.3.1 and Jobserver 0.5.1 after which I observed this behaviour.

**Comment by velvia** [comment]
@mshanm10 Actually if you look at the JSON returned, it is not invalid JSON.  What you have is an array, of length 3, and each element is a string.  The string looks like JSON, but it is not.  The elements are:
"[17799.91015625,null,PRODUCT1]"

etc.

I believe the string is basically a Spark SQL Row object, and that is the way that Spark itself serializes it.

We could potentially improve the way that Dataframes are serialized.

**Comment by zeitos** [comment]
should we close this one?
