### ISSUE TITLE
Unable to set both es.nodes and es.nodes.discovery via passthrough section

### ISSUE THREAD

**Issue by emmekappa** [spark-jobserver/spark-jobserver#178]
Elasticsearch hadoop configuration uses "es.nodes" and "es.nodes.discovery" properties. Since typesafe config has no order is not possibile to set both those properties.

More info on Elasticsearch Hadoop configuration here: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html

This is a test that expose the issue: https://github.com/emmekappa/spark-jobserver/commit/e63876b4cdfba846ad80bdfcfc6cffce6147fdda

**Comment by velvia** [comment]
Hmmm.  What is the exact config you have tried?
Have you tried JSON?

es.nodes = "a,b,c"
es.nodes.discovery = "...."

or the JSON equivalent?


On Mon, Jun 22, 2015 at 3:39 PM, Michele Cantelli <notifications@github.com>
wrote:

> Elasticsearch hadoop configuration uses "es.nodes" and
> "es.nodes.discovery" properties. Since typesafe config has no order is not
> possibile to set both those properties.
>
> More info on Elasticsearch Hadoop configuration here:
> https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html
>
> This is a test that expose the issue: emmekappa@e63876b
> <https://github.com/emmekappa/spark-jobserver/commit/e63876b4cdfba846ad80bdfcfc6cffce6147fdda>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/178>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by emmekappa** [comment]
passthrough {
  es.nodes.discovery: false
  es.nodes = "foobar:9200"
}

this is my passthrough section, it seems that es.nodes overrides the es.nodes.dicovery.

**Comment by velvia** [comment]
Hmm.... that would be a bummer.

Not that it would make a difference, but discovery = false vs : ?

Also, have you tried JSON?

Perhaps we'll have to accept a different form of config, it might be a
fundamental Typesafe Config thing.

On Mon, Jun 22, 2015 at 3:43 PM, Michele Cantelli <notifications@github.com>
wrote:

> passthrough {
> es.nodes.discovery: false
> es.nodes = "foobar:9200"
> }
>
> this is my passthrough section, it seems that es.nodes overrides the
> es.nodes.dicovery.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/178#issuecomment-114291254>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by emmekappa** [comment]
I try both : and =

What do you mean by trying JSON?

**Comment by velvia** [comment]
You can submit the config in JSON format, eg

{ "passthrough":
   { "es.nodes.discovery": false,
     "es.nodes": "foobar:9200"
   }
}

On Mon, Jun 22, 2015 at 3:48 PM, Michele Cantelli <notifications@github.com>
wrote:

> I try both : and =
>
> What do you mean by trying JSON?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/178#issuecomment-114292168>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
@emmekappa this should be resolved with the latest code on master and my tip above.
