### ISSUE TITLE
Multiple spark context

### ISSUE THREAD

**Issue by gouravgupta92** [spark-jobserver/spark-jobserver#181]
I have created a spark job and calling that spark service concurrently using spark jobserver, Spark-Jobserver is creating multiple spark context for every job and because of that i am getting exception of multiple spark context.

Please provide information that how can i force jobserver to use only one Spark-Context. because i can not use multiple spark context.

**Comment by velvia** [comment]
Right now there is no way to limit the number of contexts, but you can
change a spark setting to allow multiple spark contexts.  Also see #120.

On Fri, Jun 26, 2015 at 12:41 AM, gouravgupta92 <notifications@github.com>
wrote:

> I have created a spark job and calling that spark service concurrently
> using spark jobserver, Spark-Jobserver is creating multiple spark context
> for every job and because of that i am getting exception of multiple spark
> context.
>
> Please provide information that how can i force jobserver to use only one
> Spark-Context. because i can not use multiple spark context.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/181>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison
