### ISSUE TITLE
CONTEXT INIT ERROR when making sparkSQL context with sparkjobserver

### ISSUE THREAD

**Issue by vqas** [spark-jobserver/spark-jobserver#182]
when I run
`curl -d "" 'localhost:8090/contexts/test-context?num-cpu-cores=4&memory-per-node=512m'`
it makes sparkContext with no problem but when I want to make a sparkSQL context I get an error I used this line to make it `curl -d "" '127.0.0.1:8090/contexts/sql-context?context-factory=spark.jobserver.context.SQLContextFactory'`
here is the response it gives
`{ "status": "CONTEXT INIT ERROR", "result": { "message": "", "errorClass": "java.lang.ClassNotFoundException", "stack": ["java.net.URLClassLoader$1.run(URLClassLoader.java:366)", "java.net.URLClassLoader$1.run(URLClassLoader.java:355)", "java.security.AccessController.doPrivileged(Native Method)", "java.net.URLClassLoader.findClass(URLClassLoader.java:354)", "java.lang.ClassLoader.loadClass(ClassLoader.java:425)", "java.lang.ClassLoader.loadClass(ClassLoader.java:358)", "spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:265)", "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:106)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:465)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"] }`
the same thing happens if I use `HiveContextFactory` too , this error comes even if my curl is like this `curl -d "" '127.0.0.1:8090/contexts/sql-context?context-factory'`

**Comment by velvia** [comment]
How are you starting the job server?  If using sbt / reStart, be sure to do 'project job-server-extras' first.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by vqas** [comment]
when I write `project job-server-extras` I get this 
*****************************************************************
    * WARNING: The 'project' command is now deprecated, this legacy *
    * link to the new executable, turnincfg, may disappear in any   *
    * future release.                                               *
    *****************************************************************
Usage: project [options] [project name]

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -d, --disable         Disable submissions for the current project.
  -D, --perm-disable    Permanently disable submissions for the current
                        project.
  -e, --enable          Enable submissions for the current project and make it
                        the default project.
  -l                    Enable submissions for the current project but don't
                        make it default.
  -r, --remove          Remove the current project and all associated files.
  -i, --init            Initialize this project.
  -p, --compress        Compress this project.
  -x, --extract         Extract this project.
  -v, --verify          Verify signatures on submitted projects.
  --list                Lists projects for the course. Also displays wether or
                        not the project is enabled.
  -c COURSE, --course=COURSE
                        Course name
  -C CONFIG, --config=CONFIG
                        Use an alternate config file.
  -w, --legal           Print warranty and license information.

  Administrative options:
    These options can add or remove courses, etc.

    --create-course=CREATE_COURSE
                        Creates a course.
    --delete-course=DELETE_COURSE
                        Deletes a course.
    --archive-course=ARCHIVE_COURSE
                        Archive a course.
Please specify your course using the '-c course' or '--course=COURSE' options.

**Comment by velvia** [comment]
No I mean within SBT.  Or you can deploy job server using the scripts in bin/, see the section in README. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by vqas** [comment]
thanks , its solved

**Comment by rahuljain788** [comment]
@vqas  can you please explain how you did this i am also getting the below error:

  "status": "CONTEXT INIT ERROR",
  "result": {
    "message": "spark.jobserver.context.SQLContextFactory",
    "errorClass": "java.lang.ClassNotFoundException",
    "stack": ["java.net.URLClassLoader.findClass(Unknown Source)", "java.lang.ClassLoader.loadClass(Unknown Source)", "java.lang.ClassLoader.loadClass(Unknown Source)", "spark.jobserver.JobManagerActor.getContextFactory(JobManagerActor.scala:360)", "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:133)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:467)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"]
  }
}

**Comment by katzuri** [comment]
me either. @vqas can you please explain when you've done to solve it?

**Comment by aarthipa** [comment]
Hi, I get the same error. 
Here are the steps done to start the server (followed read me). Note that SJS version is master, Spark version is 1.6.2

1. git clone https://github.com/spark-jobserver/spark-jobserver
2. Added mySJSmaster.sh and mySJSmaster.conf according to templates to spark-jobserver/job-server/config
3. bin/server_package.sh mySJSmaster (which completed successfully with the following messages)
```[info] Done packaging.
[success] Total time: 39 s, completed Oct 3, 2016 11:13:37 AM
cp: cannot stat `config/shiro.ini': No such file or directory
/tmp/job-server ~/workspace/sparkjobserver/master/spark-jobserver
kill-process-tree.sh
log4j-server.properties
manager_start.sh
mySJSmaster.conf
server_start.sh
server_stop.sh
setenv.sh
settings.sh
spark-job-server.jar
~/workspace/sparkjobserver/master/spark-jobserver
Created distribution at /tmp/job-server/job-server.tar.gz```
4. Note that at this point, with SJS 0.6, the start/stop scripts were copied to the /spark-jobserver dir. But here is how it looks with master version
```spark-jobserver]$ ls
akka-app  build.sbt  config  job-server      job-server-extras  job-server-tests  notes    README.md              src     timing-tests
bin       ci         doc     job-server-api  job-server-python  LICENSE.md        project  scalastyle-config.xml  target  version.sbt```
5. Since there was no server_start.sh script available in the above main dir, tried the following
```bin/server_start.sh
ls: cannot access /home/spark/workspace/sparkjobserver/master/spark-jobserver/bin/*.conf: No such file or directory```
6. So I tried this alternative
   sbt
   job-server/reStart config/mySJSmaster.conf -Xmx8g
    On which, I get the following success messages
    ```[success] created output: /home/spark/workspace/sparkjobserver/master/spark-jobserver/akka-app/target
[info] Application job-server not yet started
[info] Starting application job-server in the background ...
job-server Starting spark.jobserver.JobServer.main(config/mySJSmaster.conf, -Xmx8g)
job-server[ERROR] OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0


SJS is started at this point. Now when I upload the context, I get this error

curl 'http://somemachine:8090/contexts/hiveContext?appName=secondtest&classPath=endpointWorks.getEPRBasicParmsCompare&context-factory=spark.jobserver.context.HiveContextFactory' -d ""
{
  "status": "CONTEXT INIT ERROR",
  "result": {
    "message": "Could not find resource path for Web UI: org/apache/spark/sql/execution/ui/static",
    "errorClass": "java.lang.Exception",
    "stack": ["org.apache.spark.ui.JettyUtils$.createStaticHandler(JettyUtils.scala:180)", "org.apache.spark.ui.WebUI.addStaticHandler(WebUI.scala:117)", "org.apache.spark.sql.

**Comment by aarthipa** [comment]
@velvia Can you explain this comment of yours "How are you starting the job server? If using sbt / reStart, be sure to do 'project job-server-extras' first."
Does this mean doing the following?
1. sbt (opens sbt shell)
2. job-server/reStart config/mySJSmaster.conf
3. job-server-extras/reStart config/mySJSmaster.conf

So should I also build the job-server-api then? The readme file is not specific about this.
Appreciate the help..

**Comment by velvia** [comment]
Hi,

First of all, for any serious deployment I strongly recommend you follow the Deployment section and use the scripts instead of doing reStart.

What I mean is 

1. sbt (opens shell)
2. job-server-extras/reStart

That’s it.

**Comment by AnshPrusty** [comment]
Hi @velvia ,
can tell me how to make these two options{sbt (opens shell),job-server-extras/reStart} working using ./bin/server_start.sh command.


It works fine using sbt, but I want to use the start/stop service then how to configure that???

Thanks
Anshuman

**Comment by velvia** [comment]
Hi Anush,

So the server_start script is meant to be used after you deploy.  Please follow the deploy instructions (or boot the docker container, which runs it for you).

**Comment by linsimiao** [comment]
I start jobserver by `sbt` and then `job-server-extras/reStart`, and I get the same error.
