### ISSUE TITLE
Spark-jobserver For Java Apps

### ISSUE THREAD

**Issue by littlestar99** [spark-jobserver/spark-jobserver#184]
similar to http://qnalist.com/questions/5326105/spark-jobserver-for-java-apps

Hi,
I'm working on the problem of remotely submitting apps to the spark
master. I'm trying to use the spark-jobserver project
(https://github.com/spark-jobserver/spark-jobserver) for that purpose.
For scala apps looks like things are working smoothly, but for java
apps, I have an issue with implementing the scala trait "SparkJob" in
java. Specifically, I'm trying to implement the "validate" method like
this:
@Override
public SparkJobValidation validate(SparkContext sc, Config conf) {
    return new SparkJobValid();
}
I'm getting the following compilation error:
Type mismatch: cannot convert from SparkJobValid to SparkJobValidation
Would love for some advice / working example.
Thanks,

**Comment by littlestar99** [comment]
package spark.jobserver

import org.apache.spark.SparkContext
import com.typesafe.config.Config
import org.apache.spark.api.java.JavaSparkContext

class JavaSparkJob extends SparkJob {

  override def runJob(sc: SparkContext, jobConfig: Config): Any = {
    runJob(new JavaSparkContext(sc), jobConfig);
  }

  override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
    var errMsg=validate(new JavaSparkContext(sc), config);
    if(errMsg==null){
      return SparkJobValid;
    }else{
      return SparkJobInvalid(errMsg);
    }
  }

  def runJob(jsc: JavaSparkContext, jobConfig: Config): Any={}

  def validate(jsc: JavaSparkContext, config: Config):String={null}

}

**Comment by velvia** [comment]
Thanks. I was thinking of something similar too. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by littlestar99** [comment]
another patch, also works well for java.

--- spark-jobserver-0.5.1/job-server/src/spark.jobserver/JobManagerActor.scala	2015-05-15 08:33:35.000000000 +0800
+++ spark-jobserver-0.5.1-build/job-server/src/spark.jobserver/JobManagerActor.scala	2015-06-29 18:55:38.165193298 +0800
@@ -228,7 +228,7 @@
             statusActor ! JobValidationFailed(jobId, DateTime.now(), err)
             throw err
           }
-          case SparkJobValid => {
+          case _ => {
             statusActor ! JobStarted(jobId: String, contextName, jobInfo.startTime)
             val sc = jobContext.sparkContext
             sc.setJobGroup(jobId, s"Job group for $jobId and spark context ${sc.applicationId}", true)

**Comment by littlestar99** [comment]
another patch for JobManagerActor.scala, works well for java too.
-          case SparkJobValid => {
+          case _ => {

**Comment by 0612800232** [comment]
hi, littestar99  , i have same problem , but it do not work  after 
--- case SparkJobValid => {
+++ case _ => {

here is the error info


[2015-09-02 10:57:22,664] ERROR akka.actor.ActorSystemImpl [] [ActorSystem(JobServer)] - Uncaught error from thread [JobServer-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.AbstractMethodError: com.caishuo.demo.JavaWordCount.validate(Lorg/apache/spark/SparkContext;Lcom/typesafe/config/Config;)Lspark/jobserver/SparkJobValidation;
	at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:214)

**Comment by velvia** [comment]
I just created a PR based on the JavaSparkJob thing from @littlestar99.

https://github.com/spark-jobserver/spark-jobserver/pull/239

Have a look and see if it works for you.

Java folks, please feel free to make suggestions on the PR.

On Tue, Sep 1, 2015 at 7:59 PM, 0612800232 <notifications@github.com> wrote:

> hi, littestar99 , i have same problem , but it do not work after
> --- case SparkJobValid => {
> +++ case _ => {
>
> here is the error info
>
> [2015-09-02 10:57:22,664] ERROR akka.actor.ActorSystemImpl []
> [ActorSystem(JobServer)] - Uncaught error from thread
> [JobServer-akka.actor.default-dispatcher-3] shutting down JVM since
> 'akka.jvm-exit-on-fatal-error' is enabled
> java.lang.AbstractMethodError:
> com.caishuo.demo.JavaWordCount.validate(Lorg/apache/spark/SparkContext;Lcom/typesafe/config/Config;)Lspark/jobserver/SparkJobValidation;
> at
> spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:214)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/184#issuecomment-136919366>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
@littlestar99 my PR has been merged.  Try out the JavaSparkJob and see what you think!
