### ISSUE TITLE
SparkContextFactory makeContext sparkConf parameter type causing error

### ISSUE THREAD

**Issue by vmgarcia** [spark-jobserver/spark-jobserver#185]
basically I was trying to create a custom Context but when I was building I got a type mismatch error from makeContext.
```
[error] /vagrant/SQLJob/src/main/scala/sqljob/context/CassandraSQLContextFactory.scala:12: class CassandraSQLContextFactory needs
to be abstract, since method makeContext in trait SparkContextFactory of type (config: com.typesafe.config.Config, contextConfig:
com.typesafe.config.Config, contextName: String)CassandraSQLContextFactory.this.C is not defined
[error] (Note that com.typesafe.config.Config does not match org.apache.spark.SparkConf)
[error] class CassandraSQLContextFactory extends SparkContextFactory {
[error]       ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 4 s, completed Jun 29, 2015 4:00:36 PM
```

Basically even though there is a method defined that should take a SparkConf it throws an error. The way I got around it was by changing the type of sparkConf to a typesafe Config instead of using a SparkConf and then converting it to a SparkConf using `configToSparkConf` method from SparkJobUtils

All of the example custom Contexts from spark-jobserver-extras use SparkConf type in their make context methods. 

I'm pretty sure this behavior isn't intended.

**Comment by zeitos** [comment]
@vmgarcia were you able to fix this?

**Comment by hntd187** [comment]
Since this hasn't had an update in a long time I am closing this. Please give the latest code a try and open a new issue if you are having issues still. Thanks.
