### ISSUE TITLE
Sequential or  parallel?

### ISSUE THREAD

**Issue by ChenYanting** [spark-jobserver/spark-jobserver#189]
If I send multiple requests to JobServer using the same context, does JobServer deal with these requests sequentially or  in parallel way?

**Comment by velvia** [comment]
That depends on the setting of spark.scheduler.mode.  See
https://spark.apache.org/docs/latest/configuration.html for a
description.   Hope that answers your question!

On Thu, Jul 2, 2015 at 6:58 PM, Yanting Chen <notifications@github.com>
wrote:

> If I send multiple requests to JobServer using the same context, does
> JobServer deal with these requests sequentially or in parallel way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/189>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison
