### ISSUE TITLE
Failover of Spark JobServer

### ISSUE THREAD

**Issue by ChenYanting** [spark-jobserver/spark-jobserver#190]
Hi

If too many requests causes Spark JobServer crash down, does Spark JobServer have any mechanism for failover?

**Comment by velvia** [comment]
You can run multiple ones, all pointing to the same database, and use a
load balancer in front for HA.

By the way, feel free to use the google group to ask questions, it may work
better than to use issues.  :)

On Tue, Jul 7, 2015 at 10:21 PM, Yanting Chen <notifications@github.com>
wrote:

> Hi
>
> If too many requests causes Spark JobServer crash down, does Spark
> JobServer have any mechanism for failover?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/190>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
Let's close this and refer to #42 for the HA discussion.
