### ISSUE TITLE
Question: Yarn Cluster Mode Support

### ISSUE THREAD

**Issue by orchestro-docker** [spark-jobserver/spark-jobserver#193]
I've read up in the docs and noticed that Spark Job Server supports yarn-client mode. Is yarn-cluster mode supported as well?

**Comment by camechis** [comment]
I have this same question as well.

**Comment by pavyer** [comment]
Hmm, interesting, I've the same question, I've tested the spark app in yarn cluster mode and wanted to know if spark job server supports yarns cluster mode too.

**Comment by velvia** [comment]
Why don't you guys try it out on the latest master which uses spark-submit within server_start.sh?  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by zeitos** [comment]
Last time I checked it wasn't working, I started to investigate on how to change that but I had to switch to other tasks :(

**Comment by Velmuruganms12** [comment]
I am trying to run the JobServe in Yarn cluster mode when run the server_start.sh i am getting following error. I gave my cluster master and slave url but got following error.

Please let me know the details steps for running Job Serve in Yarn cluster.

I use Cloudera 5.5.1 and spark 1.5.0


Logs :

[info] Including from cache: netty-3.8.0.Final.jar
[info] Including from cache: protobuf-java-2.5.0.jar
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[warn] Merging 'META-INF/LICENSE.txt' with strategy 'first'
[warn] Merging 'META-INF/MANIFEST.MF' with strategy 'discard'
[warn] Merging 'META-INF/NOTICE.txt' with strategy 'first'
[warn] Merging 'reference.conf' with strategy 'concat'
[warn] Strategy 'concat' was applied to a file
[warn] Strategy 'discard' was applied to a file
[warn] Strategy 'first' was applied to 2 files
[info] SHA-1: fc199848e2ab979f2562f591cfad1b20b5bf6c18
[info] Packaging /home/ubuntu/crossdata/spark-jobserver-master/job-server-extras/target/scala-2.10/spark-job-server.jar ...
[info] Done packaging.
[success] Total time: 43 s, completed Mar 7, 2016 4:56:17 PM
Permission denied (publickey).
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).

**Comment by hntd187** [comment]
@Velmuruganms12 It would appear your machine cannot ssh into the other machines. Did you setup keyless SSH login?

**Comment by hntd187** [comment]
Going to merge this with #451, let's continue the discussion there.
