### ISSUE TITLE
When submit a job, if sparkcontext not alive, send ContextStopped message to LocalContextSupervisorActor to do the sc clean up job.

### ISSUE THREAD

**Issue by litao-buptsse** [spark-jobserver/spark-jobserver#200]
When submit a job, if sparkcontext not alive (e.g. yarn application -kill $appId), the context meta is still exist in jobserver. So when I want to recreate a context, the jobserver tell me the context is existed.

So I make this PR, When submit a job, if sparkcontext not alive, send ContextStopped message to LocalContextSupervisorActor to do the sc clean up job.

I create a PR at #199

**Comment by velvia** [comment]
Many thanks for the PR!   Appreciate it.  Can probably merge before doing
next release which is imminent.

On Tue, Aug 4, 2015 at 7:55 AM, Tao Li <notifications@github.com> wrote:

> When submit a job, if sparkcontext not alive (e.g. yarn application -kill
> $appId), the context meta is still exist in jobserver. So when I want to
> recreate a context, the jobserver tell me the context is existed.
>
> So I make this PR, When submit a job, if sparkcontext not alive, send
> ContextStopped message to LocalContextSupervisorActor to do the sc clean up
> job.
>
> I create a PR at #199
> <https://github.com/spark-jobserver/spark-jobserver/pull/199>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/200>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by litao-buptsse** [comment]
You're welcome :smiley:
