### ISSUE TITLE
Reserved character '*' is not allowed outside quotes

### ISSUE THREAD

**Issue by vqas** [spark-jobserver/spark-jobserver#203]
when I try to select a whole row from a table with * in sql I get this error 

`
"result": "Cannot parse config: String: 1: Reserved character '*' is not allowed outside quotes (if you intended '*' (Reserved character '*' is not allowed outside quotes) to be part of the value for 'sql', try enclosing the value in double quotes, or you may be able to rename the file .properties rather than .conf)"
`
and this is how I call it 

`
 curl -d "sql=SELECT * FROM addresses" '127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context&sync=true'
`

and for selecting two properties the same happens I mean like this
 
`
 curl -d "sql=SELECT firstName,lastName FROM addresses" '127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context&sync=true'
`

but instead of * it gets stuck with comma 
so how should I do * or , ?
thank you

**Comment by velvia** [comment]
Try surrounding the SQL with single quotes. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by vqas** [comment]
tried
`
curl -d "'sql'=SELECT firstName,lastName FROM addresses" '127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context&sync=true' 
`
and
`
curl -d  'sql=SELECT firstName,lastName FROM addresses' '127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context&sync=true' 
`

but the error continues

**Comment by velvia** [comment]
No try quoting like this

curl -d "sql='SELECT firstName,lastName FROM addresses'"

On Mon, Aug 10, 2015 at 8:24 AM, vqas <notifications@github.com> wrote:

> tried
>
> curl -d "'sql'=SELECT firstName,lastName FROM addresses" '
> 127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context&sync=true'
>
>
> and
>
> curl -d 'sql=SELECT firstName,lastName FROM addresses' '
> 127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context&sync=true'
>
>
> but the error continues
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/203#issuecomment-129493874>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by vqas** [comment]
did that too didnt worked

**Comment by vqas** [comment]
So , what should I do ?

**Comment by velvia** [comment]
@vqas try using `--data-binary` instead of `-d` ...  or put it into a file, and do `--data-binary @file.json`,
 or using a real REST client from your favorite scripting language....   but I'm pretty sure this is a quoting thing.

**Comment by noorul** [comment]
@vqas Is this working for you with --data-binary option? If so can you close this issue?

**Comment by vqas** [comment]
double quote around key and another double quote around value and a single quote around all

`curl -d  ' "sql"="SELECT * FROM addresses" ' '127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context&sync=true'` 

thx
