### ISSUE TITLE
can't deploy jobserver in local: Assembly failed

### ISSUE THREAD

**Issue by DNgh** [spark-jobserver/spark-jobserver#204]
[root@s0 config]# /root/spark-jobserver/bin/server_deploy.sh local
Deploying job server to localhost...
[info] Loading project definition from /root/spark-jobserver/project
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to root (in build file:/root/spark-jobserver/)
[info] Setting version to 2.10.4
[info] Reapplying settings...
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to root (in build file:/root/spark-jobserver/)
[info] scalastyle using config /root/spark-jobserver/scalastyle-config.xml
[info] Processed 9 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 12 ms
[success] created output: /root/spark-jobserver/job-server-extras/target
[warn] Credentials file /root/.bintray/.credentials does not exist
[warn] Credentials file /root/.bintray/.credentials does not exist
[warn] Credentials file /root/.bintray/.credentials does not exist
[warn] Credentials file /root/.bintray/.credentials does not exist
[info] scalastyle using config /root/spark-jobserver/scalastyle-config.xml
[info] Processed 11 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 2 ms
[success] created output: /root/spark-jobserver/akka-app/target
[info] scalastyle using config /root/spark-jobserver/scalastyle-config.xml
[info] Processed 22 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 4 ms
[success] created output: /root/spark-jobserver/job-server/target
[info] scalastyle using config /root/spark-jobserver/scalastyle-config.xml
[info] Processed 3 file(s)
[info] Found 0 errors
[info] Found 0 warnings
[info] Found 0 infos
[info] Finished in 1 ms
[success] created output: /root/spark-jobserver/job-server-api/target
[info] Compiling 9 Scala sources to /root/spark-jobserver/job-server-extras/target/scala-2.10/classes...
[error] /root/spark-jobserver/job-server-extras/src/spark.jobserver/SqlTestJob.scala:22: value implicits is not a member of org.apache.spark.sql.SQLContext
[error]     import sql.implicits._
[error]                ^
[error] /root/spark-jobserver/job-server-extras/src/spark.jobserver/SqlTestJob.scala:24: value toDF is not a member of org.apache.spark.rdd.RDD[spark.jobserver.SqlLoaderJob.Address]
[error]     addrRdd.toDF().registerTempTable("addresses")
[error]             ^
[error] /root/spark-jobserver/job-server-extras/src/spark.jobserver/StreamingTestJob.scala:21: value reduceByKey is not a member of org.apache.spark.streaming.dstream.DStream[(String, Int)]
[error]     val wordCounts = pairs.reduceByKey(_ + _)
[error]                            ^
[error] three errors found
[error] (job-server-extras/compile:compile) Compilation failed
[error] Total time: 11 s, completed Aug 11, 2015 8:13:10 PM
Assembly failed

**Comment by DNgh** [comment]
I fix it, by updating spark 1.2.1 to 1.3.1.

**Comment by velvia** [comment]
Sounds like this can be closed then.
