### ISSUE TITLE
Docker standard out logging

### ISSUE THREAD

**Issue by MeiSign** [spark-jobserver/spark-jobserver#213]
I have downloaded and started the docker container as explained in the readme. 
It seems to me like logging does not work out of the box:

    ~ » docker logs -f 0032b570ae14                                                                                                                                  
    tput: No value for $TERM and no -T specified
    log4j:WARN No such property [datePattern] in org.apache.log4j.RollingFileAppender.

There should be some errors in the log because I am struggling with configuring the jobserver with yarn currently. API Responsen contain exceptions but the log remains empty except this $TERM message and the log4j warning.

**Comment by MeiSign** [comment]
The warning just says that datePattern is no valid parameter of the RollingFileAppender and can be easily resolved #214

**Comment by MeiSign** [comment]
I just found out that the `tput: No value for $TERM and no -T specified` message is gone when I use the docker run command with -t. The log however stays empty so I have no idea if this is a good or bad sign...

**Comment by velvia** [comment]
Will have a look at the PR, thanks!

On Thu, Aug 20, 2015 at 8:33 AM, Stefan Meiwald <notifications@github.com>
wrote:

> I just found out that the tput: No value for $TERM and no -T specified
> message is gone when I use the docker run command with -t. The log however
> stays empty so I have no idea if this is a good or bad sign...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/213#issuecomment-133052907>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
BTW, I just tried this, and it works for me.

docker run -d -p 8090:8090 velvia/spark-jobserver:0.5.2

ubuntu@ubuntu-amd64:~$ docker logs -f e14b5fbd97b1
LOG_DIR empty; logging will go to /tmp/job-server
tput: No value for $TERM and no -T specified
[2015-08-20 18:24:53,198] INFO  spark.jobserver.JobServer$ [] [] - Starting
JobServer with config {
    # system properties
    "app" : {
        # system properties
        "name" : "spark.jobserver.JobServer"
    },

On Thu, Aug 20, 2015 at 5:09 AM, Stefan Meiwald <notifications@github.com>
wrote:

> I have downloaded and started the docker container as explained in the
> readme.
> It seems to me like logging does not work out of the box:
>
> ~ » docker logs -f 0032b570ae14
> tput: No value for $TERM and no -T specified
> log4j:WARN No such property [datePattern] in org.apache.log4j.RollingFileAppender.
>
> There should be some errors in the log because I am struggling with
> configuring the jobserver with yarn currently. API Responsen contain
> exceptions but the log remains empty except this $TERM message and the
> log4j warning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/213>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by MeiSign** [comment]
Thats interesting, let me try it with the original config that gets shipped with the docker image. I will tell you tomorrow if that works for me aswell.. I did some changes to let the server run with yarn in client mode.

**Comment by velvia** [comment]
Would be interested in your config changes for YARN as well.... anything to
pass along to other users?

On Thu, Aug 20, 2015 at 12:09 PM, Stefan Meiwald <notifications@github.com>
wrote:

> Thats interesting, let me try it with the original config that gets
> shipped with the docker image. I will tell you tomorrow if that works for
> me aswell.. I did some changes to let the server run with yarn in client
> mode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/213#issuecomment-133125601>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by MeiSign** [comment]
If I get it up and running I will write a step by step documentation how to get it work in yarn client mode. Was missing that documentation aswell... ;)
Right now I have the problem that jobs get submitted and accepted but than they fail for any reason and I still can't access the logs so far. Might be a problem with my docker installation

**Comment by velvia** [comment]
@MeiSign will worry about the snapshot container later...  it sounds like the original issue is not an issue anymore, though, so I'll close it for now.  Feel free to reopen if this pops up again!
