### ISSUE TITLE
With PostgreSQL backend /jobs page fails to load after 135577 records

### ISSUE THREAD

**Issue by noorul** [spark-jobserver/spark-jobserver#229]
Our JOBS database has the following number of records

demeter_spark_jobserver=# select count(*) from "JOBS";
 count
--------
 135577

Is this is a known issue with other backends?

**Comment by velvia** [comment]
I think the JobSqlDao doesn't have a limit when retrieving jobs.  That's
probably the problem.

On Thu, Aug 27, 2015 at 5:02 AM, Noorul Islam K M <notifications@github.com>
wrote:

> Our JOBS database has the following number of records
>
> demeter_spark_jobserver=# select count(*) from "JOBS";
> count
>
> 135577
>
> Is this is a known issue with other backends?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/229>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by noorul** [comment]
It looks like, limit is done on the data that is fetched from DB. I think we should restrict data fetch from DB. I will work on a patch for this.

**Comment by velvia** [comment]
@noorul thanks!

On Thu, Sep 3, 2015 at 10:42 AM, Noorul Islam K M <notifications@github.com>
wrote:

> It looks like, limit is done on the data that is fetched from DB. I think
> we should restrict data fetch from DB. I will work on a patch for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/229#issuecomment-137523956>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by zeitos** [comment]
Closing the issue since PR https://github.com/spark-jobserver/spark-jobserver/pull/248 was merged
