### ISSUE TITLE
give params "input filename" and "output filename"

### ISSUE THREAD

**Issue by DNgh** [spark-jobserver/spark-jobserver#233]
in examples, submit job like this:
curl -d "input.string = hello job server" 'hdp01:8090/jobs?appName=test&classPath=spark.jobrver.WordCountExample'

But i want to supply more params, like "inputfile name and output filename in hdfs"
when i submit job to spark-jobserver, how can i give params "hdfs input filename" and "hdfs output filename"?

**Comment by velvia** [comment]
@DNgh You put them as multiple lines in a config, and POST the entire config.  For example if the config has:
```
   {
      input.string = hello job server
      hdfs {
         inputfile = "/my/file/foo"
      }
   }
```

Then inside your job, you can do `config.getString("hdfs.inputfile")`.
