### ISSUE TITLE
JobServer killed immediately after reStart

### ISSUE THREAD

**Issue by kamleshg** [spark-jobserver/spark-jobserver#235]
Im using latest JobServer code against Spark 1.3.1

If i run "sbt reStart" in the root directory of "Spark-Jobserver" directory, it starts and gets killed immediately, here is the logs:

[info] Application job-server not yet started
[info] Starting application job-server in the background ...
job-server Starting spark.jobserver.JobServer.main()
[success] Total time: 41 s, completed Aug 31, 2015 12:45:09 PM
job-server ... killing ...
spark@spark-service:~/dev/spark-jobserver$

**Comment by noorul** [comment]
Is there a file named current in the log directory or current directory? That might contain some clue. But I never used latest version of SJS.

**Comment by velvia** [comment]
@kamleshg sorry you can't do "sbt reStart", you have to log into the SBT
shell by doing "sbt" first, then when you are in the shell, do "reStart".
I'll check the instructions to make sure it's clear.

On Mon, Aug 31, 2015 at 9:59 PM, Noorul Islam K M <notifications@github.com>
wrote:

> Is there a file named current in the log directory or current directory?
> That might contain some clue. But I never used latest version of SJS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/235#issuecomment-136586885>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
Ok, I updated the README.

**Comment by kamleshg** [comment]
Ok, makes sense, it runs now.  I'm trying to get the Cassandra Connector package to be resolved, but cant seem to get it to work. I've tried the following ways..

1) if i put it in: ?dependent-jar-uris=file:///some/path/of/my-foo-lib.jar' I cant get more then one jar in url, and there are many dependencies.

2) Putting jars in in local.conf under dependent-jar-uris = ["file:///home/spark/dev/spark-cassandra-connector/target/scala-2.10....", "" ]

3) and under application.conf under dependent-jar-uris.

4) I even tried /tmp/job-server/server_start.sh --packages com.datastax.spark:spark-cassandra-connector_2.10:1.3.0-M1 to server_start.sh

Please help me, i've been at this for days :(

**Comment by noorul** [comment]
Since this issue is closed. I suggest you re-open this or create a new one.  Why are you saying that it is not getting resolved. Could you post traceback?

**Comment by velvia** [comment]
What version of everything are you using?  I would ping Russell Spitzer at
Datastax also.   Why does things fail?

On Tue, Sep 1, 2015 at 4:46 PM, Noorul Islam K M <notifications@github.com>
wrote:

> Since this issue is closed. I suggest you re-open this or create a new
> one. Why are you saying that it is not getting resolved. Could you post
> traceback?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/235#issuecomment-136893825>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by kamleshg** [comment]
Man i feel silly, i forgot to point to my local.conf it works now....
