### ISSUE TITLE
NoClassDefFoundError: spark.jobserver.SparkJobValidation running main of WordCountExample

### ISSUE THREAD

**Issue by kikicarbonell** [spark-jobserver/spark-jobserver#237]
I'm trying spark-jobserver to develop demo app. Then I create a project with:

**build.sbt**
```
name := "demo-spark-app"

version := "1.0"

scalaVersion := "2.11.7"

resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"

libraryDependencies ++= Seq (
  "spark.jobserver" %% "job-server-api" % "0.5.2" % "provided",
  "org.apache.spark" %% "spark-core" % "1.4.1"
)
```
**src/main/scala/spark/jobserver/WordCountExample**
```
package spark.jobserver

import com.typesafe.config.{Config, ConfigFactory}
import org.apache.spark._
import org.apache.spark.SparkContext._
import scala.util.Try

/**
* A super-simple Spark job example that implements the SparkJob trait and can be submitted to the job server.
*
* Set the config with the sentence to split or count:
* input.string = "adsfasdf asdkf  safksf a sdfa"
*
* validate() returns SparkJobInvalid if there is no input.string
*/
object WordCountExample extends SparkJob {
  def main(args: Array[String]) {
    val sc = new SparkContext("local[4]", "WordCountExample")
    val config = ConfigFactory.parseString("")
    val results = runJob(sc, config)
    println("Result is " + results)
  }

  override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
    Try(config.getString("input.string"))
      .map(x => SparkJobValid)
      .getOrElse(SparkJobInvalid("No input.string config param"))
  }

  override def runJob(sc: SparkContext, config: Config): Any = {
    val dd = sc.parallelize(config.getString("input.string").split(" ").toSeq)
    dd.map((_, 1)).reduceByKey(_ + _).collect().toMap
  }
}
```
After succesfull `sbt compile` I execute `sbt run` and the error it's:
```
[error] (run-main-0) java.lang.NoClassDefFoundError: spark/jobserver/SparkJobValidation
java.lang.NoClassDefFoundError: spark/jobserver/SparkJobValidation
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getMethod0(Class.java:2856)
        at java.lang.Class.getMethod(Class.java:1668)
Caused by: java.lang.ClassNotFoundException: spark.jobserver.SparkJobValidation
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getMethod0(Class.java:2856)
        at java.lang.Class.getMethod(Class.java:1668)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
```
But when I use sbt package the jar and post it to job-server, It runs very well.

**Comment by velvia** [comment]
@kikicarbonell if you want to do `run` in SBT within your app, you will have to take out the `% "provided"` in your `build.sbt`, then it will work.

The downside of not having "provided" is that if you build an assembly jar you end up with a huge one.

One possible solution is to use multiple projects:  one project is designed for you to run stuff locally.  If you are interested in a sample project to get started, LMK and I can work on it when I have time.

**Comment by kikicarbonell** [comment]
@velvia thks for your time. I'm working on spike and I think that the workflow to develop spark app will be:
write code and run it locally with small dataset and if all it's fine then run on job-server with spark cluster and full dataset.
What's your suggestion to develop spark application with job-server? Everytime submit to spark-jobserver? How to do application tests?

**Comment by velvia** [comment]
I would say for now, develop locally and submit it to job server once in a
while.

We could explore an API to job server where you could bypass the REST API
and programmatically launch jobs.... and you could then pull in job server
as a library and make it easier to develop.

On Tue, Sep 1, 2015 at 9:56 AM, Enrique Carbonell <notifications@github.com>
wrote:

> @velvia <https://github.com/velvia> thks for your time. I'm working on
> spike and I think that the workflow to develop spark app will be:
> write code and run it locally with small dataset and if all it's fine then
> run on job-server with spark cluster and full dataset.
> What's your suggestion to develop spark application with job-server?
> Everytime submit to spark-jobserver? How to do application tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/237#issuecomment-136793704>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by kikicarbonell** [comment]
it's a good idea @velvia thks for your time.

**Comment by kikicarbonell** [comment]
@velvia  I interested in a sample project to get started. Thks in advanced.

**Comment by velvia** [comment]
@kikicarbonell sure.  do you want to file a separate issue for a starter project?  Thanks.

**Comment by kikicarbonell** [comment]
@velvia thks, I create a public github project to start with spark-jobserver: https://github.com/kikicarbonell/spike-spark-app
