### ISSUE TITLE
Cannot access local files on the docker instance

### ISSUE THREAD

**Issue by eranation** [spark-jobserver/spark-jobserver#243]
Perhaps I'm doing something wrong, but I can't seem to be able to open a simple text file when using the docker instance.

## Steps to reproduce:

1. Docker launch script (+ map some shared folder from the host to the container): 

        $ docker run -d -p 8090:8090 -v /root/share:/root/share --name my-spark-jobserver velvia/spark-jobserver:0.5.2-SNAPSHOT

2. Either ssh into docker and run spark-shell from or submit a job that just opens a text file (same error)

        $ docker exec -it my-spark-jobserver bash
        $ cd /usr/local/spark-1.3.1-bin-hadoop2.4/
        $ ./bin/spark-shell
        scala> sc.textFile("README.md").count() // or sc.textFile("/root/share/somethingIputThere.txt")

    (or submit a spark job that does just that)
        
3. Exception 

          java.lang.IllegalArgumentException: java.net.UnknownHostException: 70b4a57bb473
	           at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:377)
               at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:240)

    Usually the message that goes in an UHE is the unknown host name. and in this case the host is: "70b4a57bb473" (which looked like a container ID, but I checked, it is not the same as the container ID that is running the jobserver)
 
## What I tried: 

  -  spark shell vs submitting a spark jobserver job, 
  -  a relative path vs an absolute path. 
  -  adding file:///, file://localhost/, file://IP_ADDRESS/ (I din't even know if the last two are legal file URLs bust in case) I even tried with hdfs://... (although I don't have HDFS setup, just to see if it gets passed that "UknownHostException" - all render the same exception 
  -  grep -r "70b4a57bb473" in spark's folder. nothing (it's not in the conf) 
  -  same grep in the hadoop-2.6.0 folder, and voila, in ./etc/hadoop/core-site.xml 
              
          <value>hdfs://70b4a57bb473:9000</value>

  - so I tried just to connect to hdfs and see: 

        bash-4.1# hadoop fs -ls
        -ls: java.net.UnknownHostException: 70b4a57bb473
        Usage: hadoop fs [generic options] -ls [-d] [-h] [-R] [<path> ...]
     
     same exception 

## Env information 

- Host machine 
  - Docker version 1.8.1, build d12ea79
  - CentOS Linux release 7.1.1503 (Core) 
  - java version: "1.7.0_85" OpenJDK Runtime Environment (rhel-2.6.1.2.el7_1-x86_64 u85-b01) OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
  - Docker image: spark-jobserver:0.5.2-SNAPSHOT
- Docker container (you probably know that, but just for clarity)
  - Spark version within the container (from what I saw) spark-1.3.1 built for hadoop 2.4 
  - Hadoop version within the container - Hadoop 2.6
  - JDK within the container: java version "1.7.0_51" Java(TM) SE Runtime Environment (build 1.7.0_51-b13) Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
  - env variables in container 

      BOOTSTRAP=/etc/bootstrap.sh
      SPARK_HOME=/usr/local/spark
      HOSTNAME=9147b7274cdd
      HADOOP_PREFIX=/usr/local/hadoop
      SPARK_JAR=hdfs:///spark/spark-assembly-1.3.1-hadoop2.4.0.jar
      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/usr/local/spark/bin:/usr/local/hadoop/bin
      HADOOP_HDFS_HOME=/usr/local/hadoop
      PWD=/
      HADOOP_COMMON_HOME=/usr/local/hadoop
      JOBSERVER_MEMORY=1G
      HADOOP_YARN_HOME=/usr/local/hadoop
      JAVA_HOME=/usr/java/default
      HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
      SHLVL=1
      HOME=/
      YARN_CONF_DIR=/usr/local/hadoop/etc/hadoop
HADOOP_MAPRED_HOME=/usr/local/hadoop

----

Am I doing something wrong? is this some docker magic that I need to understand first? What is that host? Is that a bug or as designed?

**Comment by velvia** [comment]
Hm, so the Spark distribution in the container is not meant for you to do
general Spark stuff, it is just for Spark Jobserver to run against a real
Spark cluster.   That said, I'm not sure why the unknown host exception.
Have you tried connecting to an external HDFS cluster, or s3:/// for
example?

On Thu, Sep 3, 2015 at 8:44 AM, Eran Medan <notifications@github.com> wrote:

> Perhaps I'm doing something wrong, but I can't seem to be able to open a
> simple text file when using the docker instance.
> Steps to reproduce:
>
>    1.
>
>    Docker launch script (+ map some shared folder from the host to the
>    container):
>
>    $ docker run -d -p 8090:8090 -v /root/share:/root/share --name my-spark-jobserver velvia/spark-jobserver:0.5.2-SNAPSHOT
>
>    2.
>
>    Either ssh into docker and run spark-shell from or submit a job that
>    just opens a text file (same error)
>
>    $ docker exec -it my-spark-jobserver bash
>    $ cd /usr/local/spark-1.3.1-bin-hadoop2.4/
>    $ ./bin/spark-shell
>    scala> sc.textFile("README.md").count() // or sc.textFile("/root/share/somethingIputThere.txt")
>
>    (or submit a spark job that does just that)
>    3.
>
>    Exception
>
>      java.lang.IllegalArgumentException: java.net.UnknownHostException: 70b4a57bb473
>           at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:377)
>           at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:240)
>
>    Usually the message that goes in an UHE is the unknown host name. and
>    in this case the host is: "70b4a57bb473" (which looked like a container ID,
>    but I checked, it is not the same as the container ID that is running the
>    jobserver)
>
> What I tried:
>
>    - spark shell vs submitting a spark jobserver job,
>    - a relative path vs an absolute path.
>    - adding file:///, file://localhost/, file://IP_ADDRESS/ (I din't even
>    know if the last two are legal file URLs bust in case) I even tried with
>    hdfs://... (although I don't have HDFS setup, just to see if it gets passed
>    that "UknownHostException" - all render the same exception
>    - grep -r "70b4a57bb473" in spark's folder. nothing (it's not in the
>    conf)
>    -
>
>    same grep in the hadoop-2.6.0 folder, and voila, in
>    ./etc/hadoop/core-site.xml
>
>      <value>hdfs://70b4a57bb473:9000</value>
>
>    -
>
>    so I tried just to connect to hdfs and see:
>
>    bash-4.1# hadoop fs -ls
>    -ls: java.net.UnknownHostException: 70b4a57bb473
>    Usage: hadoop fs [generic options] -ls [-d] [-h] [-R] [<path> ...]
>
>    same exception
>
> Env information
>
>    - Host machine
>       - Docker version 1.8.1, build d12ea79
>       - CentOS Linux release 7.1.1503 (Core)
>       - java version: "1.7.0_85" OpenJDK Runtime Environment
>       (rhel-2.6.1.2.el7_1-x86_64 u85-b01) OpenJDK 64-Bit Server VM (build
>       24.85-b03, mixed mode)
>       - Docker image: spark-jobserver:0.5.2-SNAPSHOT
>    -
>
>    Docker container (you probably know that, but just for clarity)
>    - Spark version within the container (from what I saw) spark-1.3.1
>       built for hadoop 2.4
>       - Hadoop version within the container - Hadoop 2.6
>       - JDK within the container: java version "1.7.0_51" Java(TM) SE
>       Runtime Environment (build 1.7.0_51-b13) Java HotSpot(TM) 64-Bit Server VM
>       (build 24.51-b03, mixed mode)
>       -
>
>       env variables in container
>
>       BOOTSTRAP=/etc/bootstrap.sh
>       SPARK_HOME=/usr/local/spark
>       HOSTNAME=9147b7274cdd
>       HADOOP_PREFIX=/usr/local/hadoop
>       SPARK_JAR=hdfs:///spark/spark-assembly-1.3.1-hadoop2.4.0.jar
>
>       PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/usr/local/spark/bin:/usr/local/hadoop/bin
>       HADOOP_HDFS_HOME=/usr/local/hadoop
>       PWD=/
>       HADOOP_COMMON_HOME=/usr/local/hadoop
>       JOBSERVER_MEMORY=1G
>       HADOOP_YARN_HOME=/usr/local/hadoop
>       JAVA_HOME=/usr/java/default
>       HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
>       SHLVL=1
>       HOME=/
>       YARN_CONF_DIR=/usr/local/hadoop/etc/hadoop
>       HADOOP_MAPRED_HOME=/usr/local/hadoop
>
> ------------------------------
>
> Am I doing something wrong? is this some docker magic that I need to
> understand first? What is that host? Is that a bug or as designed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/243>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by peterklipfel** [comment]
For anyone that might come across this later. I spent too much time on this error. The problem ended up being that I was doing checkpointing in a streaming job.

I'm still new to the jobserver, so I'm guessing (based on the above comments) that storage is configured to access hdfs which doesn't work. I found the hostname all over the filesystem.

An additional note for anyone that feels like modifying the dockerfile for the jobserver is that the dockerfile is dynamically generated (https://github.com/spark-jobserver/spark-jobserver/blob/50a0930b04904978ef76093912ec5addcfb2a7fa/project/Build.scala#L98)

**Comment by velvia** [comment]
Peter, thanks for looking into this.  Is the HDFS thrift port open in docker?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment]
@peterklipfel going to close this.   May update the Docker docs to warn of this issue.

**Comment by peterklipfel** [comment]
The only port I forwarded out was 8090.

Here was the port output of docker ps for the jobserver.

    22/tcp, 8030-8033/tcp, 8040/tcp, 8042/tcp, 8088/tcp, 9999/tcp, 49707/tcp, 50010/tcp, 50020/tcp, 50070/tcp, 50075/tcp, 50090/tcp, 0.0.0.0:8090->8090/tcp
