### ISSUE TITLE
SparkContextFactory.scala line37 

### ISSUE THREAD

**Issue by 0612800232** [spark-jobserver/spark-jobserver#245]
val contextCfg = config.getConfig("spark.context-settings").withFallback(contextConfig)

i think it should be  
val contextCfg = contextConfig.withFallback(config.getConfig("spark.context-settings"))

**Comment by annakepler** [comment]
We just came across the same issue. While creating StreamingContext query parameters like streaming.batch_interval were never picked up. Instead default values were always used. 
After switching to 
```
      val contextCfg = contextConfig.withFallback(config.getConfig("spark.context-settings"))
```
everything worked as expected

**Comment by zeitos** [comment]
The current code makes the default values to win over contex-specific and that's not the intention, good catch.

**Comment by zeitos** [comment]
actually it seems like the fallback configuration is done in #LocalContextSupervisorActor so we can just leave that as ` val contextCfg = contextConfig`

**Comment by velvia** [comment]
Fix is merged.  Thanks guys.
