### ISSUE TITLE
pemgen space memory leak

### ISSUE THREAD

**Issue by litao-buptsse** [spark-jobserver/spark-jobserver#246]
@velvia I upgrade spark-jobserver to 0.5.2-SNAPSHOT and found "pemgen space memory leak". The loaded classes is rising when I run a new job everytime.
Have you met this case before? I'm not sure is jobserver's or spark's bug. I will try to figure it out.

![image](https://cloud.githubusercontent.com/assets/3584226/9731072/4e4e678a-564d-11e5-9856-95c34ca9460c.png)

**Comment by litao-buptsse** [comment]
@velvia I have solve the problem. In my app, I created a SparkContext in spark-jobserver. When submit a job to spark-jobserver, in the runJob() method, I call "new HiveContext(sc)" to try to create a HiveContext which cause the pemgen space oom.

My solution is as follows:
1. set context-factory = spark.jobserver.context.HiveContextFactory, create a HiveContext in spark-jobserver directly
2. for my app implements SparkHiveJob instead of SparkJob

So the spark-jobserver will load HiveContext classes only once when init the HiveContext object. When submit job to spark-jobserver, it will never load HiveContext related class again.

**Comment by velvia** [comment]
Tao, glad you solved it, that sounds like the correct solution.  :)

On Tue, Sep 8, 2015 at 9:29 AM, Tao Li <notifications@github.com> wrote:

> Closed #246
> <https://github.com/spark-jobserver/spark-jobserver/issues/246>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/246#event-403843373>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by litao-buptsse** [comment]
@velvia job-server-extras really do a lot help to me. Thank you very much.
