### ISSUE TITLE
``union'' expected but identifier

### ISSUE THREAD

**Issue by longleis** [spark-jobserver/spark-jobserver#254]
Hi all,

When I ran curl -d  'sql="select time from test where time='2c1'"'.... , there was some error information: "message": "[1.36] failure: ``union'' expected but identifier c1 found\n\n. However, it was correct when I ran curl -d  'sql="select record from test where time='21'"'.... . It seems that non numeric characters cannot be input.
Any help will be appreciated. Thank you very much.

Long Lei

**Comment by noorul** [comment]
longleis <notifications@github.com> writes:

> Hi all,
>
> When I ran curl -d  'sql="select time from test where time='2c1'"'.... , there was some error information: "message": "[1.36] failure: ``union'' expected but identifier c1 found\n\n. However, it was correct when I ran curl -d  'sql="select record from test where time='21'"'.... . It seems that non numeric characters cannot be input.
> Any help will be appreciated. Thank you very much.
>

What type is time field?

Thanks and Regards
Noorul

**Comment by longleis** [comment]
String. Thanks.

Long Lei

**Comment by zeitos** [comment]
This really sounds like a spark failure and not a jobserver one.
did you try with time='asd' ?

It's weird that it's happening with a String field, I would understand that error if time were a timestamp

**Comment by longleis** [comment]
Actually, SqlTest job did not work either. 
curl -d  'sql="select * from addresses"' '127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context1&sync=true'
{
  "status": "OK",
  "result": ["[Bob,Charles,101 A St.,San Jose]", "[Sandy,Charles,10200 Ranch Rd.,Purple City]", "[Randy,Charles,101 A St.,San Jose]"]

curl -d  'sql="select * from addresses where firstName='bob'"' '127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context1&sync=true'
{
  "status": "ERROR",
  "result": {
    "message": "cannot resolve 'bob' given input columns firstName, lastName, street, city;",
    "errorClass": "org.apache.spark.sql.AnalysisException",

**Comment by zeitos** [comment]
Let's start from the beginning:
Which version of Jobserver and Spark are you using?

Jobserver does nothing special, here I changed SQLJobSpec and run the test, the breakpoint is in the line that executes the query.
As you can see SJS did not alter the query and that line will call spark with your query.

<img width="722" alt="screen shot 2015-09-24 at 9 37 06 am" src="https://cloud.githubusercontent.com/assets/1010275/10073511/d82b653a-629f-11e5-95ab-c1ef2a7ed2bc.png">


Did you try running that query in spark?

**Comment by longleis** [comment]
Hi,

**Comment by longleis** [comment]
Hi,
I have been using jobserver which belongs to master version  and spark 1.4.1.
In spark, I got the correct result:
scala> sqlContext.sql("select * from addresses where firstName='Bob'").collect().foreach(println)
[Bob,Charles,101 A St.,San Jose]

**Comment by velvia** [comment]
@longleis to rule out quoting issues, can you please put your query for SJS into a file like input.json, use standard JSON quoting rules, then feed it into curl using --data-binary @input.json  ?

I would also strongly advise against `-d`, and instead use `--data-binary`.

**Comment by longleis** [comment]
It works.😄Thank you very much.
curl --data-binary @1.json '127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.SqlTestJob&context=sql-context1&sync=true'
{
  "status": "OK",
  "result": ["[Bob,Charles,101 A St.,San Jose]"]

**Comment by zjffdu** [comment]
I hit similar issue, but I call the rest api using java code. Is there any solution for that case ?

**Comment by zjffdu** [comment]
Never mind, just found that this is spark issue
