### ISSUE TITLE
SBT Native Packaging  - RPM/Debian/Docker

### ISSUE THREAD

**Issue by ogirardot** [spark-jobserver/spark-jobserver#257]
Hi, 
I've been working on a draft to integrate the SBT Native Packager, but more insights into the details of what should be configured and how than what I know are needed...

For example here's how the RPM Part would be configured in my draft : 
```
lazy val packagingSettings = com.typesafe.sbt.packager.rpm.RpmPlugin.projectSettings ++ com.typesafe.sbt.packager.rpm.RpmPlugin.globalSettings ++ com.typesafe.sbt.packager.rpm.RpmPlugin.buildSettings ++ Seq(
      name := "jobserver"
      , mainClass in Compile := Some("spark.jobserver.JobServer")
      , packageSummary := s"Spark Job Server"
      , packageDescription := "summary"
      , com.typesafe.sbt.packager.Keys.maintainer := "Spark-JobServer"
      , rpmVendor := "Spark-JobServer"
      , packageArchitecture := "noarch"
      , rpmDistribution := Some("CentOS")
      , rpmLicense := Some("Apache 2.0")
      , rpmGroup := Some("spark")
      , rpmBrpJavaRepackJars := true //see https://github.com/sbt/sbt-native-packager/issues/327
      , rpmRequirements += "jdk >= 1.7.0"
    )
```

Plus the Docker plugin used right now, might be kind of a sub-set of what the sbt-native-packager plugin as a whole offers.

What do you think ?

Regards, 

Olivier.

**Comment by velvia** [comment]
Olivier,

Thanks.  I’d be very interested in the differences between sbt-native-packager vs sat-docker.  If sat-native-packager offered everything that sat-docker did (including pushing docker images — though I suppose that’s not hard) might be willing to switch.

As for the other fields:
- summary and description you could just grab from the job server repo, like the one liner at the top
- Does the distro have to be tied to Centos?  I haven’t kept up with the RPM world for a while but there are many distro’s right?
- rpmGroup - probably need your input here

**Comment by ogirardot** [comment]
Hi, 
I think you'll find what you need, sbt-native-packager's docker part (http://www.scala-sbt.org/sbt-native-packager/formats/docker.html) allows you to "sbt docker:publishLocal" which will build and push the "new build" of your docker images. The base docker image used is `dockerBaseImage := "dockerfile/java"` and you can configure pretty much everything you need (even the whole dockerFile if you need), sbt-native-packager is also the plugin used by Play! Framework for all its packaging.

Regarding rpmDistribution & rpmGroup are not mandatory and these were just examples.

Regards, 

Olivier.

**Comment by hntd187** [comment]
Hey @ogirardot if you're still working on this maybe checkout this pull request https://github.com/spark-jobserver/spark-jobserver/pull/95 and maybe you can use this to help with your packaging.
