### ISSUE TITLE
Set compress response with gzip globally

### ISSUE THREAD

**Issue by herkulano** [spark-jobserver/spark-jobserver#271]
It would be nice to have a config or global setting to make all responses compressed with gzip.

I'm very new with this, so if this is a stupid request or it's blantly obvious would you mind pointing me on how to do it?

**Comment by noorul** [comment]
I think this can be done, http://spray.io/documentation/1.2.3/spray-routing/encoding-directives/compressResponse/

But it looks like we need a patch for this.

**Comment by velvia** [comment]
I think that’s definitely a fair ask.
