### ISSUE TITLE
Compile master branch for Spark 1.3

### ISSUE THREAD

**Issue by secsubs** [spark-jobserver/spark-jobserver#277]
I have CDH 5.4.7 deployed that bundles Spark 1.3. 
- Can I compile the master branch for Spark 1.3?
- In the env.sh, I have specified Spark version at 1.3 but when I run "server_package", I notice sbt pulls all dependencies for Spark 1.5. Is this intended? Example:
[error] (job-server-extras/*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-streaming_2.10;1.5.0: not found

Thanks!

**Comment by noorul** [comment]
You need to make changes here

https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Dependencies.scala

But ideally you should be using the branch
https://github.com/spark-jobserver/spark-jobserver/tree/jobserver-0.5.3-SNAPSHOT-spark-1.3.1

Thanks and Regards
Noorul

**Comment by secsubs** [comment]
Will the branch have all the features/fixes of the master? Thanks Noorul.

**Comment by velvia** [comment]
You should be able to override the build by setting SPARK_VERSION to 1.3…  if not something changed...

**Comment by noorul** [comment]
No it will not. But you might end up doing more work on master to make it
work with 1.3. Best of luck!

Thanks and Regards
Noorul

**Comment by secsubs** [comment]
Thanks guys. The compile finished smoothly after I changed Spark version to 1.3.0 in Dependencies.scala.
