### ISSUE TITLE
How to run HiveJob? 

### ISSUE THREAD

**Issue by iusofts** [spark-jobserver/spark-jobserver#278]
error code:

object SqlJobServer extends SparkHiveJob {
  def main(args: Array[String]): Unit = {
    val config = ConfigFactory.parseString("")
    val sc = new SparkContext(config.getString("spark.master"), "TestSparkSql")
    val hive=new C(sc)
    val results = runJob(hive, config)
    println("Result is " + results)
  }
    def validate(hive: HiveContext, config: Config): SparkJobValidation = SparkJobValid

    def runJob(hive: HiveContext, config: Config): Any = {
      hive.sql(config.getString("sql")).collect()
    }

}

How to write correctly?

**Comment by velvia** [comment]
Hi, can you please give more details?

- What is the error
- Version of job server
- Version of Spark
- Deployed, how you are running SJS

**Comment by iusofts** [comment]
error : java.io.IOException: Server returned HTTP response code: 400 for URL
SJS version : 0.6
SparkVersion : 1.4.1

scala code (problem?) :
-----------------------------------------------------------------------------------
package com.iusoft.spark.jobserver

import org.apache.spark.sql.hive.HiveContext
import spark.jobserver._
import org.apache.spark.SparkContext
import com.typesafe.config.{Config, ConfigFactory}

object SparkSql extends SparkHiveJob {
  def main(args: Array[String]): Unit = {
    val config = ConfigFactory.parseString("")
    val sc = new SparkContext(config.getString("spark.master"), "TestSparkSql")
    val hive=new C(sc)
    val results = runJob(hive, config)
    println("Result is " + results)
  }
    def validate(hive: HiveContext, config: Config): SparkJobValidation = SparkJobValid

    def runJob(hive: HiveContext, config: Config): Any = {
      hive.sql(config.getString("sql")).collect()
    }

}
----------------------------------------------------

java post code(No problem):

--------------------------------------------------------------------------
String url = "http://hadoop03.iusoft.com:8090/jobs?appName=TestSparkSql&classPath=com.iusoft.spark.jobserver.SparkSql&context=test-context";
System.out.println(textPost(url, "{sql=\"select * from shopinfo2 limit 10\"}", "UTF-8"));
----------------------------------------------------------------------------

SJS log:

614] INFO  spark.jobserver.JarManager [] [akka://JobServer/user/jar-manager] - Storing jar for app TestSparkSql, 462715 bytes
[2015-10-10 10:22:11,466] INFO  .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/test-context] - Loading class com.iusoft.spark.jobserver.SparkSql for app TestSparkSql
[2015-10-10 10:22:11,469] INFO  parkContextFactory$$anon$1 [] [akka://JobServer/user/context-supervisor/test-context] - Added JAR /database/TestSparkSql-2015-10-10T10:20:28.614+08:00.jar at http://192.168.100.103:36853/jars/TestSparkSql-2015-10-10T10:20:28.614+08:00.jar with timestamp 1444443731469
[2015-10-10 10:22:11,473] INFO  util.ContextURLClassLoader [] [akka://JobServer/user/context-supervisor/test-context] - Added URL file:/database/TestSparkSql-2015-10-10T10:20:28.614+08:00.jar to ContextURLClassLoader
[2015-10-10 10:22:11,474] INFO  k.jobserver.util.JarUtils$ [] [akka://JobServer/user/context-supervisor/test-context] - Loading object com.iusoft.spark.jobserver.SparkSql$ using loader spark.jobserver.util.ContextURLClassLoader@7f793c19


context:
curl -d "" 'localhost:8090/contexts/test-context?num-cpu-cores=4&memory-per-node=512m'


I doubt 'object SparkSql'  problem.

**Comment by velvia** [comment]
So it returned 400?  How was the context set up?
400 is unusual usually means something wrong with the parameters, like jars or contexts not found.  What do you get if you GET /contexts or /jars ?

**Comment by iusofts** [comment]
@velvia My scala code no problem?

**Comment by iusofts** [comment]
@velvia jobserver UI (http://hadoop03.iusoft.com:8090/jobs) not find the job.

**Comment by velvia** [comment]
No problem, but you don’t need main().   Might want to take it out.

**Comment by iusofts** [comment]
@velvia 
/**
 * This job simply runs the Hive SQL in the config.
 */

what config?

**Comment by iusofts** [comment]
@velvia  
I run spark-jobserver/job-server-extras/src/spark.jobserver/HiveTestJob.scala problem

ERROR k.jobserver.util.JarUtils$ [] [akka://JobServer/user/context-supervisor/fc687e18-spark.jobserver.HiveTestJob] - Wrong ClassLoader for object spark.jobserver.HiveTestJob$: Expected spark.jobserver.util.ContextURLClassLoader@4f2453fa but got org.apache.spark.util.MutableURLClassLoader@54432395

**Comment by velvia** [comment]
@iusofts I think this is resolved now right?  Also the docs for HiveContext/HiveTestJob have been updated.
