### ISSUE TITLE
Can not run jobserver on spark://localhost:7077

### ISSUE THREAD

**Issue by cookeem** [spark-jobserver/spark-jobserver#279]
I use spark1.4.1 standalone on MacOSX, I follow the Deployment Manual steps to deploy SJS on my machine, I use server_start.sh to start SJS, it look fine, and I can open the SJS WebUI at http://localhost:8090, but when I open the spark WebUI,I find that there is no Running Applications.
I have add master = "spark://127.0.0.1:7077" in ./local.conf file. Can anybody help me why SJS always connect local[4] but not spark://127.0.0.1:7077? How to config it on deployment mode?

**Comment by velvia** [comment]
Did you modify the local.conf in the deploy directory?

You need spark.master = “….”, not just master = “…”

You can verify the config in the first few lines of the log output.

**Comment by cookeem** [comment]
I add follow lines in local.conf in depoly dir, like this:
spark.master = "spark://127.0.0.1:7077"
master = "spark://127.0.0.1:7077"
still not work.

And when I send jar package to server,the SJS down, here is the command and stack:

curl --data-binary @job-server-tests/target/scala-2.10/job-server-tests-$VER.jar localhost:8090/jars/test

15/10/09 15:36:51 INFO util.JarUtils$: Loading object spark.jobserver.WordCountExample$ using loader spark.jobserver.util.ContextURLClassLoader@1c495103
Uncaught error from thread [JobServer-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
java.lang.NoSuchMethodError: org.joda.time.DateTime.now()Lorg/joda/time/DateTime;
	at spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:192)

**Comment by noorul** [comment]
cookeem <notifications@github.com> writes:

> I add follow lines in local.conf in depoly dir, like this:
> spark.master = "spark://127.0.0.1:7077"
> master = "spark://127.0.0.1:7077"
> still not work.
>
> And when I send jar package to server,the SJS down, here is the command and stack:
>
> curl --data-binary @job-server-tests/target/scala-2.10/job-server-tests-$VER.jar localhost:8090/jars/test
>
> 15/10/09 15:36:51 INFO util.JarUtils$: Loading object spark.jobserver.WordCountExample$ using loader spark.jobserver.util.ContextURLClassLoader@1c495103
> Uncaught error from thread [JobServer-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
> java.lang.NoSuchMethodError: org.joda.time.DateTime.now()Lorg/joda/time/DateTime;
> 	at spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:192)
>

Can you share the config?

Thanks and Regards
Noorul

**Comment by cookeem** [comment]
deploy directory ./local.conf content:

# Template for a Spark Job Server configuration file
# When deployed these settings are loaded when job server starts
#
# Spark Cluster / Job Server configuration
spark {
  # spark.master will be passed to each job's JobContext
  spark.master = "spark://127.0.0.1:7077"
  master = "spark://127.0.0.1:7077"
  # master = "mesos://vm28-hulk-pub:5050"
  # master = "yarn-client"

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 2

  jobserver {
    port = 8090
    jar-store-rootdir = /Volumes/Share/hadoop/spark-jobserver-0.6.1/tmp/jars

    jobdao = spark.jobserver.io.JobFileDAO

    filedao {
      rootdir = /Volumes/Share/hadoop/spark-jobserver-0.6.1/tmp/filedao/data
    }
  }

  # predefined Spark contexts
  # contexts {
  #   my-low-latency-context {
  #     num-cpu-cores = 1           # Number of cores to allocate.  Required.
  #     memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
  #   }
  #   # define additional contexts here
  # }

  # universal context configuration.  These settings can be overridden, see README.md
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 1G         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

    # in case spark distribution should be accessed from HDFS (as opposed to being installed on every mesos slave)
    # spark.executor.uri = "hdfs://namenode:8020/apps/spark/spark.tgz"

    # uris of jars to be loaded into the classpath for this context. Uris is a string list, or a string separated by commas ','
    # dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]
    
    # If you wish to pass any settings directly to the sparkConf as-is, add them here in passthrough,
    # such as hadoop connection settings that don't use the "spark." prefix
    passthrough {
      #es.nodes = "192.1.1.1"
    }
  }

  # This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
  #home = "/Volumes/Share/hadoop/spark-1.4.1"
}

# Note that you can use this file to define settings not only for job server,
# but for your Spark jobs as well.  Spark job configuration merges with this configuration file as defaults.

####################################################

And settings.sh content:
# Environment and deploy file
# For use with bin/server_deploy, bin/server_package etc.
#DEPLOY_HOSTS="hostname1.net
#              hostname2.net"
DEPLOY_HOSTS="localhost"

#APP_USER=spark
#APP_GROUP=spark
APP_USER=cookeem
APP_GROUP=staff
# optional SSH Key to login to deploy server
#SSH_KEY=/path/to/keyfile.pem
INSTALL_DIR=/Volumes/Share/hadoop/spark-jobserver-0.6.1
LOG_DIR=/Volumes/Share/hadoop/spark-jobserver-0.6.1/logs
PIDFILE=spark-jobserver.pid
JOBSERVER_MEMORY=2G
SPARK_VERSION=1.4.1
SPARK_HOME=/Volumes/Share/hadoop/spark-1.4.1
SPARK_CONF_DIR=$SPARK_HOME/conf
# Only needed for Mesos deploys
SPARK_EXECUTOR_URI=/home/spark/spark-1.4.1.tar.gz
# Only needed for YARN running outside of the cluster
# You will need to COPY these files from your cluster to the remote machine
# Normally these are kept on the cluster in /etc/hadoop/conf
# YARN_CONF_DIR=/pathToRemoteConf/conf
# HADOOP_CONF_DIR=/pathToRemoteConf/conf
SCALA_VERSION=2.10.4 # or 2.11.6

**Comment by noorul** [comment]
cookeem <notifications@github.com> writes:

> I add follow lines in local.conf in depoly dir, like this:
> spark.master = "spark://127.0.0.1:7077"
> master = "spark://127.0.0.1:7077"
> still not work.
>
> And when I send jar package to server,the SJS down, here is the command and stack:
>
> curl --data-binary @job-server-tests/target/scala-2.10/job-server-tests-$VER.jar localhost:8090/jars/test
>
> 15/10/09 15:36:51 INFO util.JarUtils$: Loading object spark.jobserver.WordCountExample$ using loader spark.jobserver.util.ContextURLClassLoader@1c495103
> Uncaught error from thread [JobServer-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
> java.lang.NoSuchMethodError: org.joda.time.DateTime.now()Lorg/joda/time/DateTime;
> 	at spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:192)
>

This looks like a jar issue. You might be having colliding version in
your class path.

Thanks and Regards
Noorul

**Comment by noorul** [comment]
Can you also share the log output when you start the server?

Thanks and Regards
Noorul

**Comment by cookeem** [comment]
I use the SJS example only, here is the start log:

[2015-10-09 16:43:40,080] INFO  spark.jobserver.JobServer$ [] [] - Starting JobServer with config {
    # system properties
    "app" : {
        # system properties
        "name" : "spark.jobserver.JobServer"
    },
    # merge of /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 36,application.conf: 87
    # universal context configuration.  These settings can be overridden, see README.md
    # Default settings for ad hoc as well as manually created contexts
    # You can add any Spark config params here, for example, spark.mesos.coarse = true
    "context-settings" : {
        # application.conf: 93
        # A zero-arg class implementing spark.jobserver.context.SparkContextFactory
        # Determines the type of jobs that can run in a SparkContext
        "context-factory" : "spark.jobserver.context.DefaultSparkContextFactory",
        # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 38
        # Executor memory per node, -Xmx style eg 512m, #1G, etc.
        "memory-per-node" : "1G",
        # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 37
        # Number of cores to allocate.  Required.
        "num-cpu-cores" : 2,
        # application.conf: 110
        "passthrough" : {
            # application.conf: 111
            "spark" : {
                # application.conf: 111
                "driver" : {
                    # application.conf: 111
                    # Ignore the Multiple context exception related with SPARK-2243
                    "allowMultipleContexts" : true
                }
            }
        },
        # application.conf: 95
        "streaming" : {
            # application.conf: 97
            # Default batch interval for Spark Streaming contexts in milliseconds
            "batch_interval" : 1000,
            # application.conf: 100
            # if true, stops gracefully by waiting for the processing of all received data to be completed
            "stopGracefully" : true,
            # application.conf: 104
            # if true, stops the SparkContext with the StreamingContext. The underlying SparkContext will be
            # stopped regardless of whether the StreamingContext has been started.
            "stopSparkContext" : true
        }
    },
    # application.conf: 77
    # predefined Spark contexts
    # Below is an example, but do not uncomment it.   Everything defined here is carried over to
    # deploy-time configs, so they will be created in all environments.  :(
    "contexts" : {},
    # system properties
    "driver" : {
        # system properties
        "extraJavaOptions" : "-XX:+UseConcMarkSweepGC\n         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:/Volumes/Share/hadoop/spark-jobserver-0.6.1/gc.out\n         -XX:MaxPermSize=512m\n         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M            -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true            -Dcom.sun.management.jmxremote.port=19999            -Dcom.sun.management.jmxremote.rmi.port=19999            -Dcom.sun.management.jmxremote.authenticate=false            -Dcom.sun.management.jmxremote.ssl=false -Dlog4j.configuration=file:/Volumes/Share/hadoop/spark-jobserver-0.6.1/log4j-server.properties\n              -DLOG_DIR=/Volumes/Share/hadoop/spark-jobserver-0.6.1/logs -Dspark.executor.uri=/home/spark/spark-1.4.1.tar.gz ",
        # system properties
        "memory" : "2G"
    },
    # system properties
    "executor" : {
        # system properties
        "extraJavaOptions" : "-Dlog4j.configuration=file:/Volumes/Share/hadoop/spark-jobserver-0.6.1/log4j-server.properties\n              -DLOG_DIR=/Volumes/Share/hadoop/spark-jobserver-0.6.1/logs",
        # system properties
        "memory" : "4g",
        # system properties
        "uri" : "/home/spark/spark-1.4.1.tar.gz"
    },
    # system properties
    "jars" : "file:/Volumes/Share/hadoop/spark-jobserver-0.6.1/spark-job-server.jar",
    # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 13
    # Default # of CPUs for jobs to use for Spark standalone cluster
    "job-number-cpus" : 2,
    # merge of /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 15,application.conf: 7
    "jobserver" : {
        # application.conf: 9
        "bind-address" : "0.0.0.0",
        # application.conf: 59
        # Time out for job server to wait while creating contexts
        "context-creation-timeout" : "15 s",
        # application.conf: 20
        "datadao" : {
            # application.conf: 23
            # storage directory for files that are uploaded to the server
            # via POST/data commands
            "rootdir" : "/tmp/spark-jobserver/upload"
        },
        # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 21
        "filedao" : {
            # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 22
            "rootdir" : "/Volumes/Share/hadoop/spark-jobserver-0.6.1/tmp/filedao/data"
        },
        # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 17
        "jar-store-rootdir" : "/Volumes/Share/hadoop/spark-jobserver-0.6.1/tmp/jars",
        # application.conf: 12
        # Number of job results to keep per JobResultActor/context
        "job-result-cache-size" : 5000,
        # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 19
        "jobdao" : "spark.jobserver.io.JobFileDAO",
        # application.conf: 63
        # Number of jobs that can be run simultaneously per context
        # If not set, defaults to number of cores on machine where jobserver is running
        "max-jobs-per-context" : 8,
        # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 16
        "port" : 8090,
        # application.conf: 32
        "sqldao" : {
            # application.conf: 51
            # DB connection pool settings
            "dbcp" : {
                # application.conf: 54
                "initialsize" : 10,
                # application.conf: 52
                "maxactive" : 20,
                # application.conf: 53
                "maxidle" : 10
            },
            # application.conf: 44
            # Full JDBC URL / init string, along with username and password.  Sorry, needs to match above.
            # Substitutions may be used to launch job-server, but leave it out here in the default or tests won't pass
            "jdbc" : {
                # application.conf: 47
                "password" : "",
                # application.conf: 45
                "url" : "jdbc:h2:file:/tmp/spark-jobserver/sqldao/data/h2-db",
                # application.conf: 46
                "user" : ""
            },
            # application.conf: 37
            # JDBC driver, full classpath
            "jdbc-driver" : "org.h2.Driver",
            # application.conf: 40
            # Directory where default H2 driver stores its data. Only needed for H2.
            "rootdir" : "/tmp/spark-jobserver/sqldao/data",
            # application.conf: 34
            # Slick database driver, full classpath
            "slick-driver" : "scala.slick.driver.H2Driver"
        },
        # application.conf: 71
        # spark broadcst factory in yarn deployment
        # Versions prior to 1.1.0, spark default broadcast factory is org.apache.spark.broadcast.HttpBroadcastFactory.
        # Can't start multiple sparkContexts in the same JVM with HttpBroadcastFactory.
        "yarn-broadcast-factory" : "org.apache.spark.broadcast.TorrentBroadcastFactory",
        # application.conf: 66
        # in yarn deployment, time out for job server to wait while creating contexts
        "yarn-context-creation-timeout" : "40 s"
    },
    # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 8
    "master" : "spark://127.0.0.1:7077",
    # system properties
    "serializer" : "org.apache.spark.serializer.KryoSerializer",
    # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 7
    "spark" : {
        # /Volumes/Share/hadoop/spark-jobserver-0.6.1/local.conf: 7
        # spark.master will be passed to each job's JobContext
        "master" : "spark://127.0.0.1:7077"
    },
    # application.conf: 5
    # spark web UI port
    "webUrlPort" : 8080
}

[2015-10-09 16:43:40,083] INFO  spark.jobserver.JobServer$ [] [] - Spray config: {
    # reference.conf: 163
    # Enables/disables automatic back-pressure handling by write buffering and
    # receive throttling
    "automatic-back-pressure-handling" : "on",
    # reference.conf: 165
    "back-pressure" : {
        # reference.conf: 169
        # The reciprocal rate of requested Acks per NoAcks. E.g. the default value
        # '10' means that every 10th write request is acknowledged. This affects the
        # number of writes each connection has to buffer even in absence of back-pressure.
        "noack-rate" : 10,
        # reference.conf: 174
        # The lower limit the write queue size has to shrink to before reads are resumed.
        # Use 'infinite' to disable the low-watermark so that reading is resumed instantly
        # after the next successful write.
        "reading-low-watermark" : "infinite"
    },
    # reference.conf: 131
    # The time period within which the TCP binding process must be completed.
    # Set to `infinite` to disable.
    "bind-timeout" : "1s",
    # reference.conf: 55
    # The period during which a service must respond to a `ChunkedRequestStart` message
    # with a `RegisterChunkHandler` message. During the registration period reading from
    # the network is suspended. It is still possible that some chunks have already been
    # received which will be buffered until the registration is received or the timeout is
    # triggered. If the timeout is triggered the connection is immediately aborted.
    "chunkhandler-registration-timeout" : "500 ms",
    # reference.conf: 98
    # Enables/disables an alternative response streaming mode that doesn't
    # use `Transfer-Encoding: chunked` but rather renders the individual
    # MessageChunks coming in from the application as parts of the original
    # response entity.
    # Enabling this mode causes all connections to be closed after a streaming
    # response has been finished since there is no other way to signal the
    # response end to the client.
    # Note that chunkless-streaming is implicitly enabled when streaming
    # responses to HTTP/1.0 clients (since they don't support
    # `Transfer-Encoding: chunked`)
    "chunkless-streaming" : "off",
    # application.conf: 141
    # Needed for HTTP/1.0 requests with missing Host headers
    "default-host-header" : "spray.io:8765",
    # application.conf: 136
    # ssl engine provider protocols
    "enabledProtocols" : [
        # application.conf: 136
        "SSLv3",
        # application.conf: 136
        "TLSv1"
    ],
    # application.conf: 131
    # see http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#SSLContext for more examples
    # typical are either SSL or TLS
    "encryptionType" : "SSL",
    # application.conf: 137
    "idle-timeout" : "60 s",
    # application.conf: 132
    "keystoreType" : "JKS",
    # reference.conf: 127
    # For HTTPS connections this setting specified the maximum number of
    # bytes that are encrypted in one go. Large responses are broken down in
    # chunks of this size so as to already begin sending before the response has
    # been encrypted entirely.
    "max-encryption-chunk-size" : "1m",
    # merge of application.conf: 144,reference.conf: 315
    # The (default) configuration of the HTTP message parser for the server and
    # the client.
    # IMPORTANT: These settings (i.e. children of `spray.can.parsing`) can't be directly
    # overridden in `application.conf` to change the parser settings for client and server
    # altogether (see https://github.com/spray/spray/issues/346). Instead, override the
    # concrete settings beneath `spray.can.server.parsing` and `spray.can.client.parsing`
    # where these settings are copied to.
    "parsing" : {
        # reference.conf: 352
        # limits for the number of different values per header type that the
        # header cache will hold
        "header-cache" : {
            # reference.conf: 354
            "Content-MD5" : 0,
            # reference.conf: 355
            "Date" : 0,
            # reference.conf: 356
            "If-Match" : 0,
            # reference.conf: 357
            "If-Modified-Since" : 0,
            # reference.conf: 358
            "If-None-Match" : 0,
            # reference.conf: 359
            "If-Range" : 0,
            # reference.conf: 360
            "If-Unmodified-Since" : 0,
            # reference.conf: 361
            "User-Agent" : 32,
            # reference.conf: 353
            "default" : 12
        },
        # reference.conf: 348
        # Enables/disables the logging of warning messages in case an incoming
        # message (request or response) contains an HTTP header which cannot be
        # parsed into its high-level model class due to incompatible syntax.
        # Note that, independently of this settings, spray will accept messages
        # with such headers as long as the message as a whole would still be legal
        # under the HTTP specification even without this header.
        # If a header cannot be parsed into a high-level model instance it will be
        # provided as a `RawHeader`.
        "illegal-header-warnings" : "on",
        # reference.conf: 367
        # Sets the size starting from which incoming http-messages will be delivered
        # in chunks regardless of whether chunking is actually used on the wire.
        # Set to infinite to disable auto chunking.
        "incoming-auto-chunking-threshold-size" : "infinite",
        # reference.conf: 323
        "max-chunk-ext-length" : 256,
        # reference.conf: 324
        "max-chunk-size" : "1m",
        # application.conf: 144
        # Increase this in order to upload bigger job jars
        "max-content-length" : "30m",
        # reference.conf: 321
        "max-header-count" : 64,
        # reference.conf: 319
        "max-header-name-length" : 64,
        # reference.conf: 320
        "max-header-value-length" : "8k",
        # reference.conf: 318
        "max-response-reason-length" : 64,
        # reference.conf: 317
        # The limits for the various parts of the HTTP message parser.
        "max-uri-length" : "2k",
        # reference.conf: 372
        # Enables/disables inclusion of an SSL-Session-Info header in parsed
        # messages over SSL transports (i.e., HttpRequest on server side and
        # HttpResponse on client side).
        "ssl-session-info-header" : "off",
        # reference.conf: 338
        # Sets the strictness mode for parsing request target URIs.
        # The following values are defined:
        # 
        # `strict`: RFC3986-compliant URIs are required,
        #     a 400 response is triggered on violations
        # 
        # `relaxed`: all visible 7-Bit ASCII chars are allowed
        # 
        # `relaxed-with-raw-query`: like `relaxed` but additionally
        #     the URI query is not parsed, but delivered as one raw string
        #     as the `key` value of a single Query structure element.
        # 
        "uri-parsing-mode" : "strict"
    },
    # reference.conf: 149
    # The time after which a connection is aborted (RST) after a parsing error
    # occurred. The timeout prevents a connection which is already known to be
    # erroneous from receiving evermore data even if all of the data will be ignored.
    # However, in case of a connection abortion the client usually doesn't properly
    # receive the error response. This timeout is a trade-off which allows the client
    # some time to finish its request and receive a proper error response before the
    # connection is forcibly closed to free resources.
    "parsing-error-abort-timeout" : "2s",
    # application.conf: 139
    # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
    "pipelining-limit" : 2,
    # application.conf: 134
    # key manager factory provider
    "provider" : "SunX509",
    # reference.conf: 78
    # Enables/disables the addition of a `Raw-Request-URI` header holding the
    # original raw request URI as the client has sent it.
    "raw-request-uri-header" : "off",
    # reference.conf: 65
    # The "granularity" of timeout checking for both idle connections timeouts
    # as well as request timeouts, should rarely be needed to modify.
    # If set to `infinite` request and connection timeout checking is disabled.
    "reaping-cycle" : "250 ms",
    # reference.conf: 140
    # The time period within which a connection handler must have been
    # registered after the bind handler has received a `Connected` event.
    # Set to `infinite` to disable.
    "registration-timeout" : "1s",
    # reference.conf: 74
    # Enables/disables the addition of a `Remote-Address` header
    # holding the clients (remote) IP address.
    "remote-address-header" : "off",
    # reference.conf: 116
    # If this setting is non-zero the HTTP server automatically aggregates
    # incoming request chunks into full HttpRequests before dispatching them to
    # the application. If the size of the aggregated requests surpasses the
    # specified limit the server responds with a `413 Request Entity Too Large`
    # error response before closing the connection.
    # Set to zero to disable automatic request chunk aggregation and have
    # ChunkedRequestStart, MessageChunk and ChunkedMessageEnd messages be
    # dispatched to the handler.
    "request-chunk-aggregation-limit" : "1m",
    # application.conf: 138
    "request-timeout" : "40 s",
    # reference.conf: 121
    # The initial size if the buffer to render the response headers in.
    # Can be used for fine-tuning response rendering performance but probably
    # doesn't have to be fiddled with in most applications.
    "response-header-size-hint" : 512,
    # reference.conf: 13-623
    # Always contains the deployed version of spray.
    # Referenced, for example, from the `spray.can.server.server-header` setting.
    "server-header" : "spray-can/1.3.2",
    # reference.conf: 19
    # Enables/disables SSL encryption.
    # If enabled the server uses the implicit `ServerSSLEngineProvider` member
    # of the `Bind` command to create `SSLEngine` instances for the underlying
    # IO connection.
    "ssl-encryption" : "off",
    # reference.conf: 178
    # Enables more verbose DEBUG logging for debugging SSL related issues.
    "ssl-tracing" : "off",
    # reference.conf: 70
    # Enables/disables support for statistics collection and querying.
    # Even though stats keeping overhead is small,
    # for maximum performance switch off when not needed.
    "stats-support" : "on",
    # reference.conf: 60
    # The path of the actor to send `spray.http.Timedout` messages to.
    # If empty all `Timedout` messages will go to the "regular" request
    # handling actor.
    "timeout-handler" : "",
    # reference.conf: 48
    # After a `Timedout` message has been sent to the timeout handler and the
    # request still hasn't been completed after the time period set here
    # the server will complete the request itself with an error response.
    # Set to `infinite` to disable timeout timeouts.
    "timeout-timeout" : "2 s",
    # reference.conf: 86
    # Enables/disables automatic handling of HEAD requests.
    # If this setting is enabled the server dispatches HEAD requests as GET
    # requests to the application and automatically strips off all message
    # bodies from outgoing responses.
    # Note that, even when this setting is off the server will never send
    # out message bodies on responses to HEAD requests.
    "transparent-head-requests" : "on",
    # reference.conf: 135
    # The time period within which the TCP unbinding process must be completed.
    # Set to `infinite` to disable.
    "unbind-timeout" : "1s",
    # reference.conf: 106
    # Enables/disables the returning of more detailed error messages to
    # the client in the error response.
    # Should be disabled for browser-facing APIs due to the risk of XSS attacks
    # and (probably) enabled for internal or non-browser APIs.
    # Note that spray will always produce log messages containing the full
    # error details.
    "verbose-error-messages" : "off"
}

[2015-10-09 16:43:40,302] INFO  ka.event.slf4j.Slf4jLogger [] [] - Slf4jLogger started
[2015-10-09 16:43:40,314] INFO  rk.jobserver.io.JobFileDAO [] [] - rootDir is /Volumes/Share/hadoop/spark-jobserver-0.6.1/tmp/filedao/data
[2015-10-09 16:43:40,328] INFO  spark.jobserver.JarManager [] [akka://JobServer/user/jar-manager] - Starting actor spark.jobserver.JarManager
[2015-10-09 16:43:40,328] INFO  jobserver.DataManagerActor [] [akka://JobServer/user/data-manager] - Starting actor spark.jobserver.DataManagerActor
[2015-10-09 16:43:40,328] INFO  ocalContextSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting actor spark.jobserver.LocalContextSupervisorActor
[2015-10-09 16:43:40,329] INFO  ark.jobserver.JobInfoActor [] [akka://JobServer/user/job-info] - Starting actor spark.jobserver.JobInfoActor
[2015-10-09 16:43:40,378] INFO  k.jobserver.JobResultActor [] [akka://JobServer/user/context-supervisor/global-result-actor] - Starting actor spark.jobserver.JobResultActor
[2015-10-09 16:43:40,656] INFO  spark.jobserver.WebApi [] [] - No authentication.
[2015-10-09 16:43:40,884] INFO  spark.jobserver.WebApi [] [] - Starting browser web service...
[2015-10-09 16:43:42,103] INFO  ay.can.server.HttpListener [] [akka://JobServer/user/IO-HTTP/listener-0] - Bound to /0.0.0.0:8090
[2015-10-09 16:43:42,106] INFO  a.actor.DeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [akka.io.Tcp$Bound] from Actor[akka://JobServer/user/IO-HTTP/listener-0#-1601900205] to Actor[akka://JobServer/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2015-10-09 16:43:44,706] INFO  spark.jobserver.JarManager [] [akka://JobServer/user/jar-manager] - Storing jar for app test, 44654 bytes
[2015-10-09 16:43:44,720] ERROR akka.actor.ActorSystemImpl [] [ActorSystem(JobServer)] - Uncaught error from thread [JobServer-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: org.joda.time.DateTime.now()Lorg/joda/time/DateTime;
	at spark.jobserver.JarManager.spark$jobserver$JarManager$$saveJar(JarManager.scala:33)
	at spark.jobserver.JarManager$$anonfun$wrappedReceive$1.applyOrElse(JarManager.scala:67)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2015-10-09 16:43:44,727] INFO  rg.apache.spark.util.Utils [] [] - Shutdown hook called

**Comment by noorul** [comment]
So the problem seems to be in joda library. Did you check whether you
have conflicting jar?

Thanks and Regards
Noorul

**Comment by cookeem** [comment]
I checked joda.DateTime without method now(), but I run SJS at sbt ReStart is fine.

**Comment by cookeem** [comment]
SJS VERSION 0.6.1, spark version 1.4.1

**Comment by cookeem** [comment]
Hi, finally I find the reason, spark1.4.1 pre-built version can not support org.joda.time.DateTime.now even I add joda-time-2.5.jar in the classpath (I don't know why actually), but I found solution by google, it is nscala-time.

I add library dependencies: "com.github.nscala-time" % "nscala-time_2.10" % "2.2.0", and replace all source code "import org.joda.time.DateTime" into "import com.github.nscala_time.time.Imports._", so that spark would not output "java.lang.NoSuchMethodError: org.joda.time.DateTime.now()" and now it work!

**Comment by velvia** [comment]
I think there is something weird with your version of Spark.  Mine works:

scala> org.joda.time.DateTime.now
res16: org.joda.time.DateTime = 2015-10-12T21:12:27.983-07:00

**Comment by cookeem** [comment]
I don't know, I just use the pre-built spark version, and just add some classpath in spark-en.sh like this:
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:`/Volumes/Share/hadoop/hadoop-2.7.1/bin/hadoop classpath`"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:`/Volumes/Share/hadoop/hbase-1.0.0/bin/hbase classpath`"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/Volumes/Share/hadoop/mahout-0.11.0/*"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/Volumes/Share/hadoop/publiclib/*"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/Volumes/Share/hadoop/publiclib/cpdetector-1.0.10/*"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/Volumes/Share/hadoop/publiclib/jfree/*"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/Volumes/Share/hadoop/publiclib/lucene-5.3.0/*"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/Volumes/Share/hadoop/solr-5.3.0/dist/*"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/Volumes/Share/hadoop/solr-5.3.0/dist/solrj-lib/*"
export SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/Volumes/Share/hadoop/publiclib/spray/*"

And now when I use spray, other akka NoSuchMethodError encounter, maybe there is something wrong with my spark.

**Comment by Dom-nik** [comment]
I've just encountered the same error when running the tool with Spark 1.6.0 distributed with Cloudera Hadoop. I can't rebuild Spark, as it's prepackaged in CDH and maintained by another team.

Do you have any suggestions?

Referring: [Issue 280](https://github.com/spark-jobserver/spark-jobserver/issues/280)
