### ISSUE TITLE
JavaSparkJob

### ISSUE THREAD

**Issue by danjamker** [spark-jobserver/spark-jobserver#291]
When I create a class that extends JavaSparkJob it only inherits the Scala methods and not the JavaSparkContext methods:
runJob(sc: SparkContext, jobConfig: Config)
validate(sc: SparkContext, config: Config)

I am importing:
import spark.jobserver.JavaSparkJob;

**Comment by zeitos** [comment]
I'm not sure of what's your question.
Your IDE generates those methods with that signature? Did you try changing SparkContext for JavaSparkContext ?

**Comment by danjamker** [comment]
Yes, I tried changing SparkContext to JavaContext, it then fails to
compile.

I am using java 1.6.

On Mon, 19 Oct 2015 at 15:48 Fernando Otero <notifications@github.com>
wrote:

> I'm not sure of what's your question.
> Your IDE generates those methods with that signature? Did you try changing
> SparkContext for JavaSparkContext ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/291#issuecomment-149237537>
> .
>
-- 
Daniel Kershaw

**Comment by velvia** [comment]
Hm that’s weird.  Are you able to import the example JavaHelloWorldJob.java and compile it in the IDE?

**Comment by velvia** [comment]
@danjamker ...  Are you able to import the example JavaHelloWorldJob.java and compile it in the IDE?

**Comment by zeitos** [comment]
@danjamker should we close this one?

**Comment by velvia** [comment]
@danjamker closing, feel free to reopen.
