### ISSUE TITLE
Does the Jobserver installation node need to install Spark?

### ISSUE THREAD

**Issue by ChenYanting** [spark-jobserver/spark-jobserver#292]
In server_start.sh, it could use the command below. So, without Spark installation on Jobserver, how does Jobserver know what SPARK_HOME is?

cmd='$SPARK_HOME/bin/spark-submit --class $MAIN --driver-memory $JOBSERVER_MEMORY
  --conf "spark.executor.extraJavaOptions=$LOGGING_OPTS"
  --driver-java-options "$GC_OPTS $JAVA_OPTS $LOGGING_OPTS $CONFIG_OVERRIDES"
  $@ $appdir/spark-job-server.jar $conffile'

**Comment by zeitos** [comment]
you should have that variable in settings.sh

**Comment by ChenYanting** [comment]
@zeitos 
Thanks for your reply. However, my question is that if jobserver node does not have spark installed. Even thought I install spark in another machine with SPARK_HOME setting. In the node of jobserver installation, jobserver is not able to find spark-submit command in its machine because of no spark installed.

**Comment by zeitos** [comment]
@ChenYanting I'm still not sure what's the question :)
You have to have job-server running in a machine with spark because jobserver will use spark-submit.

So if the question is if you need to have SJS co-located with Spark the answer is yes

**Comment by ChenYanting** [comment]
@zeitos 

This is what my question is. :) 
So, it looks that SJS has to make Spark installed in the same machine.

**Comment by velvia** [comment]
Yes spark has to be installed in the same machine right now.  Not running necessarily, just installed.  So we can close this now right?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by ChenYanting** [comment]
Yes
