### ISSUE TITLE
Exceeds the configured limit when uploading jars

### ISSUE THREAD

**Issue by zombic** [spark-jobserver/spark-jobserver#294]
$curl --data-binary @....jar localhost:8090/jars/test
Request Content-Length 95182887 exceeds the configured limit of 31457280

How can I deal with it?

**Comment by velvia** [comment]
Hope you figured it out.  Simply edit your deployed *.conf (or application.conf, and rebuild) with a higher number for spray.can.server.parsing.max-content-length
