### ISSUE TITLE
handling utf-8

### ISSUE THREAD

**Issue by thushw** [spark-jobserver/spark-jobserver#295]
utf8 characters in the query string are being changed when the request gets to the job server. Where is the sender for JobManagerActor receiver?

**Comment by velvia** [comment]
Hmm…. the sender is the WebApi, or LocalContextSupervisorActor if a context needs to be started.
If this is happening it is probably where the jobConfig is being parsed….. could be easily verified by doing this in the Scala console:

    import com.typesafe.config.ConfigFactory
    val jobConfig = ConfigFactory.parseString(<<someString with UTF-8 chars>>)

It’s also possible the string is being changed when parsed in Spray.

-Evan

**Comment by thushw** [comment]
thanks.
It is not the config api. I see the string passed into the sender itself is wrong. So it is probably spray.

**Comment by velvia** [comment]
Ok, thanks for the help.  Will have to look into this some more.

**Comment by thushw** [comment]
Actually, turns out this is due to how charsets are handled in POST requests. I was using a curl cmd that did not specifically send in a UTF-8 header. When I send a UTF-8 header, the job server gets the characters.

I think the default charset for HTTP 1.1 is ISO-8859-1

**Comment by velvia** [comment]
@thushw great, seems like this is resolved now.  Will add a note about UTF-8 to the README.
