### ISSUE TITLE
Dockerfile for official Docker image

### ISSUE THREAD

**Issue by yohanliyanage** [spark-jobserver/spark-jobserver#299]
It seems that the Dockerfile for official docker image is not published anywhere as far as I can see. Having that published as part of the source would be helpful for those of us who would like to understand how it works, and perhaps to fork it for customizations. 

There are couple of comments (including mine) under the official page in Dockerhub asking for the same.  https://hub.docker.com/r/velvia/spark-jobserver/

**Comment by kiambogo** [comment]
It looks like the Dockerfile is constructed with SBT: https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Build.scala#L104.

Using `sbt docker:publishLocal`, you should be able to build an image from this source.

**Comment by yohanliyanage** [comment]
Thanks!
