### ISSUE TITLE
Server tested/running on 1.2.0

### ISSUE THREAD

**Issue by cjnolet** [spark-jobserver/spark-jobserver#30]
I notice the max version of Spark upon which the server claims to run is 1.1.0. Assuming development is still ongoing for this project, it should be tested and verified for 1.2.0 and the README updated

**Comment by jeffsteinmetz** [comment]
Is there any we we could use branches & releases in github to mark versions based on a combination of spark job server version and the spark core version? Sometimes we may want to push changes to the core spark jobserver project, but not be forced to upgrade the spark dependencies.

**Comment by velvia** [comment]
I think this is a fair ask.  Proposal:

1)  When the core project is about to be upgraded to a new Spark version, a
branch is created so work can keep going on the existing version

OR

2) When a release of spark-job-server is cut, a branch is created for that
release for patches.

2) would be based on more stable points of development, but you might end
up having multiple branches per version of Spark core.

Thoughts?

-Evan


On Mon, Jan 5, 2015 at 1:56 PM, Jeff Steinmetz <notifications@github.com>
wrote:

> Is there any we we could use branches & releases in github to mark
> versions based on a combination of spark job server version and the spark
> core version? Sometimes we may want to push changes to the core spark
> jobserver project, but not be forced to upgrade the spark dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/30#issuecomment-68789112>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by zeitos** [comment]
You can also just tag and if needed branch from the tag

**Comment by velvia** [comment]
I think this issue can be closed now.
