### ISSUE TITLE
Update Hadoop version in Dockerfile

### ISSUE THREAD

**Issue by kiambogo** [spark-jobserver/spark-jobserver#302]
Currently the Hadoop version set in the Dockerfile is 2.4 (https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Build.scala#L118). This is quite outdated, and lacking in several features (such as S3 access with IAM roles) that have forced me to fork, change, and build an image myself. Is there a particular reason for it to be kept at 2.4? Otherwise I'd advocate to bump it to the latest version (2.6).

**Comment by danisla** [comment]
One of the things I noticed that was removed in 2.6 was the jets3t library in favor of the hadoop-aws library. S3 URIs change from `s3n://` to `s3a://` and how you configure the library for custom S3 endpoints is also very different. That's just one of the reasons I'm still on 2.4, but it's not really a deal breaker.  

In the case of the Docker image, maybe we can build and push both the 2.4 and 2.6 versions of the spark distribution like how the Spark project does it. Granted this does add many more combinations to maintain with the various versions of Mesos too...

**Comment by velvia** [comment]
I’m personally not biased towards any version, but I notice there are still plenty of people on 2.4….  so can’t really win either way.

**Comment by kiambogo** [comment]
Great point @danisla. I actually needed 2.6 for this reason (leveraging `s3a://`). I really like your idea of varying Docker images, and perhaps supporting different versions of Spark/Hadoop through tags on the image.

**Comment by bsikander** [comment]
The current hadoop version used is 2.7. Closing.
