### ISSUE TITLE
Job specific jar command line arguments

### ISSUE THREAD

**Issue by kiambogo** [spark-jobserver/spark-jobserver#303]
Is it possible to supply command line arguments to the application JAR when starting a job? I have this need for specifying which configuration to use depending on which environment the SJS is running in.

**Comment by velvia** [comment]
Hi Chris, you can supply a config file when starting SJS…  I’m not sure if that’s what you mean?

**Comment by kiambogo** [comment]
I understand that you can supply a configuration file to SJS, but my question is about passing arguments to the Spark job JAR when starting a new task. For example, I have SJS running, and I have uploaded my JAR. When I construct a HTTP POST to trigger the job, I'd like to be able to provide arguments to the JAR itself (i.e. specifying a configuration file to use with `-Dconfig.file=`). Is that a bit more clear?

**Comment by velvia** [comment]
Oh, I see what you mean.   You want to pass the path to the config file.  If your file is local, you could simply pass the path in the job configuration / POST body, then parse that config file like:

def runJob(sc: SparkContext, config: Config) {
  val myJobConfigPath = config.getString(“com.abc.job_config_path”)
  val parseConfig = ConfigFactory.parseFile(new java.io.File(myJobConfigPath)) …
}

**Comment by kiambogo** [comment]
That's just what I need! However, when I implement that it looks like it is looking for the file I specify in the root directory of the SJS docker container (`/`), and not in the JAR. 

Currently I'm passing `application-prod.conf` as the config path, and it is searching for that file as `/application-prod.conf` in the SJS docker container. The JAR lives at `/tmp/spark-job-server/filedao/data/my-jar.jar`, and the config file is in the root folder of the JAR. Could this be because of the JobManagerActor's launching the JAR?

**Comment by kiambogo** [comment]
I've figured it out - issue was about accessing files within a JAR on the classpath. 

For reference, I had to do the following

    ConfigFactory.parseReader(paramReader = new InputStreamReader(getClass().getResourceAsStream(s"/$myPassedConfigPath"))`

...assuming your config file is in the root of the Jar. 

Thanks for your help @velvia!

**Comment by velvia** [comment]
Glad you figured it out!
