### ISSUE TITLE
Is it possible/planned to run "interactive" Spark Shell-like sessions

### ISSUE THREAD

**Issue by tobilg** [spark-jobserver/spark-jobserver#305]
I saw that [Livy](https://github.com/cloudera/hue/tree/master/apps/spark/java#spark-example) supports Spark Shell-like sessions over a REST API.

Is something similar possible with Spark Jobserver? I didn't find anything in the  docs... If not is this planned for the future?

**Comment by velvia** [comment]
Hi Tobi,

I’ve thought about this in the past.  Would be really interesting.  In fact, would be a killer way to debug existing jobs.  Do you want to file a ticket?  We can have it as a feature.

-Evan

**Comment by tobilg** [comment]
Evan,

that would be great. I'm currently evaluating different options to integrate Spark with our existing application. One core use case is to interact with a visual data flow modelling engine. To have to compile the Jars during runtime would probably be a no-go concerning the app's interactivity. 

That would be our "killer feature", which currently prevents us from using Spark Jobserver. 

How do I have to file a ticket? Thanks for your help.

**Comment by velvia** [comment]
Oh, I mean just go to Github and file a ticket.   

So you want a REST interface to an interactive Scala shell?

**Comment by tobilg** [comment]
I will create another issue with some requirements. Thanks for your input.

**Comment by tobilg** [comment]
Feature request is filed under https://github.com/spark-jobserver/spark-jobserver/issues/307

**Comment by velvia** [comment]
Cool thanks.
