### ISSUE TITLE
Cant specify where condition in SQL Query

### ISSUE THREAD

**Issue by neoatmn** [spark-jobserver/spark-jobserver#306]
I cannot run this query
select * from test_db.state_table where state_code ='VA'

using
curl -d ' "sql"="select * from test_db.state_table where state_code ='MN' "' 'localhost:8090/jobs?appName=hive&classPath=spark.jobserver.HiveTestJob&context=hive-context&sync=true&timeout=300'

Data type is string on state_code
This is the same issue reported on this thread 
https://github.com/spark-jobserver/spark-jobserver/issues/254

But unfortunately I cannot use --data-binary option since the query comes from a web application.

**Comment by neoatmn** [comment]
This happens only when i specify a WHERE condition on a string column with single quotes

**Comment by neoatmn** [comment]
actually any filter criteria on a  string field (with or without single quote) does not work.

Both these don't work.

select * from state_table where state_code =MN
select * from state_table where state_code ='MN'

**Comment by neoatmn** [comment]
When i used this query 
select * from test_db.state_table where state_code in ('12') 

query ran Ok  without any issues. And here is the SQL plan details from Spark UI

== Parsed Logical Plan ==
'Project [unresolvedalias(*)]
 'Filter 'state_code IN (12)
  'UnresolvedRelation [test_db,state_table], None

== Analyzed Logical Plan ==
state_name: string, state_code: string
Project [state_name#10,state_code#11]
 Filter state_code#11 IN (cast(12 as string))
  MetastoreRelation test_db, state_table, None

== Optimized Logical Plan ==
Filter state_code#11 IN (12)
 MetastoreRelation test_db, state_table, None

== Physical Plan ==
Filter state_code#11 IN (12)
 HiveTableScan [state_name#10,state_code#11], (MetastoreRelation test_db, state_table, None)

Code Generation: true

**Comment by velvia** [comment]
When you mention that this works, you mean that it works in SJS?

**Comment by neoatmn** [comment]
yes.  Both these  queries work in SJS (returning no data for obvious reasons)

select * from test_db.state_table where state_code =12
select * from test_db.state_table where state_code ='12'


These queries don't work in SJS. Gives me "message": "cannot resolve " error

select * from test_db.state_table where state_code =MN
select * from test_db.state_table where state_code ='MN'

**Comment by velvia** [comment]
@neoatmn not sure, but I just updated the section on SQL querying, with proper escapes of SQL in curl, hopefully that should help.
