### ISSUE TITLE
Enhancement: Interactive Spark Shell via REST interface

### ISSUE THREAD

**Issue by tobilg** [spark-jobserver/spark-jobserver#307]
# Description

As already asked in https://github.com/spark-jobserver/spark-jobserver/issues/305 I think it would be a great feature enhancement if there would be the possibility to use a Spark Shell via a REST interface.

Similarly to the [Livy project's Spark Shell session](https://github.com/cloudera/hue/tree/master/apps/spark/java#spark-example), meaning that an existing `context` can be used to create an interactive `session`, in which `statements` can be executed against the remote Spark Shell. 

I'm not sure if the Spark Jobserver's `context` is able to "produce" either a Scala, Python or R Shell, but if that would be possible without a lot of code changes to the `context`, then I guess it would be preferable to be as flexible as possible.

Find below my suggestion of possible REST interfaces and object. These are just to demonstrate how they **could** look like.

# Potential REST interfaces:

Preface:
--------
New `sessions` should IMHO be opened "below" a specific `context`, that's why I tried to use hierarchical resource naming patterns. Downside of this is that the URIs get quite long.

## POST /contexts/{context_name}/sessions

Creates a new session on context {context_name}
	
### Sample request

    curl -H "Content-Type: application/json" -XPOST 'http://spark-jobserver/contexts/mycontext/sessions' -d '{ "type": "spark" }'

**Request body**

Name | Description | Type
--- | --- | ---
type | The session type | string

### Sample response

The `session` object.

```
{
	"id": 0,
	"type": "spark",
	"context": "mycontext",
	"state": "idle"
}
```

## GET /contexts/{context_name}/sessions

Lists all sessions below context `{context_name}`.

### Sample request

    curl -H "Content-Type: application/json" -XGET 'http://spark-jobserver/contexts/mycontext/sessions'
	
### Sample response

A list of `session` objects.

```
{
	"sessions": [
		{
			"id": 0,
			"type": "spark",
			"context": "mycontext",
			"state": "idle"
		}
	]
}
```

## DELETE /contexts/{context_name}/sessions/{session_id}

Deletes the session `{session_id}` below context `{context_name}`.

### Sample request

    curl -H "Content-Type: application/json" -XDELETE 'http://spark-jobserver/contexts/mycontext/sessions/0'
	
### Sample response

Response will be empty, but with status 200.

## POST /contexts/{context_name}/sessions/{session_id}/statements

Create a statement for session `{session_id}` below context `{context_name}`. It would be great if this endpoint would return a URL that can be polled manually if the result cannot be returned within a defineable threshold (e.g. 250ms).

**Request body**

Name | Description | Type
--- | --- | ---
 code | The code to execute | string

### Sample request

    curl -H "Content-Type: application/json" -XPOST 'http://spark-jobserver/contexts/mycontext/sessions/0/statements' -d '{ "code": "1 + 1" }'
	
### Sample response

The `statement` object.

```
{
	"sessions": [
		{
			"id": 0,
			"type": "spark",
			"context": "mycontext",
			"state": "idle"
		}
	]
}
```

## GET /contexts/{context_name}/sessions/{session_id}/statements/{statement_id}

Retrieve specific `statement` of the session `{session_id}` below context `{context_name}`.

### Sample request

    curl -H "Content-Type: application/json" -XGET 'http://spark-jobserver/contexts/mycontext/sessions/0/statements/0'
	
### Sample response

A `statement` object.

```
{
	"id": 0,
	"output": null,
	"state": "running"
}
```

## GET /contexts/{context_name}/sessions/{session_id}/statements

Lists all `statements` of the session `{session_id}` below context `{context_name}`.

### Sample request

    curl -H "Content-Type: application/json" -XGET 'http://spark-jobserver/contexts/mycontext/sessions/0/statements'
	
### Sample response

A list of `statement` objects.

```
{
	"statements": [
		{
			"id": 0,
			"output": {
				"data": {
					"text/plain": "res0: Int = 2"
				},
				"execution_count": 0,
				"status": "ok"
			},
			"state": "available"
		}
	]
}
```

	
# Potential REST Objects

The following objects have been copied/adapted from [Livy's REST objects](https://github.com/cloudera/hue/blob/master/apps/spark/java/README.rst#rest-objects).

Session
-------

Sessions represent an interactive shell.

| Property        | Description                                    | Type                      |
| --------------- | ---------------------------------------------- | ------------------------- |
| id              | The session id                                 | integer                   |
| type            | The session type (spark, pyspark, or sparkr)   | `session type` (string)  |
| context         | The name of the context                        | string                    |
| state           | The session state                              | `session state` (string) |

Session State
-------------

Sessions State represents the state of the interactive shell session.

| State name  | Description                      |
| ----------- | -------------------------------- |
| not_started | Session has not been started     |
| starting    | Session is starting              |
| idle        | Session is waiting for input     |
| busy        | Session is executing a statement |
| error       | Session errored out              |
| dead        | Session has exited               |

Session Type
------------

Sessions Type represents the state of the interactive shell session.

| Type name  | Description                      |
| ---------- | -------------------------------- |
| spark      | Interactive scala/spark session  |
| pyspark    | Interactive python/spark session |
| sparkr     | Interactive R/spark session      |

Statement
---------

Statements represent the result of an execution statement.

| Name   | Description          | Type                |
| ------ | -------------------- | ------------------- |
| id     | The statement id     | integer             |
| state  | The execution state  | `statement state`   |
| output | The execution output | `statement output`  |

Statement State
---------------

| Name      | Description                      |
| --------- | -------------------------------- |
| running   | Statement is currently executing |
| available | Statement has a ready response   |
| error     | Statement failed                 |

Statement Output
----------------

| Name            | Description       | Type                             |
| --------------- | ----------------- | -------------------------------- |
| status          | Execution status  | string                           |
| execution_count | A monotomically increasing number  | integer         |
| data            | Statement output  | An object mapping a mime type to the result. If the mime type is ``application/json``, the value will be a JSON value |

**Comment by jlamcanopy** [comment]
+1 on this.

**Comment by tobilg** [comment]
Any updates on this topic?

**Comment by velvia** [comment]
No sorry. Need more investigation. 

-Evan
"Never doub that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by Grillz** [comment]
+1

**Comment by tobilg** [comment]
@Grillz You can have a look at https://github.com/spark-server/spark-server if you're interested in a JS implementation.
