### ISSUE TITLE
Job launch fails if Spark runs on Secure YARN Cluster

### ISSUE THREAD

**Issue by mvle** [spark-jobserver/spark-jobserver#310]
Hi,

I've deployed a Secure YARN cluster with HDFS encryption and am trying to use the SJS for submitting Spark jobs.

When submitting new jobs through the API, the job submission will fail the second time a job is submitted. Everything works fine if I create a long lasting job context and submit jobs to that single context. However, it looks like when SJS has to create a new context, the new context has a problem getting a delegation token. If I restart the SJS, then I can once again execute the job once, but the second time the job is submitted (a new context is created), it will fail once again.

I think this might be related to how the spark context is destroyed and created, causing something to go out of sync in terms of caching tokens with the YARN/HDFS cluster. Does anyone have any experience with this or can give some clues how this can be fixed?

I include error logs are below:

{
  "status": "ERROR",
  "result": {
    "errorClass": "java.lang.RuntimeException",
    "cause": "token (HDFS_DELEGATION_TOKEN token 42 for hadoop) can't be found in cache",
    "stack": ["org.apache.hadoop.ipc.Client.call(Client.java:1476)", "org.apache.hadoop.ipc.Client.call(Client.java:1407)", "org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)", "com.sun.proxy.$Proxy12.getDelegationToken(Unknown Source)", "org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getDelegationToken(ClientNamenodeProtocolTranslatorPB.java:933)", "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)", "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)", "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)", "org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)", "com.sun.proxy.$Proxy13.getDelegationToken(Unknown Source)", "org.apache.hadoop.hdfs.DFSClient.getDelegationToken(DFSClient.java:1044)", "org.apache.hadoop.hdfs.DistributedFileSystem.getDelegationToken(DistributedFileSystem.java:1543)", "org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:530)", "org.apache.hadoop.fs.FileSystem.addDelegationTokens(FileSystem.java:508)", "org.apache.hadoop.hdfs.DistributedFileSystem.addDelegationTokens(DistributedFileSystem.java:2228)", "org.apache.spark.deploy.yarn.YarnSparkHadoopUtil$$anonfun$obtainTokensForNamenodes$1.apply(YarnSparkHadoopUtil.scala:126)", "org.apache.spark.deploy.yarn.YarnSparkHadoopUtil$$anonfun$obtainTokensForNamenodes$1.apply(YarnSparkHadoopUtil.scala:123)", "scala.collection.immutable.Set$Set1.foreach(Set.scala:74)", "org.apache.spark.deploy.yarn.YarnSparkHadoopUtil.obtainTokensForNamenodes(YarnSparkHadoopUtil.scala:123)", "org.apache.spark.deploy.yarn.Client.getTokenRenewalInterval(Client.scala:495)", "org.apache.spark.deploy.yarn.Client.setupLaunchEnv(Client.scala:528)", "org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:628)", "org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:119)", "org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:56)", "org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:144)", "org.apache.spark.SparkContext.<init>(SparkContext.scala:523)", "spark.jobserver.context.DefaultSparkContextFactory$$anon$1.<init>(SparkContextFactory.scala:53)", "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:53)", "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:48)", "spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:37)", "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:48)", "spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:287)", "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:109)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:467)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"],
    "causingClass": "org.apache.hadoop.ipc.RemoteException",
    "message": "org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.token.SecretManager$InvalidToken): token (HDFS_DELEGATION_TOKEN token 42 for hadoop) can't be found in cache"
  }

**Comment by velvia** [comment]
Michael, it could be that for YARN the multiple contexts per single JVM model doesn’t really work.   You could try the feature/context-per-jvm branch, which launches a separate process for each context, and see if that works.

**Comment by neoatmn** [comment]
I had the same issue as well. I could not create more than one hive context.

**Comment by neoatmn** [comment]
cant find any reference to context-per-jvm in github

**Comment by velvia** [comment]
It’s a branch, you’ll need to check it out to try it  (e.g. git checkout feature/context-per-jvm)

**Comment by velvia** [comment]
Actually, tests should be disabled when you build and deploy already.   Just follow the normal deploy instructions and you should be good to go.

**Comment by koertkuipers** [comment]
i had a similar issue in an inhouse project, and simply doing a kerberos login from keytab just before creating a new spark context fixed it. not sure why

**Comment by moonlightheng** [comment]
@koertkuipers  how did u fixed it？ could you show your code?  I had a same error. but I don't know where to login the kerberos.  in shell script? or setting.sh or  local.conf  or somewhere     thank you !

**Comment by hntd187** [comment]
Since this hasn't been updated in a long time I am closing it. @moonlightheng if you are still having issues please open a new issue so we can help out. Thanks!
