### ISSUE TITLE
Unable to instantiate org.apache.hadoop.hive.metastore.HiveMetaStoreClient

### ISSUE THREAD

**Issue by yanji84** [spark-jobserver/spark-jobserver#312]
I am trying to create a new hivecontext in this way

curl -d "" 'localhost:8090/contexts/sqlquery?num-cpu-cores=4&memory-per-node=2g&dependent-jar-uris=file://root/jar-dep/datanucleus-api-jdo-3.2.6.jar,file://root/jar-dep/datanucleus-core-3.2.10.jar,file://root/jar-dep/datanucleus-rdbms-3.2.9.jar,file://root/jar-dep/mysql-connector-java-5.1.37-bin.jar&context-factory=spark.jobserver.context.HiveContextFactory'

But I got a "CONTEXT INIT ERROR" back

Here is the full stacktrace

    "cause": "Unable to instantiate org.apache.hadoop.hive.metastore.HiveMetaStoreClient",
    "stack": ["org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1412)", "org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:62)", "org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:72)", "org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:2453)", "org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:2465)", "org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:340)", "org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:116)", "org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:163)", "org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:161)", "org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:168)", "spark.jobserver.context.HiveContextFactory$$anon$1.<init>(HiveContextFactory.scala:17)", "spark.jobserver.context.HiveContextFactory.contextFactory(HiveContextFactory.scala:17)", "spark.jobserver.context.HiveContextFactory.makeContext(HiveContextFactory.scala:13)", "spark.jobserver.context.HiveContextFactory.makeContext(HiveContextFactory.scala:9)", "spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:37)", "spark.jobserver.context.HiveContextFactory.makeContext(HiveContextFactory.scala:9)", "spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:287)", "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:109)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:465)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"]

Is this the right way to create Hive Context?

Thanks

**Comment by allantaylor81** [comment]
I met the same issue.
curl -d "" 'ivan.local:8090/contexts/sql-context?context-factory=spark.jobserver.context.HiveContextFactory'

Response from jobserver:
"status": "CONTEXT INIT ERROR",
"result": {
"errorClass": "java.lang.RuntimeException",
"cause": "Unable to instantiate org.apache.hadoop.hive.metastore.HiveMetaStoreClient",
.........
}

@velvia  please help thank u

**Comment by velvia** [comment]
Let's track the discussion in #304... this seems like a duplicate.
