### ISSUE TITLE
Unable to work with named rdd

### ISSUE THREAD

**Issue by dhruvsinghal991** [spark-jobserver/spark-jobserver#316]
I am running the same code, but it's throwing me the error of 
Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: spark.jobserver.NamedRdds.update(Ljava/lang/String;Lscala/Function0;)Lorg/apache/spark/rdd/RDD

Below is my code:

/**

Created by dhruvsinghal on 18/11/15. */ package com.dhruv import org.apache.spark._ import com.typesafe.config.{Config,ConfigFactory} import org.apache.spark.SparkContext._ import spark.jobserver.{NamedRdds, NamedRddSupport, SparkJob, SparkJobInvalid, SparkJobValid, SparkJobValidation} import scala.util.Try
object saveRDDJob extends SparkJob with NamedRddSupport{
def main(args: Array[String]) {
val sc = new SparkContext("local[4]", "WordCountExample")
val config = ConfigFactory.parseString("")
val results = runJob(sc, config)
println("Result is " + results)
}
override def runJob(sc:SparkContext, config: Config): Any ={
val dd = sc.parallelize(1 to 100)
dd.cache()
dd.persist()
this.namedRdds.update("savedrdd", dd)
dd.collect()
}
override def validate(sc:SparkContext, config:Config): SparkJobValidation={
Try(config.getString("input.string"))
.map(x => SparkJobValid)
.getOrElse(SparkJobInvalid("No input.string config param"))
}
}

object retrieveRDDJob extends SparkJob with NamedRddSupport{
def main(args:Array[String]): Unit ={
val sc = new SparkContext("local[4]", "WordCountExample")
val config = ConfigFactory.parseString("")
val results = runJob(sc, config)
println("Result is "+ results)
}
override def runJob(sc:SparkContext, config:Config): Any={
val dd = this.namedRdds.get("sampleRDD").get

}
override def validate(sc:SparkContext, config:Config): SparkJobValidation={
Try(config.getString("input.string"))
.map(x => SparkJobValid)
.getOrElse(SparkJobInvalid("No input.string config param"))
}
}

SBT:

name := "MergingDatasets"

version := "1.0"

scalaVersion := "2.10.4"

libraryDependencies += "org.apache.spark" %% "spark-core" % "1.5.1"

resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"

libraryDependencies += "spark.jobserver" %% "job-server-api" % "0.6.0" % "provided"
libraryDependencies += "spark.jobserver" %% "job-server-extras" % "0.6.0" % "provided"

val buildSettings = Defaults.defaultSettings ++ Seq(
javaOptions += "-Xmx8G"
)

assemblyMergeStrategy in assembly := {
case PathList("META-INF", xs @ _*) => MergeStrategy.discard
case x => MergeStrategy.first
}

**Comment by velvia** [comment]
Sorry, but job server 0.6.0 (released version) is only compatible with Spark 1.4.x.   We are looking to release 0.6.1 with Spark 1.5.x soon.

**Comment by t3chg33k** [comment]
Try chaning libraryDependencies += "org.apache.spark" %% "spark-core" % "1.5.1" to libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "1.5.1"

**Comment by morpheyesh** [comment]
I am facing the same issue, the above gives the same result.

**Comment by t3chg33k** [comment]
I have tried the same using sparkSqlJob and sparkSqlContext.. find below sbt and sample code. 

name := "<<app_name>>"

version := "1.0"

scalaVersion := "2.10.4"

resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"

libraryDependencies += "org.scala-lang" % "scala-compiler" % "2.10.4"
libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "1.5.1"
libraryDependencies += "org.apache.spark" % "spark-sql_2.10" % "1.5.1"
libraryDependencies += "spark.jobserver" %% "job-server" % "0.6.0" % "provided"
libraryDependencies += "spark.jobserver" %% "job-server-extras" % "0.6.0" % "provided"

**Comment by t3chg33k** [comment]
save data to memory.. 

import org.apache.spark.{SparkConf,SparkContext}
import org.apache.spark.sql.{SQLContext,Row}
import _root_.spark.jobserver.{SparkSqlJob,SparkJobValid,SparkJobInvalid,SparkJobValidation}
import com.typesafe.config.{Config, ConfigFactory}

object dataCache extends SparkSqlJob    {
  
  override def validate(sc: SQLContext, config: Config): SparkJobValidation  = {
    println(config.entrySet())
   SparkJobValid
}
  
   override def runJob(sqlContext: SQLContext, config: Config): Any = {
       val data= //... load data to dataframe 
      
       data.registerTempTable("dataInMemory")
       sqlContext.cacheTable("dataInMemory")      
   } 
}

**Comment by t3chg33k** [comment]
retrieve data...

import org.apache.spark.{SparkConf,SparkContext}
import org.apache.spark.sql.{SQLContext,Row}
import _root_.spark.jobserver.{SparkSqlJob,SparkJobValid,SparkJobInvalid,SparkJobValidation,NamedRddSupport}
import com.typesafe.config.{Config, ConfigFactory}

object dataRetrieve extends SparkSqlJob    {
  
  override def validate(sc: SQLContext, config: Config): SparkJobValidation  = {
    println(config.entrySet())
   SparkJobValid
}
  
   override def runJob(sqlContext: SQLContext, config: Config): Any = {
       val data=sqlContext.table("dataInMemory") 
       data.registerTempTable("result")
       val df=sqlContext.sql("select * from result")
       return df.collect()

   } 
}

**Comment by velvia** [comment]
@dhruvsinghal991 I still think this is a versioning issue which is fixable on your end.  If you have any updates, feel free to reopen.

Note that you don't need to call `registerTempTable` again after you retrieve the table from sqlContext.  You could just go ahead and do a `sqllContext.sql("select * from dataInMemory")`.
