### ISSUE TITLE
Does the current code at master compatible with spark 1.5.2 

### ISSUE THREAD

**Issue by janurag** [spark-jobserver/spark-jobserver#317]
- As you might know that `Spark 1.5.2` just released will the master work with it as well.
- Also, is the current master tested for spark 1.5.1 ?

Would appreciate if you clear these things out.
Thanks

**Comment by velvia** [comment]
@janurag yes, the current code should be compatible with 1.5.2.  It is compiled and tested against 1.5.1, but Spark guarantees compatibility for minor point releases.
