### ISSUE TITLE
org.apache.spark.SparkException: Found both spark.executor.extraJavaOptions and SPARK_JAVA_OPTS. Use only the former.

### ISSUE THREAD

**Issue by kumaramit01** [spark-jobserver/spark-jobserver#318]
I get this exception with Spark 1.5.1, Spark Jobserver built from master while running the WordCountExample; 

I am able to run jobs via spark-submit; I am wondering if you have any clues -where I should dig. I see that in the SparkConf.scala -this exception is thrown when we have both the SPARK_JAVA_OPTS and extraJavaOptions.
Is this something to do with my spark env settings or an actual issue? What should I look at?

Thanks
Amit

====================

/home/spark/spark/sbin$ curl -d "input.string = a b c a b see" 'localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample'
{
  "status": "ERROR",
  "result": {
    "errorClass": "java.lang.RuntimeException",
    "cause": "Found both spark.executor.extraJavaOptions and SPARK_JAVA_OPTS. Use only the former.",
    "stack": ["org.apache.spark.SparkConf$$anonfun$validateSettings$5$$anonfun$apply$5.apply(SparkConf.scala:451)", "org.apache.spark.SparkConf$$anonfun$validateSettings$5$$anonfun$apply$5.apply(SparkConf.scala:449)", "scala.collection.immutable.List.foreach(List.scala:318)", "org.apache.spark.SparkConf$$anonfun$validateSettings$5.apply(SparkConf.scala:449)", "org.apache.spark.SparkConf$$anonfun$validateSettings$5.apply(SparkConf.scala:435)", "scala.Option.foreach(Option.scala:236)", "org.apache.spark.SparkConf.validateSettings(SparkConf.scala:435)", "org.apache.spark.SparkContext.<init>(SparkContext.scala:391)", "spark.jobserver.context.DefaultSparkContextFactory$$anon$1.<init>(SparkContextFactory.scala:53)", "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:53)", "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:48)", "spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:37)", "spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:48)", "spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:287)", "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:109)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:467)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"],
    "causingClass": "org.apache.spark.SparkException",
    "message": "org.apache.spark.SparkException: Found both spark.executor.extraJavaOptions and SPARK_JAVA_OPTS. Use only the former."
  }
}
====================

**Comment by velvia** [comment]
You could try disabling either your SPARK_JAVA_OPTS in your spark-env.sh, or disable the equivalent in the job server server_run.sh script….

**Comment by kumaramit01** [comment]
Thanks -I didn't have SPARK_JAVA_OPTS anywhere in my spark-env.sh, even
then I got the same error; However after commenting the
spark.executor.extraJavaOptions in the server run script -it works fine.

Best,
Amit
