### ISSUE TITLE
How do you setup multiple Spark Streaming jobs 

### ISSUE THREAD

**Issue by 0612800232** [spark-jobserver/spark-jobserver#321]
How to setup multiple Spark Streaming jobs with spark-jobserver?

i get the error: Only one StreamingContext may be started in this JVM

**Comment by velvia** [comment]
Try the feature/context-per-jvm branch.

**Comment by velvia** [comment]
@0612800232 going to close this as the feature/context-per-jvm branch is available and soon going to be merged.
