### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by zeitos** [spark-jobserver/spark-jobserver#325]
1- We need releaseCrossBuild set to true so sbt release will publish both 2.10 and 2.11 version.
2- We need to fix the release configuration in order to release from sbt. if you run it as it is right now the release will fail and you need to checkout the previous version and do sbt +publish

**Comment by hntd187** [comment]
I believe we now publish for both 2.11.8 and 2.10.6

**Comment by velvia** [comment]
True, it definitely should be more automated though.

**Comment by valan4ik** [comment]
We are using sbt-release plugin, which makes it easy to [publish cross releases](https://github.com/sbt/sbt-release/blob/master/README.md#cross-building-during-a-release).

-  We were releasing 2 Scala versions starting with Jobserver 0.5.1: spark-jobserver/spark-jobserver@0796476
-  And removed it in Jobserver 0.8.0: spark-jobserver/spark-jobserver@8667393

Currently we publish only Scala 2.11 as Scala 2.12 is not yet supported by us.
I would close the ticket as the functionality is there and it is clear how to switch it on again, once we support Scala 2.12.
