### ISSUE TITLE
Does 0.6.1 officially support multi context?

### ISSUE THREAD

**Issue by qiang5714** [spark-jobserver/spark-jobserver#331]
Hi everyone：
  Does jobserver 0.6.1 officially support  multi job in the sametime? I saw PR120 has been merged to branch 0.6.1. 
  Thanks

**Comment by cyx0720** [comment]
waiting

**Comment by zeitos** [comment]
no, @velvia is working on branch feature/context-per-jvm that's why #120 was closed
