### ISSUE TITLE
Using spark job server in jupyter notebook

### ISSUE THREAD

**Issue by jlamcanopy** [spark-jobserver/spark-jobserver#334]
Hi there, 

I wonder if there are development efforts in making job server works in jupyter notebook?
I read the basic usage of spark job server. It is required that users compile the code and then submit to the job server before they can use it. I wonder if the code can be submit dynamically via API as closure to the job server.

```
class MyJob implements ANY_THING_THAT_REQUIRES_BY_JOB_SERVER {
def foo
def bar
}

jobServer.submit(MyJob)

jobServer.runJob(SOME_ARGS_TO_EXECUTE_THE_JOB)
```

Just wonder if this is actually a good use case for job server.

I checked other projects like [livy](https://github.com/cloudera/hue/tree/master/apps/spark/java). They implement a REST service for spark which submit arbitrarily codes. 

Thanks!

**Comment by jlamcanopy** [comment]
I saw there is a feature request for this.

**Comment by velvia** [comment]
Are you talking about submitting a string which job server would compile?

**Comment by jerrylam** [comment]
@velvia : It is very similar to [the feature request ](https://github.com/spark-jobserver/spark-jobserver/issues/307).
