### ISSUE TITLE
Wrong a hadoop replication factor

### ISSUE THREAD

**Issue by v-gerasimov** [spark-jobserver/spark-jobserver#339]
This is part of my spark-jobserver config:
```
spark.context-settings {
  spark.hadoop.dfs.replication = 2
}
```

When I start a job, it creates files with different replication factor in my hdfs:
![image](https://cloud.githubusercontent.com/assets/8486333/11648474/d321df6a-9d96-11e5-912e-fd3fd76dc2c0.png)

But, if I start spark-jobserver with `-Dspark.hadoop.dfs.replication=2` it works great.

I don't know this is a spark-jobserver bug or spark. May be I am doing something wrong.

Have you any ideas?

**Comment by velvia** [comment]
Maybe try putting the setting under spark.context-settings.passthrough

**Comment by v-gerasimov** [comment]
I added this row in the bottom of my spark-jobserver config: ```spark.hadoop.dfs.replication=2```
But nothing is changed. I have replication factor equals 3.

Looks that something is wrong. Firstly I don't understand why I can't set own replication factor for each spark context. Secondly I don't know why jvm property is working, but when I try to add this property in config file nothing is happening.

**Comment by velvia** [comment]
Hmm.  As in a line by itself?  So then it falls in no hierarchy right?  

Try

spark.context-settings.passthrough {
  spark.hadoop.dfs.replication=2
}

**Comment by v-gerasimov** [comment]
I added ```passthrough``` in my context-settings like you posted:
```
spark.context-settings.passthrough {
  spark.hadoop.dfs.replication=2
}
```

I see ```spark.hadoop.dfs.replication``` parameter in SparkUI:
![image](https://cloud.githubusercontent.com/assets/8486333/11706697/e5b33070-9f1c-11e5-97a9-5ca98fcfd35f.png)

But nothing is changed, I still have replication factor equals 3.

**Comment by velvia** [comment]
Hmmm….  weird.  So Spark is getting the setting, but HDFS is not quite getting it.     Is the HDFS replication setting per transaction, or is it something configured when HDFS starts up?   

-Evan

**Comment by v-gerasimov** [comment]
I have default dfs.replication which equals 3 in my Hadoop cluster. Nothing else changes replication during working. However, it looks strange because when I start spark-jobserver with ```-Dspark.hadoop.dfs.replication=2``` it works as needed.

**Comment by velvia** [comment]
Hm technically it's exactly the same, setting -D just a diff way for Spark to get it.  Either way my Q for you is is HDFS supposed to pick up the setting from Spark?  How does it pick it up?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by v-gerasimov** [comment]
Yes, setting -D is different way to pass it to Spark. But I don't know why ```-Dspark.hadoop.dfs.replication=2``` works and ```spark.hadoop.dfs.replication=2``` in spark-jobserver config doesn't work.

Evan, if I have understood your question correctly, I use ```saveAsTextFile``` method of ```RDD```. It uses ```saveAsHadoopFile``` method which ```conf``` parameter is:
```conf: JobConf = new JobConf(self.context.hadoopConfiguration)``` (```JobConf``` is ```org.apache.hadoop.mapred.JobConf```).

Then this method save ```RDD``` by ```SparkHadoopWriter(jobConf: JobConf)```. So, HDFS picks a replication factor parameter up from Spark by ```JobConf``` which contains ```dfs.replication``` from ```context.hadoopConfiguration```.

**Comment by hntd187** [comment]
@v-gerasimov is there any update on your issue? Have you tried the new code?

**Comment by v-gerasimov** [comment]
@hntd187 No, it isn't. Currently I force replication factor in my spark-jobs.

**Comment by hntd187** [comment]
@v-gerasimov have you tried setting ```dfs.replication``` in the hadoop configuration via the hadoop config portion of the SJS?

**Comment by v-gerasimov** [comment]
@hntd187 Sorry, I have missed your commit. It seems to work fine. Thanks!
