### ISSUE TITLE
Documentation on debugging setup issues

### ISSUE THREAD

**Issue by JithinThomas** [spark-jobserver/spark-jobserver#340]
I've been hitting a TimeoutException when setting up Spark Job server to use a remote Spark master. However, it works when run in local mode. More details can be found [here](http://stackoverflow.com/questions/34007259/exception-when-running-spark-job-server-in-spark-standalone-mode).

Could the documentation be extended with information on how such issues could be debugged? - eg: location of relevant log files, commonly encountered setup issues, etc.

**Comment by hntd187** [comment]
@JithinThomas there appears to be a solution in your SO question, give that a try and if you are still having issues please open a new issue. Thanks
