### ISSUE TITLE
Spark job server or Spark job hidden APIs?

### ISSUE THREAD

**Issue by mvle** [spark-jobserver/spark-jobserver#342]
Hi, 

I recently ran across this post:
http://arturmkrtchyan.com/apache-spark-hidden-rest-api

Spark apparently has REST APIs to submit and query status of jobs.
These APIs are, however, not officially documented and seem to be for some internal use.
Does anyone know anything about this and whether or not Spark's Job APIs will ever be made available? What's the relationship between the SJS APIs and Spark's hidden APIs? Should there be a push to integrate SJS into Spark's already available APIs?

**Comment by noorul** [comment]
This is already answered

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/spark-jobserver/0HSHsE0-Qa0/OestarNXBAAJ

**Comment by mvle** [comment]
Thanks for your reply.
But this question has not been answered on that post.
However, I realized that this is not a good place to ask this type of question so I'll move my question to a more appropriate place.

**Comment by velvia** [comment]
That API is for internal use only.
We tried to get SJS supported a long time ago.
