### ISSUE TITLE
Spark -jobserver  can't find the spark-assembly-1.5.0-hadoop2.4.0.jar  in yarn-client mode

### ISSUE THREAD

**Issue by jxchanghe** [spark-jobserver/spark-jobserver#346]
Hi,
 First I describe my problem.I deploy Spark-jobserver 0.6.1 in yarn-client mode by Manual Steps, and the job-server is seperated from the spark cluster, is not deployed on the same host with the RM.Strangely, when the job-server started, I post the first job  failed, jusly only the first job, and the subsequent jobs work normally. In spark cluster, find the following error info:
![yarn-error](https://cloud.githubusercontent.com/assets/4560607/11889949/cf7a0644-a589-11e5-90dc-423f128d0e02.png)

If the picture can't normally show, the text description as follows:
  Application Overview
User:	root
Name:	7edddb08-com.venustech.tsoc.cupid.demo.scala.behavior.BehaviorApp
Application Type:	SPARK
Application Tags:	
State:	FAILED
FinalStatus:	FAILED
Started:	Thu Dec 17 18:35:55 +0800 2015
Elapsed:	2sec
Tracking URL:	History
Diagnostics:	
Application application_1449914420317_0032 failed 2 times due to AM Container for appattempt_1449914420317_0032_000002 exited with exitCode: -1000
For more detailed output, check application tracking page:http://BD:8088/proxy/application_1449914420317_0032/Then, click on links to logs of each attempt.
Diagnostics: java.io.FileNotFoundException: File file:/home/jy/venus_jobserver/spark-1.5.0/lib/spark-assembly-1.5.0-hadoop2.4.0.jar does not exist
Failing this attempt. Failing the application.
Application Metrics
Total Resource Preempted:	<memory:0, vCores:0>
Total Number of Non-AM Containers Preempted:	0
Total Number of AM Containers Preempted:	0
Resource Preempted from Current Attempt:	<memory:0, vCores:0>
Number of Non-AM Containers Preempted from Current Attempt:	0
Aggregate Resource Allocation:	2094 MB-seconds, 1 vcore-seconds
ApplicationMasters
Attempt Number	Start Time	Node	Logs
1	Thu Dec 17 18:35:55 +0800 2015	BD-2:8042	logs
2	Thu Dec 17 18:35:56 +0800 2015	BD-2:8042	logs
  
    I have tried some  ways, including put the jar in a fixed location in advance, but it doesn't work still. Then I deploy the Spark-jobserver in other modes, local or standalone, the problem doesn't appear.

**Comment by yanji84** [comment]
Is the assembly jar location specified in the spark jobserver config correctly?

**Comment by velvia** [comment]
Hmm, 

The spark-assembly jar is the jar of the Spark framework itself right?

**Comment by velvia** [comment]
It looks like to me that YARN is not able to find the location of Spark itself.

**Comment by hntd187** [comment]
@yanji84 if you are still having an issue give the latest code a try and also try what velvia has suggested. If you are still having issues please open a new issue, thanks.
