### ISSUE TITLE
More structured SQL Query JSON response

### ISSUE THREAD

**Issue by jamalahmedmaaz** [spark-jobserver/spark-jobserver#347]
Hi team,

Thanks for the repository. Very helpful.

I am using jobserver to build a reporting module (Query builder). Is there a way i can get List of key values or something like  java.sql.ResultSet.

Current structure is flat without any information of what is what.

Result from an SQL on DataFrame:
{
  "result": [
    "[890629,890629,890629,Login]",
    "[891175,891175,891175,Download]",
    "[890682,890682,890682,Data Export]",
    "[891936,891936,891936,Sign UP]",
    "[889337,889337,889337,Page Click]",
    "[892384,892384,892384,Report Run]",
    "[891954,891954,891954,Upload]",
    "[889348,889348,889348,Logout]",
    "[891511,891511,891511,Data Import]",
    "[890153,890153,890153,File Share]"
  ]
}

**Comment by velvia** [comment]
Well, you have that information of which columns you are querying already in the SQL statement right?  

It’s not too hard to modify the SqlTestJob (which is just meant as an example) to return a schema as well.

You could for example change the SqlTestJob runJob method to this:

  def runJob(sql: SQLContext, config: Config): Any = {
    val query = sql.sql(config.getString("sql”))
    Map(“schema” -> query.schema.toSeq, “data” -> query.collect())
  }

However, we have to do some work to make the output more proper structured JSON first.

**Comment by jamalahmedmaaz** [comment]
Sirjee,

I am handling it at the moment in the same way. Was thinking, if we can provide a way that is standard. Will keep the consumers away from any extra work.

Agree on the "more proper structured JSON"

**Comment by velvia** [comment]
I think this should be part of feature set to provide an official SQL query job that is included with job server and provides a formal response.  We can use this ticket to debate what that JSON should look like.

**Comment by bsikander** [comment]
SparkSession was introduced in 0.8.0 and this issue should be fixed.
