### ISSUE TITLE
Adding new context (ad-hoc or named) is not atomic

### ISSUE THREAD

**Issue by velvia** [spark-jobserver/spark-jobserver#349]
Right now, in `LocalContextSupervisorActor`, and in `AkkaClusterSupervisorActor` in the soon-to-be-merged `feature/context-per-jvm` branch, there are two ways to create a new SparkContext:  `AddContext`, which adds a named context and `StartAdHocContext`.  The problem is that the code in both of these checks to see if a context with the requested name is already running, or in the ad-hoc's case, it randomly generates a name and checks if it is already taken.  However, the hashmap `contexts` is not populated until the `JobManagerActor` successfully creates a new SparkContext, which is anywhere from 5-15 seconds at least.  In the intervening 5-15 seconds, someone could re-request a new context with the same name, and job server would stupidly try to create another one, since the original one was not populated in `contexts` hashmap.

This has not really been a problem because multiple contexts were not officially supported, though they kinda work with a Spark hack.

What is now needed is the following:
1) A way to track contexts that are being created via some state;
2) Do not create contexts if they are already being created, and return an appropriate error message
3) For Ad-Hoc contexts, generate a different random name if context with previously generated name is being started
4) If the contexts being started never respond, or other error situation, remove them from the "being created" list after some timeout so that creation could be re-tried.

This needs to be done for both ad-hoc and named contexts, and both Local and AkkaCluster supervisor actors.

**Comment by bsikander** [comment]
I think this issue can be closed. Since it seems atomic now. Actor can only process 1 message at a time and AddContext synchronously launches the JVM and saves in DB. Only after this next message will be processed.

But there is one corner case, we use "tell" to save in DB. If save operation did not finish before next message is picked up, we can have 2 contexts with same name at the same time but the possibilities are rare.

@velvia @noorul should we close it?

**Comment by valan4ik** [comment]
@bsikander I checked the code and agree.

**Comment by bsikander** [comment]
Closing.
