### ISSUE TITLE
Get context information with GET /contexts/<context_id>

### ISSUE THREAD

**Issue by jamalahmedmaaz** [spark-jobserver/spark-jobserver#351]
Hi team,

I was looking for the created time with contexts call. Currently we display only the context names. Can we add context created time as-well (or this already exist).

curl  '1.1.1.1:8090/contexts/'

[abc,efg]

**Comment by velvia** [comment]
That's a good idea.  I think what we do is to have a specific route to get context info.   That would include things like creation time, status, maybe active jobs, link to Spark UI, logs, and more. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by noorul** [comment]
Are we planning to persist context? I think as of now it is not.

**Comment by velvia** [comment]
Perhaps.  Fer (@zeitos) is experimenting with it, and it is often requested feature.

-Evan

**Comment by zeitos** [comment]
@noorul what do you mean by persist a context? the context information? That's definitely something we can do.

@jamalahmedmaaz /all do we care about terminated contexts or just the ones that are currently running?

**Comment by jamalahmedmaaz** [comment]
Hi @zeitos 

Must have is the running context.

Good to have the terminated ones.

**Comment by msemelman** [comment]
+1 for get /context/<contextid>

**Comment by velvia** [comment]
Merging #387 into this ticket.

**Comment by bsikander** [comment]
This feature is already available in SJS. Closing.
