### ISSUE TITLE
Timout is working for only 40 sec.

### ISSUE THREAD

**Issue by jamalahmedmaaz** [spark-jobserver/spark-jobserver#352]
Hi team,

I am requesting something like this.

curl -d "" 'x.x.x.x:8090/jobs?appName=postgresApp&classPath=com.gainsight.LoadDataToSparkJob&context=postgres&sync=true&timeout=90'

But i get timeout after 40 sec. The exception is described below.

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   282  100    69  100   213      1      5  0:01:09  0:00:40  0:00:29     0

The server was not able to produce a timely response to your request.

Same request sometime give this output (when using 30 sec)

{
    "result": {
        "errorClass": "akka.pattern.AskTimeoutException",
        "message": "Ask timed out on [Actor[akka://JobServer/user/context-supervisor/redshift#1002214844]] after [30000 ms]",
        "stack": [
            "akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)",
            "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)",
            "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)",
            "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)",
            "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)",
            "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)",
            "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)",
            "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)",
            "java.lang.Thread.run(Thread.java:745)"
        ]
    },
    "status": "ERROR"
}

**Comment by velvia** [comment]
Hmm.  Do you have another context named redshift?

**Comment by jamalahmedmaaz** [comment]
Hi @velvia 

Was running multiple test. There were two context separately i have tested named (postgres and redshift).

I should have cleared in the description itself (different context).

**Comment by velvia** [comment]
Weird.  It’s like the two requests are getting mixed up.

If you are able, try deploying the code on latest master, which forks jvms for each context, and see if it’s better.

**Comment by jamalahmedmaaz** [comment]
Tried everything this is not working.

**Comment by jamalahmedmaaz** [comment]
Is anyone from the team looking into it. Or there is an example of configuration which deals with this.

**Comment by noorul** [comment]
Do you know that you can't have multiple contexts from single SJS on spark at the same time unless you move to master branch?

Can you let us know which version of SJS are you using? At the time of this exception do you have another context running?

**Comment by jamalahmedmaaz** [comment]
Hi @noorul 

I am creating multiple contexts from job server and i am on master branch.
**
-bash-4.2$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean**

It is happening when there are multple contexts or only single.

**Comment by hntd187** [comment]
@jamalahmedmaaz are you still having issues? Have you tried the latest code?

**Comment by noorul** [comment]
@jamalahmedmaaz Have you solved this issue?

**Comment by hntd187** [comment]
It's been almost 20 days, if you are still having issues please open up a new issue. Thanks
