### ISSUE TITLE
Proper reconnection / HA for forked JVM contexts

### ISSUE THREAD

**Issue by velvia** [spark-jobserver/spark-jobserver#353]
Right now with the JVM-per-context PR merged, here is one problem that remains.  When the forked JVM contexts are not explicitly killed, and a user runs `server_stop.sh`, then only the HTTP WebApi process is killed, not the child JVMs.  This is a problem because when the process is re-launched, it is not able to re-connect with the forked JVMs.  While the master HTTP server is down, the forked manager JVM is not able to persist status changes, because the JobDAO is only run on the HTTP server.

While we could have the forked JVMs kill themselves when the master goes down, it seems much better to be able to re-start the HTTP component and re-connect to running contexts.   Thus the goals of this issue are:
1. If the HTTP process ("master") goes down, and comes back up, it is able to discover currently running forked JVM contexts and automatically add them to the list of current contexts.  This may mean that contexts that are auto-started do not need to be started up anymore.
2. If the forked JVM process goes down, or heartbeat dies, it is properly recognized by the HTTP master and marked as down
3. If the forked JVM process goes down, and comes back up, the HTTP master recognizes it
4. When the HTTP process ("master") is down, the forked JVM contexts should still be able to update status in the DB.
5. All of the above should be testable in the regular test suite, probably using sbt-multi-jvm and the Akka clustering testing plugin.

Some implications of the above:
- Forked JVM processes must have their own JobDAO.  I would in fact eliminate the JobDAOActor.  This satisfies the ability to update when the HTTP master is down.
- Discovery of forked JVMs implies that state about existing running contexts (as well as their port #'s or Akka connection info) must be persisted somewhere.
- Need to investigate if we need to connect with just one member of the remaining cluster or how many (or all of them).

**Comment by velvia** [comment]
Reported by Nick Xie (thanks!):

I did a small set of testing.  Here are what I've found.

Methodology:

1. create two context, one is predefined in conf and the other one manually created.
2. put a bunch of jobs into non-stop loops in two script files.  The jobs are mostly spark mllib operations and reduce/group by on data from a couple of MB to 1GB.
3. run the two scripts continuously for about an hour.

Issues found:

1. after a while the predefined context died, unclear why.  The underlying yarn application seem to be gone.  But the job server is unaware and returning Akka timeout errors.   

2. While the other context is fine, the web UI show many of the jobs as STILL running when they completed long ago.  There seem to be some state update issues.

3. I manually deleting the predefined context (curl -X DELETE) and recreating it returns OK, verified that a new yarn application has been created, launch a simple job, still timeout as if the job server's states might be messed up.

4.  I ran server_stop.sh, noticed that yarn applications were left there.  I verified this a couple of time, each time after server_stop.sh are called, yarn applications were not properly removed.

5. I started server_start.sh again, the Web UI showed the last job (after context re-created) which was supposedly timeout was indeed successfully completed.

6. there was a bogus class not found error in in the spark-job-server.log, probably something messed up eventually in the context which killed the yarn application in #1.

Thanks a lot for your help.

**Comment by hntd187** [comment]
Do we want to dedicate 0.7 to the new job APIs and then take 0.8 to dedicate totally to HA and forked JVM? Or do we want to put both in the same version? They both seem like major factors on their own.

**Comment by velvia** [comment]
I think 0.7 for new API and 0.8 for HA / separate context seems more reasonable.  What do others think

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by permanentstar** [comment]
hi, does the current version 0.8.0 support reconnect/ha ?
when job-server shutdown or crash, do we have to manaully close contexts by kill the spark application(ex. on yarn)?
thanks.

**Comment by bsikander** [comment]
This feature is implemented in the latest release of jobserver. If jobserver master goes down, it can come up and reconnect to cluster using the information stored in DAO. Closing it. Please reopen if something is missing.
