### ISSUE TITLE
jobserver+mesos doesn't kill jobs

### ISSUE THREAD

**Issue by peterklipfel** [spark-jobserver/spark-jobserver#358]
Process:

Submit streaming job to spark jobserver
kill job on mesos
kill job on jobserver

Result:

Lots of errors coming out of the jobserver related to the job(s) that are supposedly dead.
Jobs that are supposedly dead continue to run

The jobs do show up in the mesos dashboard, but when the job is resubmitted, it dies instantly with no error message (that I can see/capture).

Connections from previous jobs are not cleaned up (this could be my fault for not properly cleaning up the connections)

**Comment by bsikander** [comment]
Should be fixed in 9.0.0.
