### ISSUE TITLE
[job status]Job status update failed

### ISSUE THREAD

**Issue by jeffonia** [spark-jobserver/spark-jobserver#359]
I've got a very strange problem recently, the job almost accomplished only if it updated it's status correctly. Specifically the job submitted by job-server was going to finish correctly when it's status update hung up. 
I guess something may go wrong at Akka-Actor-System. Unfortunately,  i'm a fresh-man at scala programming. Anyone have got a good idea to shoot this problem? 

PS:
1. I've change the log level into DEBUG, but i haven't got any useful info. 
2. I'm going to set the typesafe-console to monitor the message of the actor, hope it work.

**Comment by jeffonia** [comment]
Here are some snapshots:
![Uploading job-server.png…]()
![Uploading image.png…]()

spark 1.4.0  + job-server0.5.1

**Comment by velvia** [comment]
HI @jeffonia.  Hmmm.   I see you tried to upload screenshots, but I don't see anything?
So from the Spark UI, the job finished, but the job server never got the status message, is that right?

**Comment by jeffonia** [comment]
@velvia . Thanks for your attention. That's absolutely right. So i guess it's possible the actor may be crashed. Now i'm working on to prove that.

**Comment by velvia** [comment]
If you have any results from Tyrpesafe console that would be great.  I believe it is also possible to turn on actor message logging via config only.

**Comment by jeffonia** [comment]
@velvia Thanks for your tips. I'll turn on actor message logging and check it again.

**Comment by zeitos** [comment]
@jeffonia did it work? can we close this issue?

**Comment by hntd187** [comment]
This is over a month old with no response, if you still have an issue try the latest code and open a new issue thanks!
