### ISSUE TITLE
job id on UI should link to status endpoint

### ISSUE THREAD

**Issue by h0ke** [spark-jobserver/spark-jobserver#360]
On our fork at Preact, I've linked the job id to the status endpoint. Also, I've added a small link the config endpoint (see screenshot). Is this something you would be interested in? I can get the PR prepped pretty quickly.

![screen shot 2016-01-15 at 8 42 16 am](https://cloud.githubusercontent.com/assets/181554/12358860/2f1b755c-bb64-11e5-9809-b7818911120a.png)

**Comment by velvia** [comment]
Yes definitely!

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
