### ISSUE TITLE
Problem submitting multiple dependent jars

### ISSUE THREAD

**Issue by loveyanbei** [spark-jobserver/spark-jobserver#363]
I have 3 dependent jars to use a method in a.jar
a.jar depends on b.jar and c.jar
when I tried to post to:
http://localhost:8090/context/new?dependent-jars-uri=file:///path/a.jar&dependent-jars-uri=file:///path/b.jar&dependent-jars-uri=file:///path/c.jar

I got the result of NoClassDef error, noting me that jobserver cannot find the class in a.jar

Later I tried to change a.jar to the last:

http://localhost:8090/context/new?dependent-jars-uri=file:///path/c.jar&dependent-jars-uri=file:///path/b.jar&dependent-jars-uri=file:///path/a.jar

The reponse tells me that he can't find related method in b and c

Can anybody tell me how to submit deps?

**Comment by velvia** [comment]
Only the latest dependent-jar-uris (btw it’s jar-uris, not jars-uri) takes effect.  You can specify multiple URIs by comma-separating them.  So like this:

&dependent-jar-uris=file:///path/a.jar,file:///path/b.jar <file:///path/a.jar,file:///path/b.jar>

Although the better way is to use something like sbt-assembly (or maven assembly) to cobble together your dependencies.

**Comment by velvia** [comment]
Going to close this and update the README in master to make this more clear.
