### ISSUE TITLE
Enable per job dependencies management

### ISSUE THREAD

**Issue by amarouni** [spark-jobserver/spark-jobserver#364]
Currently the Spark-JobServer takes a list of dependencies per context but what about extending that to the job level where a user can do a POST request to the /jobs endpoint with a list of jars. These jars need to be made available to the Spark driver and the executors ?

**Comment by velvia** [comment]
This could work in theory, so long as the jars don’t step on each other.
We could make dependent-jar-uris or something similar available on a per job basis.

**Comment by amarouni** [comment]
In fact we did something similar :
```scala
case StartJob(appName, classPath, jobConfig, events) => {
      getSideJars(jobConfig).foreach { jarUri =>
          jarLoader.addURL(new URL(convertJarUriSparkToJava(jarUri)))
        }
      startJobInternal(appName, classPath, jobConfig, events, jobContext, sparkEnv, rddManagerActor)
    }
```
We call the same code that add jars to the context in the StartJob case.

The only issue is that you can add but cannot remove jars and as you said as long as the jars don't step on each other.
So what do you think about the code ? maybe we can do a PR.

**Comment by velvia** [comment]
Hmm.  I think this would be fine.  You are talking about being able to manage dependent jars, not the main jars, right?

What about having dependent jars use the same jar management mechanism as the main job jars?   My only concern is there would be two mechanisms.   It’s better if we can extend the main mechanism too.

**Comment by amarouni** [comment]
Yes I'm talking about dependent jars, here's an example of how we're using it : 
1- Start a context ctx01
2- upload a jar for job01 that doesn't need any dependencies and execute it on ctx01
3- upload a jar for job02 that have a runtime dependency on jar01.jar
4- execute job02 on ctx01 using something like : 
```
curl 'localhost:8090/jobs?appName=job02&classPath=MainClass&sync=true&context=ctx01' -d '{
dependent-jar-uris = "file:///jar01.jar"
}'
```
The jar01.jar in this example is present locally on the same node as SJS. This what we've done so far.
We haven't thought about a mechanism to upload these jars. We can have something like :
dependent-jar-uris : for jars already present on the SJS
dependent-jars : jars present on the client node and that should be uploaded (using the main jar upload mechanism to SJS) and made available as uris for the job execution.

**Comment by velvia** [comment]
Hold on, so job02 depends on jar01.jar, and jar01.jar is not what job01 uses?
Just making sure.

**Comment by velvia** [comment]
Yeah I think this would be welcome as a PR for sure.

**Comment by amarouni** [comment]
> Hold on, so job02 depends on jar01.jar, and jar01.jar is not what job01 uses?

Yes job02 has a runtime dependency on jar01.jar and yes jar01.jar is not a SparkJobServer job it's just a set of routines that are required by job02. 
It's not the best jar name ! Sorry for the confusion.

**Comment by amarouni** [comment]
I created a PR : https://github.com/spark-jobserver/spark-jobserver/pull/373

**Comment by velvia** [comment]
This is merged, let's close
