### ISSUE TITLE
Custom job logs listener

### ISSUE THREAD

**Issue by amarouni** [spark-jobserver/spark-jobserver#366]
Adding custom listeners for the job logs. The idea is to be able to collect the logs per job and send them back to a Kafka topic for example.

**Comment by velvia** [comment]
So the latest code on master, when you deploy it and enable context-per-jvm, will automatically put logs in separate directory for each context.  Could you just use some CLI app to watch the log files and push them into Kafka?

**Comment by amarouni** [comment]
That's an interesting Idea. I'll give that a try.

But in the long run I want to avoid writing the logs to disk then reading them back to Kafka. Streaming the logs to Kafka directly would be better when the number of simultaneous jobs running increase.

**Comment by velvia** [comment]
Agreed.  Hmm.  SJS logs just go through Spark. Could log4j be configured to write to Kafka?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by amarouni** [comment]
Thanks, I have a look at that.
