### ISSUE TITLE
OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by LHaferkamp** [spark-jobserver/spark-jobserver#367]
Currently running jobs via Spark jobserver yields OutOfMemory errors as shown below, but submitting the same job via spark-submit runs smoothly. 
Spark Monitoring tells me:
"Job aborted due to stage failure: Exception while getting task result: org.apache.spark.storage.BlockFetchException: Failed to fetch block from 1 locations."
in org.apache.spark.api.java.AbstractJavaRDDLike.mapToPair(JavaRDDLike.scala:46)
The logs show an OutOfMemory as reason:
```
16/01/18 07:53:16 WARN server.TransportChannelHandler: Exception in connection from XXXXX.org/XXX.XX.XX.XXX:47133
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:651)
	at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:237)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:215)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:132)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:271)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146)
	at io.netty.buffer.CompositeByteBuf.allocBuffer(CompositeByteBuf.java:1345)
	at io.netty.buffer.CompositeByteBuf.consolidateIfNeeded(CompositeByteBuf.java:276)
	at io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:116)
	at org.apache.spark.network.util.TransportFrameDecoder.decodeNext(TransportFrameDecoder.java:148)
	at org.apache.spark.network.util.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
16/01/18 07:53:17 ERROR scheduler.TaskSchedulerImpl: Lost executor 0 on XXXXX.org: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
```
I had this problem running Spark 1.4 and upgraded then to Spark 1.6 due to some hints to memory leaks in Netty (https://issues.apache.org/jira/browse/SPARK-8101), but the same problem still exists. 
Played also around with various memory settings and partitioning which didn't help. 
Curious why its happening only when using Spark jobserver and not at spark-submit.

**Comment by velvia** [comment]
Lars,

Which version of spark job server are you using?
Have you increased the amount of memory available to spark job server itself?

-Evan

**Comment by LHaferkamp** [comment]
In my latest tests I'm using version 0.6.2-SNAPSHOT from the master branch and upgraded the dependencies to Spark 1.6. Had the same problem also with an older Jobserver version.

In jobserver/settings.sh I configured:
`JOBSERVER_MEMORY=8G`

A job on jobserver is executed like:
`curl -v --data-binary @$JOB_CONFIG  "$JOBSERVER/jobs?appName=$APP_NAME&classPath=$CLASS_PATH"`

and the JOB_CONFIG file contains e.g. (tried different memory settings here)
```
driver-java-options = "-Xmx14G -XX:MaxDirectMemorySize=1G -XX:+UseCompressedOops"

spark.context-settings {
  spark.driver.memory = "14G"
  spark.executor.memory = "14G"
  spark.driver.maxResultSize = "14G"
}
```

**Comment by velvia** [comment]
Lars, are you deploying job server with context-per-jvm set to true?  (i.e. is a separate process spun up when you create a context / run a job?)  if so, the latest code does not pass the memory to the subprocess unfortunately, that has to be fixed.  (and will fix it very soon).  You could verify this by checking the other process with ps -ax etc.

A temporary workaround is to hack / edit bin/manager_start.sh.  Put the driver-java-options in here, or just add —driver-memory 14G, and that should do it.

**Comment by LHaferkamp** [comment]
I didn't set context-per-jvm to true and don't see a separate process, so this shouldn't be the problem.
In manager_start.sh the parameter `--driver-memory $JOBSERVER_MEMORY` with memory settings from settings.sh is already there (but couldn't find the place where manager_start.sh is called). 
I'm setting now MaxDirectMemory=1G in server_start.sh and manager_start.sh, but didn't help.

**Comment by velvia** [comment]
Hm weird.  The direct memory is usually used by executors and not the driver.  What is your master set to?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by LHaferkamp** [comment]
After carefully reading http://spark.apache.org/docs/latest/configuration.html and reducing total size of serialized results to `spark.driver.maxResultSize = "1G"` in `spark.context-settings` of job configuration it seems to be working. I'm currently checking if it remains stable.

**Comment by velvia** [comment]
Thanks for the insight.  If it remains stable, we can definitely document it.

**Comment by deenar** [comment]
I am getting the same error, when a number of concurrent jobs are submitted. The Spark documentation says the default for spark.driver.maxResultSize is  "1G" so I am not sure if that will help. I am going to try setting it explicitly anyway.

**Comment by addisonj** [comment]
I am running into this as well now after upgrading to spark 1.6.0 and running off master of SJS. This same set of jobs works fine under spark 1.4.1 and the SJS 0.6.1 tag (with some minor local changes). Looking at the code changes between it wasn't an issue running the same workload.

For me, this all is happening inside spark sql inserting into a table, so unless there are things about spark sql I don't understand, no large results sets should be being serialized. 

I will experiment around with some of the things here and report back.

**Comment by velvia** [comment]
Hi Addison,
 Try modifying the Xmx or driver-memory settings and executor memory settings in manager_start.sh.  Or the other start script.  I'm not sure the memory and core settings are being passed onto the forked JVM properly.  (Actually wait - did u enable context-per-jvm?)

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by yang0228** [comment]
Hi,

I‘m also encountering the same issue: I'm running job server on yarn. When I trigger http sql query once every time, the job server works well. If I trigger multiple queries, i saw task failed in spark dashboard and encounter this "java.lang.OutOfMemoryError: Direct buffer memory" in job server log as well, which I saw was thrown from netty, please advice : )

**Comment by velvia** [comment]
Hi guys, please update to the latest master, @addisonj pushed a patch where you can modify the MAX_DIRECT_MEM env var and increase the direct memory setting, which should fix the problem.  Thanks.

**Comment by Ahmad-Maroof** [comment]
Hi,
I am getting the same error, how can I update to latest master?

Thanks

**Comment by velvia** [comment]
You can using the latest master fix this by setting the MAX_DIRECT_MEM environment variable I think, to a higher value than the default 512m.

**Comment by jomach** [comment]
Having this error to on 1.6.2 with executors and drivers with 20G when are you doing the 0.7.0 realease with tag ?
