### ISSUE TITLE
Can‘t find dependencies  in Maven

### ISSUE THREAD

**Issue by moonlightheng** [spark-jobserver/spark-jobserver#368]
why not put the job-server-api & job-server-extras on the maven repository
In my project I want to write a job but I can not find the dependency in maven
and
here https://dl.bintray.com/spark-jobserver/maven/spark/jobserver/

I can’t find the version 0.6.1

**Comment by noorul** [comment]
Its https://dl.bintray.com/spark-jobserver/maven/spark/jobserver/

**Comment by moonlightheng** [comment]
ok in https://dl.bintray.com/spark-jobserver/maven/spark/jobserver/job-server-api_2.10/  I find it
it will be more convenient  if you put jars in maven repository

**Comment by aarthipa** [comment]
I agree. It will good to have this in maven repo.
