### ISSUE TITLE
Passing in EC2 credentials

### ISSUE THREAD

**Issue by ujjwal** [spark-jobserver/spark-jobserver#371]
What's the configuration driven way to pass in ec2 credentials to the job server? Environment variables?

```
 sc.hadoopConfiguration.set("fs.s3n.awsAccessKeyId", "redacted")
 sc.hadoopConfiguration.set("fs.s3n.awsSecretAccessKey", "redacted")
```

**Comment by velvia** [comment]
Hmmm I’m not sure, how would you set these via env variables?

**Comment by noorul** [comment]
You can pass this as a json body during POST request and can be parsed them inside the job.

**Comment by hntd187** [comment]
This should be fixed in the latest code, please give that try.
