### ISSUE TITLE
Spark JobServer JDBC-ClassNotFound error

### ISSUE THREAD

**Issue by JanJaniszewski** [spark-jobserver/spark-jobserver#372]
I have:
- Hadoop
- Spark JobServer
- SQL Database

I have created a file to access my SQL Database from a local instance of the Spark JobServer. In order to do this, I first have to load my JDBC-driver with this command: `Class.forName("com.mysql.jdbc.Driver");`. However, when I try to execute the file on Spark JobServer, I get a classNotFound error: 

    "message": "com.mysql.jdbc.Driver",
    "errorClass": "java.lang.ClassNotFoundException",

I have read that in order to load the JDBC driver, you have to change some configurations in either the application.conf file of the Spark JobServer or its server_start.sh file. I have done this as follows. In server_start.sh I have changed the cmd value which is sent with as spark-submit command:

    cmd='$SPARK_HOME/bin/spark-submit --class $MAIN --driver-memory $JOBSERVER_MEMORY
      --conf "spark.executor.extraJavaOptions=$LOGGING_OPTS spark.executor.extraClassPath = hdfs://quickstart.cloudera:8020/user/cloudera/mysql-connector-java-5.1.38-bin.jar"
      --driver-java-options "$GC_OPTS $JAVA_OPTS $LOGGING_OPTS $CONFIG_OVERRIDES"
      --driver-class-path "hdfs://quickstart.cloudera:8020/user/cloudera/mysql-connector-java-5.1.38-bin.jar"
      --jars "hdfs://quickstart.cloudera:8020/user/cloudera/mysql-connector-java-5.1.38-bin.jar"
      $@ $appdir/spark-job-server.jar $conffile'
    
I also changed some lines of the application.conf file of the Spark JobServer which is used when starting the instance:

    # JDBC driver, full classpath
    jdbc-driver = com.mysql.jdbc.Driver

    # dependent-jar-uris = ["hdfs://quickstart.cloudera:8020/user/cloudera/mysql-connector-java-5.1.38-bin.jar"]
But the error that JDBC class cannot be found still comes back.

Already checked for the following errors:

ERROR1:
In case somebody thinks that I just have the wrong file path (which could very well be the case as far as I know myself), I have checked for the correct file on HDFS with `hadoop fs -ls hdfs://quickstart.cloudera:8020/user/cloudera/` and the file was there:

    -rw-r--r--   1 cloudera cloudera     983914 2016-01-26 02:23 hdfs://quickstart.cloudera:8020/user/cloudera/mysql-connector-java-5.1.38-bin.jar

ERROR2:
I have the necessary dependency loaded in my build.sbt file: `libraryDependencies += "mysql" % "mysql-connector-java" % "5.1.+"` and the import command in my scala-file `import java.sql._`.

How can I solve this ClassNotFound error?
Are there any good alternatives to JDBC to connect to SQL?

**Comment by JanJaniszewski** [comment]
SOLUTION:
I have packaged the project using sbt assembly and it works. Still there should be a way to do it without producing an Uber-Jar

**Comment by velvia** [comment]
Hi Jan,

Glad that assembly works.   If you don’t want to produce an Auber-jar, dependent-jar-uris should work, or adding —jars (or —package) to spark-submit command.  Note that HDFS paths do not work with dependent-jar-uris though.  You want to stick to file:/ or http://.

**Comment by JanJaniszewski** [comment]
Hey.
Thanks. That was indeed the problem.
