### ISSUE TITLE
Problem with load Cassandra Table as DataFrame

### ISSUE THREAD

**Issue by michelecoppola89** [spark-jobserver/spark-jobserver#376]
hello,
I have this code where I try to load a Cassandra Table as DataFrame using spark Job Server. Here is the code:
-------------------------------------------------------------------------------------------------------------------------------
package spark.jobserver
import com.typesafe.config.{Config, ConfigFactory}
import org.apache.spark._
import scala.util.Try
import spark.jobserver.context.SQLContextFactory
import spark.jobserver._
import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.SparkConf
import com.datastax.spark.connector
import com.datastax.spark.connector._
import org.apache.spark.sql._

object CassandraExample extends SparkSqlJob {
  def main(args: Array[String]) {
    val conf = new SparkConf(true).set("spark.cassandra.connection.host", "127.0.0.1")    
    val sc = new SparkContext("local", "CassandraExample", conf)
    val sql = new org.apache.spark.sql.SQLContext(sc)
    val config = ConfigFactory.parseString("")
    val results = runJob(sql, config)
    println("Result is " + results)
  }

  def validate(sql: SQLContext, config: Config): SparkJobValidation = SparkJobValid  
  def runJob(sql: SQLContext, config: Config): Any = {
    val df = sql.read.format("org.apache.spark.sql.cassandra").options(Map( "table" -> "measurement", "keyspace" -> "mykeyspace" )).load()
    df.describe()
  }
}
-------------------------------------------------------------------------------------------------------------------------------
and here are dependencies in my build.sbt:

-------------------------------------------------------------------------------------------------------------------------------
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.5.1" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "1.5.1" % "provided"
libraryDependencies += "com.datastax.spark" %% "spark-cassandra-connector" % "1.5.0-M2" % "provided"

resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"
libraryDependencies += "spark.jobserver" %% "job-server-api" % "0.6.1" % "provided"
libraryDependencies += "spark.jobserver" %% "job-server-extras" % "0.6.1" % "provided"
-------------------------------------------------------------------------------------------------------------------------------

I created the fat jar using sbt assembly and submitted it to spark job server using the following command:

curl -data-binary @/home/michele/Storage/Magistrale/Tesi/Spark_Cassandra/Esempi/cassandra_jobserver/target/scala-2.10/cassandra.jar localhost:8090/jars/cassandra_v3

When i tried to run this job with the command:

curl -d "" 'localhost:8090/jobs?appName=cassandra_v2&classPath=spark.jobserver.CassandraExample&sync=true'

I got the following response:

{
  "status": "ERROR",
  "result": "Invalid job type for this context"
}

I can't resolve the problem. 

someone can tell me where I'm wrong?

**Comment by noorul** [comment]
Is there any error in spark-jobserver.log? If so post that too.

**Comment by velvia** [comment]
Hi Michelle,

You need to specify the SQLContextFactory, then it will work.  See the contexts.md in doc folder for examples.  Best of luck...

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by michelecoppola89** [comment]
Hello,

thank you for suggestion. I resolved the problem creating a sql context using the following command:

curl-d "" '127.0.0.1:8090/contexts/sql_context?context-factory=spark.jobserver.context.SQLContextFactory&spark.cassandra.connection.host=localhost'


Best regards

**Comment by velvia** [comment]
@michelecoppola89 glad u got it working!
