### ISSUE TITLE
spark.jobserver.auth hasPermission

### ISSUE THREAD

**Issue by jdavidmitchell** [spark-jobserver/spark-jobserver#377]
In the AuthInfo class (spark.jobserver.auth), the hasPermission method is empty. There is a comment that states "all authenticated users can perform all actions."

The AuthInfo class takes a "User" (or user name) as input.  Would it be good idea to create a pull request to add code to group users by roll and to grant permission by role?  What would be the best way to do this?

**Comment by velvia** [comment]
+cc @TimMaltGermany @koettert  Would you guys be able to answer this question?  I believe @TimMaltGermany wrote the auth code?

**Comment by velvia** [comment]
It would be awesome to have this feature of role permissions btw.   I’m not sure about configuration though, if there are any standards for that in Shiro for role permissions, then we should stick to that.

**Comment by TimMaltGermany** [comment]
Hi, a PR sounds like an excellent idea. I never got around to implementing the permissions stuff. I think the Shiro website has some nice examples on how to handle this.
