### ISSUE TITLE
job server stucked after serving some concurrent request

### ISSUE THREAD

**Issue by sandy724** [spark-jobserver/spark-jobserver#379]
I have setup the job server on the EMR with spark cluster. after serving some request it get stuck. it shows job is running for 4 to 5 hours.

**Comment by noorul** [comment]
Is there something in spark-jobserver.log ?

**Comment by velvia** [comment]
and did the job finish in Spark UI?  Are you able to get the results from job server API?

**Comment by sandy724** [comment]
sorry for late response
There is nothing in logs.
Job is not finishing in Spark UI but I am able to get results from API.
So if there are multiple request on the job server, as there are already running jobs, as a result of which it consumes more memory and then all further jobs are deadlocked.

**Comment by velvia** [comment]
As a workaround are you able to delete the jobs (DELETE jobs/jobid). Or in the worst case shut down the context?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by sandy724** [comment]
can you guide me through the best practices to setup job server on EMR Cluster with spark

**Comment by sandy724** [comment]
how to implement job and jar persistent

**Comment by velvia** [comment]
EMR instructions are here:
https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/EMR.md <https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/EMR.md>

Job and jar persistence: I would recommend we discuss this on the mailing list instead.  What are your requirements?    The job jar is persisted by Job Server in a  database when you POST it.   If you are talking about persistence of state in your job, that is probably outside of our scope.

-Evan

**Comment by sandy724** [comment]
Need to discuss about Job and jar info is persisted via a pluggable DAO interface

**Comment by hntd187** [comment]
@sandy724 I don't believe we support what you are looking for if i understood you correctly. Since this issue doesn't have much movement I am closing this.
