### ISSUE TITLE
Unable to use yarn-client as master

### ISSUE THREAD

**Issue by chrismcbride** [spark-jobserver/spark-jobserver#38]
Setting master to 'yarn-client' in the config results in this error during startup:

2015-01-05 22:06:55,765 ERROR [JobServer-akka.actor.default-dispatcher-5] actor.OneForOneStrategy (Slf4jLogger.scala:apply$mcV$sp(66)) - exception during creation
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:218)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:425)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
	at akka.dispatch.Mailbox.run(Mailbox.scala:218)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at akka.util.Reflect$.instantiate(Reflect.scala:65)
	at akka.actor.Props.newActor(Props.scala:337)
	at akka.actor.ActorCell.newActor(ActorCell.scala:534)
	at akka.actor.ActorCell.create(ActorCell.scala:560)
	... 9 more
Caused by: java.lang.RuntimeException: Could not parse Master URL: 'yarn-client'
	at spark.jobserver.SparkWebUiActor.getSparkHostName(SparkWebUiActor.scala:85)
	at spark.jobserver.SparkWebUiActor.<init>(SparkWebUiActor.scala:40)
	... 17 more

**Comment by velvia** [comment]
How are you setting the config, and are you using latest master or which
version?  There is code in the latest master which will not spin up the
SparkWebUiActor if your master is set to yarn-client.

On Mon, Jan 5, 2015 at 2:08 PM, chrismcbride <notifications@github.com>
wrote:

> Setting master to 'yarn-client' in the config results in this error during
> startup:
>
> 2015-01-05 22:06:55,765 ERROR [JobServer-akka.actor.default-dispatcher-5]
> actor.OneForOneStrategy (Slf4jLogger.scala:apply$mcV$sp(66)) - exception
> during creation
> akka.actor.ActorInitializationException: exception during creation
> at akka.actor.ActorInitializationException$.apply(Actor.scala:218)
> at akka.actor.ActorCell.create(ActorCell.scala:578)
> at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:425)
> at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
> at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
> at akka.dispatch.Mailbox.run(Mailbox.scala:218)
> at
> akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
> at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> at
> scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> at
> scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> Caused by: java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at
> sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
> at
> sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
> at akka.util.Reflect$.instantiate(Reflect.scala:65)
> at akka.actor.Props.newActor(Props.scala:337)
> at akka.actor.ActorCell.newActor(ActorCell.scala:534)
> at akka.actor.ActorCell.create(ActorCell.scala:560)
> ... 9 more
> Caused by: java.lang.RuntimeException: Could not parse Master URL:
> 'yarn-client'
> at
> spark.jobserver.SparkWebUiActor.getSparkHostName(SparkWebUiActor.scala:85)
> at spark.jobserver.SparkWebUiActor.(SparkWebUiActor.scala:40)
> ... 17 more
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/38>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by chrismcbride** [comment]
I'm using 0.4.1 because thats the latest on http://dl.bintray.com/spark-jobserver/maven as far as I can tell.

**Comment by velvia** [comment]
Looks like the fix was merged 10 days after 0.4.1 was released.

commit 0db8b41aeb829e8300bb74f572a2b4bb318d0d7a
Author: David Resnick <abunetta@gmail.com>
Date:   Mon Nov 24 15:39:32 2014 +0200

    Fix finding Spark UI when running on Mesos.

    Spark UI is on localhost when spark.master is set to a mesos URL.


Would you be able to run off of master for a while?   We plan to release
Spark 1.2 support soon.

On Fri, Jan 9, 2015 at 10:42 AM, chrismcbride <notifications@github.com>
wrote:

> I'm using 0.4.1 because thats the latest on
> http://dl.bintray.com/spark-jobserver/maven as far as I can tell.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/38#issuecomment-69378538>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by curran** [comment]
I am also not able to use yarn-client mode. I set `master = "yarn-client"` in `config/local.conf`, then launched the server with `reStart config/local.conf`.

The jobserver accepted the example jar with `curl -data-binary @job-server-tests/target/job-server-tests-0.5.0.jar localhost:8090/jars/test`, but when I try to run the example I get the following error:

```
$ curl d "input.string = a b c a b see" 'localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample''

{ "status": "ERROR", "result": { "errorClass": "java.lang.RuntimeException", "cause": null, "stack":
["org.apache.spark.util.Utils$.getSparkOrYarnConfig(Utils.scala:1784)",
"org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:105)",
"org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:180)",
"org.apache.spark.SparkEnv$.create(SparkEnv.scala:292)",
"org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:159)",
"org.apache.spark.SparkContext.<init>(SparkContext.scala:232)",
"spark.jobserver.context.DefaultSparkContextFactory$$anon$1.<init>(SparkContextFactory.scala:41)",
"spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:41)",
"spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:34)",
"spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:261)",
"spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:104)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)",
"ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)",
"ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)",
"ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)",
"ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)",
"scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)",
"ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)",
"akka.actor.Actor$class.aroundReceive(Actor.scala:465)",
"ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)",
"akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)",
"akka.actor.ActorCell.invoke(ActorCell.scala:487)",
"akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)",
"akka.dispatch.Mailbox.run(Mailbox.scala:220)",
"akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)",
"scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)",
"scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)",
"scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)",
"scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"],
"causingClass": "java.lang.ExceptionInInitializerError", "message":
"java.lang.ExceptionInInitializerError" } }
```
The Word Count example works for me when `master = "local[4]"`, but gives this error when `master = "yarn-client"`.

I have the following environment variables set, but I'm not sure which are being used by spark-jobserver: HADOOP_CONF_DIR, YARN_CONF_DIR, SPARK_HOME, SPARK_CONF_DIR. I am on a Mac, using Apache Hadoop-2.6.0 and Spark-1.2.1.

Any ideas on what is causing this error, or advice for what to try next? Thank you.

**Comment by velvia** [comment]
Been a long time, there are now `yarn.md` tips in the doc section, try it now.
