### ISSUE TITLE
Jobserver sends private IP to the spark master instead of public IP

### ISSUE THREAD

**Issue by SergeiSidorov** [spark-jobserver/spark-jobserver#382]
Hi all,

I use spark cluster in the standalone mode. I installed spark cluster on the Amazon AWS
And deployed Jobserver NOT on the Amazon AWS (in the different networks). 

When I try to create spark context using following command 
curl -X POST '***host:8090/contexts/cfspark-context'
I will get following exception in the jobserver log 
"The server was not able to produce a timely response to your request.root@ubuntu"
Also I got following error in the Spark Master log (that deployed in the Amazon AWS)"
16/02/08 08:55:56 ERROR ErrorMonitor: dropping message [class akka.actor.ActorSelectionMessage] for non-local recipient [Actor[akka.tcp://sparkMaster@aws-public-ip:7077/]] arriving at [akka.tcp://sparkMaster@aws-public-ip:7077] inbound addresses are [akka.tcp://sparkMaster@aws-private-ip:7077]
akka.event.Logging$Error$NoCause$
16/02/08 08:56:16 INFO Master: privite-ip:35942 got disassociated, removing it.
16/02/08 08:56:16 INFO Master: privite-ip:35942 got disassociated, removing it.
16/02/08 08:56:16 WARN ReliableDeliverySupervisor: Association with remote system [akka.tcp://sparkDriver@privite-ip:35942] has failed, address is now gated for [5000] ms. Reason: [Disassociated]"

As I mentioned above spark master and jobserver is deployed in the different networks
And spark master can't send response to the jobserver using private IP

I tried to deploy Jobserver in the Amazon AWS and all worked good 
Because Jobserver and spark master were in the same network
And spark master can send response to the jobserver using private IP
But it doesn't work in the different networks. 

How to tune Jobserver, that jobserver sends public IP to the spark master instead of public IP?

**Comment by noorul** [comment]
I think it is the reverse communication that is causing the problem. To which IP does DNS resolve for the spark-jobserver hostname from spark nodes?

**Comment by noorul** [comment]
Closing this because of less activity. Please feel free to re-open
