### ISSUE TITLE
Does "namedObjects" work for consecutive jobs?

### ISSUE THREAD

**Issue by e-** [spark-jobserver/spark-jobserver#386]
Hello, I am using the master repo with Spark 1.6.0.

I created two jobs with `NamedObjectSupport`: one for registering a dataframe as `my_df` and the other for retrieving the registered dataframe. Both jobs return `this.namedObjects.getNames()` as a result.

When I ran two jobs consecutively on the same context, the first job successfully registered the dataframe and returned `set(my_df)` but the second job returned an empty set `set()`. It seems that the dataframe is no longer maintained after the first job where the dataframe was registered. Is this an expected behavior? I set `forceComputation=true` and `storageLevel=StorageLevel.MEMORY_ONLY` in the first job.

**Comment by velvia** [comment]
Hmm, we’ll have to investigate this…. /cc @TimMaltGermany

**Comment by TimMaltGermany** [comment]
Interesting. I will investigate. Would it be possible that you attach your code?

**Comment by TimMaltGermany** [comment]
hmm, it appears that this really does not work....
I have written some tests that fail.
Even, it appears that the JobManagerActor always sets the NamedObject reference anew in line 250 of the JobManagerActor.  Could you please have a look ?
I will email you my test classes...

**Comment by e-** [comment]
Thank you for the reply.

I wrote two very simple spark jobs as follows (only `runJob` method is attached):

### Job 1 (registers a named dataframe)

```scala
override def runJob(sc: SparkContext, config: Config): Any = {
    val df = ... // load a dataframe
    val ndf = NamedDataFrame(df, true, StorageLevel.MEMORY_ONLY);
    this.namedObjects.update("my_df", ndf);
    return this.namedObjects.getNames();
}
```

### Job 2 (checks whether the dataframe is available)

```scala
override def runJob(sc: SparkContext, config: Config): Any = {    
    return this.namedObjects.getNames();
}
```

Then, I ran the first job and the second job consecutively in the same context. The first job returned the name of the dataframe correctly (`set(my_df)`) while the second job returned an empty set (`set()`).

**Comment by velvia** [comment]
@TimMaltGermany I think I understand why this fails.  It's actually really obvious if you just stare at the code in `JobManagerActor`.... you are right that it is creating a new `JobServerNamedObjects` class every time.  In the original code, this was not a problem because `JobServerNamedRdds` just wrapped around an actor that held the actual state.  However, now `JobServerNamedObjects` contains the cache, so the cache is created anew every single time for each new job.

The short term solution is to have each JobManagerActor actually hold an instance of the JobServerNamedObjects.    I'll open a PR with a test to fix this.

However, I'd like to take this opportunity to change the API a bit.  Instead of having each user mix in NamedObjectsSupport, I think we should be able to pass in something like a `RuntimeContext` to each job, which gives access to things like job ID, context info, named objects, context configuration, and lots of other things.

**Comment by tverbeiren** [comment]
I stumbled upon the same issue today. As a temporary workaround, the following works for me.

In Job 2, refer to the _object_ created in Job 1 rather than `this`. Say Job 1 is called `Job1`, then this works in the scope of `Job2`:

```
override def runJob(sc: SparkContext, config: Config): Any = {    
    return Job1.namedObjects.getNames();
}
```

**Comment by TimMaltGermany** [comment]
Yeah, sorry. I created a PR that should fix the problem (without the API changes suggested by @velvia)

**Comment by CBribiescas** [comment]
Is this in?  I'm having the same issue.  Here is my sample code

`
import com.typesafe.config.{ConfigFactory, Config}
import org.apache.spark.{SparkConf, SparkContext}
import spark.jobserver.{SparkJobValid, SparkJobValidation, NamedRddSupport, SparkJob}

/**
  * Created by carbribi on 3/7/16.
  */
object CreateJob extends SparkJob with NamedRddSupport {
  
  override def runJob(sc: SparkContext, jobConfig: Config): Any = {
    val rddName = "data"
    val savedRdd = this.namedRdds.get[Int](rddName)
    if (savedRdd.isDefined){
      return savedRdd.get
    }else{
      val data = Array(1, 2, 3, 4, 5)
      val distData = sc.parallelize(data)
      this.namedRdds.update(rddName,distData)
      return distData
    }
  }
  
  override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
    return SparkJobValid
  }
}
`

**Comment by CBribiescas** [comment]
Is this in?  I'm having the same issue.  Here is my code

```
import com.typesafe.config.{ConfigFactory, Config}
import org.apache.spark.{SparkConf, SparkContext}
import spark.jobserver.{SparkJobValid, SparkJobValidation, NamedRddSupport, SparkJob}

/**
  * Created by carbribi on 3/7/16.
  */
object CreateJob extends SparkJob with NamedRddSupport {
  
  override def runJob(sc: SparkContext, jobConfig: Config): Any = {
    val rddName = "data"
    val savedRdd = this.namedRdds.get[Int](rddName)
    if (savedRdd.isDefined){
      return savedRdd.get
    }else{
      val data = Array(1, 2, 3, 4, 5)
      val distData = sc.parallelize(data)
      this.namedRdds.update(rddName,distData)
      return distData
    }
  }
  
  override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
    return SparkJobValid
  }
}
```

**Comment by velvia** [comment]
Hey everyone, the fix for this has been merged, so closing.
