### ISSUE TITLE
Spark UI Host/Port should be exposed in job/context api

### ISSUE THREAD

**Issue by drewrobb** [spark-jobserver/spark-jobserver#387]
`GET /jobs/[jobId]` should include a link to the corresponding spark UI if there is one.

**Comment by velvia** [comment]
Hmmm.  Since the Spark UI/Port is tied to a context, not a job, how about this?   `GET /contexts/<context ID>` would return details about the context.

**Comment by velvia** [comment]
@drewrobb I found another ticket similar to this, going to merge this into it.   Feel free to follow #351 thanks!

**Comment by drewrobb** [comment]
Sounds good, thanks. I think returning the information in the context data would be fine as well!
