### ISSUE TITLE
Yarn Cluster mode details step required

### ISSUE THREAD

**Issue by Velmuruganms12** [spark-jobserver/spark-jobserver#393]
I am trying to run the Spark-JobServer in Yarn cluster mode when run the server_start.sh i am getting following error. I gave my cluster master and slave url but got following error.

I am able to run it in local mode but need run it in cluster.

Please let me know the details steps for running Job Serve in Yarn cluster.

I use Cloudera 5.5.1 and spark 1.5.0

Logs :

[info] Including from cache: netty-3.8.0.Final.jar
[info] Including from cache: protobuf-java-2.5.0.jar
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[warn] Merging 'META-INF/LICENSE.txt' with strategy 'first'
[warn] Merging 'META-INF/MANIFEST.MF' with strategy 'discard'
[warn] Merging 'META-INF/NOTICE.txt' with strategy 'first'
[warn] Merging 'reference.conf' with strategy 'concat'
[warn] Strategy 'concat' was applied to a file
[warn] Strategy 'discard' was applied to a file
[warn] Strategy 'first' was applied to 2 files
[info] SHA-1: fc199848e2ab979f2562f591cfad1b20b5bf6c18
[info] Packaging /home/ubuntu/crossdata/spark-jobserver-master/job-server-extras/target/scala-2.10/spark-job-server.jar ...
[info] Done packaging.
[success] Total time: 43 s, completed Mar 7, 2016 4:56:17 PM
Permission denied (publickey).
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Permission denied (publickey).

**Comment by Velmuruganms12** [comment]
when run the ec2_deploy.sh to start the EC2 cluster getting following logs.


[info] Merging files...
[warn] Merging 'META-INF/LICENSE.txt' with strategy 'first'
[warn] Merging 'META-INF/MANIFEST.MF' with strategy 'discard'
[warn] Merging 'META-INF/NOTICE.txt' with strategy 'first'
[warn] Merging 'reference.conf' with strategy 'concat'
[warn] Strategy 'concat' was applied to a file
[warn] Strategy 'discard' was applied to a file
[warn] Strategy 'first' was applied to 2 files
[info] Assembly up to date: /home/ubuntu/crossdata/spark-jobserver-master/job-server-extras/target/scala-2.10/spark-job-server.jar
[success] Total time: 5 s, completed Mar 7, 2016 5:23:49 PM
ssh: Could not resolve hostname : Name or service not known
ssh: Could not resolve hostname : Name or service not known
ssh: Could not resolve hostname : Name or service not known
The Job Server is listening at :8090

**Comment by velvia** [comment]
Hi, for that deploy script you need to set your hostnames and username info etc. in the <environment>.sh file that you are trying to deploy to.
As an alternative you can just use the server_package.sh, which writes an installation directory to /tmp/job-server, and you can just scp that yourself to your destination hosts.

**Comment by Velmuruganms12** [comment]
Thanks for the reply.

now i ran the bin/server_package.sh and it generated the job-server.tar.gz.

In EC2 CDH cluster where in master or slave or both place, do i need unzip tar file and run start the server_start.sh for starting the sjs.

**Comment by velvia** [comment]
Yes exactly - unzip and run server start.  
Note that there is a ec2 specific guide in the docs.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by Velmuruganms12** [comment]
i followed the guide but did not help me out.

I am not able to start the server on master or slave using ec2 guide or server_start.sh.

**Comment by Velmuruganms12** [comment]
I am able to run as standalone in master but i need to run using Yarn in cluster mode. EC2 guide has broken link to githubusercontent which runs without starting the server

**Comment by Velmuruganms12** [comment]
Now I able run in local but when deployed on cluster got error SparkContext did not initialize.

I used branch created for cloudera changed spark version to 1.5.0cdh5.5.1 in dependency able to build and run in local mode.

https://github.com/bjoernlohrmann/spark-jobserver/tree/cdh-5.4

But when running on cluster :

  sudo -u spark /opt/cloudera/parcels/CDH/lib/spark/bin/spark-submit --class spark.jobserver.JobServer   --master yarn --deploy-mode cluster spark-job-server.jar local.conf



Application Logs : 

16/03/10 08:43:54 INFO slf4j.Slf4jLogger: Slf4jLogger started
16/03/10 08:43:54 INFO io.JobFileDAO: rootDir is /tmp/spark-job-server/filedao/data
16/03/10 08:43:54 INFO jobserver.JarManager: Starting actor spark.jobserver.JarManager
16/03/10 08:43:54 INFO jobserver.JobInfoActor: Starting actor spark.jobserver.JobInfoActor
16/03/10 08:43:54 INFO jobserver.LocalContextSupervisorActor: Starting actor spark.jobserver.LocalContextSupervisorActor
16/03/10 08:43:54 INFO jobserver.DataManagerActor: Starting actor spark.jobserver.DataManagerActor
16/03/10 08:43:54 INFO jobserver.JobResultActor: Starting actor spark.jobserver.JobResultActor
16/03/10 08:43:54 INFO jobserver.WebApi: No authentication.
16/03/10 08:43:54 INFO jobserver.WebApi: Starting browser web service...
16/03/10 08:43:54 INFO yarn.ApplicationMaster: Final app status: SUCCEEDED, exitCode: 0
16/03/10 08:43:55 INFO server.HttpListener: Bound to /0.0.0.0:8090
16/03/10 08:44:03 ERROR yarn.ApplicationMaster: SparkContext did not initialize after waiting for 100000 ms. Please check earlier log output for errors. Failing the application.
16/03/10 08:44:03 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with SUCCEEDED
16/03/10 08:44:03 INFO yarn.ApplicationMaster: Deleting staging directory .sparkStaging/application_1457581667246_0025
16/03/10 08:44:03 INFO util.ShutdownHookManager: Shutdown hook called

Log Type: stdout
Log Upload Time: Thu Mar 10 08:44:19 +0000 2016
Log Length: 0
