### ISSUE TITLE
problem in starting spark-jobserver using yarn client 

### ISSUE THREAD

**Issue by Velmuruganms12** [spark-jobserver/spark-jobserver#396]
installed spark jobserver on master node and started the server but its getting terminated without any error. 

How can we start the spark Job server on the yarn client mode and I need to my application to reuse the named RDD.

local.conf

#Template for a Spark Job Server configuration file
# When deployed these settings are loaded when job server starts
#
# Spark Cluster / Job Server configuration
spark {
  # spark.master will be passed to each job's JobContext
  #master = "local[4]"
  # master = "mesos://vm28-hulk-pub:5050"
   master = "yarn-client"

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 4

  jobserver {
    port = 8090
    jar-store-rootdir = /tmp/jobserver/jars

    context-per-jvm = true

    jobdao = spark.jobserver.io.JobFileDAO

    filedao {
      rootdir = /tmp/spark-job-server/filedao/data
    }
  }

  # predefined Spark contexts
  # contexts {
  #   my-low-latency-context {
  #     num-cpu-cores = 1           # Number of cores to allocate.  Required.
  #     memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
  #   }
  #   # define additional contexts here
  # }

  # universal context configuration.  These settings can be overridden, see README.md
  context-settings {

spark.driver.port = 32456 # important
spark.yarn.jar = "/opt/cloudera/parcels/CDH/lib/spark/assembly/lib/spark-assembly-1.5.0-cdh5.5.1-hadoop2.6.0-cdh5.5.1.jar"

num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

    # in case spark distribution should be accessed from HDFS (as opposed to being installed on every mesos slave)
    # spark.executor.uri = "hdfs://namenode:8020/apps/spark/spark.tgz"

Logs :

ubuntu@ip-172-31-14-212:~/spark-jobserver-master/bin$ ./server_start.sh job-server-tests_2.10-0.6.2-SNAPSHOT.jar
LOG_DIR empty; logging will go to /tmp/job-server
./server_start.sh: line 41: kill: (19069) - No such process
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p0.11/jars/avro-tools-1.7.6-cdh5.5.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p0.11/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
16/03/09 12:46:35 INFO RMProxy: Connecting to ResourceManager at ip-172-31-14-212.us-west-1.compute.internal/172.31.14.212:8032
16/03/09 12:46:35 INFO Client: Requesting a new application from cluster with 2 NodeManagers
16/03/09 12:46:35 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (16384 MB per container)
16/03/09 12:46:35 INFO Client: Will allocate AM container, with 1408 MB memory including 384 MB overhead
16/03/09 12:46:35 INFO Client: Setting up container launch context for our AM
16/03/09 12:46:35 INFO Client: Setting up the launch environment for our AM container
16/03/09 12:46:35 INFO Client: Preparing resources for our AM container
16/03/09 12:46:36 INFO Client: Uploading resource file:/home/ubuntu/spark-jobserver-master/bin/job-server-tests_2.10-0.6.2-SNAPSHOT.jar -> hdfs://ip-172-31-14-212.us-west-1.compute.internal:8020/user/ubuntu/.sparkStaging/application_1457504327876_0016/job-server-tests_2.10-0.6.2-SNAPSHOT.jar
16/03/09 12:46:36 INFO Client: Uploading resource file:/tmp/spark-1d76b876-f735-4ca6-a18b-87ecf15fd1af/__spark_conf__706336806598116309.zip -> hdfs://ip-172-31-14-212.us-west-1.compute.internal:8020/user/ubuntu/.sparkStaging/application_1457504327876_0016/__spark_conf__706336806598116309.zip
16/03/09 12:46:36 INFO SecurityManager: Changing view acls to: ubuntu
16/03/09 12:46:36 INFO SecurityManager: Changing modify acls to: ubuntu
16/03/09 12:46:36 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(ubuntu); users with modify permissions: Set(ubuntu)
16/03/09 12:46:37 INFO Client: Submitting application 16 to ResourceManager
16/03/09 12:46:37 INFO YarnClientImpl: Submitted application application_1457504327876_0016
16/03/09 12:46:38 INFO Client: Application report for application_1457504327876_0016 (state: ACCEPTED)
16/03/09 12:46:38 INFO Client:
         client token: N/A
         diagnostics: N/A
         ApplicationMaster host: N/A
         ApplicationMaster RPC port: -1
         queue: root.ubuntu
         start time: 1457527597073
         final status: UNDEFINED
         tracking URL: http://ip-172-31-14-212.us-west-1.compute.internal:8088/proxy/application_1457504327876_0016/
         user: ubuntu
16/03/09 12:46:39 INFO Client: Application report for application_1457504327876_0016 (state: ACCEPTED)
16/03/09 12:46:40 INFO Client: Application report for application_1457504327876_0016 (state: ACCEPTED)
16/03/09 12:46:41 INFO Client: Application report for application_1457504327876_0016 (state: ACCEPTED)
16/03/09 12:46:42 INFO Client: Application report for application_1457504327876_0016 (state: ACCEPTED)
16/03/09 12:46:43 INFO Client: Application report for application_145
Exit code: 10
Stack trace: ExitCodeException exitCode=10:
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:543)
        at org.apache.hadoop.util.Shell.run(Shell.java:460)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:720)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:210)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Container exited with a non-zero exit code 10
Failing this attempt. Failing the application.
         ApplicationMaster host: N/A
         ApplicationMaster RPC port: -1
         queue: root.ubuntu
         start time: 1457527597073
         final status: FAILED
         tracking URL: http://ip-172-31-14-212.us-west-1.compute.internal:8088/cluster/app/application_1457504327876_0016
         user: ubuntu
Exception in thread "main" org.apache.spark.SparkException: Application application_1457504327876_0016 finished with failed status
        at org.apache.spark.deploy.yarn.Client.run(Client.scala:927)
        at org.apache.spark.deploy.yarn.Client$.main(Client.scala:973)
        at org.apache.spark.deploy.yarn.Client.main(Client.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Log generated in yarn logs jobhistory details :

Log Type: stderr
Log Upload Time: Wed Mar 09 12:46:46 +0000 2016
Log Length: 516
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p0.11/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p0.11/jars/avro-tools-1.7.6-cdh5.5.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

Log Type: stdout
Log Upload Time: Wed Mar 09 12:46:46 +0000 2016
Log Length: 0

**Comment by velvia** [comment]
You might need to modify server_start.sh to pass in —master yarn-client.   In the future we should have the start script recognize your setting in the config, but it doesn’t do that yet.

-Evan

**Comment by Velmuruganms12** [comment]
Now I able run in local but when deployed on cluster got error SparkContext did not initialize.

I used branch created for cloudera changed spark version to 1.5.0cdh5.5.1 in dependency able to build and run in local mode.

https://github.com/bjoernlohrmann/spark-jobserver/tree/cdh-5.4

But when running on cluster :

  sudo -u spark /opt/cloudera/parcels/CDH/lib/spark/bin/spark-submit --class spark.jobserver.JobServer   --master yarn --deploy-mode cluster spark-job-server.jar local.conf



Application Logs : 

16/03/10 08:43:54 INFO slf4j.Slf4jLogger: Slf4jLogger started
16/03/10 08:43:54 INFO io.JobFileDAO: rootDir is /tmp/spark-job-server/filedao/data
16/03/10 08:43:54 INFO jobserver.JarManager: Starting actor spark.jobserver.JarManager
16/03/10 08:43:54 INFO jobserver.JobInfoActor: Starting actor spark.jobserver.JobInfoActor
16/03/10 08:43:54 INFO jobserver.LocalContextSupervisorActor: Starting actor spark.jobserver.LocalContextSupervisorActor
16/03/10 08:43:54 INFO jobserver.DataManagerActor: Starting actor spark.jobserver.DataManagerActor
16/03/10 08:43:54 INFO jobserver.JobResultActor: Starting actor spark.jobserver.JobResultActor
16/03/10 08:43:54 INFO jobserver.WebApi: No authentication.
16/03/10 08:43:54 INFO jobserver.WebApi: Starting browser web service...
16/03/10 08:43:54 INFO yarn.ApplicationMaster: Final app status: SUCCEEDED, exitCode: 0
16/03/10 08:43:55 INFO server.HttpListener: Bound to /0.0.0.0:8090
16/03/10 08:44:03 ERROR yarn.ApplicationMaster: SparkContext did not initialize after waiting for 100000 ms. Please check earlier log output for errors. Failing the application.
16/03/10 08:44:03 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with SUCCEEDED
16/03/10 08:44:03 INFO yarn.ApplicationMaster: Deleting staging directory .sparkStaging/application_1457581667246_0025
16/03/10 08:44:03 INFO util.ShutdownHookManager: Shutdown hook called

Log Type: stdout
Log Upload Time: Thu Mar 10 08:44:19 +0000 2016
Log Length: 0

**Comment by Velmuruganms12** [comment]
At-last  able to start the Spark JobServer using following command, now its running in yarn client mode.

spark-submit --class spark.jobserver.JobServer --master local $@ spark-job-server.jar local.conf


local.conf

# Template for a Spark Job Server configuration file
# When deployed these settings are loaded when job server starts
#
# Spark Cluster / Job Server configuration
spark {
  # spark.master will be passed to each job's JobContext
 # master = "local[4]"
  # master = "mesos://vm28-hulk-pub:5050"
   master = "yarn-client"

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 4

  jobserver {
    port = 8090
    jar-store-rootdir = /tmp/jobserver/jars

    jobdao = spark.jobserver.io.JobFileDAO

    filedao {
      rootdir = /tmp/spark-job-server/filedao/data
    }
  }

  # predefined Spark contexts
   contexts {


 shared {
    num-cpu-cores = 3 # shared tasks work best in parallel.
    memory-per-node = 2608M # trial-and-error discovered memory per node
    spark.executor.instances = 12 # 4 r3.xlarge instances with 4 cores each = 16 + 1 master
    spark.scheduler.mode = "FAIR"
    #spark.scheduler.allocation.file = "/home/hadoop/spark/job-server/job_poolconfig.xml"
  }
    # my-low-latency-context {
     #  num-cpu-cores = 1           # Number of cores to allocate.  Required.
     #  memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
     #}
  #   # define additional contexts here
   }

  # universal context configuration.  These settings can be overridden, see README.md
  context-settings {
spark.driver.port = 32456 # important
spark.yarn.jar = "/opt/cloudera/parcels/CDH/lib/spark/assembly/lib/spark-assembly-1.5.0-cdh5.5.1-hadoop2.6.0-cdh5.5.1.jar"

    num-cpu-cores = 1           # Number of cores to allocate.  Required.
    memory-per-node = 2120m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

 # in case spark distribution should be accessed from HDFS (as opposed to being installed on every mesos slave)
    # spark.executor.uri = "hdfs://namenode:8020/apps/spark/spark.tgz"

    # uris of jars to be loaded into the classpath for this context. Uris is a string list, or a string separated by commas ','
    # dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]

    # If you wish to pass any settings directly to the sparkConf as-is, add them here in passthrough,
    # such as hadoop connection settings that don't use the "spark." prefix
    passthrough {
      #es.nodes = "192.1.1.1"
    }
  }

  # This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
  home = "/opt/cloudera/parcels/CDH/lib/spark/"
}

# Note that you can use this file to define settings not only for job server,
# but for your Spark jobs as well.  Spark job configuration merges with this configuration file as defaults.

**Comment by velvia** [comment]
I think —master local … so is it actually running on the cluster?

**Comment by Velmuruganms12** [comment]
yes i tried all options such as but only  local worked.

	spark-submit --class spark.jobserver.JobServer --master yarn  --deploy-mode cluster $@ spark-job-server.jar local.conf
		spark-submit --class spark.jobserver.JobServer --master yarn  --deploy-mode client $@ spark-job-server.jar local.conf
		spark-submit --class spark.jobserver.JobServer --master yarn-cluster  $@ spark-job-server.jar local.conf
		spark-submit --class spark.jobserver.JobServer --master yarn-client  $@ spark-job-server.jar local.conf
