### ISSUE TITLE
classPath not found

### ISSUE THREAD

**Issue by nvijayap** [spark-jobserver/spark-jobserver#397]
Hello,
My code used Spark SQL classes - SQLContext and DataFrame.  The resulting jar was uploaded successfully to JobServer.  But when I try to submit, I am getting this ...
`{
  "status": "ERROR",
  "result": "classPath com.abc.def.Union not found"
}`
I have chk'd the jar.  It has the class com.abc.def.Union

**Comment by noorul** [comment]
Can you describe the steps that you followed to 

1. Upload the jar
2. Run the job

**Comment by noorul** [comment]
Can you describe the steps that you followed to 

1. Upload the jar
2. Run the job

**Comment by nvijayap** [comment]
1. This is how I uploaded the jar ...
`curl -d @union.jar localhost:8090/jars/union`
2. This is how I submitted the job ...
`curl -d "input.string = abc01.parquet abc06.parquet 5" 'localhost:8090/jobs?appName=union&classPath=com.abc.def.Union'

**Comment by nvijayap** [comment]
Sorry, my mistake ; I need to use --data-binary (and not -d) to upload jar

**Comment by iamnagesh** [comment]
I'm facing a similar issue which I posted [here](https://github.com/spark-jobserver/spark-jobserver/issues/797). Please help.
