### ISSUE TITLE
spark-jobserver creating too many threads

### ISSUE THREAD

**Issue by aanastasov** [spark-jobserver/spark-jobserver#402]
We are using spark-jobserver in a setup where we have a single context, and running spark jobs against it. After running the spark-jobserver for over than 110 hours, it gets stuck and doesn't process any new requests.

After some inspection, we discovered the following. After running the spark-jobserver for about 10 hours, the number of threads that the spark-jobserver is maintaining is on the order of 22'000 for a total of about 21'000 spark jobs, all of which have finished. It seems that each job that is send to spark-jobserver creates an additional thread that is not GC-ed once the job is done. Is this expected behavior?

Initially, we thought that we should use the DELETE job call after a job finishes in order to remove the thread, but it seems that the DELETE call is only for killing jobs that are still running. Is that correct?

**Comment by velvia** [comment]
Hi there,

Thanks for the report.  No the threads should be killed off.    Unless somehow the jobs just don’t finish.    Anything more you can tell us about the setup?   

I’ve been meaning to write a stress test to test this out, this would also let folks try it out in their own environments and report what’s wrong.

-Evan

**Comment by aanastasov** [comment]
We are using Spark 1.5.2 and spark-jobserver 0.6.1.

We are using the spark-jobserver in a continuosly running setup with 20 queries per minute. We are submitting the jobs in an async mode with no timeout set. We use `POST /jobs` to start a job, and then we continuously poll for its completion with `GET /jobs/<jobId>` call. When we get a terminal result (either FINISHED or ERROR), we consider the job as finished. In an attempt to debug it, we call `DELETE /jobs/<jobId>`  after a terminal result, but we get 404 Not Found. We are positive that the spark-jobserver creates at least one thread for each submitted job.

**Comment by velvia** [comment]
Does your code use any async APIs or somehow create extra threads?

**Comment by aanastasov** [comment]
Thanks for that question. It helped us realize what was the problem.

It turns out that the thread leak is on our end -- we are creating a fixed-size thread pool whose purpose was to run two SparkJobs concurrently. However, we were not explicitly shutdowning the pool. We didn't know that the driver was running inside the spark-jobserver, and hence assumed that the leak was outside of our code. After the fix, the number of threads inside the spark-jobserver is constant.

This issue can be closed.

**Comment by velvia** [comment]
Great to hear.  SJS can run jobs in parallel btw so you don’t need to do it on your end…. maybe.   :)
