### ISSUE TITLE
Unable to start job server in Spark Cluster

### ISSUE THREAD

**Issue by franyfpk** [spark-jobserver/spark-jobserver#407]
Hi, I have got a new issue that, when i run server_start.sh the spark submit command is working and my job is getting submitted (i checked that in my spark ui (hostname:8080)) but the server is not starting up and im not able to open the SJS UI hostname:8090. Please help me on this

**Comment by velvia** [comment]
Can you share logs?   How did you verify the submit is working?

**Comment by franyfpk** [comment]
i am able to see the job running in the spark ui running in the port 8080

**Comment by velvia** [comment]
Do you have logs?

**Comment by addisonj** [comment]
Also running into this and I am pretty sure it has to do with the scala and/or spark versions you compile under.

Using the same commit, it worked fine with `SPARK_VERSION=1.4.1` and `SCALA_VERSION=2.10.4`, but seems to just never start with `SPARK_VERSION=1.6.0` and `SCALA_VERSION=2.11.8`.

The logs for when it fail to start are pretty basic:
```
[2016-03-25 19:36:16,018] INFO  spark.jobserver.JobServer$ [] [] - Starting JobServer with config {
    # system properties
   ...
}

[2016-03-25 19:39:16,370] INFO  ka.event.slf4j.Slf4jLogger [] [] - Slf4jLogger started
```
After printing out that Slf4jLogger line, it never does anything else. The process is still running and even has some CPU activity, but it never prints out the log lines indicating that the JobServer has started listening, so it seems like are getting to where the socket is attached to.

If I had to guess, I figure it probably has more to do with scala version that it does spark version, even though I compiled against 1.4.1, the provided scala libs on my cluster are 1.6.0 (and still works)

**Comment by velvia** [comment]
Hmmm.   so this only fails in scala 2.11.8?   If you compile with scala 2.10.x does it work?

**Comment by addisonj** [comment]
Correct, with 2.10.x everything is fine and dandy, even on the same commit.

I also confirmed that the spark version works with 1.6.0, so definitely seems like a scala version issue.
