### ISSUE TITLE
slow REST response in yarn-client

### ISSUE THREAD

**Issue by fwang7** [spark-jobserver/spark-jobserver#409]
It would take around 10-15s to get the response of the REST call running the job(like this:https://github.com/spark-jobserver/spark-jobserver#ad-hoc-mode---single-unrelated-jobs-transient-context) in yarn-client mode.

However,  it only takes 2-3s to get the response in standalone mode. Is it working as expected or any suggestions to resolve this issue?  

configuration reference: https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/yarn.md

**Comment by velvia** [comment]
My guess is that this has to do with YARN taking longer to spin up executors/workers.  That’s the only difference I can think of — but others with more YARN or EMR experience should comment.

If you really want lower latency, you should consider spinning up a long-lived context.

**Comment by fwang7** [comment]
Thanks, Evan!
I have another 2 issues related to this.
* I tried to use a persistent context but seems like the long-lived persistent context will be gone if I restart the SJC, how can I make persistent somewhere?
* when I created a persistent context via:
` curl -d "" 'localhost:8090/contexts/test-context?num-cpu-cores=4&memory-per-node=512m'`
I could see an application created in yarn web ui named "text-context" and it won't stop until I kill it. 

thanks,
-feng

**Comment by velvia** [comment]
Hi Feng,

Yes, persistent contexts will get restarted if you restart SJC.   The “context-per-jvm” will help with this.   If you enable this, the separate context becomes a separate JVM process, and will not be killed if the main app HTTP server is restarted - however right now they will not reconnect yet.  This is coming.

As for not stopping, how were you trying to stop the persistent context?

**Comment by fwang7** [comment]
Thanks for your **QUICK**  reply!!!

I will try enable the `context-per-jvm` to see how it goes. thanks again.

But I was confused why Yarn would treat the newly created context as an 'application' or what just happened in backend  when I create a context in SJC on Yarn? How much resources it would take? 

And also I could find the killed context 'application' from the spark history web UI.

thanks,
-feng

**Comment by fwang7** [comment]
i got it. thanks. will close this issue.
