### ISSUE TITLE
Support job cancellation via cancelJobGroup

### ISSUE THREAD

**Issue by litao-buptsse** [spark-jobserver/spark-jobserver#41]
Hi,
I notice you will support job cancellation via cancelJobGroup in the future. But In my application,  when I use this feature, it doesn't work for me. It can't cancel the running jobs.
I want to know it's my usage mistake, or there exist some bugs?

**Comment by velvia** [comment]
Hi there,

Right now you can only delete a context, which cancels all the jobs.  There
is no API to delete a specific job, which is what the cancelJobGroup will
do in the future.

Are you saying that you did -X DELETE /contexts/foo and the context does
not shut down?

-Evan


On Wed, Jan 7, 2015 at 7:56 PM, Tao Li <notifications@github.com> wrote:

> Hi,
> I notice you will support job cancellation via cancelJobGroup in the
> future. But In my application, when I use this feature, it doesn't work for
> me. It can't cancel the running jobs.
> I want to know it's my usage mistake, or there exist some bugs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/41>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by litao-buptsse** [comment]
Hi velvia:

Thanks for your reply. I met the problem when using spark core API, not your spark-jobserver in my application. But I am very interesting in your project, and we are planning to use it in the next week. Any issues, I will give you feedback immediately.

Thanks for your help again!
