### ISSUE TITLE
Need a way to determine weather a created context is still alive

### ISSUE THREAD

**Issue by yeyan** [spark-jobserver/spark-jobserver#412]
Current context api (which listed in below) does not cover the current status of a context.

GET /contexts               - lists all current contexts
POST /contexts/<name>       - creates a new context
DELETE /contexts/<name>     - stops a context and all jobs running in it
PUT /contexts?reload=reboot - kills all contexts and re-loads only the contexts from config

should we have another REST api end point
GET /contexts/<name> to describe state of a particular context? This will allow users to determine weather a context needs to be reboot or create before they submit their jobs

**Comment by velvia** [comment]
@yeyan this is a good idea, there is already another issue for it.  Please see #351, feel free to continue the discussion there.
