### ISSUE TITLE
SparkContext issue CDH5.4 version of Spark Job Server

### ISSUE THREAD

**Issue by deepakims** [spark-jobserver/spark-jobserver#414]
We have CDH 5.5 environment, we deployed CDH5,4 version of Spark Job Server (https://github.com/bjoernlohrmann/spark-jobserver/tree/cdh-5.4),  
Our cloudera is kerberos enabled, issue we are getting when creating sparkcontext, 
we tried adding keytab and  setting principal ...still no luck ... same job works with Spark Submit. 
Let me know if we need to set some configuration while creating spark context.

**Comment by zeitos** [comment]
you shouldn't... when running with spark-submit do you use any special configuration?

If so: did you add it to SJS config file (under passthrough) ?

**Comment by deepakims** [comment]
thanks for getting back. No, we are not using special configuration. Whatever configuration used in spark-submit we are setting while creating context on spark job server.

We are able to create context now, but issue now is we cannot create multiple sparkcontext, we get this error "Delegation Token can be issued only with kerberos or web authentication" when creating second sparkcontext 
Please advise.

**Comment by velvia** [comment]
You might want to try the context-per-jvm option on master.

**Comment by deepakims** [comment]
We tried it. No luck, we got same kerberos error.

**Comment by hntd187** [comment]
@deepakims any update on this?
