### ISSUE TITLE
Several problems on master branch

### ISSUE THREAD

**Issue by geoHeil** [spark-jobserver/spark-jobserver#419]
Hi,

I tried to build a docker image on master for spark 1.6.0. Several files e.g. setenv.sh seem to be missing.
`copy(baseDirectory(_ / "bin" / "setenv.sh").value, file("app/setenv.sh"))`
but it can be re-added using this. 

However, 
`copy(baseDirectory(_ / "bin" / "manager_start.sh").value, file("app/manager_start.sh"))`
 does not help with the manager script. What else is needed to successfully build for a current spark version?

**Comment by velvia** [comment]
Sorry, you’re right, will need to address this.   Those are the two main things I can think of.

**Comment by jaceklaskowski** [comment]
@geoHeil How did you build the master? I've just done it few times recently with no issues.

**Comment by geoHeil** [comment]
Indeed 

Locally it works fine. Only in the container there were these problems

**Comment by jaceklaskowski** [comment]
Can you please describe the problems in more detail? What do you mean by "only in the container"? How to reproduce your issue?

**Comment by geoHeil** [comment]
Running it locally works fine. 

When building the container initially there  was a failure until one of the start scripts was added again. Still missing is the other script called on job submission. If I re-add that as well submission of the job works but I get the java/ scala exception from above

**Comment by geoHeil** [comment]
seems to be resolved in the latest 0.6.2.** image on dockerhub @velvia pushed 2 hours ago
