### ISSUE TITLE
sql context time out thread pool error

### ISSUE THREAD

**Issue by geoHeil** [spark-jobserver/spark-jobserver#420]
Hi,

I can run the basic word-count example and it works great. However trying a little bit more advanced like:
create the sql context `curl -d "" 'localhost:8090/contexts/sql-context?context-factory=spark.jobserver.context.SQLContextFactory'` to be used later. Upload the jar and execute it:
`curl -d "sql = \"select * from addresses limit 10\"" "localhost:8090/jobs?appName=myJar&classPath=mypackage.SqlTestJob&context=sql-context&sync=true"`

The following code is run:
```
package mypackage;

import com.typesafe.config.Config
import org.apache.spark.sql.SQLContext
import spark.jobserver.{ SparkJobValid, SparkJobValidation, SparkSqlJob }

/**
 * This job simply runs the SQL in the config.
 */
object SqlTestJob extends SparkSqlJob {

  case class Address(firstName: String, lastName: String, street: String, city: String)

  def validate(sql: SQLContext, config: Config): SparkJobValidation = SparkJobValid

  def runJob(sql: SQLContext, config: Config): Any = {

    val addresses = Seq(
      Address("Bob", "Charles", "101 A St.", "San Jose"),
      Address("Sandy", "Charles", "10200 Ranch Rd.", "Purple City"),
      Address("Randy", "Charles", "101 A St.", "San Jose")
    )

    val addrDf = sql.createDataFrame(addresses)
    addrDf.count()

    //    sql.sql(config.getString("sql")).collect()
  }
}

```
But the server never returns a response (besides a timeout) and checking the logs only reveals:

```
Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$JavaMirror;
job-server-extras[ERROR]        at at.ac.tuwien.ase2016.rebeat.prototype.SqlTestJob$.runJob(SqlTestJob.scala:24)
job-server-extras[ERROR]        at at.ac.tuwien.ase2016.rebeat.prototype.SqlTestJob$.runJob(SqlTestJob.scala:10)
job-server-extras[ERROR]        at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:279)
job-server-extras[ERROR]        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server-extras[ERROR]        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server-extras[ERROR]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
job-server-extras[ERROR]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
job-server-extras[ERROR]        at java.lang.Thread.run(Thread.java:745)

```

What is wrong?
I only found the following example to start from: https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server-extras/src/spark.jobserver/SqlTestJob.scala and even that example does not work e.g. the tempTable is not found.

**Comment by geoHeil** [comment]
In fact, the package name contained some digits like `2016` and was pretty long. 

Resolution:

use just a short package name

**Comment by velvia** [comment]
Are you on Windows?  I know on certain systems the length of the paths will prevent the jar / tar archive from properly being generated.

**Comment by geoHeil** [comment]
Nope osx and windows.

Now I am stuck with the following problem: https://groups.google.com/forum/#!topic/spark-jobserver/V4finry_RoM

**Comment by ChenZhaobin** [comment]
I met with the same problem,but after I use a short package name ,it makes no different. Did you do some other changes before you make it ?
