### ISSUE TITLE
Question:How to run the spark sql example SqlTestJob? 

### ISSUE THREAD

**Issue by bigstar863** [spark-jobserver/spark-jobserver#43]
Hi,
How to run the expamle  spark-jobserver/job-server-tests/src/spark.jobserver/SqlTestJob.scala? What's the right way to start a sparksql job? I got an error when I typed  

curl -d '{"sql":"select first from addresses"}' 'localhost:8090/jobs?
appName=sqltest01&classPath=spark.jobserver.SqlTestJob&sync=true':
{
  "status": "ERROR",
  "result": "Invalid job type for this context"
} 

Please help me,
Thank you very much~~

**Comment by velvia** [comment]
Hi there,

You need to specify, when you create a context using curl -d ""
localhost:8090/contexts/foo?<params>,
in the params this:

context-factory=spark.jobserver.context.SQLContextFactory

I'll add more documentation, but basically you need to create a SQL context
first.

-Evan


On Mon, Jan 12, 2015 at 3:52 AM, bigstar863 <notifications@github.com>
wrote:

> Hi,
> How to run the expamle
> spark-jobserver/job-server-tests/src/spark.jobserver/SqlTestJob.scala?
> What's the right way to start a sparksql job? I got an error when I typed
>
> curl -d '{"sql":"select first from addresses"}' 'localhost:8090/jobs?
> appName=sqltest01&classPath=spark.jobserver.SqlTestJob&sync=true':
> {
> "status": "ERROR",
> "result": "Invalid job type for this context"
> }
>
> Please help me,
> Thank you very much~~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/43>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by aarthipa** [comment]
Here is my simple app that extends SparkHiveJob
import spark.jobserver._
import com.typesafe.config._
import spark.jobserver.SparkHiveJob
import org.apache.spark.sql.hive.HiveContext

object testSJS extends SparkHiveJob{
  override def validate(hive: HiveContext, config: Config): SparkJobValidation = SparkJobValid  
  override def runJob(hive: HiveContext, config: Config): Any = {  return "helloo SJS" }
}

And here is the curl  command that returns the same error.
