### ISSUE TITLE
Lots of dependencies are outdated - difficult to obtain

### ISSUE THREAD

**Issue by saifellafi** [spark-jobserver/spark-jobserver#431]
Hi,

I am trying to setup a jobserver here, built through SBT, but the plugin dependencies are largely outdated and very difficult to find, or moved. Is there anything that can be done or mention plugins which can be ignored/removed/updated.

Appreciated,
Saif

**Comment by velvia** [comment]
Which plugins are hard to find?

There is a PR that will update some of the plugins.  It will be merged soon.

-Evan

**Comment by hntd187** [comment]
@saifellafi I'll be overhauling a lot of the build and dependencies to bring them more up to date, but if you wanna take a portion of it that'd be very helpful

**Comment by saifellafi** [comment]
Appreciated you both and sorry of low level of explanation.

The thing is that, with restricted access to Bintray, combined to a lot of sbt dependencies being moved from typesafe / maven central plus that some of them are outdated, there is a lot of bintray internal redirection and is complicated from restricted proxy access.

Some of them also changed organization name in repo (not in package name), which also made it difficult to track manually.

Thanks!
Saif

**Comment by velvia** [comment]
Hm, ok, so you guys have trouble accessing Bintray?

**Comment by hntd187** [comment]
Is there a place we could provide built distributions for people? That way, people could just download those instead of having to build from source. I don't know of any off the top of my head, but providing something like that otherwise might be expensive.

**Comment by velvia** [comment]
If there is, let me know  :)

I suppose we could stick binaries up on Bintray.  There is another service that I heard about.  Problem with Bintray is a 500MB limit.   I suppose Maven Central is possible too.

-Evan

**Comment by saifellafi** [comment]
From my workplace, there is an internal repository that does some fetching to bintray remotely, but bintray is a mess right now, it has different internal redirections, for example they have a repo for sbt plugins here: http://dl.bintray.com/content/sbt/sbt-plugin-releases

but if you use the standard search from their web pages, you are probably not going to find that internal sbt-plugin-releases packages (e.g. try looking for bintray-sbt or sbt-release in bintray.com).

Also, I am not really sure of the benefits of ls-sbt, but if instead of that having some standard sbt dependency management would help, or at least having the option to. Perhaps the dependency tree can be more light-weighted :-)

Just my two cents after spending two days trying to resolve dependencies to deploy job-server 
Regards!

**Comment by velvia** [comment]
Hi, yes I agree a standard Scala jar repo or way of finding things would be super useful.  I don’t use ls-sbt to actually find dependencies, I just go straight to each repo’s directions and add the necessary repo manually.

I’ve meant to sync job-server jars to maven central, but getting them signed again is kind of a pain.

**Comment by hntd187** [comment]
@velvia You should be able to cross list them in maven central pretty easily from bintray. I recently published something really simple in bintray and you can cross export it to maven central from there.

**Comment by jaceklaskowski** [comment]
Is this still an issue after the last changes to the dependencies?

**Comment by hntd187** [comment]
@jaceklaskowski yes, slick, yammer and spray still need to be upgraded. 

Slick should be straight forward but some work. 
Yammer is done I have it sitting in a branch already
Spray is gonna be a significant effort because akka-http is very different and apparently really slow. There are a lot of stuff out there to accomplish that but it's not a straightforward thing. So I'm fine writing it just gotta decide with what.

**Comment by velvia** [comment]
Upgrading to akka-http is not an option until Spark goes 2.0 and doesn’t have Akka as a dependency any more.   Hopefully by then it might be a bit faster.  We would also need to possibly upgrade JSON libraries by then, and I believe it is nontrivial.

**Comment by hntd187** [comment]
We could use colossus which uses a similar version of akka to spark. It's actively developed.

**Comment by velvia** [comment]
Oh yeah colossus is great.  Or Scalatra. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by hntd187** [comment]
We have some of the dependencies updated and some others waiting in pull requests, closing this for now. #453 and #449 after this I believe only dropwizard metrics remains to be upgraded.
