### ISSUE TITLE
NoClassDefFoundError for SQLContext

### ISSUE THREAD

**Issue by alek300itechla** [spark-jobserver/spark-jobserver#434]
Hi, I'm trying to implement JobServer to run my jobs, i've installed it, been able to run the WordCountExample just fine, but when running a project with an instance of SQLContext I get the Job stuck listed as a Running Job, and the following error on the server side:

```
job-server[ERROR] Exception in thread "pool-58-thread-1" java.lang.NoClassDefFoundError: org/apache/spark/sql/SQLContext
job-server[ERROR]       at spark.jobserver.TestProfile$.runJob(TestProfile.scala:61)
job-server[ERROR]       at spark.jobserver.TestProfile$.runJob(TestProfile.scala:21)
job-server[ERROR]       at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:301)
job-server[ERROR]       at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server[ERROR]       at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server[ERROR]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
job-server[ERROR]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
job-server[ERROR]       at java.lang.Thread.run(Thread.java:745)
job-server[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.SQLContext
job-server[ERROR]       at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
job-server[ERROR]       at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
job-server[ERROR]       at java.security.AccessController.doPrivileged(Native Method)
job-server[ERROR]       at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
job-server[ERROR]       at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
job-server[ERROR]       at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
job-server[ERROR]       ... 8 more
```

and this is my sbt file:
```
organization := "com.test"

name := "TestProfile"

version := "1.0"

scalaVersion := "2.10.5"

resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"

libraryDependencies += "spark.jobserver" %% "job-server-api" % "0.6.1" % "provided"

libraryDependencies += "spark.jobserver" %% "job-server-extras" % "0.6.1" % "provided"

libraryDependencies += "org.apache.spark" %% "spark-core" % "1.6.0"

libraryDependencies += "org.apache.spark" %% "spark-sql" % "1.6.0"
```

any pointers on how to solve this will be greatly appreciated as I'm stuck on trying to deploy this.

Thanks!

**Comment by hntd187** [comment]
Chances are good since you are listing the job server dependencies first the  fact they list spark as provided is being overridden by your spark dependencies. Switch them so spark is first, if that doesn't help then check the managed classpath

**Comment by velvia** [comment]
I would also make your spark dependencies in your job as “provided”.

If someone can help create a sample project repo, I’d be happy to let you own and manage it on the official spark-observer github organization.  :)   I’ve been meaning to do this for a while, but just haven’t had the time.

**Comment by alek300itechla** [comment]
Hey guys, thank you for the quick response, I'm fairly new in both spark and using the job server. I really have no idea what's happening here, I followed the advice and reversed the order of the dependencies, that seemed to work for a little bit, until I had to restart my server, and then the error started showing up again and at this point I'm unsure on what to do as the build.sbt seems correct and the error is showing up again, could it be some setting?. I'm not sure what **hntd187** meant by check the managed classpath so unsure on what to try there.

Also while i was able to get rid of the error I was running into another error ( I'm using mssql jdbc driver ) of ClassNotFound for the driver. I added the jdbc driver Jar trough the --jars of spark-submit in the server-start.sh but it didn't make a difference, am I missing anything else to have the jdbc dependency working?

Thank you all!

**Comment by velvia** [comment]
I think what he means is to check the Spark UI.   Usually if no other app is running you can find it at port 4040.   Go to the environment tab and you will see bottom section a list of all jars in the class path.

**Comment by hntd187** [comment]
@alek300itechla is there any update on this are you still having issues?

**Comment by noorul** [comment]
@alek300itechla Its been a while. Closing this. Please feel free to re-open this.
