### ISSUE TITLE
[Java] validate(): SparkJobValid is not implementing SparkJobValidation

### ISSUE THREAD

**Issue by d-ee** [spark-jobserver/spark-jobserver#436]
SJS 0.6.1

`SparkJobValidation validate(SparkContext sc, Config jobConfig)` can not return `SparkJobValid` as it does not qualify as being of type `SparkJobValidation`.

`Type mismatch: cannot convert from Class<SparkJobValid> to SparkJobValidation`

It is therefore not possible to have a `validate()`-method as it is not possible to return a valid object and returning `null` results in a `"errorClass": "scala.MatchError"`.

As implementing `SparkJob` or `SparkSqlJob`, being subclasses of `SparkJobBase`, brings in the two abstract methods
`Object SparkJobBase.runJob(Object, Config)` and
`SparkJobValidation SparkJobBase.validate(Object, Config)`

it is not possible to proceed as it is not possible to have `validate()` implemented without the compiler complaining.

**Comment by velvia** [comment]
So you’re not supposed to use these classes directly.  If you use the JavaSparkJob then you shouldn’t be touching these directly…

**Comment by d-ee** [comment]
It is necessary to extend SparkSqlHob abs

**Comment by nishutayal** [comment]
To return `SparkJobValid` from `validate(SparkContext sc, Config config) `method in Java, 
use  `SparkJobValid$.MODULE$;`

**Comment by velvia** [comment]
Just a heads up, we are planning on changing the Java API to make it more Java friendly, and extensible to other types of contexts easily, as well as take advantage of NamedRdds etc.

**Comment by hntd187** [comment]
Yes, I am currently working on making the JavaAPI better and easier to use. I Hope to have a pull request on it soon

**Comment by noorul** [comment]
@hntd187 is this fixed in master?

**Comment by bsikander** [comment]
Fixed in master already.
