### ISSUE TITLE
Job Server Not Able To Handle All The Requests At A Time, Even Though Resources Are Available

### ISSUE THREAD

**Issue by SanthoshPrasad** [spark-jobserver/spark-jobserver#439]
We have 32 cores  and  60 GB RAM on machine where we deployed the job server, but when multiple people are executing the jobs concurrently, job server was handling only 6 request at a time, is there any configuration which job server will use when submitting the jobs, we are using context per jvm feature, 
We are running AWS EMR Cluster with 10 Nodes , with 160 vCores and 230GB   RAM.

Thanks in advance.

**Comment by velvia** [comment]
Just to be clear, are you talking about 6 concurrent contexts (JVMs/applications) at a time, or 6 concurrent SJS jobs within one context?

For the latter case, there is a parameter you can adjust, 

spark.jobserver.max-jobs-per-context

You will also want to enable the spark.scheduler.mode=FAIR and configure your fair-scheduler.xml properly.

The default is 8 which probably translates to about 6 concurrent jobs.

-Evan

**Comment by hntd187** [comment]
If you set max jobs and setup FAIR scheduling in the context as well as in the jobs themselves, I've had over 100 jobs running across 10 contexts at once with no issues at all. Also on much less hardware than yours.

**Comment by SanthoshPrasad** [comment]
Hi @velvia , @hntd187 , thank you very much  for responding, in our case we are running each and every job in a different context, also as context per jvm is enabled so every job executing in a different jvm, in this scenario is there any config which will decide how many jobs we can execute concurrently (or)  it depends on number of available cores in master node?

Also i am not able to find out any property in job server conf to specify number of cores for driver, how many cores will job server allocate to each driver when running each job under a different context/jvm.

Thanks,
Santhosh.

**Comment by velvia** [comment]
So the only thing limiting the number of concurrent contexts is amount of available mem/cpu in your cluster.’

As for number of cores for driver, typically driver apps are single threaded and consume only 1 core.  Job server Actor logic consumes more threads but really very low activity.

**Comment by velvia** [comment]
@SanthoshPrasad closing.  We can keep chatting but this does not appear to be a SJS issue.
