### ISSUE TITLE
Will spark-jobserver work with  yarn-cluster?

### ISSUE THREAD

**Issue by seaizon** [spark-jobserver/spark-jobserver#451]

**Comment by noorul** [comment]
It should, as I see a dedicated document for this
https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/yarn.md

**Comment by seaizon** [comment]
It can work with yarn-client ,but not with yarn-cluster

**Comment by zeitos** [comment]
@seaizon is right, it doesn't work on cluster mode, I never had the time to investigate it and it's in my TODO list :S

**Comment by igreenfield** [comment]
What the status of that?

**Comment by bsikander** [comment]
@igreenfield The pull request for YARN is open right now. You can try it if you want
https://github.com/spark-jobserver/spark-jobserver/pull/927

**Comment by B87** [comment]
Hi! Is the feature ready?

**Comment by bsikander** [comment]
Yes, cluster-mode for YARN is ready.

**Comment by bsikander** [comment]
Already implemented.
