### ISSUE TITLE
Streaming Job is not stopping even after killing it.

### ISSUE THREAD

**Issue by FK7** [spark-jobserver/spark-jobserver#452]
I am running Spark Streaming twitter job using `curl -d 'batch.interval:1' 'localhost:8090/jobs?appName=TwitterStreaming&classPath=com.yash.sa.main.TwitterStreamApp&sync=true' `in `yarn-client `mode via job server, but I've seen wired thing in that my stream job is running continuously even after killing it using following curl.
	
```
curl -X DELETE localhost:8090/jobs/7bf355a9-7a3c-4fff-8f5f-5fb8571cb867
{
  "status": "KILLED"
}
```
As you can see following are cluster metrics and Job server UI snapshot, First one shows job in running state and second one shows job as completed.

![capture2](https://cloud.githubusercontent.com/assets/10955711/15038073/6599fd2c-12be-11e6-9786-b41f9c16c443.PNG)

![capture](https://cloud.githubusercontent.com/assets/10955711/15038074/65a04f24-12be-11e6-965d-c01187c183ff.PNG)

Context 

![context](https://cloud.githubusercontent.com/assets/10955711/15038274/f813a9cc-12bf-11e6-9f5d-aa9855d91288.PNG)

Why this is happening or Is this any other way to kill a streaming job ?

**Comment by noorul** [comment]
I am not sure whether you can kill a synchronous job.

**Comment by noorul** [comment]
Is this related to https://github.com/spark-jobserver/spark-jobserver/issues/222

**Comment by FK7** [comment]
Yes @noorul this is the same issue that I am facing.

**Comment by velvia** [comment]
I’m not sure you can kill a spark streaming job.  I think you need to kill the context.  -X DELETE /contexts/name-of-context

**Comment by FK7** [comment]
On deleting the spark context, allocated resources are releasing from Resource manager but Job is running continuously with` java.lang.IllegalStateException: SparkContext has been shutdown`
exception.

**Comment by velvia** [comment]
Are you running latest master?
Do you have context-per-ivm turned on?

**Comment by FK7** [comment]
Yes, I am running latest master.
Yes, I've context-per-jvm turned on.

**Comment by velvia** [comment]
For now, you need to kill the process manually.  We will try to fix this.

**Comment by FK7** [comment]
Hi guys, 

1)   I've context-per-jvm turned on.and am getting the following error on submitting the spark job on SJS.
` Cannot run program \"./manager_start.sh\": error=2, No such file or directory`
When I turned off the context-per-jvm, Jobs are submitting successfully.

2)  I am running Spark streaming job via SJS and have mentioned `stopSparkContext = false`  but on deleting the  streaming job context still I am getting  `Spark Context already shut down ` exception while running another spark job. For now I am restarting SJS server to overcome this issue. I believe this is not a good way to do the same.

3) Following is the context configuration that I am using.

```
 context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 4G      # Executor memory per node, -Xmx style eg 512m, 1G, etc.
	spark.executor.instances = 2

    # A zero-arg class implementing spark.jobserver.context.SparkContextFactory
    # Determines the type of jobs that can run in a SparkContext
    context-factory = spark.jobserver.context.DefaultSparkContextFactory

    streaming {
      # Default batch interval for Spark Streaming contexts in milliseconds
      batch_interval = 1000

      # if true, stops gracefully by waiting for the processing of all received data to be completed
      stopGracefully = false

      # if true, stops the SparkContext with the StreamingContext. The underlying SparkContext will be
      # stopped regardless of whether the StreamingContext has been started.
      stopSparkContext = false
    }

    # uris of jars to be loaded into the classpath for this context. Uris is a string list, or a string separated by commas ','
    # dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]

    # Timeout for SupervisorActor to wait for forked (separate JVM) contexts to initialize
    context-init-timeout = 60s
	# If you wish to pass any settings directly to the sparkConf as-is, add them here in passthrough,
	# such as hadoop connection settings that do not use the "spark." prefix
    passthrough {
      spark.driver.allowMultipleContexts = true  # Ignore the Multiple context exception related with SPARK-2243
    }

    #This adds configuration to the underlying Hadoop configuration in the Spark Context
    #hadoop {
    #  mapreduce.framework.name = "FooFramework"
    #}
  }
```

**Comment by noorul** [comment]
@FK7 You need to copy manager_start.sh script to current location. How are you deploying SJS?

**Comment by FK7** [comment]
@noorul I've fixed it out by specifing absolute path.

Thanks for your time.
