### ISSUE TITLE
User defined variables when creating a new context

### ISSUE THREAD

**Issue by Nav1982** [spark-jobserver/spark-jobserver#455]
Is this possible today to pass any custom parameter when creating a context? So that is available for all jobs submitted against that context.
Documentation says we can overwrite these 
POST /contexts/my-new-context?num-cpu-cores=10

But how if I would like to initialize my custom variable?

**Comment by velvia** [comment]
I think if you pass in nonstandard query params when you create a context it will just get passed in as part of the context config and is accessible from the job. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by Nav1982** [comment]
I assume that all query params are merged with standard Jobserver config and passed on to every job.
But that is not happening
I tried passing my-param when creating the SQLContext like this
POST /contexts/my-context?context-factory=spark.jobserver.context.SQLContextFactory&my-param=value

I am printing entire Config object received in the runJob method but can't see 'my-param' being passed anywhere.

**Comment by ee99ee** [comment]
I'm having the same issue... I've tried the following:

* Adding it as a URL param to the POST when creating the context
* Setting `myparam=value` inside `context-settings` in the jobserver config
* Setting `myparam=value` inside `context-settings.passthrough` in the jobserver config
* Setting `spark.executor.extraJavaOptions="-Dmyparam=value"` and `spark.driver.extraJavaOptions="-Dmyparam=value"`

The weird thing is if I look at the environmental variables listed in the context's Spark UI app, I see my variables set. However, when my job is executed, `System.getProperty("myparam")` returns null.... wtf?? So weird.

**Comment by noorul** [comment]
@Nav1982, @ee99ee Use json body in http post request which will be merged with config. This config object is accessible from job.

Closing.
