### ISSUE TITLE
Support for named Models 

### ISSUE THREAD

**Issue by zeitos** [spark-jobserver/spark-jobserver#46]
We currently have support for Named RDDs but the MLlib returns Models (KMeansModel, MatrixFactorizationModel, GeneralizedLinearModels)

I think it would be useful to have a mechanism to cache those.

**Comment by velvia** [comment]
How did you decide to tackle those?

I think once we merge in the context extension support you could easily
create a custom context to save models.

On Wed, Jan 14, 2015 at 7:01 AM, Fernando Otero <notifications@github.com>
wrote:

> Closed #46 <https://github.com/spark-jobserver/spark-jobserver/issues/46>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/46#event-218785126>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by zeitos** [comment]
I aded the issue before even started to look at the problem,

Then my idea was generalizing the NamedRDD to NamedObject, but then I saw
the refreshRDD() comment and that scared me... b/c mllib any object might
have an RDD and we won't have a way "refresh" them.

On the other hand: if the object is frequently used ie: a model which is
queried every second: that rdd will not be garbage collected.

anyway, we can let the user define a refresh function when adding the
NamedObject and use that....

But I felt that the issue needed some discussion and it wasn't that trivial
to implement and that's why I closed it

**Comment by JanJaniszewski** [comment]
Has anybody found a solution to this problem? I would feel like... awesome... if I could cache my models.

**Comment by velvia** [comment]
Yes in fact... We just merged in NamedObject support, which lets you cache and name any kind of object.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by aschillingpayne** [comment]
I was looking at JobServer for the very same reasons. That being said - what methods of the NamedObjectPersister would need implementations to support the caching NamedObject models?

TIA

**Comment by velvia** [comment]
The persist method, mainly.   Maybe the refresh method.
