### ISSUE TITLE
using spark-jobserver 0.6.2 with spark 1.4.1

### ISSUE THREAD

**Issue by rottemp** [spark-jobserver/spark-jobserver#461]
In the documentation there is a mapping between spark-jobserver 0.6.0 and Spark 1.4.1
I would like to use the updated spark-jobserver with the newest bug fixes with Spark 1.4.1. 
Is that possible? If so, how?

**Comment by noorul** [comment]
There is a branch for this. But that does not have everything in master, most importantly JVM per context.

**Comment by rottemp** [comment]
1. what is the name of the branch? Is it maintained?
2. is there a reason for not using the latest spark-jobserver release?

**Comment by noorul** [comment]
I am sorry, I thought you were looking for SJS 0.6.0 with spark 1.4.1. It looks like you are looking for SJS 0.6.2 with spark 1.4.1. It is not there. I was referring to the branch https://github.com/spark-jobserver/spark-jobserver/tree/jobserver-0.6.0-spark-1.4. I would suggest you to create your own branch from this one and back port SJS related changes alone (not spark related changes) that you need from 0.6.2.

**Comment by noorul** [comment]
@rottemp  Shall we close this issue?

**Comment by rottemp** [comment]
How can I know which changes are SJS alone? It seems that there are many bug fixes that should be taken.

**Comment by velvia** [comment]
Sorry what do you mean, SJS alone?

**Comment by rottemp** [comment]
In your response above you wrote that I can port "SJS related changes alone". How can I know that?

**Comment by noorul** [comment]
@rottemp By SJS alone, I meant that changes that are not related to Spark version.

**Comment by hntd187** [comment]
If you want to use Spark 1.4.1 then you should use the branch for that version of Spark job server

**Comment by hntd187** [comment]
@rottemp are you still having issues?

**Comment by noorul** [comment]
Closing this as we don't maintain the branch which @rottemp is looking for.
