### ISSUE TITLE
Unable to upload fat jar.

### ISSUE THREAD

**Issue by FK7** [spark-jobserver/spark-jobserver#462]
I am getting following error while uploading fat jar using curl command.

`[2016-05-16 13:42:31,589] WARN erver.HttpServerConnection [] [akka.tcp://JobServer@127.0.0.1:42033/user/IO-HTTP/listener-0/2] - Illegal request, responding with status '413 Request Entity Too Large': Request Content-Length 38175252 exceeds the configured limit of 31457280 `

I've configured the `parsing.max-content-lengthvalue `to 100m in emr.conf

```
spray.can.server {
   # uncomment the next lines for making this an HTTPS example
   # ssl-encryption = on
   idle-timeout = 60 s
   request-timeout = 40 s
   pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
   # Needed for HTTP/1.0 requests with missing Host headers
   default-host-header = "spray.io:8765"

   # Increase this in order to upload bigger job jars
   parsing.max-content-length = 100m
 }
```
And also is showing the correct value in logs

    # /mnt/lib/spark-jobserver/emr.conf: 61
    "spray" : {
        # /mnt/lib/spark-jobserver/emr.conf: 61
        "can" : {
            # /mnt/lib/spark-jobserver/emr.conf: 61
            # check the reference.conf in spray-can/src/main/resources for all defined settings
            "server" : {
                # /mnt/lib/spark-jobserver/emr.conf: 68
                # Needed for HTTP/1.0 requests with missing Host headers
                "default-host-header" : "spray.io:8765",
                # /mnt/lib/spark-jobserver/emr.conf: 64
                # uncomment the next lines for making this an HTTPS example
                # ssl-encryption = on
                "idle-timeout" : "60 s",
                # /mnt/lib/spark-jobserver/emr.conf: 71
                "parsing" : {
                    # /mnt/lib/spark-jobserver/emr.conf: 71
                    # Increase this in order to upload bigger job jars
                    "max-content-length" : "100m"
                },
                # /mnt/lib/spark-jobserver/emr.conf: 66
                # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
                "pipelining-limit" : 2,
                # /mnt/lib/spark-jobserver/emr.conf: 65
                "request-timeout" : "40 s"
            }
        }
But still getting error, dont know what is happening.
Kindly let me know am I missing something ?

**Comment by giaosudau** [comment]
I had this error before but when I had added 
```
spray.can.server {
  # uncomment the next lines for making this an HTTPS example
  # ssl-encryption = on
  # path to keystore
  #keystore = "/some/path/sjs.jks"
  #keystorePW = "changeit"

  # see http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#SSLContext for more examples
  # typical are either SSL or TLS
  encryptionType = "SSL"
  keystoreType = "JKS"
  # key manager factory provider
  provider = "SunX509"
  # ssl engine provider protocols
  enabledProtocols = ["SSLv3", "TLSv1"]
  idle-timeout = 60 s
  request-timeout = 40 s
  pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
  # Needed for HTTP/1.0 requests with missing Host headers
  default-host-header = "spray.io:8765"

  # Increase this in order to upload bigger job jars
  parsing.max-content-length = 300m
}
```
You should try to copy and restart server again.

**Comment by FK7** [comment]
@giaosudau  Not working on my side.

Which SJS version you are referring ?
I am using `v0.6.2`


```
spark {
 # spark.master will be passed to each job\'s JobContext
 # master = "mesos://<IP:PORT>"
master = "yarn-client"

 # Default # of CPUs for jobs to use for Spark standalone cluster
 #job-number-cpus = 4

jobserver {
 port = 8090
 jar-store-rootdir = /mnt/tmp/spark-jobserver/jars

 jobdao = spark.jobserver.io.JobFileDAO
 
 # Automatically load a set of jars at startup time.  Key is the appName, value is the path/URL.
 job-jar-paths {    # NOTE: you may need an absolute path below
      #sql = job-server-extras/target/scala-2.10/job-server-extras_2.10-0.6.2-SNAPSHOT-tests.jar
    }
 
 filedao {
   rootdir = /mnt/tmp/spark-jobserver/filedao/data
 }
}

# predefined Spark contexts
contexts {
 # test {
 #   num-cpu-cores = 1            # Number of cores to allocate.  Required.
 #   memory-per-node = 1g         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
 #   spark.executor.instances = 1
 # }
 # define additional contexts here
 
 # sql-context {
 #     num-cpu-cores = 1           # Number of cores to allocate.  Required.
 #     memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
 #     context-factory = spark.jobserver.context.HiveContextFactory
 #   }
}

# universal context configuration.  These settings can be overridden, see README.md
context-settings {
 num-cpu-cores = 2          # Number of cores to allocate.  Required.
 memory-per-node = 4G         # Executor memory per node, -Xmx style eg 512m, #1G, etc.
 spark.executor.instances = 2

 # uris of jars to be loaded into the classpath for this context
 #dependent-jar-uris = ["file:///usr/local/spark-dependencies-assembly-0.1.jar"]
 
 # If you wish to pass any settings directly to the sparkConf as-is, add them here in passthrough,
 # such as hadoop connection settings that don\'t use the "spark." prefix
 passthrough {
   #es.nodes = "192.1.1.1"
   spark.cassandra.connection.host = "127.0.0.1"
   spark.driver.extraClassPath ="/home/hadoop/guava-19.0.jar"
   spark.executor.extraClassPath ="/home/hadoop/guava-19.0.jar"
 }
}
# This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
home = "/usr/lib/spark"

# check the reference.conf in spray-can/src/main/resources for all defined settings
spray.can.server {
  # uncomment the next lines for making this an HTTPS example
  # ssl-encryption = on
  # path to keystore
  #keystore = "/some/path/sjs.jks"
  #keystorePW = "changeit"

  # see http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#SSLContext for more examples
  # typical are either SSL or TLS
  encryptionType = "SSL"
  keystoreType = "JKS"
  # key manager factory provider
  provider = "SunX509"
  # ssl engine provider protocols
  enabledProtocols = ["SSLv3", "TLSv1"]
  idle-timeout = 60 s
  request-timeout = 40 s
  pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
  # Needed for HTTP/1.0 requests with missing Host headers
  default-host-header = "spray.io:8765"

  # Increase this in order to upload bigger job jars
  parsing.max-content-length = 300m
}
}
```

**Comment by FK7** [comment]
I've figured out the issue hence closing the same.

**Comment by andreyzhm** [comment]
Can you explain how did you overcome that issue, I am hitting the same

**Comment by FK7** [comment]
Andrey 
Everything was perfect but I mistakenly mentioned the 'spray.can.server' inside the bracket. As you can see in above my emr.conf.

**Comment by andreyzhm** [comment]
Could you advise on my config:

# Template for a Spark Job Server configuration file
# When deployed these settings are loaded when job server starts
#
# Spark Cluster / Job Server configuration
spark {
  # spark.master will be passed to each job's JobContext
  # master = "local[4]"
  # master = "mesos://vm28-hulk-pub:5050"
  # master = "yarn-cluster"
    master = "yarn-client"

  # Default # of CPUs for jobs to use for Spark standalone cluster
  job-number-cpus = 4

  jobserver {
    port = 8090

    jobdao = spark.jobserver.io.JobFileDAO

    filedao {
      rootdir = /opt/ccih/dependencies/ccih-sjs/internal-state/filedao/data
    }
    datadao {
      rootdir = /opt/ccih/dependencies/ccih-sjs/internal-state/upload
    }

  }

  # predefined Spark contexts
   contexts {
       #SJS-CJA-Context {
       #spark.executor.instances = 1              # instances executors for all nodes
       #spark.executor.memory = 15G              # memory per executor
       #spark.executor.cores = 4                      # Num of cores per executor
       #spark.task.cpus = 1                             # Num of cpus per task
       #spark.serializer = "org.apache.spark.serializer.KryoSerializer"
       #spark.kryo.registrationRequired = true
             #spark.kryo.classesToRegister = "[Lcom.ccih.jobs.scenario.analyzer.statistics.metrics.MetricResult;,com.ccih.model.Session,com.$
          }
     # define additional contexts here
   }


  # universal context configuration.  These settings can be overridden, see README.md
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

    # in case spark distribution should be accessed from HDFS (as opposed to being installed on every mesos slave)
    # spark.executor.uri = "hdfs://namenode:8020/apps/spark/spark.tgz"

    # uris of jars to be loaded into the classpath for this context. Uris is a string list, or a string separated by commas ','
    # dependent-jar-uris = ["file:///some/path/present/in/each/mesos/slave/somepackage.jar"]

    # If you wish to pass any settings directly to the sparkConf as-is, add them here in passthrough,
    # such as hadoop connection settings that don't use the "spark." prefix
    passthrough {
      #es.nodes = "192.1.1.1"
    }
  }

  # This needs to match SPARK_HOME for cluster SparkContexts to be created successfully
  # home = "/home/spark/spark"


   # check the reference.conf in spray-can/src/main/resources for all defined settings
spray.can.server {
  # uncomment the next lines for making this an HTTPS example
  # ssl-encryption = on
  # path to keystore
  #keystore = "/some/path/sjs.jks"
  #keystorePW = "changeit"

  # see http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#SSLContext for more examples
  # typical are either SSL or TLS
  encryptionType = "SSL"
  keystoreType = "JKS"
  # key manager factory provider
  provider = "SunX509"
  # ssl engine provider protocols
  enabledProtocols = ["SSLv3", "TLSv1"]
  idle-timeout = 60 s
  request-timeout = 40 s
  pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
  # Needed for HTTP/1.0 requests with missing Host headers
  default-host-header = "spray.io:8765"

  # Increase this in order to upload bigger job jars
  parsing.max-content-length = 900m
}

}

# Note that you can use this file to define settings not only for job server,
# but for your Spark jobs as well.  Spark job configuration merges with this configuration file as defaults.

**Comment by Nithanaroy** [comment]
If `sh server_start.sh` the right way to start the server, how does it know to use the updated local.conf file? Should I re-deploy with this environment first, `sh server_deploy.sh local` and then start?

**Comment by bsikander** [comment]
@Nithanaroy yes.
Since server_deploy.sh copies files to a remote folder. If you update config file then this file needs to be copied again to remote folder again.
