### ISSUE TITLE
Update jar file and re-run the same context of last jar don't work

### ISSUE THREAD

**Issue by giaosudau** [spark-jobserver/spark-jobserver#464]
I re upload the jar after change some code but when re-run with the same class I change don't work.

```bash 
curl -i -d "config.path=/Users/giaosudau/IdeaProjects/ImpressionMetric/src/main/resources/test.conf" 'localhost:8090/jobs?appName=test-cassandra-4&classPath=job.SqlLoaderJob&context=sql_context'
```

Even I did change the location of jar but it still didn't work.
I need to create a new context then it works.
So when I wanna update a jar I need to create a new context?

**Comment by hntd187** [comment]
Yes, spark contexts are immutable. Once a jar is loaded into the context you can't update it.

**Comment by giaosudau** [comment]
Thank you.
