### ISSUE TITLE
Cannot import SQLContextFactory

### ISSUE THREAD

**Issue by jomach** [spark-jobserver/spark-jobserver#470]
Hi Guys, 

I have a problem importing / Using SQLcontexts.  I'm getting : "result": "Invalid job type for this context"

My steps are  : 
1- Edit applcation.conf and add : 
  sql-context {
      num-cpu-cores = 1           # Number of cores to allocate.  Required.
      memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, 1G, etc.
      context-factory = spark.jobserver.context.SQLContextFactory
    }

2- sbt -> job-server-extras/reStart
3- upload my jar
4 - run it : curl -d "" '127.0.0.1:8090/jobs?appName=georefv1&classPath=com.here.JobServer.TestSparkJobServer&context=sql-context&sync=true'

My class looks like :
`trait SparkSqlJob extends SparkJobBase {
  type C = SQLContext
}
class TestSparkJobServer extends SparkSqlJob{

  override def runJob(sql: SQLContext, jobConfig: Config): Any ={

    val options = CreateOptions("nearestd1")
    val output_location = GetOptions.nextOption(Map(),options.toList).get('output).get.asInstanceOf[String]
    ReverseGeoref.run(sql.sparkContext,sql,options)
    val test_result = sql.read.parquet(output_location)
    test_result.show()
  }`

Why I'm getting this error ?

**Comment by hntd187** [comment]
Don't use your own SQL context use the spark extras jar which has one implemented for you.

**Comment by jomach** [comment]
@hntd187 thats what I'm trying to use. But it does not work for me

**Comment by velvia** [comment]
Hmm.  You shouldn’t have to define one yourself though.  What is the error?

**Comment by jomach** [comment]
@velvia : I get only Invalid job type for this context as response. I would be nice to have an complete example for the people starting I would submit a pull request when I get this working...

**Comment by zeitos** [comment]
@jomach if you do
```
trait SparkSqlJob extends SparkJobBase {
```
what you are creating is a ```com.here.JobServer.SparkSqlJob``` that extends from SparkJobBase
That job is **not** a spark.jobserver.SparkSqlJob

SQLContextFactory verifies that your job is a subclass of ```spark.jobserver.SparkSqlJob``` and your isn't.

Just delete your SparkSqlJob and import ```spark.jobserver.SparkSqlJob```  and you should be OK.

**Comment by jomach** [comment]
@zeitos that's exactly my problem. Whenn I try to do :

`class TestSparkJobServer extends spark.jobserver.SparkSqlJob` I get cannot find Symbol SparkSqlJob. 

Today I Found the error on my maven file. The dependency was not being resolved correctly. Now it works
