### ISSUE TITLE
Is support python or how to submit python files?

### ISSUE THREAD

**Issue by heramerom** [spark-jobserver/spark-jobserver#472]
I have some jobs written in python, and I use this [blog](http://arturmkrtchyan.com/apache-spark-hidden-rest-api) to submit it, but what is "mainClass". Google for a long time but did not find the answer

**Comment by hntd187** [comment]
Python jobs are currently not supported.

**Comment by heramerom** [comment]
Thanks. So I must rewrite in Java.
