### ISSUE TITLE
Job Server Not Started Because Of Exception, But The Exception Information Was Not Logged

### ISSUE THREAD

**Issue by SanthoshPrasad** [spark-jobserver/spark-jobserver#474]
When executing spark-submit from server_start.sh if exception comes ( ClassNotFoundException, Class Version Mismatch ..etc) , that information was not logged into spark jobserver log, for debugging we need to manually invoke spark-submit.

**Comment by noorul** [comment]
If you set JOBSERVER_FG, it will run in foreground that way you can see the output in stdout and find issues. Once you fix the issue you can unset this and run it in background.

By default it runs in background any command related error will not be sent to stdout. If jobserver starts successfully logs goes to loggers defined in log4j properties.

**Comment by zeitos** [comment]
@SanthoshPrasad can I close this issue?
