### ISSUE TITLE
No Logs are generated

### ISSUE THREAD

**Issue by jomach** [spark-jobserver/spark-jobserver#475]
Hi Guys, 

when I run this in Development mode no log file are generated as say in the docs. 
My Steps: 
sbt
job-server-extras/reStart or job-server/reStart

I get this on the command line : 
job-server-extras[ERROR] log4j:WARN No appenders could be found for logger (spark.jobserver.JobServer$).
job-server-extras[ERROR] log4j:WARN Please initialize the log4j system properly.
job-server-extras[ERROR] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
job-server-extras[ERROR] Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties

**Comment by noorul** [comment]
It will looks for config/log4j-local.properties

See https://github.com/spark-jobserver/spark-jobserver/blob/master/project/Build.scala#L238

**Comment by zeitos** [comment]
@jomach did noorul's  answer worked? can I close this issue?

**Comment by jomach** [comment]
@noorul: For me the config file is there but still I get no file with name : job-server-local.log

**Comment by noorul** [comment]
@jomach You are right. This is an issue on master branch.

**Comment by noorul** [comment]
Fixed in master
