### ISSUE TITLE
Build sjs in Scala 2.11 and use a custom spark build

### ISSUE THREAD

**Issue by stannie42** [spark-jobserver/spark-jobserver#479]
In order to build sjs in scala 2.11, we have to provide a custom archive of spark.

We should make the choice of of scala version as optional (default will be 2.10.6) and we should add a way to provide a path to a custom spark archive in Build.scala. So the spark dir will be added (docker ADD instruction) directly into the container.

Another way to deal with scala 2.11 version and spark tgz is to provide these versions in your AWS S3/CloudFront buckets and then add $SCALA_VERSION in the filename. But providing a custom spark dir could avoid you some spark build duties :)

**Comment by zeitos** [comment]
I'm not sure what you mean by "provide a custom archive of spark" ... you can build for scala 2.11 by specifying ```SCALA_VERSION``` in env.sh (in /config)

**Comment by stannie42** [comment]
Thanks for the advice with env.sh !

There is no package available for spark in scala 2.11, so we had to build it. That's why I need a way to specify a "custom archive of spark"

**Comment by hntd187** [comment]
@stannie42 you should be able to set the spark_home in your configuration and then use the spark 2.11 dependencies in the build. You might have to make sure the versions line up but you should be able to do something like

``` sbt ++2.11.8 clean update package assembly ``` or whatever version you are looking for.

**Comment by noorul** [comment]
@stannie42 As @hntd187 mentioned this is already configurable. Shall we close this issue?

**Comment by hntd187** [comment]
@noorul @stannie42 yup, give those options a try, they should be what you are looking for. If you are still having an issue open a new issue thanks.
