### ISSUE TITLE
Getting out of memory on java 1.8 spark 1.6.0

### ISSUE THREAD

**Issue by cgeorge-rms** [spark-jobserver/spark-jobserver#483]
I'm getting out of memory error on java 1.8 and spark 1.6.0 stand-alone
Specifically DirectBufferMemory
Every time I submit a job I see the DirectBuffer Pool go up and never come back down until I run out of memory.
![image](https://cloud.githubusercontent.com/assets/16123309/15724993/eb3313a8-2806-11e6-8953-5d4ea1cdc702.png)
I noticed the docker image uses java 1.7

The job I'm running is pretty straight forward... it just reads a single parquet file with a single row and then returns the result.

**Comment by hntd187** [comment]
Is the job caching anything? Is the contest persistent?

**Comment by cgeorge-rms** [comment]
no... not anymore
class RetrievePhysicalStructureJob extends SparkJob {// with NamedObjectSupport {
  override def runJob(sc: SparkContext, jobConfig: Config): Any = {
    val sqlContext =  new SQLContext(sc)

    val physicalStructure = sqlContext.read.parquet("/estore/physicalStructure")
    val id = jobConfig.getInt("id")
    val retString = physicalStructure.filter(s"id=${id}").toJSON.collect()
    retString
  }

  override def validate(sc: SparkContext, config: Config): SparkJobValidation = SparkJobValid
}

**Comment by hntd187** [comment]
Try removing the retString and just return the expression.

**Comment by cgeorge-rms** [comment]
same result

**Comment by hntd187** [comment]
Does this help? https://github.com/spark-jobserver/spark-jobserver/issues/367

**Comment by cgeorge-rms** [comment]
I saw that.. I tried setting MAX_DIRECT_MEM to 2g which I can see took effect in visualvm, but it only delayed how long it took to run out of memory

**Comment by hntd187** [comment]
Did you try setting the ```spark.driver.maxResultSize``` ?

**Comment by cgeorge-rms** [comment]
same result

**Comment by cgeorge-rms** [comment]
so I tried making an empty spark job... 
 override def runJob(sc: SparkContext, jobConfig: Config): Any = {
    "done"
  }
and it seems like the direct buffer can be cleaned up after doing a gc
I'll try adding back in things incrementally and see what happens

**Comment by cgeorge-rms** [comment]
so I did the following:
` override def runJob(sc: SparkContext, jobConfig: Config): Any = {
    val sqlContext = new SQLContext(sc)
    val tenant = jobConfig.getString("tenant")
    //      val physicalStructure = sqlContext.read.parquet("/estore/physicalStructure").count()
    val data = Array(1, 2, 3, 4, 5)
    val distData = sc.parallelize(data)
    distData.count()
    "done"
  }`
The above I see the spike from the parallelize of about 100mb, but after garbage collection the buffer is cleaned up. However when I run the reading from parquet line it's unable to garbage collect the 100 mb spike

**Comment by cgeorge-rms** [comment]
this following also recreates the issue without using a datasource for parquet
  override def runJob(sc: SparkContext, jobConfig: Config): Any = {
    val sqlContext = new SQLContext(sc)
    val data = Array(1, 2, 3, 4, 5)
    val distData = sc.parallelize(data)
    import sqlContext.implicits._
    val tempDF = distData.toDF()
    tempDF.registerTempTable("blah")
    sqlContext.sql("select * from blah").count()
  }

**Comment by hntd187** [comment]
You should not be creating your own SQLContext inside the job. Use the extras jar and let the factory method through the API make the context for you. Let's see if that cleans up the memory.

**Comment by cgeorge-rms** [comment]
that so far seems to be working... 
so since I have context-per-jvm = false... it's still running the driver from the main jobserver right?

**Comment by hntd187** [comment]
Yep, my mistake I missed that part of your code before, but basically you are creating all these rogue SQLContexts that are just eating up memory over time it would seem

**Comment by cgeorge-rms** [comment]
we should update troubleshooting documentation... as trying to prevent that might be non trivial within an extend to SparkJob

**Comment by hntd187** [comment]
Yea, it's always a double edged sword. We have to turn on the ability to have multiple running contexts just for the server to do what it does, but it leads to these problems if people try and create lots of contexts all rogue and such. Inevitably, I'd like to be able to track the contexts created by SJS and have a watchdog so to speak that will basically bar people from creating contexts, well out of context.

**Comment by cgeorge-rms** [comment]
btw there is an example of named object support that starts a sqlcontext 
https://github.com/spark-jobserver/spark-jobserver/blob/a8805815585d384253ffbb1712bc2a25c0664b68/job-server-extras/src/spark.jobserver/NamedObjectsTestJob.scala#L28

I found it cause I'm trying to use named object support with dataframes but NamedObjectSupport doesn't work with SparkSqlJob

**Comment by hntd187** [comment]
Thanks for pointing this out. If you'd like to fix that example and put in a pull request, otherwise I'll add it in to be fixed, if you have anymore issues either reopen this issue or open a new one.

**Comment by lionelfeng** [comment]
@hntd187  woud it help to init sqlContext by `getOrCreate`? But I am still seeing some me
```scala
val sqlContext = SQLContext.getOrCreate(sc)
