### ISSUE TITLE
NamedObjectSupport only works with SparkJob and not SparkJobBase

### ISSUE THREAD

**Issue by cgeorge-rms** [spark-jobserver/spark-jobserver#485]
I was trying to use NamedObjectSupport on a SparkSQLJob, but noticed it only works with SparkJob and not SparkJobBase. Is this intentional to not use NamedObjects with SparkSQLJob?

**Comment by cgeorge-rms** [comment]
looks like this is already fixed in latest code

**Comment by velvia** [comment]
Ok, can we close this then?

**Comment by cgeorge-rms** [comment]
yes please... do you know when you'll have a release for 0.7?

**Comment by velvia** [comment]
Not quite sure.
