### ISSUE TITLE
Make SparkSqlJob compatible with Java

### ISSUE THREAD

**Issue by d-ee** [spark-jobserver/spark-jobserver#487]
We are about to begin a project using the Spark Jobserver in a Java-environment.

Issue #483 reminds the developer to not create own `SQLContext`-objects, however it is currently impossible to have a `SparkSqlJob` in Java due to a Scala/Java incompatibility.

The workaround we currently use is to create a `SQLContext` in every called `JavaSparkJob`, which is contraindicated by Issue #483.

**Comment by hntd187** [comment]
We have a new java API in the pipeline right now. It should fix whatever issues the java API is having. Can we close this issue?

**Comment by d-ee** [comment]
Is there an ETA?

If this issue is covered you can close it.

**Comment by hntd187** [comment]
There is not an ETA as far as I know right now, but it should be included in 0.7. When it is merged to the master branch you'll be able to use it right away.

**Comment by d-ee** [comment]
Thanks for all your work! If you need additional testers for the Java-stuff give me a call.

**Comment by velvia** [comment]
@d-ee do you want to watch #442 PR?   That is where I will post the new java API.   Your review would definitely help.   Thanks.

**Comment by d-ee** [comment]
Using `git` is a large pain to me and uses up much of my project time. I'll invest some days to get the basics up again. Cheers.
