### ISSUE TITLE
Unable to listen to a port through SJS via Spark Streaming Jobs

### ISSUE THREAD

**Issue by FK7** [spark-jobserver/spark-jobserver#489]
Hi Guys,

1) I am trying to connect to a port on EMR from SparkStreaming Job on SJS using socketTextStream("master-ip",9997) and it always give error of `connection refused `.

2) Also  made a Kafka Consumer for Spark Streaming Job and after submitting it to SJS it shows:- `org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 10000`.I also overriden the timeout but still the problem persists.

Could you please let me know whether I am missing anything or not?

**Comment by hntd187** [comment]
Probably a firewall issue inside EMR.

**Comment by noorul** [comment]
@FK7 Are you still facing this issue?

**Comment by FK7** [comment]
@hntd187 Thanks for your time.

@noorul We've fixed it out.
