### ISSUE TITLE
Use the Spark args "packages" in dev mode

### ISSUE THREAD

**Issue by DivLoic** [spark-jobserver/spark-jobserver#490]
hi !!
I’m using the version 0.6.0 of jobserver, (i’m in spark 1.4.1)
I'd like to know if there is any way to use the option `--packages` of spark-submit.
Like the script `bin/server_start.sh` but with the **reStart** command of sbt in development.

I'm facing issues with the spark-cassandra-connector.

```json
{
  "status": "JOB LOADING FAILED",
  "result": {
    "errorClass": "java.lang.NoClassDefFoundError",
    "cause": "com.datastax.spark.connector.rdd.reader.RowReaderFactory",
    "stack": [ " … "
 "some really ugly stack",
 " … "],
    "causingClass": "java.lang.ClassNotFoundException",
    "message": "com/datastax/spark/connector/rdd/reader/RowReaderFactory"
  }
}
```

More than the library itself (put the jar in the class path isn't enough) i need to use the dependency manager to fetch others libs like guava, joda and so on ...

**Comment by velvia** [comment]
Hi,

So have you tried the dependent-jar-uris option?  It is intended for libraries like cassandra spark connector.

I forgot which version has spark-submit underneath server_start, but if it is there you could definitely use —packages as well.

**Comment by noorul** [comment]
I think dependent-jar-uris will not help here. It looks like we need
spark cassandra connector in sjs classpath too.

So, I think, may be a combination of setting EXTRA_JAR environment
variable and dependent-jar-uris might work.

**Comment by velvia** [comment]
Oh, you are talking about dev mode …. in that case why not just add the connector to your Dependencies.scala?

**Comment by noorul** [comment]
@DivLoic Is everything working fine now? If so shall we close this issue?

**Comment by DivLoic** [comment]
Thanks @velvia , It works fine. 

I was looking for some options in the configuration file. 
After dealing with some exclusion stuffs, it’s totally feasible!

In Dev : -- packages ==> Edit project/Dependencies.scala

I’m closing it! anyone to flag this as a question?
