### ISSUE TITLE
Unify project name, folders, etc.

### ISSUE THREAD

**Issue by d-ee** [spark-jobserver/spark-jobserver#492]
Project artifacts like file names, folder names, configuration parameters, PID/JAR-files, etc. name the project differently.
So far I have found `spark-job-server`, `spark-jobserver`, `job-server`, `jobserver`, sometimes existing in parallel in the same folder.
Wouldn't it be nice to only have one writing?

**Comment by noorul** [comment]
I completely agree with this. Do you mind proposing a patch?

**Comment by d-ee** [comment]
PO should review and comment and after accepting propose the unified name

**Comment by hntd187** [comment]
I have this in my latest pull request for the Java API

**Comment by hntd187** [comment]
In my branch, I have the projects made as job-server, job-server-api, job-server-extras, job-server-tests and akka-app. I also moved the projects to all be in a style of <project name>/src/{main,test}/scala this is for the Java API because of java's insistence on a folder hierarchy. Also the folders like "spark.jobserver" was split out into 2 folders spark/jobserver in these directories so Java and scala play nice with the packaging.

**Comment by velvia** [comment]
Let’s tackle this after we tackle the new job API.

**Comment by hntd187** [comment]
Yes @velvia let's tie up the new scala API, I can rebase off that, then I can finish up the Java API with your work.

**Comment by velvia** [comment]
Sweet.  Ping me on Gitter, let’s work together as I have some ideas about the Java API.

**Comment by hntd187** [comment]
Okay @velvia, I'm gonna have all weekend to do this, it's just me and the shiba for most of the weekend.

**Comment by noorul** [comment]
@hntd187 Are you still working on this?

**Comment by hntd187** [comment]
Yes I am it's part of the Java-API

**Comment by noorul** [comment]
I am using ensime emacs and when I say go to corresponding test file it looks for spark/jobserver instead of spark.jobserver. I hope this will be fixed with this refactoring.

**Comment by hntd187** [comment]
It will. Everything that should be a package directory like in java has been converted. You can look at how it's structured in my working branch https://github.com/hntd187/spark-jobserver/tree/javaapi might want to rename some projects too, but for now I just have the correct directory tree.

**Comment by noorul** [comment]
@hntd187 Thank you! It looks like the parent module folder is still job-server.

**Comment by noorul** [comment]
Closing as this is done by @hntd187  in series of patches
