### ISSUE TITLE
Web Auth Timeout tests fail sometimes...

### ISSUE THREAD

**Issue by hntd187** [spark-jobserver/spark-jobserver#494]
The tests in [spark.jobserver.auth.WebApiWithAuthenticationSpec](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/test/spark.jobserver/auth/WebApiWithAuthenticationSpec.scala#L390 ) fail sometimes for no obvious reason. Given how they are written it seems really strange they fail, but one is ignored and the other 2 are not. Could we make a decision on whether or not these tests should remain or set to ignore for the time being? They seem to cover a rather edge case situation. 

@TimMaltGermany do you have any insight on this?

**Comment by TimMaltGermany** [comment]
Do you have any logs? They never fail for me locally. It might be some strange concurrency issue. I suppose we could disable them if we keep ignoring failures, but I would prefer that we understand the reason for their occasional failure...

**Comment by hntd187** [comment]
@TimMaltGermany They also never fail for me locally, they fail on Travis often though.

**Comment by TimMaltGermany** [comment]
I have created a new PR (#496) to work on this issue.

**Comment by hntd187** [comment]
Thanks @TimMaltGermany let's talk there
