### ISSUE TITLE
In yarn-client mode, sparkcontext can't be recreated after crashed 

### ISSUE THREAD

**Issue by litao-buptsse** [spark-jobserver/spark-jobserver#50]
In yarn-client mode, I met a problem. AM was crashed, so the whole sparkcontext was crashed. But the sparkcontext didn't recreate. My new comming jobs submmited to sparkjobserver was accepted, but never to run, because the sparkcontext was not exist.
I want to know whether the sparkjobserver have sparkcontext recreate feature. If not, will you consider to add this feature in the future?

**Comment by zeitos** [comment]
there's a feature to create your own context  :
```
curl -d "" 'host:8090/contexts/aContextName'
```

**Comment by litao-buptsse** [comment]
Sorry I did't explain myself clearly. I mean that when sparkcontext crash, do you have sparkcontext auto recover mechanism？If you did't have this feature, will you consider to add this future in the future?

My problem is that, when sparkcontext crashed, First sc did't auto recover, Second I can still submit my job(If the server could tell me, sparkcontext have been crashed, your submit job was not accepted, it would be good to me.).

**Comment by velvia** [comment]
Hi Tao,

I'm not sure about the second problem, but in terms of auto recovery, that
is not there yet.   It would be similar to the HA feature, that when one
node goes down, the job server can auto recover and restart on the second
node.   That is a lot of work, but definitely is on the future roadmap.

-Evan


On Tue, Jan 20, 2015 at 7:53 PM, Tao Li <notifications@github.com> wrote:

> Sorry I did't explain myself clearly. I mean that when sparkcontext crash,
> do you have sparkcontext auto recover mechanism？If you did't have this
> feature, will you consider to add this future in the future?
>
> My problem is that, when sparkcontext crashed, First sc did't auto
> recover, Second I can still submit my job(If the server could tell me,
> sparkcontext have been crashed, your submit job was not accepted, it would
> be good to me.).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/50#issuecomment-70780653>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by qiaohaijun** [comment]
I am using spark-jobserver in hadoop 2.3.0 and yarn-client mode

there is a problem that when the am which runs in the yarn container crashed, the data structure [contextname: string, JobManagerActor:ActorRef] still exists.

**Comment by velvia** [comment]
Hi, can you give more context and information?  Thanks.

On Wed, Jan 21, 2015 at 7:42 PM, qiaohaijun <notifications@github.com>
wrote:

> I am using spark-jobserver in hadoop 2.3.0 and yarn-client mode
>
> there is a problem that when the am which runs in the yarn container
> crashed, the data structure [contextname: string, JobManagerActor:ActorRef]
> still exists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/50#issuecomment-70967168>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by qiaohaijun** [comment]
i will write a unitest for this issue

**Comment by qiaohaijun** [comment]
i add a unitest

**Comment by velvia** [comment]
Closing this, due to inactivity.
