### ISSUE TITLE
Context per JVM: Jobserver job status is always RUNNING, unable to get result

### ISSUE THREAD

**Issue by noorul** [spark-jobserver/spark-jobserver#502]
Spark: 1.6.1
SJS: 0.6.2

I have the following in config

    # If true, a separate JVM is forked for each Spark context
    context-per-jvm = true

I could submit a job and get jobId. I see from spark UI that job is getting completed. Also the spawned new process is gone after that. But in jobserver UI, job status is still running, hence unable to get the result.

**Comment by noorul** [comment]
@ankitson Have you face this issue before?

**Comment by hntd187** [comment]
Are you sure it's not possible for the job to somehow take a very very long time or never complete?

**Comment by ankitson** [comment]
@noorul Yeah i have seen weird behavior with job statuses - velvia also mentioned problems with the job state here - https://github.com/spark-jobserver/spark-jobserver/issues/353. Sorry I don't really have an answer as to how to fix this quickly - i think we are not persisting state correctly and many other issues like https://github.com/spark-jobserver/spark-jobserver/issues/109 might be related to that.

**Comment by hntd187** [comment]
Would it make sense to have say a cleaner or a watcher above the forked JVMs to keep track of their existence, status and results respectively?

**Comment by noorul** [comment]
I see the forked process is completing successfully.

**Comment by noorul** [comment]
I had plans to use this in production. But it looks like it will be difficult with these issues.

**Comment by noorul** [comment]
@ankitson But without multi-jvm on, everything is working fine.

**Comment by velvia** [comment]
Some how the remote messages when job is complete is not being sent back.    
I was thinking of getting started by adding real tests for context-per-ivm mode.

**Comment by zeitos** [comment]
I have the same config and my jobs work great.. I currently have 2 contexts and both work great. One job takes about 40 minutes to complete
```
{
  "duration": "3731.154 secs",
  "classPath": "com.avenida.rd.recommend.CollaborativeFilteringInit",
  "startTime": "2016-06-15T18:47:53.986Z",
  "context": "prod_model",
  "result": "DONE",
  "status": "FINISHED",
  "jobId": "3e855d69-30cd-4172-85c2-9b27f0842bbb"
}
```

**Comment by noorul** [comment]
I confirm that word count example works. But the one that was failing is the following 

`import com.datastax.spark.connector._
import com.datastax.spark.connector.cql.CassandraConnector
import com.datastax.spark.connector.writer.RowWriterFactory

import com.typesafe.config.Config

import org.apache.spark.{SparkConf, SparkContext}

import spark.jobserver.{SparkJob, SparkJobValid, SparkJobValidation}

object TestCassandra extends SparkJob {

  override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
    SparkJobValid
  }

  override def runJob(sc: SparkContext, config: Config): Any = {

    sc.cassandraTable("dse_system", "real_leaders").collect()

  }
}
`

**Comment by noorul** [comment]
It looks like cassandra connection libraries which is part of the fat app jar, are not available at driver side. So when we do a collect(), the driver is trying to map to com.datastax.spark.connector.CassandraRow type and errors out.

The clue was in the the following warning. Not sure why this is not throwing an exception.

[2016-06-16 13:20:33,955] WARN ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:63727/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A63731-0] - Association with remote system [akka.tcp://JobServer@127.0.0.1:63731] has failed, address is now gated for [5000] ms. Reason: [com.datastax.spark.connector.CassandraRow]

After changing the code to do the conversion at spark worker, everything is working fine.

**Comment by noorul** [comment]
Removing the bug label and closing this ticket. Not sure why there is no traceback. But that is not related to this issue.

**Comment by velvia** [comment]
Ohhh..  yeah try translating from cassandra row to something else for the serialization.   Though you should not have class path issues.

Aren’t you using DSE?   You should not need to include connector in DSE.
