### ISSUE TITLE
Postgres Driver - Flyway non-empty schema "public" without metadata table

### ISSUE THREAD

**Issue by stannie42** [spark-jobserver/spark-jobserver#503]
I've tried the postgres sqldao driver in version 0.6.2 and I am encountering the following error

Caused by: org.flywaydb.core.api.FlywayException: Found non-empty schema "public" without metadata table! Use baseline() or set baselineOnMigrate to true to initialize the metadata table.
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1035)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
	at spark.jobserver.io.JobSqlDAO.init(JobSqlDAO.scala:103)
	at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:88)
	... 16 more

After some research I've found that we should put initOnMigrate to true, is it a viable solution or is there another issue I could fix? Thanks

**Comment by stannie42** [comment]
I am using the following sqldao in conf:

    sqldao {
      # Slick database driver, full classpath
      slick-driver = scala.slick.driver.PostgresDriver

      # JDBC driver, full classpath
      jdbc-driver = org.postgresql.Driver

      jdbc {
        url = "jdbc:postgresql://xxxxx"
        user = "xxx"
        password = "xxxx"
      }

      dbcp {
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
    flyway.locations="db/postgresql/migration"

**Comment by noorul** [comment]
Maybe dropping the database and re-creating it would fix it.

**Comment by stannie42** [comment]
I created a dedicated db for spark-jobserver and it worked fine, thanks noorul.

Getting next issue :(

Migration V0_7_0__init_tables.sql failed
----------------------------------------
SQL State  : 42601
Error Code : 0
Message    : ERROR: syntax error at or near "AUTO_INCREMENT"
  Position: 55
Location   : db/h2/migration/V0_7_0__init_tables.sql (/file:/app/spark-job-server.jar!/db/h2/migration/V0_7_0__init_tables.sql)

**Comment by noorul** [comment]
Since you are using postgresql, you should not see this getting executed.

**Comment by noorul** [comment]
This flyway.locations="db/postgresql/migration" should be at the root level, not inside jobserver namespace

**Comment by stannie42** [comment]
I moved flyway.locations outside jobserver scope but didn't change anything :(

**Comment by noorul** [comment]
https://github.com/spark-jobserver/spark-jobserver/commit/cdde1ca35234a3d84fc9b61b282bd7525c013def

Closing
