### ISSUE TITLE
Rest API delete file

### ISSUE THREAD

**Issue by big8extreme** [spark-jobserver/spark-jobserver#507]
Hi all,
We send file to jobserver via the Rest API and when we need to delete them 

with `GET /data/` i have this
`
[
"/data/file/test-17T08_45_15.492Z.dat"
]
`
and then when i try to delete the file with 
`DELETE /data/"/data/file/test-17T08_45_15.492Z.dat"
or
DELETE /data/data/file/test-17T08_45_15.492Z.dat`
this dont work.

**Comment by hntd187** [comment]
Because there is no ability to delete jars currently. You must delete them physically on disk. This is to prevent people from accidentially deleting things by mistake.

**Comment by hntd187** [comment]
Sorry read this wrong initially, do the logs say anything?

**Comment by noorul** [comment]
@big8extreme I think you should try "DELETE /data/file/test-17T08_45_15.492Z.dat"

**Comment by noorul** [comment]
@big8extreme Did you try it?

**Comment by big8extreme** [comment]
Yes it didn't work, i try everything

**Comment by noorul** [comment]
Should work now on master. See the updated readme for example
