### ISSUE TITLE
Publish Docker with Scala 2.11

### ISSUE THREAD

**Issue by mariussoutier** [spark-jobserver/spark-jobserver#517]
I want to use Spark Jobserver using Docker, however only the Scala 2.10 version is available. Please create a tag with Scala 2.11.
- [x] Add Scala version tag to docker image
- [x] Read Scala version from environment var
- [x] Use correct spark-job-server binaries
- [x] Instead of fetching pre-built binaries, build Spark with according Scala version
- [ ] Update release process to publish two versions

Thanks!

**Comment by mariussoutier** [comment]
One issue I'm seeing is how to fetch the right Spark version; Spark + Scala 2.11 must be built from source.

**Comment by janschultecom** [comment]
+1

**Comment by mariussoutier** [comment]
See #530

**Comment by noorul** [comment]
Closing
