### ISSUE TITLE
running multiple HiveContext's through HiveContextFactory

### ISSUE THREAD

**Issue by cgeorge-rms** [spark-jobserver/spark-jobserver#519]
This isn't an issue, but wanted to give everyone heads up if someone is searching on this problem.
When running context per jvm=true and running multiple HiveContexts without using a shared mysql database you will get an exception about derby locking.
I found that if you put a hive-site.xml in spark/conf directory containing:

```
 <configuration>
          <property>
                  <name>javax.jdo.option.ConnectionURL</name>
                  <value>jdbc:derby:memory:myDB;create=true</value>
                  <description>JDBC connect string for a JDBC metastore</description>
          </property>
          <property>
                   <name>javax.jdo.option.ConnectionDriverName</name>
                   <value>org.apache.derby.jdbc.EmbeddedDriver</value>
                   <description>Driver class name for a JDBC metastore</description>
          </property>
  </configuration>
```

It will then create an in memory derby instance for the hive metastore (this is assuming you don't need persistent data stored in actual hive metastore) 
We are doing this because we want context isolation and are running HiveServer2 from a shared context for jdbc access which works really well for us.

**Comment by velvia** [comment]
Thanks!!

**Comment by nkbhansali** [comment]
Thanks a lot :)

**Comment by cgeorge-rms** [comment]
If you have a recent stack trace of this might be helpful for people searching

**Comment by noorul** [comment]
Closing this.

**Comment by bsikander** [comment]
Closed.
