### ISSUE TITLE
Question: context-per-jvm and HA

### ISSUE THREAD

**Issue by cgeorge-rms** [spark-jobserver/spark-jobserver#520]
If I'm running context-per-jvm=true and I'm using a postgres for the job server dao. 
Is it theoretically possible if the context jvm information was within the dao that both job servers connecting to same dao could both execute commands on that context?
I'm sure this would require coding effort, but I would be curious if that would make all of this HA other than the single context jvm?

**Comment by velvia** [comment]
Yeah it’s sort of HA.  The main missing part is coordination between contexts - i.e. having one SJS know about the contexts in the other SJS, routing requests, etc.

**Comment by noorul** [comment]
@cgeorge-rms Can we close this issue ?

**Comment by noorul** [comment]
Closing this
