### ISSUE TITLE
tests cannot run on Windows

### ISSUE THREAD

**Issue by blue666man** [spark-jobserver/spark-jobserver#521]
Tests assume some hard coded Unix / POSIX file paths such as "/tmp/".

Additionally, JobSqlDAO#createJarName() and its test use Joda Time's .toString() which leaves colons in the file name.  This produces invalid ntfs file names.

**Comment by velvia** [comment]
I’m not sure if the effort to make everything run on Windows is worth it.  Maybe someone can do some investigation and report back.
You can just run everything in Cygwin or similar wrapper layer, no?

**Comment by blue666man** [comment]
This is running on Cygwin / Babun.  I'm working on putting together the PR; mainly using relative paths and a simple DateTimeFormatter that's compatible with all filesystems.

**Comment by zeitos** [comment]
@velvia  and specially since bash [is coming to windows](http://www.theverge.com/2016/3/30/11331014/microsoft-windows-linux-ubuntu-bash) 

@blue666man PR would be nice :D

**Comment by hntd187** [comment]
Gonna close this as it really isn't a bug, I don't think we've ever supported windows, but hopefully when bash comes to Windows this will be fixed. In the mean time if you want you are more than welcome to adjust the paths to be windows friendly. If you're having any other issues, just open a new issue, thanks!
