### ISSUE TITLE
org.apache.spark.SparkException: Failed to get broadcast_0_piece0 of broadcast_0

### ISSUE THREAD

**Issue by kishorez** [spark-jobserver/spark-jobserver#524]
Hi

We are experiencing the following issue when we create multiple jobs via Spark Job Server. Do any one experienced this issue. The Jobs we deployed are streaming jobs (Kafka) we also tried setting up a context with the context-per-jvm via curl and submitted jobs using that context. It failed too
Any help is appreciated

Environment 
Spark - 1.6
Scala - 2.10.6
Deployment  - Yarn client mode

message: "org.apache.spark.SparkException: Failed to get broadcast_0_piece0 of broadcast_0",
errorClass: "java.lang.RuntimeException",
stack: [
"org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1$$anonfun$2.apply(TorrentBroadcast.scala:138)",
"org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1$$anonfun$2.apply(TorrentBroadcast.scala:138)",
"scala.Option.getOrElse(Option.scala:120)",
"org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply$mcVI$sp(TorrentBroadcast.scala:137)",
"org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply(TorrentBroadcast.scala:120)",
"org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply(TorrentBroadcast.scala:120)",
"scala.collection.immutable.List.foreach(List.scala:318)",
"org.apache.spark.broadcast.TorrentBroadcast.org$apache$spark$broadcast$TorrentBroadcast$$readBlocks(TorrentBroadcast.scala:120)",
"org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:175)",
"org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1219)",
"org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:165)",
"org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:64)",
"org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:64)",
"org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:88)",
"org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)",
"org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)",
"org.apache.spark.scheduler.Task.run(Task.scala:89)",
"org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)",
"java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)",
"java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)",
"java.lang.Thread.run(Thread.java:745)"
]

Thanks
K

**Comment by zeitos** [comment]
I think everytime I had a broadcast issue it was a problem of getting short on the memory config.

**Comment by zeitos** [comment]
@kishorez did you fix this issue?

**Comment by kishorez** [comment]
yes it was fixed when we tried to put context-per-jvm using the curl it didn't took effect. However when updated the sparkyarn conf file itself we were able to see seperate context being created for each job and able to view in the resource manager multiple spark context

**Comment by swatisaini** [comment]
Hi, 

I'm also getting the same error while working with mesos.  What can be the reason behind it?. And any solution is appreciated.
