### ISSUE TITLE
Deprecate FileDAO

### ISSUE THREAD

**Issue by noorul** [spark-jobserver/spark-jobserver#526]
FileDAO has too many issues. Let us get rid of it.

**Comment by velvia** [comment]
I suggest we don't just get rid of it, but remove it from the default and mark the class as @deprecated, and make it clear in the docs.  This will provide for a smoother transition.

**Comment by zeitos** [comment]
+1 for velvia's comment

**Comment by hntd187** [comment]
I agree with @velvia deprecate it leave it in for a version or two and then remove it.
