### ISSUE TITLE
Unable to run SJS with context-per-jvm = true for Spark Streaming

### ISSUE THREAD

**Issue by martin-voigt** [spark-jobserver/spark-jobserver#535]
Hi,

we got SJS 0.6.2 successful running with  `context-per-jvm = false ` in order to lunch multiple non-streaming or one streaming application. However, we face the problem with setting `context-per-jvm = true` because we need to run Spark Streaming applications as well. What we did and what is the problem:

1. Adapted our config in the application directory
```
spark {
  master = "mesos://MESO-MASTER_IP:5050"
  job-number-cpus = 4
  jobserver {
    port = 8090
    context-per-jvm = true
    jobdao = spark.jobserver.io.JobFileDAO
    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }
    result-chunk-size = 1m
  }

  context-settings {
    num-cpu-cores = 2   
    memory-per-node = 512m  
	context-init-timeout = 60s
    passthrough {
	  spark.driver.allowMultipleContexts = true
    }
  }
  home = "/opt/spark"
}
```
2. start the SJS with `server_start.sh`. This works without problems and it is reachable via REST API and browser

3. tried to create a Streaming Context
`curl -d "" 'http://SJS-IP:8090/contexts/streaming-context?context-factory=spark.jobserver.context.StreamingContextFactory&timeout=60'`

This results
- the REST response: `The server was not able to produce a timely response to your request.`
- no error is shown, the log tells me:
```
[2016-06-30 11:51:30,976] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting context with actor name jobManager-02-a609-3d9a0534e1a9
[2016-06-30 11:51:30,987] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Created working directory /var/log/spark-jobserver/jobserver-streaming-context5295359839288158509 for context streaming-context
[2016-06-30 11:51:31,000] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting to execute sub process [./manager_start.sh, /var/log/spark-jobserver/jobserver-streaming-context5295359839288158509, akka.tcp://JobServer@127.0.0.1:60814]
```
- a subdirectory in the `$LOG_DIR` is create which comprises a file called `context.conf`
- in the web browser nor for a REST call a context is shown
- mesos does not show the context

Have you any hint for me, what could be wrong or what I may missed for the configuration?

Thanks in advance.

**Comment by noorul** [comment]
There should be a log file /var/log/spark-jobserver/jobserver-streaming-context5295359839288158509/spark-job-server.log , it might have some clue.

**Comment by martin-voigt** [comment]
Thanks. Unfortunately, there is only the `context.conf` file. Any other suggestions?

**Comment by noorul** [comment]
I am not sure why the log file is not created. Can you try increasing context-init-timeout ?

**Comment by martin-voigt** [comment]
I increased the timeout to 5min but no log file appeared. However, I think I found my problem. I added in `manager_start.sh` in the` $JAVA_OPTS` also the JMX setting from `server_start.sh`. After removing it, the instances start fine. I think the JMX port, which was already used, was the problem.
@noorul thanks for your time!

**Comment by basvandenbrink** [comment]
I am facing the same problem. First, I had to modify `deploy.manager-start-cmd = "/app/manager_start.sh"` (use the full path) to resolve an error. However, after this modification, I still cannot start streaming jobs with `context-per-jvm = true`. @martin-voigt, did you reverse your own modifications, or did you had to modify the original version of `manager_start.sh`. How did you make it work?

I am using the Spark Jobserver locally via the latest version of the Docker image (v0.6.2).

**Comment by noorul** [comment]
What exactly is the error that you are getting?

**Comment by noorul** [comment]
Can you try running https://github.com/spark-jobserver/spark-jobserver/blob/spark-2.0-preview/job-server-extras/src/main/scala/spark/jobserver/HiveTestJob.scala ?

**Comment by basvandenbrink** [comment]
Did not really get an error. However, the same application did run with `context-per-jvm = false`. It turned out the `--packages <packages>` is not passed to the forked process, so I fixed that by editing `manager_start.sh`.

However, there is an issue with the logging of forked contexts. There should be a log file for each context in `/tmp/job-server/<context_name><random_id>`, but there is none, even though the directory itself exists. I think this is a bug.

**Comment by dMidrano** [comment]
@martin-voigt can you please guide me on how you managed to solve the issue above? currently the Spark job server does not work when i set context-per-jvm = true, Thanks..
