### ISSUE TITLE
Mark killed jobs as failed instead of completed

### ISSUE THREAD

**Issue by leoromanovsky** [spark-jobserver/spark-jobserver#536]
When using the API to kill a job, such as:

`curl -X DELETE http://url/jobs/5450e2ca-468b-486e-ae15-bcfd62345d85`

The job as marked as "completed", which makes monitoring and alerting more complicated, since the job has not completed successfully. In this case, shouldn't it be considered failed?

**Comment by noorul** [comment]
I think "KILLED" should be more appropriate.

**Comment by kishorez** [comment]
Just want to add on top of it. Not sure if it should be a different issue.

Env - Spark Job Server, Yarn, Spark 1.6

When we delete a job using curl we noticed the job entry being deleted in spark job server but we still see the respective job spark context running when we look in the resource manager. Unless we delete the context in the spark job server the job is not being completely deleted in the yarn.

**Comment by noorul** [comment]
@leoromanovsky  Is this related to https://github.com/spark-jobserver/spark-jobserver/issues/222 ?

**Comment by velvia** [comment]
@kishorez …. is this an ad hoc job or a long running context?  For long running contexts the behavior you describe is completely reasonable … you don’t want to delete the context if the job is deleted.

**Comment by leoromanovsky** [comment]
I haven't personally had any problems with the job itself not terminating, this issue is mostly a discussion around the API behavior of when a job is forcefully terminated.

For further background, I'm developing a monitoring solution @strava to alert when jobs have not succeeded after a certain period of time. Jobs that are purposefully killed are currently recorded as having been `COMPLETED` by SJS which pushes back the time that an alert should have surfaced.

I'll get a PR together to address this.

**Comment by kishorez** [comment]
@velvia Yes. you are right this is a streaming job (continuous and long running). can you share the expected behavior if a job(long running) is deleted by an rest http delete. I presumed when a job is deleted it should delete the respective job running in the cluster. (Ex: Yarn)

@noorul Yes you are right it looks the same.

Documenting this behavior will be helpful

**Comment by noorul** [comment]
Closing
