### ISSUE TITLE
UI is not showing running jobs if completed jobs fills the limit

### ISSUE THREAD

**Issue by noorul** [spark-jobserver/spark-jobserver#547]
Today there is a limit of fetching 50 records and filter for different sections like Running, Completed and Failed. But over a period of time when number of completed jobs crosses 50, running jobs are no longer displayed. The logic should be changed such a way that, records should be filtered at the DB level for each section.

**Comment by TianLangStudio** [comment]
change the code in spark-jobserver-ui.js , replace /jobs to /jobs?limit=200    show more jobs    
![qq 20160728175053](https://cloud.githubusercontent.com/assets/20293523/17208574/e35bee9a-54eb-11e6-9991-b580112add55.png)

**Comment by noorul** [comment]
This is like delaying the issue.

**Comment by TianLangStudio** [comment]
Yes,if you sumbit a lot of job on one time

**Comment by noorul** [comment]
We do submit lots of job.

**Comment by TianLangStudio** [comment]
Maybe I create a patch to add a query param "status ", like /jobs?limit=200&status=running  
Somebody is working on this?

**Comment by noorul** [comment]
No one is working on this. But the approach should be to fetch data for different sections separately.

**Comment by TianLangStudio** [comment]
Add one param  don't affect other,the param is not required,I think.

**Comment by velvia** [comment]
A patch for the UI?  Sure go ahead. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by TianLangStudio** [comment]
Thanks,I'll be do it

**Comment by TianLangStudio** [comment]
I have created a pull ,[https://github.com/spark-jobserver/spark-jobserver/pull/552](https://github.com/spark-jobserver/spark-jobserver/pull/552)

**Comment by baweaver** [comment]
I can see about incorporating concerns like this in the UI side project I'm working on.

**Comment by noorul** [comment]
This is done via https://github.com/spark-jobserver/spark-jobserver/pull/552

@baweaver Is it possible for you to give an idea of what are you upto. So that anyone who might be interested in working on UI side can align with you?

**Comment by baweaver** [comment]
Right now trying to get full clearance for open source. Internal company
politics and whatnot can be pesky...

**Comment by noorul** [comment]
@baweaver Agree!

**Comment by baweaver** [comment]
I'll keep you all posted as I get clearances on things, but there will be a
mostly ready to fly project by the time I get it more than likely.

On Thu, Aug 18, 2016 at 10:23 PM, Noorul Islam K M <notifications@github.com

**Comment by TianLangStudio** [comment]
@baweaver   is your ui project open source , I'm  expecting it
