### ISSUE TITLE
Persistent Context Kills if run new job.

### ISSUE THREAD

**Issue by dhruvsinghal991** [spark-jobserver/spark-jobserver#548]
Hi, 

We have been using the spark job server for some time now on yarn, it works great when working with nonpersistent contexts. But when we ran a job in a persistent context then the context got killed giving no proper logs.

**Comment by TianLangStudio** [comment]
is the example run ok? you must be find the wrong with the job or JobServer

**Comment by noorul** [comment]
which version of spark jobserver are you using?

**Comment by noorul** [comment]
@dhruvsinghal991 Closing this. Please feel free to re-open if you are still facing this issue.
