### ISSUE TITLE
Contexts dont persist through jobserver restart

### ISSUE THREAD

**Issue by sclasen** [spark-jobserver/spark-jobserver#549]
I have a spark-jobserver set up and able to create contexts and run jobs, backed by postgres, connected to a standalone spark cluster.

I noticed that there arent any tables that reflect context information?

I created a context, uploaded a jar and  ran a job in that context successfully, restarted the job server and attempted to run the job again.  I get a 404 when that happens.

``` 
{
  "status": "ERROR",
  "result": "context first-context not found"
}
```

Is there any mechanism for persisting context information or otherwise ensuring the jobserver spins up desired contexts?

**Comment by sclasen** [comment]
Assuming here the best practice is to configure the contexts in jobserver.conf rather than by the rest api?

**Comment by velvia** [comment]
Hi Scott,

Yeah currently if you want contexts started at startup you need to configure them via the config file.  There is thought about persisting current context info for HA, but this is not slated until 0.8.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by sclasen** [comment]
Gotcha, +1 to that and HA in general, lmk if I can help.
