### ISSUE TITLE
sbt not able to resolve dependencies related to Cassandra connector

### ISSUE THREAD

**Issue by sumant28** [spark-jobserver/spark-jobserver#56]
Hi,

I am new to spark-jobserver and trying to write code which will connect to cassandra from spark-jobserver. For that I am trying to include dependencies related to spark-cassandra-connector.

In /apps/spark-jobserver-master/project/plugins.sbt I have included the plugin as follow:

addSbtPlugin("com.datastax.spark" % "spark-cassandra-connector-java_2.10" % "1.1.0" withSources() withJavadoc())

When I run sbt command at path /apps/spark-jobserver-master/ it is giving me error as : 

*********************************************************************************************************************
[info] Loading global plugins from /home/cloud/.sbt/0.13/plugins
[info] Updating {file:/home/cloud/.sbt/0.13/plugins/}global-plugins...
[info] Resolving com.datastax.cassandra#cassandra-driver-core;2.0.2 ...
[warn] 	module not found: com.datastax.cassandra#cassandra-driver-core;2.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/cloud/.ivy2/local/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/datastax/cassandra/cassandra-driver-core_2.10_0.13/2.0.2/cassandra-driver-core-2.0.2.pom
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
[warn] ==== bintray-sbt-plugin-releases: tried
[warn]   http://dl.bintray.com/content/sbt/sbt-plugin-releases/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.datastax.cassandra#cassandra-driver-core;2.0.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.datastax.cassandra:cassandra-driver-core:2.0.2 (sbtVersion=0.13, scalaVersion=2.10)
[warn] 
sbt.ResolveException: unresolved dependency: com.datastax.cassandra#cassandra-driver-core;2.0.2: not found

[error] (*:update) sbt.ResolveException: unresolved dependency: com.datastax.cassandra#cassandra-driver-core;2.0.2: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

*********************************************************************************************************************

Am I missing something here ? Do I need to update any other file for this ?
Can someone help me to solve this issue ?

Thanks in advance.

**Comment by velvia** [comment]
Not too sure.   cc'ing one of the committers of the spark connector, maybe
Helena can help  :)

On Wed, Jan 28, 2015 at 11:22 AM, sumant28 <notifications@github.com> wrote:

> Hi,
>
> I am new to spark-jobserver and trying to write code which will connect to
> cassandra from spark-jobserver. For that I am trying to include
> dependencies related to spark-cassandra-connector.
>
> In /apps/spark-jobserver-master/project/plugins.sbt I have included the
> plugin as follow:
>
> addSbtPlugin("com.datastax.spark" % "spark-cassandra-connector-java_2.10"
> % "1.1.0" withSources() withJavadoc())
>
> When I run sbt command at path /apps/spark-jobserver-master/ it is giving
> me error as :
> ------------------------------
>
> [info] Loading global plugins from /home/cloud/.sbt/0.13/plugins
> [info] Updating {file:/home/cloud/.sbt/0.13/plugins/}global-plugins...
> [info] Resolving com.datastax.cassandra#cassandra-driver-core;2.0.2 ...
> [warn] module not found: com.datastax.cassandra#cassandra-driver-core;2.0.2
> [warn] ==== typesafe-ivy-releases: tried
> [warn]
> http://repo.typesafe.com/typesafe/ivy-releases/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
> [warn] ==== sbt-plugin-releases: tried
> [warn]
> http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
> [warn] ==== local: tried
> [warn]
> /home/cloud/.ivy2/local/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
> [warn] ==== public: tried
> [warn]
> http://repo1.maven.org/maven2/com/datastax/cassandra/cassandra-driver-core_2.10_0.13/2.0.2/cassandra-driver-core-2.0.2.pom
> [warn] ==== sbt-plugin-releases: tried
> [warn]
> http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
> [warn] ==== bintray-sbt-plugin-releases: tried
> [warn]
> http://dl.bintray.com/content/sbt/sbt-plugin-releases/com.datastax.cassandra/cassandra-driver-core/scala_2.10/sbt_0.13/2.0.2/ivys/ivy.xml
> [info] Resolving org.fusesource.jansi#jansi;1.4 ...
> [warn] ::::::::::::::::::::::::::::::::::::::::::::::
> [warn] :: UNRESOLVED DEPENDENCIES ::
> [warn] ::::::::::::::::::::::::::::::::::::::::::::::
> [warn] :: com.datastax.cassandra#cassandra-driver-core;2.0.2: not found
> [warn] ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]
> [warn] Note: Some unresolved dependencies have extra attributes. Check
> that these dependencies exist with the requested attributes.
> [warn] com.datastax.cassandra:cassandra-driver-core:2.0.2
> (sbtVersion=0.13, scalaVersion=2.10)
> [warn]
> sbt.ResolveException: unresolved dependency:
> com.datastax.cassandra#cassandra-driver-core;2.0.2: not found
>
> error sbt.ResolveException: unresolved dependency:
> com.datastax.cassandra#cassandra-driver-core;2.0.2: not found
> Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
> ------------------------------
>
> Am I missing something here ? Do I need to update any other file for this ?
> Can someone help me to solve this issue ?
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/56>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by helena** [comment]
Hi,
the spark-cassandra-connector is not an sbt plugin, it's a library ;) that's your issue.

just add this to your sbt build:

"com.datastax.spark" %% "spark-cassandra-connector-java" % "1.1.0"

but note: this is compatible with spark version 1.1.0, so if you are using spark 1.2.0, you need to use connector version 1.2.0-alpha

Cheers,
Helena

**Comment by sumant28** [comment]
Hi Helena,

I suspected that its not plugin.
As you said I added the the line to my sbt build file and it compiled successfully.

Thanks for your help :)
