### ISSUE TITLE
HTTP method not allowed while creating SparkSQL Context

### ISSUE THREAD

**Issue by rahuljain788** [spark-jobserver/spark-jobserver#562]
creating a new Spark SQL context using curl command 
curl -d "" 'localhost:8090/contexts/sql-context?context-factory=spark.jobserver.context.SQLContextFactory'

results in error : http method not allowed supported methods get

**Comment by hntd187** [comment]
Can you look at the logs and give us the full error

**Comment by rahuljain788** [comment]
$ curl -d "" "localhost:8090/context/sql-context?context-factory=spark.jobserver.context.SQLContextFactory" --verbose
* timeout on name lookup is not supported
*   Trying ::1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (::1) port 8090 (#0)
> POST /context/sql-context?context-factory=spark.jobserver.context.SQLContextFactory HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.49.1
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 405 Method Not Allowed
< Server: spray-can/1.3.3
< Date: Mon, 08 Aug 2016 16:55:37 GMT
< Allow: GET
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 47
* HTTP error before end of send, stop sending
<
{ [47 bytes data]
100    47  100    47    0     0   1516      0 --:--:-- --:--:-- --:--:--  3133HTTP method not allowed, supported methods: GET
* Closing connection 0

**Comment by rahuljain788** [comment]
tried again with : curl -X OPTIONS -v "localhost:8090/context/sql-context?context-factory=spark.jobserver.context.SQLContextFactory" --verbose

* timeout on name lookup is not supported
*   Trying ::1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (::1) port 8090 (#0)
> OPTIONS /context/sql-context?context-factory=spark.jobserver.context.SQLContextFactory HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: spray-can/1.3.3
< Date: Mon, 08 Aug 2016 17:59:59 GMT
< Access-Control-Allow-Methods: OPTIONS, GET
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Accept-Encoding, Accept-Language, Host, Referer, User-Agent
< Access-Control-Max-Age: 1728000
< Content-Length: 0
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

Though i still cannot see the context in Spark Job Server UI

**Comment by hntd187** [comment]
How are you running this? ReStart? Or some other method?

**Comment by rahuljain788** [comment]
I was not doing "assembly" after "project job-server-extras" because of this it was showing NoClassFoundException. 

I am able to submit "sql-context" over the server now.
