### ISSUE TITLE
when the spark-jobserver can support spark 1.6.2?

### ISSUE THREAD

**Issue by lhcg** [spark-jobserver/spark-jobserver#566]
I am setting up spark on yarn, and  the spark's version is 1.6.2.  Can you tell me when the spark-jobserver can make the jobserver-0.6.3-spark1.6.2  branch?

**Comment by hntd187** [comment]
You can just change the version yourself during the build. Minor versions of spark are backwards compatible so you can just bump the version up no problem.

**Comment by mozinrat** [comment]
Did you guys published any docker container also for the job-server with spark 1.6.2

**Comment by noorul** [comment]
@mozinrat We do not have a docker image for 1.6.2. But it is pretty straight forward to create one. As @hntd187 mentioned you can create your own branch jobserver-0.6.2-spark1.6.2 from jobserver-0.6.2-spark1.6.1 branch and bump spark version to 1.6.2. Compile the code and use sbt docker to get build the docker image.

**Comment by hntd187** [comment]
Yea @noorul I think we can close this, the method of building it is well documented and it's a minor version so there is no reason it shouldn't be compatible.
