### ISSUE TITLE
Unable to set num executors on yarn-client

### ISSUE THREAD

**Issue by dannylinden** [spark-jobserver/spark-jobserver#58]
How can i set the max. number of Yarn Containers to allocate?

```
  passthrough {
  "--num-executors" = 4
  }
```

does not work?

**Comment by qiaohaijun** [comment]
https://github.com/spark-jobserver/spark-jobserver/issues/47

**Comment by qiaohaijun** [comment]
this closed issuse maybe useful 
https://github.com/spark-jobserver/spark-jobserver/issues/47

**Comment by velvia** [comment]
I thought somebody else solved this issue.

On Thu, Jan 29, 2015 at 8:06 PM, qiaohaijun <notifications@github.com>
wrote:

> this closed issuse maybe useful
> #47 <https://github.com/spark-jobserver/spark-jobserver/issues/47>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/58#issuecomment-72151269>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by qiaohaijun** [comment]
this is not a issue but not enough detailed document
