### ISSUE TITLE
Maven repository issues

### ISSUE THREAD

**Issue by djodar** [spark-jobserver/spark-jobserver#587]
Hi,
I'm trying to use the artifact `spark.jobserver:job-server-api_2.11:pom:0.6.2` in my maven project for what I configured Bintray repository as advised in https://bintray.com/spark-jobserver/maven/job-server-api/0.6.2.

Unfortunately, Maven is not able to find the POM or jar there: 

> Unable to find resource 'spark.jobserver:job-server-api_2.11:pom:0.6.2' in repository bintray-spark-jobserver-maven (http://dl.bintray.com/spark-jobserver/maven)

Which is odd as that URL is perfectly valid and I am able to download the JAR from there correctly.
Any idea why is not automatically resolved by Maven? Thanks in advance.

``` xml
<profile>
            <repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-spark-jobserver-maven</id>
                    <name>bintray</name>
                    <url>http://dl.bintray.com/spark-jobserver/maven</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-spark-jobserver-maven</id>
                    <name>bintray-plugins</name>
                    <url>http://dl.bintray.com/spark-jobserver/maven</url>
                </pluginRepository>
            </pluginRepositories>
            <id>bintray</id>
        </profile>
```

**Comment by mbuccini** [comment]
I had the same issue. Try without "pom". It will work nevertheless.

**Comment by djodar** [comment]
Thanks for your answer @mbuccini, I don't explicitely ask for POM, I attached the error log from Maven but it doesn't find neither POM nor JAR files. I'll keep trying... Thanks

**Comment by mbuccini** [comment]
@djodar could you maybe post the dependency as you have it in pom.xml?

**Comment by djodar** [comment]
Sure,
```xml
<dependency>
  <groupId>spark.jobserver</groupId>
  <artifactId>job-server-api_2.11</artifactId>
  <version>0.6.2</version>
</dependency>

**Comment by mbuccini** [comment]
It looks good, I don't know. How about you debug a bit with
> mvn clean
> mvn -X package

**Comment by noorul** [comment]
Closing this as there is less activity

**Comment by linsimiao** [comment]
by adding 
`    <repositories>
        <repository>
            <id>job-server</id>
            <url>http://repo.spring.io/plugins-release/</url>
        </repository>
    </repositories>`

i solve the problem. Hope it would help.
