### ISSUE TITLE
is there a way to create context with config files?

### ISSUE THREAD

**Issue by loveyanbei** [spark-jobserver/spark-jobserver#588]
```
I am using spark with elasticsearch, there are some extra options 
like:
conf.set("es.index.auto.create","true")
conf.set("spark.es.resource","201608/OMS_Station")
conf.set("es.nodes","192.168.1.3:9200,192.168.1.2:9200,192.168.1.1:9200")
And the last option made me confused.
```

   conf.set("es.query", "...")
   my dsl is a bit long and inconvinent to be attached to query string.
   Can I post the string with config files to create my own SparkContext?
   DSL:
   POST /201608a/OMS_Station/_search
   {
  "query": {
    "filtered": {
      "query": {
        "bool": {
          "should": [
            {
              "match_phrase": {
                "内容": "退出"
              }
            },
            {
              "match_phrase": {
                "内容": "中断"
              }
            }
          ]
        }
      }
    }
  }
}

**Comment by noorul** [comment]
You can get this as json body and set it

**Comment by loveyanbei** [comment]
spark.context-settings {
    spark.cores.max = 10
    passthrough {
      some.custom.hadoop.config = "192.168.1.1"
    }
}
you mean replacing nodes under passthrough?
I tried ,got Internal server error : The server cannot generate timely response

**Comment by noorul** [comment]
closing this
