### ISSUE TITLE
Job Server Concurrent Requests

### ISSUE THREAD

**Issue by pronoleg** [spark-jobserver/spark-jobserver#59]
Hi, we are testing Spark Job server version 0.4.1 in YARN mode with FAIR job scheduler. Currently we have an issue with concurrent requests testing. The problem is that server can run only 6 concurrent same requests at the moment. It refuses to accept any more with the below error:
{
  "status": "NO SLOTS AVAILABLE",
  "result": "Too many running jobs (6) for job context 'con'"
}
Each request just queries the same Cached RDD in memory via SQLContext and prints the count of rows to the output. Could you please advise are there any restrictions to run many queries at the same time?

**Comment by velvia** [comment]
Hi pronoleg,

The number of concurrent queries is limited by currently:
- the size of the thread pool
- the setting of the number of outstanding concurrent jobs (

* {{{
 *   spark {
 *     jobserver {
 *       max-jobs-per-context = 16      # Number of jobs that can be run
simultaneously per context
 *     }
 *   }

The other question I have for you is, you are not using the latest
SQLContext support, right?  Therefore with each job, you need to create the
SQLContext from scratch, is that right?  That likely introduces a high
latency.  This will get much better once I merge in the SQLContext support.

-Evan


On Mon, Feb 2, 2015 at 7:26 AM, pronoleg <notifications@github.com> wrote:

> Hi, we are testing Spark Job server version 0.4.1. Currently we have an
> issue with concurrent requests testing. The problem is that server can run
> only 6 concurrent same requests at the moment. It refuses to accept any
> more with the Unexpected response status: 503:Service Unavailable error.
> Each request just queries the same Cached RDD in memory via SQLContext and
> prints the count of rows to the output. Could you please advise are there
> any restrictions to run many queries at the same time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/59>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by pronoleg** [comment]
Hi Velvia,

Thanks for the response, the setting max-jobs-per-context is what I was looking for and it solved the issue.
You are right, we don't use the latest SQLContext support as we didn't find it. So by looking at RDD support example, we have added it by ourselves temporary for our testing needs, so each job uses the same context. It would be nice if you can give us a timeline when SQLContext support will be introduced officially.

**Comment by velvia** [comment]
@pronoleg trying to work around an issue, looking to merge in SQLContext support soon.
