### ISSUE TITLE
Update a new jar

### ISSUE THREAD

**Issue by yang0228** [spark-jobserver/spark-jobserver#591]
Dear developers,

Currently I'm using Jobserver 0.6.1 and encountered a tricky issue. I tried to update a exist old jar to a new one but failed. 

One method: try "curl -X DELETE http://localhost:8090/data/somejar", but it seems such request only support GET and POST = failed; 
Another method:  curl --data-binary .. a new jar with the old same name, and I run the job in the jar again, however it runs the content in the old jar = failed. 
These are my observations, I not sure if there's another way around to solve this, cause I think it's quite common to have such a requirement when running job on jobserver. Thanks!

**Comment by noorul** [comment]
I don't think we should be using /data api for uploading jars. Jars are uploaded using /jars api

**Comment by yang0228** [comment]
Yes, I'm using /jars API to upload jars, while how can I delete or update a jar if I don't need it?

**Comment by noorul** [comment]
@yang0228 After uploading new jar, you need to re-start the context. After that jobs will start using latest jar.

For delete see https://github.com/spark-jobserver/spark-jobserver/pull/598

Closing this.
