### ISSUE TITLE
compile spark-jobserver 0.6.1 fail

### ISSUE THREAD

**Issue by mahuichao** [spark-jobserver/spark-jobserver#593]
this is what i got,anyone know what's wrong?

> [info] Done updating.
> [info] scalastyle using config /usr/local/spark-jobserver-0.6.1/scalastyle-config.xml
> [error] /usr/local/spark-jobserver-0.6.1/job-server/src/spark.jobserver/JobStatusActor.scala: Expected token RBRACKET but got Token(XML_START_OPEN,<,3323,<)
> [error] /usr/local/spark-jobserver-0.6.1/job-server/src/spark.jobserver/context/SparkContextFactory.scala: `=',`>:', or `<:' expected, but got Token(XML_START_OPEN,<,608,<)
> [info] Processed 31 file(s)
> [info] Found 2 errors
> [info] Found 0 warnings
> I use scala 2.10.5

**Comment by noorul** [comment]
@mahuichao Is there any specific reason for using 0.6.1 ? Which branch are you trying to compile?

**Comment by noorul** [comment]
Closing this

**Comment by mahuichao** [comment]
@noorul  sorry,I forget this question,closing is ok.
