### ISSUE TITLE
sbt assembly does not work with latest push: cassandra support (#563)

### ISSUE THREAD

**Issue by yduf** [spark-jobserver/spark-jobserver#596]
I was trying to build spark-job-server from master branch, it doesn't work for me for
ac9e9caaa731b85aa90f038b7789cbe07a68f593 but it is working on previous commit
52ced0e574d44627e8236989393da0d9a02ddb12.

In latest version "sbt assembly" is failing because of conflict when merging netty-\* things.
Theses conflict seems to come from different netty-\* version/implementation being used with different content. And form my understanding have been brought by the addition of cassandra support (seen from looking at the library dependency tree).

As said when checkouting 52ced0e574d44627e8236989393da0d9a02ddb12 everything goes fine.

At the begining I was perplex that it fail on my machine, whereas it is marked as "green" by github/travis CI.  And I admit I am not used to sbt / and the build system, so bear with me.
But it is not clear looking at the  script that the "assembly" target is being tested (https://travis-ci.org/spark-jobserver/spark-jobserver/jobs/158458219/config): 
sbt clean coverage testPython test coverageReport

Is it the case ?

**Comment by hntd187** [comment]
@yduf this also fails for me, what version of scala and java are you using?

**Comment by yduf** [comment]
$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) Client VM (build 24.80-b11, mixed mode)

$ sbt scala-version
[info] job-server-extras/*:scalaVersion
[info] 	2.10.6
[info] job-server-tests/*:scalaVersion
[info] 	2.10.6
[info] job-server-api/*:scalaVersion
[info] 	2.10.6
[info] job-server-python/*:scalaVersion
[info] 	2.10.6
[info] job-server/*:scalaVersion
[info] 	2.10.6
[info] akka-app/*:scalaVersion
[info] 	2.10.6
[info] root/*:scalaVersion
[info] 	2.10.6

**Comment by noorul** [comment]
@yduf sbt's test target would run all the tests. I see that they are running fine on travis infra. Not sure what is wrong with your environment. Are you still facing this issue?

**Comment by noorul** [comment]
closing this as it is working fine on master
