### ISSUE TITLE
Escape underscores in 'doc/python.md'

### ISSUE THREAD

**Issue by dario-chiappetta** [spark-jobserver/spark-jobserver#601]
Hello everyone, just a small thing about the Python docs (`doc/python.md`): in section "Packaging a job", underscores for `__init__.py` need to be escaped, changing

    **__init__.py** A file inside the module directory...

into

    **\_\_init\_\_.py** A file inside the module directory...

Withous the slashes that name renders to just `init.py`, which may confuse the reader.

Thanks!

**Comment by noorul** [comment]
Thank you @dario-chiappetta for the patch. I pushed the change. Closing this.
