### ISSUE TITLE
How to get SQLContext from the new api method ? 

### ISSUE THREAD

**Issue by jomach** [spark-jobserver/spark-jobserver#606]
Hi until now I had a method: 

object JobServerReverseGeoRefFromRedShift extends spark.jobserver.SparkSqlJob{
    val logger = Logger.getLogger(getClass.getName)

  override def runJob(sql: SQLContext, jobConfig: Config): Any ={
    val options = GetOptions.parse_configs(jobConfig)
    ReverseGeoRefFromRedShift.run(sql.sparkContext, sql, options)
  }

  override def validate(sc: SQLContext, config: Config): SparkJobValidation ={
    val options = GetOptions.parse_configs(config)
    spark.jobserver.SparkJobValid
  }

}

migration this to the new How can I overwrite the rubJob to get the SQLContext ?

**Comment by velvia** [comment]
Sorry just to clarify.  Is the question how to adapt this to the new API?

**Comment by yiu31802** [comment]
Is there a follow-up on this original question? I have this question as well, cause the new api method does not seem to have `SparkSqlJob` in https://github.com/spark-jobserver/spark-jobserver/tree/master/job-server-api/src/main/scala/spark/jobserver
