### ISSUE TITLE
Apache Ignite - IgniteContext

### ISSUE THREAD

**Issue by nvijayap** [spark-jobserver/spark-jobserver#607]
Has anyone tested or tried with Apache Ignite (https://ignite.apache.org/use-cases/spark/sql-queries) by leveraging IgniteContext (the main entry point to Spark-Ignite integration)?

**Comment by velvia** [comment]
Nope.  Could this be raised on the google groups / discusssion lists / Gitter instead of as an issue?  Thanks. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by noorul** [comment]
https://github.com/spark-jobserver/spark-jobserver#contact

Also on the same page at the top you could see gitter badge

**Comment by noorul** [comment]
Closing this.
