### ISSUE TITLE
Unable to use yarn-client with spark 1.2.0

### ISSUE THREAD

**Issue by mshirley** [spark-jobserver/spark-jobserver#61]
I'm getting an exception when using master="yarn-client":

Caused by: java.lang.ClassNotFoundException: org.apache.spark.deploy.yarn.YarnSparkHadoopUtil

This class is in spark-yarn_2.1.0 but the latest version is 1.1.1. 

https://maven-repository.com/artifact/org.apache.spark/spark-yarn_2.10

**Comment by petro-rudenko** [comment]
It's a [spark issue](https://issues.apache.org/jira/browse/SPARK-5289) - it was [fixed in spark-1.2.1](http://spark.apache.org/releases/spark-release-1-2-1.html), need to rebuild with a new spark version.

**Comment by velvia** [comment]
Right.  Anybody want to submit a PR?

On Tue, Mar 10, 2015 at 3:54 PM, Peter Rudenko <notifications@github.com>
wrote:

> It's a spark issue <https://issues.apache.org/jira/browse/SPARK-5289> -
> it was fixed in spark-1.2.1
> <http://spark.apache.org/releases/spark-release-1-2-1.html>, need to
> rebuild with a new spark version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/61#issuecomment-78166322>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa
