### ISSUE TITLE
Executor logs

### ISSUE THREAD

**Issue by Murukaen** [spark-jobserver/spark-jobserver#610]
Hey.

Is it possible to access an aggregated version of the executor logs corresponding to a job run?

Thank you

**Comment by velvia** [comment]
So this has to do with how you configure logging in Spark, and has nothing to do with SJS.   However in general if your executors are on different hosts you’ll need something like Splunk.

**Comment by Murukaen** [comment]
Thank you for your comment. I want to point out, though, that if I run the code with spark-submit in yarn-cluster mode, I can see executor logging with `yarn logs -applicationId <application ID>`.

**Comment by hntd187** [comment]
Yes, that is because yarn is aggregating them all for you. If we pass off the job to yarn we don't have the lens into the job like that. Also if you already have it in yarn, why would you need it in SJS?

**Comment by Murukaen** [comment]
@hntd187 I ran it directly in yarn for comparison
