### ISSUE TITLE
Support for integration with zeppelin

### ISSUE THREAD

**Issue by kishorez** [spark-jobserver/spark-jobserver#615]
Hi 

Do you have any plans to integrate with Zeppelin. It will be a value addition for the job server given the adoption of the zeppelin. So that it can enable the users to author the spark job using zeppelin and deploy to a spark job server running in a remote server.

Thanks
Kishore

**Comment by hntd187** [comment]
I don't think we have any plans to do that or at least I've never heard us talk about anything related to it. That being said I don't think it'd something we would do unless someone stepped up to contribute it, it's probably a good bit of work to implement something like that.

**Comment by noorul** [comment]
@hntd187 I agree with you. Closing this.
