### ISSUE TITLE
Error: Incompatible version of org.scalactic on builld with master SJS

### ISSUE THREAD

**Issue by aarthipa** [spark-jobserver/spark-jobserver#616]
Hi,
Please note that I use SparkHiveJob on my spark applications.
Did the following steps on the master (latest) SJS
1. abt package job-server-api, job-server-extras
2. Added jars to my project.  I use Scala 2.11.8 for my project.
3. On build, I get the following errors

[ERROR] error: missing or invalid dependency detected while loading class file 'SparkJobBase.class'.
[INFO] Could not access type Or in value org.scalactic,
[INFO] because it (or its dependencies) are missing. Check your build definition for
[INFO] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[INFO] A full rebuild may help if 'SparkJobBase.class' was compiled against an incompatible version of org.scalactic.

Am I missing something here?

**Comment by hntd187** [comment]
Package doesn't include any dependencies, you are packaging those 2 projects with none of their supporting libraries. Add scalatic to your project as a dependency and any other dependencies.

**Comment by aarthipa** [comment]
Thanks. Doing a sbt assembly on the project builds a fat jar. This resolves the problem.
