### ISSUE TITLE
Type casting with NamedDataFrame

### ISSUE THREAD

**Issue by aarthipa** [spark-jobserver/spark-jobserver#617]
I used SJS for my project and would like to know how NamedDataFrame from SJS works. My first program does this

```
val schemaString = "parm1:int,parm2:string,parm3:string,parm4:string,parm5:int,parm6:string,parm7:int,parm8:int"
val schema = StructType(schemaString.split(",").map(fieldName => StructField(fieldName.split(":")(0), getFieldTypeInSchema(fieldName.split(":")(1)),true)))   

val eDF1 = hive.applySchema(rowRDD1, schema)
this.namedObjects.getOrElseCreate("edf1", new NamedDataFrame(eDF1, true, StorageLevel.MEMORY_ONLY))  
```

My second program does this to retrieve the DataFrame.

 `val eDF1: Option[NamedDataFrame]   = this.namedObjects.get("eDF1")
`
Here I only able to use Option. How must I cast NamedDataFrame to a Spark DataFrame?

Is something of this equivalent available?

this.namedObjects.get[(Int,String,String,String,Int,String,Int,Int)]("eDF1")

Appreciate the help.

**Comment by noorul** [comment]
Here is an example https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server-extras/src/spark.jobserver/NamedObjectsTestJob.scala

**Comment by aarthipa** [comment]
@noorul - The above example does not say how to retrieve a Dataframe. Here are some lines from your example. Can you say how to retrieve df1 while keeping the StructType?
```
    val struct = StructType(
        StructField("i", IntegerType, true) ::
          StructField("b", BooleanType, false) :: Nil)
      val df = sqlContext.createDataFrame(rows(sc), struct)
      namedObjects.update("df1", NamedDataFrame(df, true, StorageLevel.MEMORY_AND_DISK))
```

**Comment by aarthipa** [comment]
Just wanted to share that I was able to resolve this by doing the following
To save:
namedObjects.getOrElseCreate("df:eDF2", new NamedDataFrame(erDF2, true, StorageLevel.MEMORY_ONLY))
To retrieve:
val NamedDataFrame(erDF2, _, _) = namedObjects.get[NamedDataFrame]("df:eDF2").get
The schema of erDF2 is preserved.
