### ISSUE TITLE
Hello, when will the jobserver support spark 1.2.0, thanks

### ISSUE THREAD

**Issue by litaotao** [spark-jobserver/spark-jobserver#62]
Hello, when will the jobserver support spark 1.2.0, thanks
And is there any place to talk about this project, such as mailing list, IRC or blogs, thanks very much.

**Comment by velvia** [comment]
Master already has 1.2.0 support merged in.   If you are asking about
released artifacts, this is coming soon.

On Tue, Feb 3, 2015 at 6:51 PM, litaotao <notifications@github.com> wrote:

> Hello, when will the jobserver support spark 1.2.0, thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/62>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by qiaohaijun** [comment]
we are using spark 1.2

**Comment by velvia** [comment]
@litaotao please sign up for spark-jobserver google group, you can reach everyone there.  Thanks.
Going to close as 1.2.0 already in master and working, and release coming soon.
