### ISSUE TITLE
 GET jobs 500 (Internal Server Error)

### ISSUE THREAD

**Issue by raghumarla** [spark-jobserver/spark-jobserver#622]
All,

I compiled and started Spark Job Server (Cloudera version -from https://github.com/bjoernlohrmann/spark-jobserver ) . I see 500 error while fetching jobs but contexts and jars are loading fine.

It looks like requests is timing out and I don't see anything in logs. Any help on this issue is greatly appreciated.

Thanks,
Raghu

**Comment by noorul** [comment]
Can you create a ticket against https://github.com/bjoernlohrmann/spark-jobserver ? If you see same issue here, please feel free to re-open.
