### ISSUE TITLE
Dependent jar path

### ISSUE THREAD

**Issue by girishbin** [spark-jobserver/spark-jobserver#631]
Hi 
Its not a issue but curios to know , sorry for posting it here.

I posted a jar. 
`curl --data-binary @/PATH/jobs_jar_2.10-1.0.jar 192.168.0.115:8090/jars/job_registered`

Created a new context with with dependent jar.

`curl -d "" 'http://192.168.0.115:8090/contexts/new_context?dependent-jar-uris=file:///path/dependent.jar'`

There is tmp space where jobserver keeps the main jar 
`/tmp/spark-job-server/filedao/data/`

Where will the dependency jars are placed as I do not see it in "tmp" jobserver space ?

In log it says 
`http://192.168.0.115:39898/jars/job_registered.jar` is picking from.

Thanks

**Comment by noorul** [comment]
@girishbin dependent-jar-uris=file:///path/dependent.jar you are giving the path from where it needs to be picked. But spark driver will serve it over HTTP for worker to download.

**Comment by girishbin** [comment]
@noorul  Thanks you
