### ISSUE TITLE
"message": "org.apache.spark.SparkException: File ./xxx-2016-10-21T18_03_06.005Z.jar exists and does not match contents of http://:46219/jars/xxx-2016-10-21T18_03_06.005Z.jar",

### ISSUE THREAD

**Issue by cgeorge-rms** [spark-jobserver/spark-jobserver#635]
"message": "org.apache.spark.SparkException: File ./xxx-2016-10-21T18_03_06.005Z.jar exists and does not match contents of http://:46219/jars/xxx-2016-10-21T18_03_06.005Z.jar"
After doing some digging I've found that when two different job classpaths are being executed using the same appName I hit this exception.
I found that setting the following spark conf property seems to solve the issue:
spark.files.overwrite = true
However this is kinda a hacky solution.
I think it would be better that instead of always checking the latest jar date and adding it to the context, that we should maintain the cached list of jars without the date and only add a given jar once to the context. 
I say this because:
1. since classloading prevents a class from reloading once it's already been loaded.
2. if I loaded Class A and then upload a jar and then loaded Class B I would actually get class B from the newer jar... but executions from A would be from older jar... this is really confusing.

So why not just check the cache for the appName regardless of date/classpath for the context... and if it doesn't exist in the cache then go ahead and check the latest date and load the jar.

**Comment by noorul** [comment]
@cgeorge-rms I think one should restart the context/adhoc-job.

**Comment by cgeorge-rms** [comment]
so we don't see a context failing when we upload a new jar to be an issue? I think we should be able to restart the context when it makes sense for the application. Or spin up a new context that will use the latest jar and then transition calls/jobs to that new context and then shutdown the old context. Currently things just fail with concurrent users on a new jar and erratic behavior.

**Comment by hntd187** [comment]
Well, when a context is spun up it's jars are set and cached, they can't be updated or changed. In spark 1.6.2 configuration was static at runtime and couldn't be changed. So in order to get a new jar you'd have to restart the context no matter what

**Comment by cgeorge-rms** [comment]
I get that I need to restart the context to get the new jar... but I would like to have the existing context not crash/have issues when a new jar is uploaded prior to restart.

**Comment by hntd187** [comment]
Well, it seems normal to me that if you were to change an outside resource which Spark is expecting not to change then when it actually tries to access it Spark would freak out and just fail. This is kind of more of a Spark issue than an SJS issue, but I agree, SJS could be more tolerant to such errors.
