### ISSUE TITLE
Java Job Server implementation: Compilation exception when extending the class 'spark.jobserver.JavaSparkJob'

### ISSUE THREAD

**Issue by balakrishnadhanekula** [spark-jobserver/spark-jobserver#640]
I am getting compile time exception when extending the class 'spark.jobserver.JavaSparkJob'

'The return types are incompatible for the inherited methods SparkJobBase.validate(Object, JobEnvironment, Config), JavaSparkJob.validate(Object, JobEnvironment, Config)'

[sparkjobserver_wordcount.txt](https://github.com/spark-jobserver/spark-jobserver/files/561478/sparkjobserver_wordcount.txt)

**Comment by velvia** [comment]
Sorry, hang on….   new Java API is coming shortly.

**Comment by ammills01** [comment]
I'm still seeing this issue.  Was something changed to correct it?

**Comment by velvia** [comment]
Not yet.   @htnd187 is working on a new Java API; there was a PR but he is refactoring and cleaning up stuff.

**Comment by ammills01** [comment]
Thanks for the quick response and your continued effort on this project @velvia, and the rest of the contributors.

**Comment by MirzaGaushBeg** [comment]
i am using the https://github.com/spark-jobserver/spark-jobserver/tree/spark-2.0-preview branch as we migrated our applications to spark 2.1. i am seeing following error
`The return types are incompatible for the inherited methods SparkJobBase.validate(Object, JobEnvironment, Config), JavaSparkJob.validate(Object, JobEnvironment, 
 Config)`

**Comment by hntd187** [comment]
@MirzaGaushBeg no support for spark 2 right now, so don't expect it to work at all. The new java api in here is pretty different, I prolly have to remove the old java API since it's confusing a lot of people with what to use and what to return.

**Comment by dgrinwald93** [comment]
@hntd187 Hey Stephen. I'm having the same compile time exception, saying : "The return types are incompatible for the inherited methods SparkJobBase.validate(Object, JobEnvironment, Config), JavaSparkJob.validate(Object, JobEnvironment, Config)" when extending "JavaSparkJob". I'm using spark-2.1.1 and the spark-jobserver version is : "0.8.0-SNAPSHOT" . Is there a solution yet to fix that problem?
Thanks in advance for your help, 
Dennis

**Comment by hntd187** [comment]
I do not believe you are suppose to extend you it, you are supposed to implement it as it is an interface.

**Comment by dgrinwald93** [comment]
@hntd187 Hi Stephen, thank you for your quick response! I'm referencing on the Java class as described in this post: https://nishutayaltech.blogspot.com/2016/06/how-to-write-spark-jobs-in-java-for.html?showComment=1506384549335#c7735994576895122493

It looks like it is the same issue as @balakrishnadhanekula already mentioned. Can this issue be fixed yet?
Thanks again for reaching out and your effort!
