### ISSUE TITLE
Spark 2.0

### ISSUE THREAD

**Issue by watsondavetrendalyze** [spark-jobserver/spark-jobserver#641]
Hello is there an update on the 2.0 support? Is this plan for SJS 0.70?

**Comment by velvia** [comment]
The plan is to merge 2.0 support to a branch and release 0.7.0 with big API changes and 1.6.x… though we could flip that and release 0.7.0 with Spark 2.0 support.

**Comment by aadu** [comment]
2.0 support would be great. What is the timeline looking like?

**Comment by hntd187** [comment]
Please refer to #570 for spark 2.0 support
