### ISSUE TITLE
RabbitMq in java

### ISSUE THREAD

**Issue by NirMendel** [spark-jobserver/spark-jobserver#642]
Hey,

I'm trying to write a simple job that just listens to rabbit-mq.
I'm using spark 1.6.1, from jobserver-0.6.2-spark1.6.1 branch.
My sbt version is 0.13.11.

I downloaded the rabbit-client jars, and put them under "lib" folder in job-server-tests:
spark-jobserver
---- job-server-tests
--------lib
------------*.jar
--------src
...
-------------- Send.java

It succeeds when I'm compiling the code: "sbt package", no compilation errors (when I remove the lib directory, it fails since it doesn't know rabbitmq in my Send.java code).

My Send.java is:
`package spark.jobserver;

import java.util.ArrayList;
import com.typesafe.config.Config;
import org.apache.spark.api.java.JavaSparkContext;
import spak.jobserver.JavaSparkJob;

import com.rabbitmq.client.ConnectionFactory;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.Channel;

public class Send extends JavaSparkJob {
    private final static String QUEUE_NAME = "hello_queue";

    @Override
    public Object runJob(JavaSparkContext jsc, Config jobConnfig) {
        try {
        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("rabbitmq-host");
        factory.setPort + setUsername + setPassword
        return "Success";
        }
        catch (Exception ex) {
            System.out.println("WTF");
            return "Failure";
        }
    }
}`

I'm starting the jobserver using docker (the jobserver is and working, since other jobs are running and working).

I'm uploading the jar file from the sbt:
`curl --data-binary @path-to-jar localhost:8090/jars/MyApp`

And when I'm trying to call my Send job:
`curl -d "" 'localhost:8090/jobs?appName=MyApp&classPath=spark.jobserver.Send`
I can see in the logs that an exception is throws:

Exception in thread "pool-39-thread-1" java.lang.NoClassDefFoundError: com/rabbitmq/client/ConnectionFactory
    at spark.jobserver.Send.runJob(Send.java:18)
    at spark.jobserver.JavaSparkJob.runJob(JavaSparkJob.scala:17)
    at spark.jobserver.JavaSparkJob.runJob(JavaSparkJob.scala:14)
   ...
Caused by: java.lang.ClassNotFoundException: com.rabbitmq.client.ConnectionFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
...

What could be the reason?
Has anyone worked with sparkjobserver and rabbitmq?

Thanks,
Nir

**Comment by hntd187** [comment]
Because when the job server starts up it doesn't have dependent jar you are looking for. The documentation talks about this in, so you can find how to properly do that here https://github.com/spark-jobserver/spark-jobserver#dependency-jars

**Comment by NirMendel** [comment]
Thanks, I added the dependency-jars and it worked.
