### ISSUE TITLE
SJS throws: No slots available while no jobs are running in a persistent context.

### ISSUE THREAD

**Issue by dhruvsinghal991** [spark-jobserver/spark-jobserver#645]
Hi,

I have a running context for more than 33.4 hrs, with no running jobs. When I try to start a new job, SJS throws me the following response.

`{
  "status": "NO SLOTS AVAILABLE",
  "result": "Too many running jobs (8) for job context 'pipeline_279'"
}`

The limit for max-jobs-per-context is set to default 8. There are no threads running for the current context. 

It will be really helpful if someone can guide me through this.

Thanks.

**Comment by noorul** [comment]
I think the jobs here mean the tasks. So even if you submit a single job there could be many tasks. Why don't you increase the value for max-jobs-per-context

**Comment by noorul** [comment]
Closing this
