### ISSUE TITLE
0.6.2  on spark 1.6.0

### ISSUE THREAD

**Issue by girishbin** [spark-jobserver/spark-jobserver#662]
QUESTION:
Do jobserver version 0.6.2 works for cloudera spark 1.6.0 ?  Is there any hard restriction that specific version  of jobserver only works with a specific version of spark as mentioned in the table. 

0.6.0	1.4.1
0.6.1 	1.5.2
0.6.2	1.6.1
master	1.6.2

Any help will be great.

**Comment by noorul** [comment]
Yes, it is better to follow the matrix.
