### ISSUE TITLE
How to Use Dynamic Resource Allocation in spark-jobserver

### ISSUE THREAD

**Issue by YuanGunGun** [spark-jobserver/spark-jobserver#664]
I use under config in context-settings :

passthrough {
  spark.executor.heartbeatInterval = 60s
  spark.port.maxRetries = 100
  spark.dynamicAllocation.enabled = true
  spark.shuffle.service.enabled = true
  spark.shuffle.service.port = 7337
  spark.dynamicAllocation.minExecutors = 1
  spark.dynamicAllocation.maxExecutors = 30
  spark.dynamicAllocation.schedulerBacklogTimeout = 1s
  spark.dynamicAllocation.sustainedSchedulerBacklogTimeout = 5s
  spark.dynamicAllocation.executorIdleTimeout = 60s
}

but these doesn't work.

The Job Submitted by spark-jobserver only have two executor, one of them is driver

**Comment by YuanGunGun** [comment]
reference:
https://spark.apache.org/docs/1.6.1/job-scheduling.html#dynamic-resource-allocation

**Comment by velvia** [comment]
Well, technically it does work, because you requested minimum one executor, and you got one right?  :)

**Comment by YuanGunGun** [comment]
Thanks velvia. I only got one, How can I use dynamic allocation in jobsvr?

**Comment by YuanGunGun** [comment]
I found information from the office website: 

The number of executors. Note that this property is incompatible with spark.dynamicAllocation.enabled. If both spark.dynamicAllocation.enabled and spark.executor.instances are specified, dynamic allocation is turned off and the specified number of spark.executor.instances is used.

And I found spark.executor.instances = 1 in driver environment, How can I remove the spark.executor.instances parameter or let spark.executor.instances  has  no effect

**Comment by velvia** [comment]
Hm, there is nothing job server itself is inserting, we don’t insert spark.executor.instances.   Are you sure you are not injecting it, say in your job server config?

**Comment by noorul** [comment]
@YuanGunGun Do you need further information?

**Comment by noorul** [comment]
Closing this.

**Comment by YuanGunGun** [comment]
@noorul @velvia  I check My code servery times, And I don't find spark.executor.instances

below is my jobsvr config

`context-settings {
     spark.driver.port = 32456
     num-cpu-cores = 16     # Number of cores to allocate.  Required.
     memory-per-node = 32g         # Executor memory per node, -Xmx style eg 512m, #1G, etc.
 
     spark.yarn.queue = bkdata.default
     spark.yarn.jar = "hdfs:///nfsserver/spark_support/core/spark-assembly-1.6.1-hadoop2.6.0-cdh5.4.1.jar"

 
 
     # Timeout for SupervisorActor to wait for forked (separate JVM) contexts to initialize
     context-init-timeout = 600s
 
     # Add settings you wish to pass directly to the sparkConf as-is such as Hadoop connection
     # settings that don't use the "spark." prefix
     passthrough {
       spark.executor.heartbeatInterval = 120s
       spark.port.maxRetries = 100
       # for yarn dynamic 
       spark.dynamicAllocation.enabled = true
       spark.shuffle.service.enabled = true
       spark.shuffle.service.port = 7337
       spark.dynamicAllocation.minExecutors = 1
       spark.dynamicAllocation.maxExecutors = 30
       spark.dynamicAllocation.schedulerBacklogTimeout = 1s
       spark.dynamicAllocation.sustainedSchedulerBacklogTimeout = 5s
       spark.dynamicAllocation.executorIdleTimeout = 60s
       #spark.driver.allowMultipleContexts = true
	 }
}

`

**Comment by YuanGunGun** [comment]
@velvia @noorul wish your answer

**Comment by velvia** [comment]
I would look in spark UI and it should be able to tell you where the instances are coming from.  There is a tab for environment.
Have you tried overriding it in your SJS config to do what you want?
Also make sure you are not disabling dynamic allocation.

**Comment by YuanGunGun** [comment]
@velvia  Thanks for your reply. I try to remove spark.executor.instances in my sjs config, but it not effect . And  I'm sure that I'm not close dynamic allocation
