### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ww102111** [spark-jobserver/spark-jobserver#666]
[info] Application job-server-extras not yet started
[info] Starting application job-server-extras in the background ...
job-server-extras Starting spark.jobserver.JobServer.main()
job-server-extras[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
job-server-extras[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=512M; support was removed in 8.0
[info] Application root not yet started
job-server-python[ERROR] Error: Could not find or load main class spark.jobserver.JobServer
job-server-python ... finished with exit code 1
[trace] Stack trace suppressed: run last root/*:reStart for the full output.
[trace] Stack trace suppressed: run last akka-app/*:reStart for the full output.
[trace] Stack trace suppressed: run last job-server-api/*:reStart for the full output.
[error] (root/*:reStart) No main class detected!
[error] (akka-app/*:reStart) No main class detected!
[error] (job-server-api/*:reStart) No main class detected!
[error] Total time: 140 s, completed Dec 1, 2016 4:01:24 AM

**Comment by noorul** [comment]
How are you starting job-server ?

**Comment by noorul** [comment]
Closing this. Feel free to re-open once you have more information to provide.

**Comment by akontaxakis** [comment]
same issue here I am just doing reStart or job-server-api/reStart in the sbt shell.
