### ISSUE TITLE
can not find class SparkJobValidation in the job-server-tests-0.4.1.jar

### ISSUE THREAD

**Issue by liu-hongwei** [spark-jobserver/spark-jobserver#67]
hi,

i am trying to directly submit the test job to spark cluster like below, but failed.

$ bin/spark-submit --class "spark.jobserver.WordCountExample" --master "spark://127.0.0.1:7077" "/home/localadmin/test/job-server-tests-0.4.1.jar"

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
Exception in thread "main" java.lang.NoClassDefFoundError: spark/jobserver/SparkJobValidation
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:301)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:55)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: spark.jobserver.SparkJobValidation
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

here is how i build the spark job server code:

spark-jobserver-0.4.1$ sudo sbt package

this will generate the jars files.

i could not use run this :
$ bin/server_package.sh xxx

as i get tests errors (too long, so not paste here)

why can not submit to spark? i though all the dependencies should be packaged into the final jar file.

thanks in advance.

**Comment by velvia** [comment]
Hi,

The job server is incompatible with spark-submit.  The jobs are not
designed to be standalone applications, but rather run with the admin
interface of the job server, and spark-submit is not designed to allow for
job server type programs to run.

Also, you want to build using "sbt assembly" to create a jar with all the
dependencies.  The job-server-tests jar only has the test files, not job
server itself.

On Fri, Feb 6, 2015 at 3:51 PM, liu-hongwei <notifications@github.com>
wrote:

> hi,
>
> i am trying to directly submit the test job to spark cluster like below,
> but failed.
>
> $ bin/spark-submit --class "spark.jobserver.WordCountExample" --master
> "spark://127.0.0.1:7077"
> "/home/localadmin/test/job-server-tests-0.4.1.jar"
>
> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option
> MaxPermSize=128m; support was removed in 8.0
> Exception in thread "main" java.lang.NoClassDefFoundError:
> spark/jobserver/SparkJobValidation
> at java.lang.Class.getDeclaredMethods0(Native Method)
> at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
> at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
> at java.lang.Class.getMethod0(Class.java:3010)
> at java.lang.Class.getMethod(Class.java:1776)
> at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:301)
> at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:55)
> at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> Caused by: java.lang.ClassNotFoundException:
> spark.jobserver.SparkJobValidation
> at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ... 8 more
>
> here is how i build the spark job server code:
>
> spark-jobserver-0.4.1$ sudo sbt package
>
> this will generate the jars files.
>
> i could not use run this :
> $ bin/server_package.sh xxx
>
> as i get tests errors (too long, so not paste here)
>
> why can not submit to spark? i though all the dependencies should be
> packaged into the final jar file.
>
> thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/67>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by hntd187** [comment]
Since this issue is very old, if you are still having an issue please try the latest version of the code and if that doesn't work please open a new issue on the issue you are having. Thanks
