### ISSUE TITLE
jar too large

### ISSUE THREAD

**Issue by ww102111** [spark-jobserver/spark-jobserver#670]
how to reverse it

**Comment by ww102111** [comment]
Request Content-Length 44771687 exceeds the configured limit of 31457280root@ubuntu:~/soft#

**Comment by YuanGunGun** [comment]
Too Large jar usually produce with the reason of the jar contaion other jars. Why not seperate depend jar to   different jar?

**Comment by ww102111** [comment]
yes,but I can not how to separate depend jar to different jar.  I use the tool with maven ,is not sbt.

**Comment by noorul** [comment]
Try this configuration in your local.conf


    spray.can.server {
      parsing.max-content-length = 200m
      idle-timeout = 400s
      request-timeout = 300s
    }

**Comment by markjlaney** [comment]
I've tried this fix above and it doesn't work. I had to extract the spark-job-server jar and increase the size there. I'm running 5.0.4.

**Comment by velvia** [comment]
Sorry, what do you mean by 5.0.4?  That’s not an SJS version or Spark version.

**Comment by markjlaney** [comment]
I apologize, that was a mistake. Thought I had removed it.

**Comment by ww102111** [comment]
And now  I want to know whether I can push so large jar or not.thx

**Comment by ww102111** [comment]
And now the problem exists，I do not know how to do and please help me

**Comment by noorul** [comment]
Are you still getting the same error?

**Comment by noorul** [comment]
@ww102111 Are you still getting the same error or different one?

**Comment by noorul** [comment]
Closing this. Please re-open if required.
