### ISSUE TITLE
hive new coming data not found

### ISSUE THREAD

**Issue by e726** [spark-jobserver/spark-jobserver#673]
jobserver version：0.6.2
spark version：1.6.0
code snapshot:
override def runJob(hive: HiveContext, jobConfig: Config): Any = {
XXX
hive.sql(my own sql).collect
XXX
}

Q:
hive table is parquet format with lzo compression,  mysql data imported into it about every 5 minute using sqoop, however, when I use jobserver query this table,  new coming data not found,  after a long time (10h or more) it is found, spark-sql and hive-cli OK, any idea?  thanks in advance

**Comment by velvia** [comment]
This is most likely due to misconfiguration …. SJS just passes a HiveContext which is the same as the HiveContext you would get for Spark Shell.

**Comment by e726** [comment]
hi @velvia 
thanks for your response, HiveContext  is created by spark.jobserver.context.HiveContextFactory, configured 
in local.conf,  right?  so I dig into class HiveContextFactory, but find nothing useful, my local.conf is

spark {
  master = "yarn-client"
  job-number-cpus = 4
  jobserver {
    port = 18888
    jar-store-rootdir = /data/job-server/jars
    jobdao = spark.jobserver.io.JobFileDAO
    filedao {
      rootdir = /tmp/spark-job-server/filedao/data
    }
  }
  contexts {
     low-latency {
       num-cpu-cores = 2          
       memory-per-node = 1G        
       context-factory=spark.jobserver.context.HiveContextFactory
      }
   }
  context-settings {
    num-cpu-cores = 2        
    memory-per-node = 1G   
    context-factory=spark.jobserver.context.HiveContextFactory
    passthrough {
      #es.nodes = "192.1.1.1"
    }
  }
}
