### ISSUE TITLE
package spark-2.0 preview

### ISSUE THREAD

**Issue by girishbin** [spark-jobserver/spark-jobserver#674]
I'm packaging for "spark-2.0 preview"  branch  using below command 

"bin/server_package.sh local"

https://paste.ubuntu.com/23593516/

^^ facing problem where in I'm not able to find any of the .pom files in public  repo's  like below 

https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.10/2.4.9/

Please may I know how to solve this problem  ?

**Comment by velvia** [comment]
The problem is probably because for some reason you have Scala 2.10 in SBT.   Try doing ++2.11.8 first, then it should work.

**Comment by girishbin** [comment]
hey @velvia . Thanks it worked.
