### ISSUE TITLE
Spark Event Listener Not Triggered

### ISSUE THREAD

**Issue by markjlaney** [spark-jobserver/spark-jobserver#677]
I'm running a HelloWorld Spark job to get familiar with the technology. I have a simple job that parallelizes some data like this:

List<Integer> data = Arrays.asList(1, 2, 3, 4, 5);
JavaRDD<Integer> distData = jsc.parallelize(data);
distData.reduce((a, b) -> a + b);

I've implemented a SparkListener with some print statements in the onJobEnd method. My problem is this - my listener is only triggered the first time I run the job; after that, nothing is triggered. I have to re-start the job server for the event listener to be triggered again.

Here is the listener method:

public void onJobEnd(SparkListenerJobEnd arg0) {
			LOGGER.info("Listener Triggered");
}

Would anyone know why?

**Comment by amarouni** [comment]
I did some tests with SparkListener and I didn't see this odd behavior. That's being said, I wrote metrics in the `onApplicationEnd` callback (aggregating them in `onJobEnd` callback).
I can share some findings if you're still looking for answers.
