### ISSUE TITLE
404 response when trying to get job status when using JobSqlDao

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#682]
I noticed this problem while experimenting with the spark 2.0-preview branch, but I suspect it is also an issue on master. 

Recenlty there was a switch to use JobSqlDAO instead of JobFileDao to persist job info.
The problem I have noticed when using JobSqlDAO is that you can often get 404 errors when requesting status for a job - especially if you ask for that status immediately after submitting the request for that job. 

I have a suite of cucumber bdd integration tests for our product. It works fine using the master version of job-server (from a couple months ago) and spark 1.6.3, and JobFileDao. However, on the jobserver 2.0-preview branch, I see that JobFileDao has been deprecated and there is a push to use JobSqlDAO instead. When I run our bdd tests using JobSqlDAO there are a lot of intermittent failures caused by 404 errors when trying to get status or results. However, if I simply replace JobSqlDAO with JobFileDao in the configuration, then the errors go away and everything runs successfully.

**Comment by velvia** [comment]
Hmm interesting.  So FileDAO works better for you…. there are some edge cases where it won’t work as well as SQLDao.  Also SqlDao depends if you use the embedded H2 one or a production worthy one… I would think if you used PostGres etc. that you would not have the 404’s.

**Comment by barrybecker4** [comment]
That's possible. Are there instructions for setting up postgres for this? I have never used postgres for anything, and am a little worried about adding another moving part. What are the edge cases when FileDAO does not work? What are the general pros and cons of each? Is one of them faster? more robust?

**Comment by velvia** [comment]
Well, FileDAO does not work with ContextPerJVM.   That’s probably the biggest drawback.  It was not designed to be a super robust solution like a standard DB, just an embedded storage layer.    In theory H2 _should_ be far more robust  :-p

**Comment by noorul** [comment]
This https://github.com/spark-jobserver/spark-jobserver/pull/668 should have fixed it.

**Comment by barrybecker4** [comment]
I built my spark 2.1.0 jobserver branch (which is based on spark-2.0-preview) and which incorporates the #668 fix, but I still have the same problem when I try to run using the JobSqlDAO, so I again switched back to the deprecated JobFileDAO to get my integration tests working.

**Comment by kapil-malik** [comment]
I also incorporated #668 and yet am facing 404 error.
I am using MySQL and context per jvm = true.

**Comment by basvandenbrink** [comment]
@velvia, could you explain why the FileDAO would not work with `context-per-jvm = true`? It is because of file locks or something similar? Because for me, it actually seems to be the only solution to get it working. The SqlDAO combined with H2 causes timeouts every time I try to submit a Streaming job (I am using the 0.6.2 version of the Docker image).

**Comment by velvia** [comment]
FileDAO does not have any locking so different processes could easily corrupt each other.  Though I guess you could luck out. 

H2 is embedded by default so you have the same issue actually.  

The solution for now is to stand up a real DB.  If filedao really works for you, good tho it wasn't designed for multi process concurrency. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by basvandenbrink** [comment]
Ah, I see. Thanks for your comment. Since I don't use it in production, I think I will just continue using the FileDAO unless I get too many errors.

**Comment by basvandenbrink** [comment]
@velvia Another option is to enable [Automatic Mixed Mode](http://h2database.com/html/features.html#auto_mixed_mode). This can be enabled by adding `;AUTO_SERVER=TRUE` to the JDBC URI, which works for me.

**Comment by velvia** [comment]
Thanks Bas!   I’ll add this to the docs and maybe the default settings.

**Comment by LannyRipple** [comment]
Going through all these very issues so thought I'd add observations.

We are using spark-2.0-preview modified for spark 2.1.0

1. There is a memory leak in spark around netty threads that will bite you if you don't context-per-jvm.  Sadly FileDAO works great for us but now we are using H2.
2. Using Automatic Mixed Mode we still see errors in the logs about concurrent access (although the H2 docs seem to indicate we shouldn't see such).  We've gone to using a server setup.

*Server*
```
java -cp ./h2-1.3.176.jar org.h2.tools.Server -tcp -tcpDaemon -baseDir /tmp/spark-jobserver/filedao/data
```

*URL*
```
url = "jdbc:h2:tcp://localhost:9092/h2-db"
```

3. We are experiencing problems with the UI.  Jars and contexts resolve but jobs either shows only failed jobs or nothing but the standard page without any data.  Occasionally it will load until the next time when it will show problems.  I can't say for sure this is an H2 issue but that's the only thing we've changed (and context-per-jvm=true).

**Comment by barrybecker4** [comment]
Just to follow up on this - I think that this issue can be closed now.
I can no longer reproduce the 404 errors that I reported with the earlier spark 2.0.x preview version.
I am running 0.8.1-SNAPSHOT with spark 2.3 locally, and its working great. I have run our full suite of cucumber bdd tests many times in a row, and there are no 404 errors. I am use JobSqlDao with mysql.
One annoying thing was that I had to increase max_allowed_packet in the MySql db because apparently it tries to write the whole uploaded jar file into the database. Why does it need to write the jar into the db? Could it just write the location of it instead?
For reference, here is my config for it in local.conf:
```
jobserver {
    port = 8090
    context-per-jvm = false
    max-jobs-per-context = 16      # Number of jobs that can be run simultaneously per context
    context-creation-timeout = 20s
    short-timeout = 60s   # needed for fat jars

    jobdao = spark.jobserver.io.JobSqlDAO

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    datadao {
      # storage directory for files that are uploaded to the server
      # via POST/data commands
      rootdir = /tmp/spark-jobserver/upload
    }

    sqldao {
      slick-driver = slick.driver.MySQLDriver
      jdbc-driver = com.mysql.jdbc.Driver
      jdbc {
        url = "jdbc:mysql://localhost/job_server?createDatabaseIfNotExist=true&useSSL=false"
        user = "job_server"
        password = "******"
      }

      # DB connection pool settings
      dbcp {
        enabled = false
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }

    # When using chunked transfer encoding with scala Stream job results, this is the size of each chunk
    result-chunk-size = 1m
  }

  flyway.locations="db/mysql/migration"
```
