### ISSUE TITLE
Configure memory for mesos

### ISSUE THREAD

**Issue by vvsh** [spark-jobserver/spark-jobserver#694]
Hi,

Could you please suggest how to specify memory for spark job when it is run on mesos?

I tried spark.executor.memory, but job still has 92 MB as by default.

Thanks.

**Comment by velvia** [comment]
I think that should be the right setting.  How are you setting spark.executor.memory?

**Comment by vvsh** [comment]
I tried several places:
https://drive.google.com/file/d/0B_Qdw-RQWjukUDgxZlU3dk5INms/view?usp=drivesdk

**Comment by vvsh** [comment]
@velvia, isn't it correct?

**Comment by noorul** [comment]
@vvsh Not sure why you re-opened this issue.

**Comment by vvsh** [comment]
@noorul, I closed it by mistake, question is still relevant.

**Comment by bsikander** [comment]
Using Jobserver API you can now pass any configuration to forked JVM using `launcher.any.spark.property=value` format. e.g. launcher.spark.driver.memory=1g.
```
curl -X POST localhost:8090/contexts/batch?launcher.spark.driver.memory=1g
```

Was introduced in https://github.com/spark-jobserver/spark-jobserver/pull/982
