### ISSUE TITLE
Question: Why is config in both /config and /job-server/config?

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#697]
The exact same configuration files are in both /config and /job-server/config directories. Is that intentional? Shouldn't they only be in one place? I never know which I am supposed to be modifying, so I make the same modifications in both.

**Comment by noorul** [comment]
In the actual deployment you will have only one.

**Comment by barrybecker4** [comment]
How do I know which will be in the deployment? Why does there need to be two copies of the same configuration in the repository. As far as I can tell they are identical.

**Comment by noorul** [comment]
Agree, we need to look into it.

**Comment by noorul** [comment]
I looked into it. /config is a soft link to /job-server/config. So there are no two copies.
