### ISSUE TITLE
Spark job server creating multiple threads on server_start

### ISSUE THREAD

**Issue by cyberSane** [spark-jobserver/spark-jobserver#700]
Hi, I started the spark job server with server_start.sh , resulting it creates multiple threads with the **status sleeping** .
I am not sure why it is happening.

**Comment by velvia** [comment]
Sorry, I don’t understand what is the actual problem with multiple threads?   That is pretty normal for a server right?

**Comment by cyberSane** [comment]
Actually when i start server, around 300 threads gets created which stays in sleep condition forever.
And when i run jobs more threads spawn.
why job server spawn threads in starting when it is not going to use them?

**Comment by velvia** [comment]
Its probably Spark.  Spark creates lots of threads.  It also depends on your configuration.

**Comment by cyberSane** [comment]
Is there any config field which can limit no. threads or can kill the thread after job completion.

**Comment by hntd187** [comment]
You can look at the spark documentation on how to tune this option but otherwise this doesn't seem like an issue.
