### ISSUE TITLE
Ad-hoc Mode accept context configuration as params

### ISSUE THREAD

**Issue by RajatGoyal** [spark-jobserver/spark-jobserver#703]
I am running a job in ad-hoc mode (creating context dynamically, rather than passing it) and I want to specify the number of cores and executor memory in the job POST call itself, is it possible to achieve this? 

Different jobs require different resources. Therefore, I don't want to change the default in job-server config, I would rather want to dynamically pass the configuration. 

Currently, I am able to do it using 3 api calls. Create context with configuration -> run job -> delete context but that is a very hacky way to do it.

**Comment by noorul** [comment]
I think you could pass something like this as job config

    spark.context-settings {
        spark.cores.max = 10
    }

**Comment by RajatGoyal** [comment]
Dosen't work, I tested using this as payload

{
	"action":"sql",
	"keyspace":"test",
	"table":"demo",
	"sql":"select * from test.demo limit 10",
	"spark.context-settings": {
		"num-cpu-cores": "2",
		"memory-per-node": "1024m"
	}
}

**Comment by noorul** [comment]
Ok, as json you might have to give like this 

    {
        "spark": {
            "context-settings": {
                "spark": {
                    "ui": {
                        "port": "4040"
                    },
                    "cores": {
                        "max": "2"
                    },
                    "executor": {
                        "memory": "1g",
                        "cores": "2"
                    }
                }
            }
            }
    }

**Comment by velvia** [comment]
Try making spark and context-settings actually different JSON levels, or use Typesafe Config.

**Comment by RajatGoyal** [comment]
```
{
	"action":"sql",
	"keyspace":"test",
	"table":"demo",
	"sql":"select * from test.demo limit 10",
	"spark": {
        "context-settings": {
            "spark": {
                "cores": {
                    "max": "1"
                },
                "executor": {
                    "memory": "1g"
                }
            }
        }
    }
}
```

Thanks @noorul @velvia This works just fine

**Comment by YuanGunGun** [comment]
@RajatGoyal Do you still use the adhoc in the  "Create context with configuration -> run job -> delete context but that is a very hacky way to do it."  way
