### ISSUE TITLE
Request Content-Length 135506831 exceeds the configured limit of 31457280

### ISSUE THREAD

**Issue by vijaypabothu** [spark-jobserver/spark-jobserver#707]
Hi,
I am running spark job server in local 
I have changed the parsing.max-content-length = 150m in applications.conf and also local.conf.
Still the problem is not resolved. Please advise at the earliest. Thanks in advance.

**Comment by noorul** [comment]
Can you try this config? 

    spray.can.server {
        parsing.max-content-length = 150m
        idle-timeout = 400s
        request-timeout = 300s
    }

**Comment by vijaypabothu** [comment]
Thanks for the quick reply.

I am getting the below error after trying the setup given by you. Also my spark web server UI  on localhost:8090 is not clearing previous completed jobs and failed jobs even after restarting spark job server by re-stop and  re-start . please advise. 

Command ran :
C:\Users\vpabothu\Desktop\spark-jobserver>curl --data-binary @job-server-tests/target/scala-2.10/EaaS-0.0.1-SNAPSHOT-jar-with-dependencies.jar localhost:8090/jars/EaaS
{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/binary-manager#-2095618790]] after [3000 ms]",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)", "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)", "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)", "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)", "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)", "java.lang.Thread.run(Thread.java:745)"]
  }
}

**Comment by noorul** [comment]
@vijaypabothu I would really try to reduce the size of the JAR. See reply from @velvia  in mailing list.

It looks like the API is timing out. By default API timeout time is 3 seconds. You could try increasing it.

https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/resources/application.conf#L78

**Comment by vijaypabothu** [comment]
Thanks noorul for the quick reply.

I changed the ask pattern timeout for Api in local.conf and applications.conf. Still the problem persisits , Please advise.
    #short-timeout = 3 s
     short-timeout = 60 s

**Comment by noorul** [comment]
What is the error that you are getting now?

**Comment by vijaypabothu** [comment]
Getting the below error . Please advise
"status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/context-supervisor/b56c4193-spark.jobserver.WordCountExample#2084841685]] after [10000 ms]",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)", "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)", "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)", "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)", "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)", "java.lang.Thread.run(Thread.java:745)"]

**Comment by noorul** [comment]
This doesn't look like a JAR upload error. Are you getting this error when you do a POST /jars ?

**Comment by vijaypabothu** [comment]
I have tested for word count  (Which was working fine before ) and giving this kind of error. Please advise.
[ERROR] 17/01/24 12:37:26 INFO BlockManagerMaster: Registered BlockManager
job-server-extras[ERROR] 17/01/24 12:37:26 INFO LocalContextSupervisorActor: SparkContext a034ac04-spark.jobserver.WordCountExample initialized
job-server-extras[ERROR] 17/01/24 12:37:29 ERROR JobManagerActor: About to restart actor due to exception:
job-server-extras[ERROR] java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
job-server-extras[ERROR]        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
job-server-extras[ERROR]        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
job-server-extras[ERROR]        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
job-server-extras[ERROR]        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
job-server-extras[ERROR]        at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
job-server-extras[ERROR]        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
job-server-extras[ERROR]        at scala.concurrent.Await$.result(package.scala:107)
job-server-extras[ERROR]        at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:221)
job-server-extras[ERROR]        at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:157)

**Comment by noorul** [comment]
Can you close this issue as the problem in the subject is resolved? You can create new issue for current problem.

**Comment by vijaypabothu** [comment]
Thanks
