### ISSUE TITLE
ERROR: Jar is not of the right format

### ISSUE THREAD

**Issue by paulrinckens** [spark-jobserver/spark-jobserver#709]
I followed the instructions in the README and keep getting an Error "Jar is not of the right format" when trying to upload the generated jar of examples:

...:~/programme/spark-jobserver/job-server-tests/target$ curl --data-binary @job-server-tests/target/job-server-tests-0.4.1.jar localhost:8090/jars/test
Warning: Couldn't read data from file 
Warning: "job-server-tests/target/job-server-tests-0.4.1.jar", this makes an 
Warning: empty POST.
{
  "status": "ERROR",
  "result": "Jar is not of the right format"
}

Any idea what possibly could have gone wrong?

**Comment by noorul** [comment]
Can you try absolute path in curl command?

**Comment by paulrinckens** [comment]
Yes, I tried that but nothing changes, same error.

**Comment by noorul** [comment]
@paulrinckens Does the file really exist?

**Comment by paulrinckens** [comment]
@noorul thanks for making me doublecheck the n-th time! Absolute path did the job

**Comment by I348773** [comment]
Could you for ex. how to white use Absolute path?

**Comment by AbhayAg** [comment]
Thanks. Absolute path worked for me too.
