### ISSUE TITLE
best way to implement spark streams

### ISSUE THREAD

**Issue by jamborta** [spark-jobserver/spark-jobserver#71]
Hi all,

Just wondering if someone could point me the right direction to interact with streams in a runJob method. We have a streaming job implemented that passes the streaming context in runJob, but streams behave differently from single RDDs, so they never really return any value.

thanks,

**Comment by velvia** [comment]
What interactions are you looking for?   You are probably one of the
earlier adopters of streaming with job server, so your input would be great.

On Fri, Feb 13, 2015 at 2:01 AM, jamborta <notifications@github.com> wrote:

> Hi all,
>
> Just wondering if someone could point me the right direction to interact
> with streams in a runJob method. We have a streaming job implemented that
> passes the streaming context in runJob, but streams behave differently from
> single RDDs, so they never really return any value.
>
> thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/71>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by jamborta** [comment]
I am trying to setup a streaming ML model (e.g. regression) and would like to query to model coefficients as they get updated.

**Comment by velvia** [comment]
My guess is we need some other method to query the running job....   here's
a question for you that would help point at the answer.    Could you store
the intermediate results in some RDD in the underlying Sparkcontext?  If so
then it could be queried using a separate job that shares the same
SparkContext.

On Mon, Feb 16, 2015 at 3:37 AM, jamborta <notifications@github.com> wrote:

> I am trying to setup a streaming ML model (e.g. regression) and would like
> to query to model coefficients as they get updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/71#issuecomment-74495682>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by jamborta** [comment]
Yes, thought about that. I was aiming to solve this it in one job, as essentially the streaming job does not have any output.

**Comment by tarekabouzeid** [comment]
have you found a solution for this issue ?

**Comment by velvia** [comment]
@tarekabouzeid yeah, @zeitos is proposing that we let specialized contexts add Spray routes so that you can extend the Web API to access jobs.  I **think** that should allow to do what you want... so long as the context can be used to access the streaming state.

**Comment by zeitos** [comment]
I just found this mention! I opened https://github.com/spark-jobserver/spark-jobserver/issues/148 to discuss possible solution

**Comment by velvia** [comment]
Closing this since we have #148
