### ISSUE TITLE
Moving from Spray to akka-http

### ISSUE THREAD

**Issue by amarouni** [spark-jobserver/spark-jobserver#711]
As Spray is being superseded by akka-http is there any plans to move to akka-http ?
AFAIK akka-http provides the same spray API, so this should be relatively easy to swap spray for http-akka.

**Comment by hntd187** [comment]
Yes, but akka-http is akka 2.4 only at this point, which is Java8 and Scala 2.11+ only. We've decided not to break our compatibility with Java7 and Scala 2.10 since a lot of people still need it. There is still the old experimental version of akka-http which gets fixes backported to 2.3 Akka, but that is not really an upgrade.

**Comment by velvia** [comment]
We can discuss doing this upgrade for spark 2.0 only, but that would still break Scala 2.10 compatibility….. :/

**Comment by hntd187** [comment]
@velvia I would say this is only okay if Spark ever drops support for 2.10, otherwise I don't think we can do that because there are a lot of people still using 2.10

**Comment by amarouni** [comment]
@hntd187 Fair enough, I'll keep the issue open for future reference.

**Comment by jpgbus** [comment]
Apache provided Spark 2 binaries are built with 2.11 - since this is the default, why not provide _primary_ support for Spark 2 dependent branches aligned with Spark? Support for 2.10 doesn't have to stop altogether, but it makes sense to put it in the back seat.

**Comment by velvia** [comment]
So after the imminent release spark 2.0 will become master and we can def move to 2.11.    Then spark 1.6 would just become a maintenance branch, and I think that makes sense to stay at 2.10… what do you think?

**Comment by amarouni** [comment]
@velvia Totally agree with the move to **master + Spark 2.0 + Scala 2.11.** We're seeing more and more Scala 2.11 adoption and lots of projects are ditching Scala 2.10 in newer releases.

**Comment by amarouni** [comment]
Discussion moved to #863.
