### ISSUE TITLE
--bash: ./server_start.sh: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by vijaypabothu** [spark-jobserver/spark-jobserver#712]
Hi Team,
Deployed spark job server successfully . From deployed directory I ran the  command to start server and getting the below error. Please advise.
[root@icx-lt-002 spark-jobserver]# server_start.sh
-bash: ./server_start.sh: /bin/bash^M: bad interpreter: No such file or directory

![job server deployment](https://cloud.githubusercontent.com/assets/22211655/22323439/eb8fe528-e3c8-11e6-9472-afce2168bd9d.jpg)

**Comment by avkapustin** [comment]
Hi, this is looks like you have DOS CR/LF line endings in shell scripts

**Comment by vijaypabothu** [comment]
This is my bash script , Please advise .

#!/bin/bash
# Script to start the job server
# Extra arguments will be spark-submit options, for example
#  ./server_start.sh --jars cassandra-spark-connector.jar
#
# Environment vars (note settings.sh overrides):
#   JOBSERVER_MEMORY - defaults to 1G, the amount of memory (eg 512m, 2G) to give to job server
#   JOBSERVER_CONFIG - alternate configuration file to use
#   JOBSERVER_FG    - launches job server in foreground; defaults to forking in background
set -e

get_abs_script_path() {
  pushd . >/dev/null
  cd "$(dirname "$0")"
  appdir=$(pwd)
  popd  >/dev/null
}

get_abs_script_path

. $appdir/setenv.sh

GC_OPTS="-XX:+UseConcMarkSweepGC
         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:$appdir/gc.out
         -XX:MaxPermSize=512m
         -XX:+CMSClassUnloadingEnabled "

# To truly enable JMX in AWS and other containerized environments, also need to set
# -Djava.rmi.server.hostname equal to the hostname in that environment.  This is specific
# depending on AWS vs GCE etc.
JAVA_OPTS="-XX:MaxDirectMemorySize=$MAX_DIRECT_MEMORY \
           -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true \
           -Dcom.sun.management.jmxremote.port=$JMX_PORT \
           -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT \
           -Dcom.sun.management.jmxremote.authenticate=false \
           -Dcom.sun.management.jmxremote.ssl=false"

MAIN="spark.jobserver.JobServer"

PIDFILE=$appdir/spark-jobserver.pid
if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
   echo 'Job server is already running'
   exit 1
fi

cmd='$SPARK_HOME/bin/spark-submit --class $MAIN --driver-memory $JOBSERVER_MEMORY
  --conf "spark.executor.extraJavaOptions=$LOGGING_OPTS"
  --driver-java-options "$GC_OPTS $JAVA_OPTS $LOGGING_OPTS $CONFIG_OVERRIDES"
  $@ $appdir/spark-job-server.jar $conffile'
if [ -z "$JOBSERVER_FG" ]; then
  eval $cmd > $LOG_DIR/server_start.log 2>&1 < /dev/null &
  echo $! > $PIDFILE
else
  eval $cmd
fi

**Comment by amarouni** [comment]
@vijaypabothu 
as @avkapustin said this might be a Dos to Linux line separator issue, if you're on Ubuntu try something like :
```
sudo apt-get install tofrodos
fromdos server_start.sh
```
Then try running the script again.

**Comment by avkapustin** [comment]
Please note what all *.sh files should be converted, not only server_start.sh (both in bin/ and conf/ directories)

**Comment by hntd187** [comment]
I take it the package was built on windows and then transferred to a linux machine, you should either build it on linux or run the scripts through like dos2unix to correct the line endings. For the future too, please don't paste gigantic text in your comments.

**Comment by vijaypabothu** [comment]
Thanks to every one. Issue resolved by dos2unix scipt.sh - done for all the files.
