### ISSUE TITLE
Enforce stricter contribution rules 

### ISSUE THREAD

**Issue by amarouni** [spark-jobserver/spark-jobserver#713]
I was looking at recent commits and I realized that this projects should enforce stricter contribution rules :

For starters, it would be really nice if all the commit messages follow some naming rule :
```
fix(script) : Remove ... from startup script
feature(akka-app) : Add ...
chore(routes) : clean routes ...
```
That would really make it easier to generate change logs and better overall readability.

On another note, it would be also nice to prefer squash & merge to simple merges when merging PRs.

One other thing, is there any bug tracker ? if not and since this is an open source project I'm sure we can get some free bug tracker somewhere (JIRA, ...). Maybe also a simple website with a landing page.

I think this the right moment to start thinking about all of the above suggestions. I can help around and work on these above suggestions if you're interested.

**Comment by velvia** [comment]
@amarouni, +1 to naming rules for commits.

**Comment by noorul** [comment]
amarouni <notifications@github.com> writes:

> I was looking at recent commits and I realized that this projects should enforce stricter contribution rules :
>
> For starters, it would be really nice if all the commit messages follow some naming rule :
> ```
> fix(script) : Remove ... from startup script
> feature(akka-app) : Add ...
> chore(routes) : clean routes ...
> ```
> That would really make it easier to generate change logs and better overall readability.
>
> On another note, it would be also nice to prefer squash & merge to simple merges when merging PRs.
>
> One other thing, is there any bug tracker ? if not and since this is an open source project I'm sure we can get some free bug tracker somewhere (JIRA, ...). Maybe also a simple website with a landing page.
>
> I think this the right moment to start thinking about all of the above suggestions. I can help around and work on these above suggestions if you're interested.

I agree with this. It is time we add some process around contribution,
not only for commits alone.

Regards,
Noorul

**Comment by amarouni** [comment]
@velvia @noorul I opened a first PR for contribution guidelines and PR template #719

**Comment by hntd187** [comment]
I think we need to clean up our own code formatting and style before trying to make other people follow a guideline.

**Comment by noorul** [comment]
@hntd187 I agree

**Comment by noorul** [comment]
@hntd187 For that we need to come up with guidelines and we should work towards meeting them.

**Comment by amarouni** [comment]
@noorul I agree that there's a need to clean code formatting & style, the commit & PR guidelines are a good starting point. 
@hntd187 What do you have in mind ? a better scalastyle ?

**Comment by noorul** [comment]
@amarouni How do you want to take this further?

**Comment by noorul** [comment]
Closing this
