### ISSUE TITLE
./server_start.sh: line 41: kill: (2924) - No such process

### ISSUE THREAD

**Issue by vijaypabothu** [spark-jobserver/spark-jobserver#714]
Hi Team,
while starting the server in from deployed directory getting the below error. Please advise.

[root@icx-lt-002 bin]# ./server_start.sh
./server_start.sh: line 41: kill: (2924) - No such process

**Comment by avkapustin** [comment]
Hi, looks like you have spark-jobserver.pid file with outdated PID. If spark job server actually isn't up and running, remove this file before start server

**Comment by vijaypabothu** [comment]
I commented the PID file script in server_start.sh and settings.sh  and ran the command 
[root@icx-lt-002 bin]# ./server_start.sh , but job server is not starting .Please advise.

**server_start.sh**
#PIDFILE=$appdir/spark-jobserver.pid
#if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
#   echo 'Job server is already running'
#   exit 1
#fi

cmd='$SPARK_HOME/bin/spark-submit --class $MAIN --driver-memory $JOBSERVER_MEMORY
  --conf "spark.executor.extraJavaOptions=$LOGGING_OPTS"
  --driver-java-options "$GC_OPTS $JAVA_OPTS $LOGGING_OPTS $CONFIG_OVERRIDES"
  $@ $appdir/spark-job-server.jar $conffile'
#if [ -z "$JOBSERVER_FG" ]; then
#  eval $cmd > $LOG_DIR/server_start.log 2>&1 < /dev/null &
#  echo $! > $PIDFILE
#else
#  eval $cmd
#fi

settings.sh
#PIDFILE=spark-jobserver.pid

**Comment by velvia** [comment]
The message is harmless.  There is another reason why it is not starting; to allow others to help you, please post logs and more details.

**Comment by vijaypabothu** [comment]
Thanks Evan. Please find the log details.Please advise.

[server log.txt](https://github.com/spark-jobserver/spark-jobserver/files/733149/server.log.txt)

**Comment by vijaypabothu** [comment]
Thanks eveyone. Closing this as this is fixed now.
