### ISSUE TITLE
Job server is already running

### ISSUE THREAD

**Issue by vijaypabothu** [spark-jobserver/spark-jobserver#717]
Hi Team,
when I run the command ./server_start.sh from deployed directory and I am getting the message. When i check the port 8090 from the deployed host , still the job server is not seems to be up and also in jps not seeing any job server process . Please advise whether I am missing anything here .

'Job server is already running'

**Comment by avkapustin** [comment]
Hi, could you provide log files after start of server? As I saw from previous log, probably you  build jar without any dependencies, so it's failed to start. What the size of spark-job-server.jar in deployed directory?

**Comment by vijaypabothu** [comment]
Please see the log files attached. Size of  spark-job-server.jar is 29MB . Please advise.
[server log.txt](https://github.com/spark-jobserver/spark-jobserver/files/734709/server.log.txt)

Steps I followed:
From my local PC:  Ran server_deploy.sh  for deployment to remote host
on Host  PC: Received  spark-job-server.jar , settings.sh ad local.conf,setenv.sh and few other files .
On Host PC: I ran the command ./server_start.sh  and getting this error 'Job server is already running' , but when I check JPS on Host PC I could not see any job server is running , also IP of Host PC:8090 also not available .

**Comment by avkapustin** [comment]
The exception in the server log (java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce) points to incompatibility of Scala version between Spark job server and Spark on the HostPC.
As I understand, spark job server use Spark 1.6.2 build by Scala 2.10
Which version of Spark installed on your Host PC?

**Comment by vijaypabothu** [comment]
I am using spark-2.0.0-bin-hadoop2.6 in my Host PC.

**Comment by avkapustin** [comment]
Hmm... AFAIK, spark-job-server doesn't support Spark 2.0. I'll be also happy if this incorrect

**Comment by noorul** [comment]
@vijaypabothu In order to use spark-2.0 you need to use preview branch

**Comment by vijaypabothu** [comment]
@noorul - Please confirm can we use this preview branch in Deployment  , because I deployed the jar by server_deploy.sh  from the clone of the git (below command) and after that jar is automatically created in my hosted PC. Will curl works in deployed PC. Do we need to download again .

git clone https://github.com/spark-jobserver/spark-jobserver

**Comment by velvia** [comment]
The code in spark-2.0-preview should be usable, though it’s not officially released.  It is based on code that some folks are running in deployment.

**Comment by noorul** [comment]
Preview branch should work.
