### ISSUE TITLE
NamedRDD Update function: Returns Null Pointer Exception

### ISSUE THREAD

**Issue by Prateek057** [spark-jobserver/spark-jobserver#718]
`val similarityRDD = sc.parallelize(docSimilarityMap.toIndexedSeq)
    this.namedRdds.update("similarity_dictionary", similarityRDD, false, StorageLevel.DISK_ONLY)

    val oldRDD = this.namedRdds.get[(String, scala.collection.mutable.Map[String, Double])]("similarity_dictionary").get`

**Comment by Prateek057** [comment]
Exception in thread "main" java.lang.NullPointerException
	at spark.jobserver.NamedRddSupport$$anon$1.<init>(NamedRddSupport.scala:161)
	at spark.jobserver.NamedRddSupport$class.namedRdds(NamedRddSupport.scala:159)

**Comment by valan4ik** [comment]
Jobserver code was changed a lot since the issue was opened and Spark version was bumped several times.
Please reopen the issue if the problem happens again.
