### ISSUE TITLE
Support for cluster deployment mode

### ISSUE THREAD

**Issue by vatsalmevada** [spark-jobserver/spark-jobserver#720]
I want to launch jobs in cluster deployment mode in order to avoid all the driver running on job-server.  Hence I tried setting `spark.submit.deployMode` property to _"cluster"_ and `spark.master` property to spark rest URL (_spark://server:6066_). 

However, after doing above mentioned change I am not able to create a new context using rest API. 

Note that I have set `jobserver.context-per-jvm` to "_true_" and I am manually managing context lifecycle.

Is cluster deployment mode is supported by job-server? If yes then what am I missing?

**Comment by noorul** [comment]
This is not yet supported

**Comment by amarouni** [comment]
@noorul I'm also interested in the feature, but it looks like a big feature. The whole code was written with the yarn-client mode in mind. Can we get some approximation of the work needed here ?

**Comment by noorul** [comment]
I did some work on this line https://github.com/noorul/spark-jobserver/tree/aruba-jobserver-0.6.2-spark-1.6.2 but I could not find time to make it ready to raise a PR.

**Comment by jomach** [comment]
I all, So I was researching about this I think the best way would be: JobServer  uses the standard spark-submit command to create new jobs. Then we can us  the monitoring api from the history server : http://spark.apache.org/docs/1.6.2/monitoring.html

**Comment by velvia** [comment]
Jorge,

Job server on master, if you enable context-per-jvm, does use spark-submit to submit jobs.

**Comment by jomach** [comment]
@velvia  with on master you mean on master branch right ? :) yeah I prefer to wait until everything is publish to mvn...

**Comment by noorul** [comment]
multi-jvm support is available on 0.6.2 also.

**Comment by jomach** [comment]
On the issue that I described bellow I have the context-per-jvm set to true. For what is the manager_start.sh ? If I unterstand correct for using yarn cluster mode I need to follow this points: 
1 - set  context-per-jvm =true
2 - start the manager_start.sh

what are the parameters that the manager_start.sh needs? 
# args: <work dir for context> <cluster address> [proxy_user] 
 -cluster address ? is this connecting to spark driver ?  Or is this the address where the spark driver will try to reach ? 
 - work dir needs a file named context.conf ? Any Example how this should look like ?

**Comment by velvia** [comment]
Hi, so you don’t need to start manager_start.sh yourself, this is what job server calls to start each child process.  What I was suggesting is that you could modify manager_start.sh with custom start parameters for now if you need to, like adding —jar.  In the future we should give an option so you don’t need to modify it.

The work dir is created by job server master process.

**Comment by jomach** [comment]
@velvia  yeah I noticed that after playing a bit around. But still the cluster mode would be nice to have. thanks for the help anyways

**Comment by Sokrates80** [comment]
Hi @vatsalmevada , are you sure you have to set the spark.master property to `spark://server:6066` ? Shouldn't be `spark://server:7077` instead?

**Comment by vatsalmevada** [comment]
Hi @sokrates80, I have tried 6066 as well as 7077 and cluster mode is working with neither.  In my question I explicilty mentioned 6066 as according to my knowledge, for cluster deployment mode REST url of spark master(with port 6066) needs to be passed while using spark-submit.

**Comment by bsikander** [comment]
Cluster mode is supported now.
