### ISSUE TITLE
Error: JMX connector server communication error: service:jmx:rmi://icx-lt-002:9999

### ISSUE THREAD

**Issue by vijaypabothu** [spark-jobserver/spark-jobserver#721]
Hi,
I deployed preview branch -spark-jobserver-spark-2.0-preview ( Because I am using spark 2.0.0 in my remote host). jar is deployed in remote host with all necessary property files . I have configured settings.sh  and environment.sh and environment.conf accordingly. When I try to start the server I am getting this error.Please advise.

Error: JMX connector server communication error: service:jmx:rmi://icx-lt-002:9999

![image](https://cloud.githubusercontent.com/assets/22211655/22503420/ae806b52-e897-11e6-983a-e2f5c77a966a.png)
[setting.txt](https://github.com/spark-jobserver/spark-jobserver/files/744561/setting.txt)

**Comment by amarouni** [comment]
@vijaypabothu Do you have anything running on port 9999 ?
Change `JMX_PORT=9999` in your settings.sh to a free port on your machine.

**Comment by vijaypabothu** [comment]
@amarouni , Thnaks for the reply.
in my settings.sh -JMX_PORT=9999 is already set and nothing running on port 9999.
Please advise.

**Comment by vijaypabothu** [comment]
Thanks amarouni. Issue fixed.
