### ISSUE TITLE
Which version of jobserver to use for Spark 2.0.2

### ISSUE THREAD

**Issue by raviteja-ms** [spark-jobserver/spark-jobserver#722]
Hi,
 I have recently upgraded my spark cluster from **1.6.1** to **2.0.2** and earlier I was using **spark-jobserver 0.6.2** 

  Can you please suggest me which version of this library to use and also any example jobs for the newer version API's will be appreciated. 

 Are there any major changes in the jobserver API's to support `spark-session` instead of `sqlContext` which was a new addition in spark 2.0.2?

Thanks..!!

**Comment by amarouni** [comment]
@raviteja-ms There's a `Spark 2.0` preview branch : https://github.com/spark-jobserver/spark-jobserver/tree/spark-2.0-preview

**Comment by raviteja-ms** [comment]
@amarouni  I have few questions:

1. Is this version (2.0 preview) stable or experimental ?
2. How to get support for `spark-session` ?
3. If `spark-session` is available, can you please give me an example how to use it with jobserver ?

Thanks..!!

**Comment by noorul** [comment]
>
> 1. Is this version (2.0 preview) stable or experimental ?

There are people who are using this in their deployment.

> 2. How to get support for `spark-session` ?

This is not available.

Thanks and Regards
Noorul

**Comment by raviteja-ms** [comment]
Ok Thanks :)

**Comment by yiu31802** [comment]
Hello, I am new to Spark and Spark-JobServer. When creating a new job for spark-2.0-preview, is this instruction still valid?

https://github.com/spark-jobserver/spark-jobserver/blame/bdf59293d90ed13f3e81a300b166cdcb08c5a997/README.md#L244

Otherwise, how should I do with `libraryDependencies`?
I was wondering because there is no corresponding maven binary for spark-2.0-preview.

**Comment by yiu31802** [comment]
I commented out `libraryDependencies` and placed two jars from `job-server-api` and `job-server-extra` in `/lib` which are build on the preview branch and with command `job-server-api/package`. Not really sure if I am doing the right thing, but now my job started to run normally!

**Comment by velvia** [comment]
great!

**Comment by yiu31802** [comment]
Thanks for the reply. I happened to re-visit the README.md once again and now I found that there is additional repository (Jitpack) which serves the latest package as well. Maybe

https://github.com/spark-jobserver/spark-jobserver/blob/master/README.md#version-information

*Side note*
Considering that there is significant popularity of this repository but the information is yet scattered a bit, I am tempted to summarize my findings on deploying a practical job-server system. Would you consider my Pull Request with, for example, `/doc/example-01-cassandra-with-spark-2.0.md`?

**Comment by velvia** [comment]
Hi Junji, yes, a PR for better docs is definitely welcome.  Thanks.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by raviteja-ms** [comment]
@yiu31802 Can you please elaborate how you added job-server-dependencies for spark 2.0.2?

**Comment by yiu31802** [comment]
Hello @raviteja-ms .

Here's my code snippet of `build.sbt`:

```
resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven"
resolvers += "jitpack" at "https://jitpack.io"
```

and that of `Dependencies.scala`:

```
    lazy val sparkDeps = Seq(
      "org.apache.spark" %% "spark-sql" % sparkVersion % "provided" excludeAll(excludeNettyIo),
      "com.github.spark-jobserver.spark-jobserver" % "job-server-extras_2.11" % "spark-2.0-preview-SNAPSHOT" % "provided",
```

Hope this helps.

**Comment by yiu31802** [comment]
Hello, @raviteja-ms .

I noticed that the my above command does not work currently due to presumably jitpack.io side. The binary seems no longer available. The workaround for this is to use a local binary of spark-job-server that you built, and place them under `lib/*.jar`.

**Comment by noorul** [comment]
Closing this!
