### ISSUE TITLE
 ./server_start.sh: line 41: kill: (21556) - No such process

### ISSUE THREAD

**Issue by phanirajl** [spark-jobserver/spark-jobserver#723]
/usr/share/dse/spark/spark-jobserver
./server_start.sh: line 41: kill: (21556) - No such process

**Comment by velvia** [comment]
This is not a problem in and of itself.   Is the server not starting up?   That line is nonfatal.

**Comment by phanirajl** [comment]
I'm trying to start the job server using  "dse spark-jobserver start"

**Comment by velvia** [comment]
I would suggest you close this ticket and contact DSE support….    and observe whether this is really preventing job server from starting.  In my experience it does not prevent the starting.
