### ISSUE TITLE
Who is saying `Guava Issue #1635`?

### ISSUE THREAD

**Issue by yiu31802** [spark-jobserver/spark-jobserver#736]
Hello,

I am still new to Spark and this Server.

I am trying to setup a spark-job-server which accesses to Cassandra DB to get dataframe back. I've been struggling for several days already, but I am not really sure about where this `Guava` issue is actually raised. I am already aware that this comes from Guava's versions conflict of Spark's and Cassandra's. So far, none of Internet investigation helped me to resolve this issue.

- Am I doing wrong with `server_start.sh --jars spark-cassandra-connector-2.0.0-M2-s_2.11.jar`? But I made sure this `connector` jar has `guava-18.0` according to its `pom.xml`.
- Am I doing wrong with my job? But it also has `16.0.1`. (My job is pasted below)
- my Spark version is `2.0.2`
- spark-job-server is `spark-2.0-preview`.
- Cassandra version is bit old 2.2.8, but I believe this is not an issue.
- I have ever successfully used `spark-cassandra-connector` in the same setup but not via spark-job-server.

```
[2017-02-12 21:09:20,815] ERROR .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/mycontext] - Got Throwable
java.lang.ExceptionInInitializerError
        at com.datastax.spark.connector.cql.DefaultConnectionFactory$.clusterBuilder(CassandraConnectionFactory.scala:35)
        at com.datastax.spark.connector.cql.DefaultConnectionFactory$.createCluster(CassandraConnectionFactory.scala:92)
        at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:154)
        at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$3.apply(CassandraConnector.scala:149)
        at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$3.apply(CassandraConnector.scala:149)
        at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31)
        at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56)
        at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:82)
        at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:110)
        at com.datastax.spark.connector.rdd.partitioner.dht.TokenFactory$.forSystemLocalPartitioner(TokenFactory.scala:98)
        at org.apache.spark.sql.cassandra.CassandraSourceRelation$.apply(CassandraSourceRelation.scala:255)
        at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:55)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:345)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
        at com.sonymobile.almv.spark.PivotTable$.runJob(pivottable.scala:34)
        at com.sonymobile.almv.spark.PivotTable$.runJob(pivottable.scala:17)
        at spark.jobserver.SparkJobBase$class.runJob(SparkJob.scala:31)
        at com.sonymobile.almv.spark.PivotTable$.runJob(pivottable.scala:17)
        at com.sonymobile.almv.spark.PivotTable$.runJob(pivottable.scala:17)
        at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:290)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Detected Guava issue #1635 which indicates that a version of Guava less than 16.01 is in use.  This introduces codec resolution issues and potentially other incompatibility issues in the driver.  Please upgrade to Guava 16.01 or later.
        at com.datastax.driver.core.SanityChecks.checkGuava(SanityChecks.java:62)
        at com.datastax.driver.core.SanityChecks.check(SanityChecks.java:36)
        at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:68)
        ... 26 more
```

My Job (and its build.sbt) looks like this:

```{scala}
object PivotTable extends SparkSqlJob {
  def validate(sql: SQLContext, config: Config): SparkJobValidation = SparkJobValid
  def runJob(sql: SQLContext, config: Config): Any = {
    import sql.implicits._

    val df = sql.read.
      format("org.apache.spark.sql.cassandra").
      options(Map("table" -> "test_instances", "keyspace" -> "almv", "cluster" -> "default")).
      load()
    "hellohellohello4"
  }
}

...

resolvers += "jitpack" at "https://jitpack.io"

lazy val jobServerTestJarSettings = Seq(
  libraryDependencies ++= apiDeps,
...

lazy val apiDeps = Seq(
    "org.apache.spark" %% "spark-sql" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ),
    "com.github.spark-jobserver.spark-jobserver" % "job-server-api_2.11" % "spark-2.0-preview-SNAPSHOT" % "provided",
    "com.github.spark-jobserver.spark-jobserver" % "job-server-extras_2.11" % "spark-2.0-preview-SNAPSHOT" % "provided",
    "io.netty" % "netty-all" % "4.0.37.Final"
)

```

My `server-deploy` Configuration looks like this (only the changed part):

```
   contexts {
     mycontext {
        context-factory = spark.jobserver.context.SQLContextFactory
        spark.cassandra.connection.host = 10.159.34.54
     }
   }
```

Any comments is really appreciated!

**Comment by noorul** [comment]
Just exclude Guava from your dependencies.

**Comment by yiu31802** [comment]
@noorul thank you for your quick reply.

Do you mean excluding Guava dependencies in my Job (`PivotTable` in this example), don't you?
Removal of Guava solely did not help. I also tried it with Cassandra-driver removal, but still not yet resolved:

```
    lazy val sparkDeps = Seq(
      "org.apache.spark" %% "spark-sql" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ, excludeGuava, excludeGuavaBundle, excludeCassandra),
      "com.github.spark-jobserver.spark-jobserver" % "job-server-api_2.11" % "spark-2.0-preview-SNAPSHOT" % "provided"  excludeAll(excludeNettyIo, excludeQQ, excludeGuava, excludeGuavaBundle),
      "com.github.spark-jobserver.spark-jobserver" % "job-server-extras_2.11" % "spark-2.0-preview-SNAPSHOT" % "provided"  excludeAll(excludeNettyIo, excludeQQ, excludeGuava, excludeGuavaBundle, excludeCassandra)
      //"io.netty" % "netty-all" % "4.0.37.Final"
    )

...

object ExclusionRules {
  val excludeGuava = ExclusionRule(organization = "com.google.guava")
  val excludeGuavaBundle = ExclusionRule(organization = "org.glassfish.jersey.bundles.repackaged")
  val excludeCassandra = ExclusionRule(organization = "com.datastax.cassandra")
}

```

I am bit curious about whether #563 took into account of https://datastax-oss.atlassian.net/browse/SPARKC-355 as these two issues were merged closely in timing.

**Comment by noorul** [comment]
I have something like this which works

    //NettyIo is very bad one, the organization name is different from the jar name for older versions
    val excludeNettyIo = ExclusionRule(organization = "org.jboss.netty")
    val excludeJline = ExclusionRule(organization = "jline")
    val excludeSlf4j = ExclusionRule(organization = "org.slf4j")
    val excludeXerial = ExclusionRule(organization = "org.xerial.snappy")
    val excludeJpountz = ExclusionRule(organization = "net.jpountz.lz4")
    val excludeScalaLang = ExclusionRule(organization = "org.scala-lang")
    val excludeGuava = ExclusionRule(organization = "com.google.guava")
    val excludeScalaTest = ExclusionRule(organization = "org.scalatest")
    val excludeSparkTags = ExclusionRule(organization = "org.apache.spark", name = "spark-tags_2.11")
    val excludeSparkProject = ExclusionRule(organization = "org.spark-project.spark")
  
    lazy val sparkDeps = Seq(
      "org.apache.spark" %% "spark-core" % spark % "provided" excludeAll (excludeNettyIo),
      // Force netty version.  This avoids some Spark netty dependency problem.
      "io.netty" % "netty-all" % netty
    )
  
    lazy val sparkExtraDeps = Seq(
      "org.apache.spark" %% "spark-sql" % spark % "provided" excludeAll (excludeNettyIo),
      "org.apache.spark" %% "spark-streaming" % spark % "provided" excludeAll (excludeNettyIo),
      "org.apache.spark" %% "spark-streaming-kafka-0-8" % spark excludeAll(excludeXerial, excludeNettyIo,
        excludeJline, excludeJpountz, excludeSparkProject, excludeScalaTest, excludeSparkTags)
    )
  
    lazy val jobserverDeps =
      if (deployMode == "sjs") Seq(
        "spark.jobserver" %% "job-server-api" % jobServer % "provided",
        "spark.jobserver" %% "job-server-extras" % jobServer % "provided"
      )
      else Seq(
        "spark.jobserver" %% "job-server-api" % jobServer intransitive(),
        "spark.jobserver" %% "job-server-extras" % jobServer intransitive()
      )

**Comment by yiu31802** [comment]
Thanks for your support. I am still working on this issue. Just to make sure, do you run SJS with `--jars ./spark-cassandra-connector_2.11-2.0.0-M3.jar` (i.e., `dependent-jar-uris` in config), or passing jars as arguments unnecessary?

**Comment by noorul** [comment]
We are using fat jar using abt-assembly plugin

**Comment by yiu31802** [comment]
Ok. I am building myJob app with `sbt assembly` now. But when I `./start-server.sh (without args)` and upload the jar & trigger a job, I get this error:

```
[2017-02-14 17:20:36,845] ERROR .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/mycontext] - Got Throwable
java.lang.ClassNotFoundException: Failed to find data source: org.apache.spark.sql.cassandra. Please find packages at https://cwiki.apache.org/confluence/display/SPARK/Third+Party+Projects
	at org.apache.spark.sql.execution.datasources.DataSource.lookupDataSource(DataSource.scala:148)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:79)
```
So I restarted with `./server-start.sh --jars ./spark-cassandra-connector_2.11-2.0.0-M3.jar`, again the same `guava` error. Hm...

By the way, I noticed that any of your Dependencies do not exclude `guava`.

**Comment by noorul** [comment]
Does you jar has spark cassandra connector classes?

**Comment by yiu31802** [comment]
Not really sure if I am answering correctly, but I have this `Dependencies.scala`:

```
    lazy val sparkDeps = Seq(
      "org.apache.spark" %% "spark-sql" % sparkVersion % "provided" excludeAll(excludeNettyIo),
      "com.github.spark-jobserver.spark-jobserver" % "job-server-api_2.11" % "spark-2.0-preview-SNAPSHOT" % "provided",
      "com.github.spark-jobserver.spark-jobserver" % "job-server-extras_2.11" % "spark-2.0-preview-SNAPSHOT" % "provided",
      "com.datastax.spark" %% "spark-cassandra-connector" % "2.0.0-M3" % "provided" excludeAll(excludeScalaLang, excludeNettyIo, excludeSparkProject),
      "io.netty" % "netty-all" % netty
    )
```

and the code is exactly this (one file):

```
package com.sonymobile.almv.spark

import com.typesafe.config.{ Config, ConfigFactory }
import org.apache.spark._
import scala.util.Try
import spark.jobserver.context.SQLContextFactory
import spark.jobserver._
import org.apache.spark.sql.{ SQLContext, _ }

object PivotTable extends SparkSqlJob {
  def validate(sql: SQLContext, config: Config): SparkJobValidation = SparkJobValid
  def runJob(sql: SQLContext, config: Config): Any = {
    import sql.implicits._

    val df = sql.read.
      format("org.apache.spark.sql.cassandra").
      options(Map("table" -> "test_instances", "keyspace" -> "almv", "cluster" -> "default")).
      load()
    "hellohellohello4"
  }
}
```

and the context ...

```
   contexts {
     mycontext {
        context-factory = spark.jobserver.context.SQLContextFactory
        spark.cassandra.connection.host = 10.159.34.54
     }
   }
```

**Comment by yiu31802** [comment]
Ah... I now know what you meant. Sorry! Your comment reminded me of removing `"provided"` for the connector, yes, it was wrong. My latest Dependencies looks like ` "com.datastax.spark" %% "spark-cassandra-connector" % "2.0.0-M3" excludeAll(excludeScalaLang, excludeNettyIo, excludeSparkProject)`.

The JAR result shows that I successfully included the connector:

```
$ unzip ../target/scala-2.11/almv-spark-assembly-0.1-SNAPSHOT.jar
$ ls com/*
ls com/*
com/datastax:
driver  spark

com/google:
thirdparty

com/sonymobile:
almv

com/twitter:
jsr166e

$ find . -name *guava*
(No result)

$ ls org/apache
commons  spark
```

Strangely, I still get a claim of the guava issue... But now I do no longer need to give `--jars <path-to-connector>.jar` option to `./start_server.sh`.

What's wrong with the connector here... again, I am using `spark-2.0.2` and `spark-job-server-2.0-preview`.

**Comment by yiu31802** [comment]
Still investigating...

I just found that several `guava` versions are found after compiling `spark-job-server.jar` on the clean `spark-2.0-preview` branch. One of the package (`com.googlecode.concurrentlinkedhashmap`) has violated dependency on `14.0.1` guava. Is this okay? I could not figure out which package is using `concurrentlinkedhashmap` package due to lack of my knowledge...

```
$ unzip spark-job-server.jar
$ grep *guava*
(several lines of output)
$ cat ./META-INF/maven/com.googlecode.concurrentlinkedhashmap/concurrentlinkedhashmap-lru/pom.xml
$ grep META-INF/maven/com.googlecode.concurrentlinkedhashmap/concurrentlinkedhashmap-lru/pom.xml -e guava -A 3 -B 1
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>14.0.1</version>
      <scope>test<
```

**Comment by yiu31802** [comment]
You saved me @noorul. I experimentally removed the cassandra support files (https://github.com/yiu31802/spark-jobserver/commit/ea6690), and now my job successfully connected to my cluster!!

```
sport in the classpath, using it
[2017-02-16 15:37:17,142] INFO  tastax.driver.core.Cluster [] [akka://JobServer/user/context-supervisor/mycontext] - New Cassandra host /10.159.34.54:9042 added
[2017-02-16 15:37:17,143] INFO  tor.cql.CassandraConnector [] [akka://JobServer/user/context-supervisor/mycontext] - Connected to Cassandra cluster: Test Cluster
```

Need some fix on the Cassandra commits?

**Comment by velvia** [comment]
Hmmm… the cassandraDAO is in extras right?   Probably only thing we can do is to shade our own cassandra driver.

**Comment by noorul** [comment]
@velvia I think this is a blocker for 0.7.0 release.

**Comment by f1yegor** [comment]
I didn't expect such an issue with cassandra driver (

**Comment by omkar999** [comment]
I am facing the same Guava version issue when executing spark-submit job which  connects to cassandra using datastax cassandra driver.  The expected Guava version should be > 16.0.1 but found a version which is < 16.0.1. The program runs fine when running the spark job in eclipse but the spark-submit command fails!!!
