### ISSUE TITLE
Is there a retention policy on the database?

### ISSUE THREAD

**Issue by mbuccini** [spark-jobserver/spark-jobserver#738]
Hello,

I am wondering whether there is a retention policy on the database. 

What happens if I try to get information about a job after X weeks? Is this information always going to be available there? (I am talking about the default implementation/config). 
Do I need to change any settings to make this information persistent and not volatile?

Thanks in advance.

**Comment by noorul** [comment]
Yes, by default it goes to jdbc:h2:file:/tmp/spark-jobserver/sqldao/data/h2-db , that mean it is persisted. Since /tmp could go away on restart, I would suggest you use some other folder. I would even prefer RDBMS like PostgreSQL.

**Comment by velvia** [comment]
@mbuccini if you configure a real database via JDBC that stands behind Job server then the info should be persisted forever.
