### ISSUE TITLE
akka.pattern.AskTimeoutException

### ISSUE THREAD

**Issue by liu-hongwei** [spark-jobserver/spark-jobserver#74]
hi, 

i see tons of below error when i run test on a local job server:

send request :http://devsparkcluster.cloudapp.net/jobs?appName=job-server-tests&classPath=spark.jobserver.WordCountExample
{
  "status": "ERROR",
  "result": {
    "message": "Timed out",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)", "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)", "akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)", "akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)", "akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)", "java.lang.Thread.run(Thread.java:745)"]
  }
}

here is the complete of my configuration (i have increased the value for context-creation-timeout, and the akka.actor.creation-timeout):

/spark-jobserver-0.4.1/job-server/src/main/resources$ cat application.conf
# Settings for safe local mode development
spark {
  master = "local[4]"
  # spark web UI port
  webUrlPort = 8080

  logConf = true

  jobserver {
    port = 8090
    bind-address = "0.0.0.0"

    # Number of job results to keep per JobResultActor/context
    job-result-cache-size = 5000

    jobdao = spark.jobserver.io.JobFileDAO

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    # Time out for job server to wait while creating contexts
    context-creation-timeout = 180 s

    # A zero-arg class implementing spark.jobserver.util.SparkContextFactory
    context-factory = spark.jobserver.util.DefaultSparkContextFactory

  }

  # predefined Spark contexts
  # Below is an example, but do not uncomment it.   Everything defined here is carried over to
  # deploy-time configs, so they will be created in all environments.  :(
  contexts {
    # abc-demo {
    #   num-cpu-cores = 4            # Number of cores to allocate.  Required.
    #   memory-per-node = 1024m      # Executor memory per node, -Xmx style eg 512m, 1G, etc.
    # }
    # define additional contexts here
  }

  # Default settings for ad hoc as well as manually created contexts
  # You can add any Spark config params here, for example, spark.mesos.coarse = true
  context-settings {
    num-cpu-cores = 8           # Number of cores to allocate.  Required.
    memory-per-node = 1G      # Executor memory per node, -Xmx style eg 512m, 1G, etc.
    # max-jobs-per-context = 4  # Max # of jobs to run at the same time
  }
}

akka {
  # Use SLF4J/logback for deployed environment logging
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel="DEBUG"
  log-config-on-start = on
  stdout-loglevel = "DEBUG"
  jvm-exit-on-fatal-error = on

  timeout = 180

  io
    {
      tcp
        {
          nr-of-selectors = 10
          trace-logging = on
        }

      udp
        {
          nr-of-selectors = 10
          trace-logging = on
        }

      udp-connected
        {
          trace-logging = on
        }
    }

  actor
    {
      creation-timeout = 180 s
      debug
        {
          autoreceive = on
          lifecycle = on
          fsm = on
          unhandled: on
          receive: on
          event-stream = on
        }
    }

  remote {
    log-sent-messages = on
    log-received-messages = on
  }

}

# check the reference.conf in spray-can/src/main/resources for all defined settings
spray.can.server {
  # uncomment the next line for making this an HTTPS example
  # ssl-encryption = on
  idle-timeout = 20 s
  request-timeout = 15 s
  pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
  # Needed for HTTP/1.0 requests with missing Host headers
  default-host-header = "spray.io:8765"

  verbose-error-messages = on

}

where am i wrong? and what cause that timeout issue?  i know the startJob failed , due to this error in the getJobFeture call:

debug=> getJobFeture failed for job ab4dcf01-94ef-480c-9014-2d783ac8aabe : error - org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 6, 10.0.0.7): java.io.IOException: unexpected exception type
        java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1538)
        java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1025)
        java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
        java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
        java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
        java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
        org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:159)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        java.lang.Thread.run(Thread.java:745)
Driver stacktrace:

but i don't know whether this caused by the spark cluster.  if it is, then why errors in spark cluster affect the job server? especially the weird akkaTimeout error?

thanks in advance for any help.

**Comment by velvia** [comment]
Hmm.  Does this happen on the latest master code?  Are you running this
from SBT?

On Mon, Feb 16, 2015 at 6:39 PM, liu-hongwei <notifications@github.com>
wrote:

> hi,
>
> i see tons of below error when i run test on a local job server:
>
> send request :
> http://devsparkcluster.cloudapp.net/jobs?appName=job-server-tests&classPath=spark.jobserver.WordCountExample
> {
> "status": "ERROR",
> "result": {
> "message": "Timed out",
> "errorClass": "akka.pattern.AskTimeoutException",
> "stack":
> ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)",
> "akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)",
> "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)",
> "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)",
> "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)",
> "akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)",
> "akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)",
> "akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)",
> "java.lang.Thread.run(Thread.java:745)"]
> }
> }
>
> here is the complete of my configuration (i have increased the value for
> context-creation-timeout, and the akka.actor.creation-timeout):
>
> /spark-jobserver-0.4.1/job-server/src/main/resources$ cat application.conf
> Settings for safe local mode development
>
> spark {
> master = "local[4]"
> # spark web UI port
> webUrlPort = 8080
>
> logConf = true
>
> jobserver {
> port = 8090
> bind-address = "0.0.0.0"
>
> # Number of job results to keep per JobResultActor/context
> job-result-cache-size = 5000
>
> jobdao = spark.jobserver.io.JobFileDAO
>
> filedao {
>   rootdir = /tmp/spark-jobserver/filedao/data
> }
>
> # Time out for job server to wait while creating contexts
> context-creation-timeout = 180 s
>
> # A zero-arg class implementing spark.jobserver.util.SparkContextFactory
> context-factory = spark.jobserver.util.DefaultSparkContextFactory
>
> }
>
> # predefined Spark contexts
> # Below is an example, but do not uncomment it. Everything defined here is
> carried over to
> # deploy-time configs, so they will be created in all environments. :(
> contexts {
> # abc-demo {
> # num-cpu-cores = 4 # Number of cores to allocate. Required.
> # memory-per-node = 1024m # Executor memory per node, -Xmx style eg 512m,
> 1G, etc.
> # }
> # define additional contexts here
> }
>
> # Default settings for ad hoc as well as manually created contexts
> # You can add any Spark config params here, for example,
> spark.mesos.coarse = true
> context-settings {
> num-cpu-cores = 8 # Number of cores to allocate. Required.
> memory-per-node = 1G # Executor memory per node, -Xmx style eg 512m, 1G,
> etc.
> # max-jobs-per-context = 4 # Max # of jobs to run at the same time
> }
> }
>
> akka {
> # Use SLF4J/logback for deployed environment logging
> loggers = ["akka.event.slf4j.Slf4jLogger"]
> loglevel="DEBUG"
> log-config-on-start = on
> stdout-loglevel = "DEBUG"
> jvm-exit-on-fatal-error = on
>
> timeout = 180
>
> io
> {
> tcp
> {
> nr-of-selectors = 10
> trace-logging = on
> }
>
>   udp
>     {
>       nr-of-selectors = 10
>       trace-logging = on
>     }
>
>   udp-connected
>     {
>       trace-logging = on
>     }
> }
>
> actor
> {
> creation-timeout = 180 s
> debug
> {
> autoreceive = on
> lifecycle = on
> fsm = on
> unhandled: on
> receive: on
> event-stream = on
> }
> }
>
> remote {
> log-sent-messages = on
> log-received-messages = on
> }
>
> }
> check the reference.conf in spray-can/src/main/resources for all defined
> settings
>
> spray.can.server {
> # uncomment the next line for making this an HTTPS example
> # ssl-encryption = on
> idle-timeout = 20 s
> request-timeout = 15 s
> pipelining-limit = 2 # for maximum performance (prevents StopReading /
> ResumeReading messages to the IOBridge)
> # Needed for HTTP/1.0 requests with missing Host headers
> default-host-header = "spray.io:8765"
>
> verbose-error-messages = on
>
> }
>
> where am i wrong? and what cause that timeout issue? i know the startJob
> failed , due to this error in the getJobFeture call:
>
> debug=> getJobFeture failed for job ab4dcf01-94ef-480c-9014-2d783ac8aabe :
> error - org.apache.spark.SparkException: Job aborted due to stage failure:
> Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in
> stage 1.0 (TID 6, 10.0.0.7): java.io.IOException: unexpected exception type
> java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1538)
> java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1025)
> java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
> java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
> java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
> java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
> java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
> java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
> java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
> java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
>
> org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
>
> org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
> org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:159)
>
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> java.lang.Thread.run(Thread.java:745)
> Driver stacktrace:
>
> but i don't know whether this caused by the spark cluster. if it is, then
> why errors in spark cluster affect the job server? especially the weird
> akkaTimeout error?
>
> thanks in advance for any help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/74>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by baank** [comment]
This happens on the master code (checked in few hours ago) and the server is running after a standard ./server-deploy.

The job I was running was pretty heavy e.g. takes minutes to run. I tailed the job-server logs and it is still executing the job well after we get the error.

Looks like this setting maybe needs to be tweaked:
https://github.com/spray/spray/blob/master/spray-can/src/main/resources/reference.conf#L277
connecting-timeout = 10s

**Comment by baank** [comment]
Note I was also running this with ?sync=true.

**Comment by liu-hongwei** [comment]
hey, change the value of connecting-timeout does not help.
here is my setting
spray.can
  {
        server {
          # uncomment the next line for making this an HTTPS example
          # ssl-encryption = on
          idle-timeout = 20 s
          request-timeout = 15 s
          pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
          # Needed for HTTP/1.0 requests with missing Host headers
          default-host-header = "spray.io:8765"

          verbose-error-messages = on

        }

    client
      {
        connecting-timeout = infinite
      }
  }

but i still see the timed out error

what shoud we do?

**Comment by MikhailGolubtsov** [comment]
I face the same problem with v0.4.0 tag. Also tried run WordCountExample and had no luck.

curl -d "input.string = a b c a b see"  'hadoop1:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample&sync=true'
{
  "status": "ERROR",
  "result": {
    "message": "Timed out",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)", "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)", "akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)", "akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)", "akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)", "java.lang.Thread.run(Thread.java:745)"]
  }

**Comment by velvia** [comment]
Sometimes networking has issues if you have VPN and other things on.....

On Thu, Feb 26, 2015 at 3:53 AM, Mikhail Golubtsov <notifications@github.com
> wrote:

> I face the same problem with v0.4.0 tag. Also tried run WordCountExample
> and had no luck.
>
> curl -d "input.string = a b c a b see"
> 'hadoop1:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample&sync=true'
> {
> "status": "ERROR",
> "result": {
> "message": "Timed out",
> "errorClass": "akka.pattern.AskTimeoutException",
> "stack":
> ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)",
> "akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)",
> "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)",
> "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)",
> "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)",
> "akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)",
> "akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)",
> "akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)",
> "java.lang.Thread.run(Thread.java:745)"]
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/74#issuecomment-76165772>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by mshanm10** [comment]
send timeout param along with your request (in secs). eg below.

http://devsparkcluster.cloudapp.net/jobs?appName=job-server-tests&classPath=spark.jobserver.WordCountExample&sync=true&timeout=20

reference: https://github.com/ooyala/spark-jobserver/blob/master/job-server/src/spark.jobserver/WebApi.scala

**Comment by velvia** [comment]
Thanks.  The timeout option has been added to README as well as the
troubleshooting guide.

On Thu, May 21, 2015 at 8:03 AM, mshanm10 <notifications@github.com> wrote:

> send timeout param along with your request (in secs). eg below.
>
>
> http://devsparkcluster.cloudapp.net/jobs?appName=job-server-tests&classPath=spark.jobserver.WordCountExample&sync=true&timeout=20
>
> reference:
> https://github.com/ooyala/spark-jobserver/blob/master/job-server/src/spark.jobserver/WebApi.scala
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/74#issuecomment-104311666>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by claesenm** [comment]
I'm still having this issue, setting the timeout option doesn't solve the problem for me.

**Comment by pbhatIIT** [comment]
Any update? I am having same issue

**Comment by thoHeinze** [comment]
@pbhatIIT The AskTimeout Exception is a quite common exception of the Spark Jobserver hiding different kind of problems, which happen during the start of a context. Did you check your log files ?

**Comment by eliadv** [comment]
Did someone manage to solve it?
