### ISSUE TITLE
can't start a job, error in server logs: java.lang.ClassCastException: $ cannot be cast to spark.jobserver.SparkJobBase

### ISSUE THREAD

**Issue by bronzels** [spark-jobserver/spark-jobserver#740]
hi，

i cloned latest spark job server and used in development mode(some how local/deploy all failed). Then a maven/scala jar is uploaded. When i tried to start the job by a curl, error is returned after curl and titled error log is detected in log.

BTW, there are job-server[ERROR] precede every log output line, but i don't think it is the root cause of the ClassCastException, WordCountExample together with spark job server source code as a job is successfully executed with the same error prefix.

Any one can kindly help:
1, anything wrong in my way to integrate spark job server in maven project? only SBT is supported?
2, anything wrong in my code to extend SparkJob and NamedRddSupport?

My maven integration is to include spark job server from a 3rd party maven repository like this:
        \<repository\>
            \<id\>spark-jobserver\<\/id\>
            \<name\>spark-jobserver\<\/name\>
            \<url\>https://dl.bintray.com/spark-jobserver/maven\<\/url\>
        \<\/repository\>
        \<dependency\>
            \<groupId\>spark.jobserver\<\/groupId\>
            \<artifactId\>job-server_2.11\<\/artifactId\>
            \<version\>0.6.2\<\/version\>
        \<\/dependency\>

my code of spark job server integration:
trait ContactsGraphsCommon extends SparkJob {
    def validate(sc:SparkContext, config: Config): SparkJobValidation = {
        EventAllCached2Update.validate(sc, config)
    }
}

object ContactsGraphs extends ContactsGraphsCommon with NamedRddSupport {
    def runJob(sc: SparkContext, config: Config): Any = {
    }
}

error after curl like this:
[hadoop@hadoop1 SparkTest]$curl --data-binary @$PWD/spark-maven-0.0.1-SNAPSHOT.jar localhost:8090/jars/bqsdata
OK[hadoop@hadoop1 SparkTest]$ curld "input.string = xxx" 'localhost:8090/jobs?appName=bqsdata&classPath=com.bqs.risk.bigdata.graphx.ContactsGraphs'
{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/context-supervisor/fe4f159d-com.bqs.risk.bigdata.graphx.ContactsGraphs#-1961108690]] after [10000 ms]",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)", "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)", "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)", "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)", "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)", "java.lang.Thread.run(Thread.java:745)"]
  }

error in server log:
job-server[ERROR] 17/02/16 16:39:28 INFO HttpServer: Starting HTTP Server
job-server[ERROR] 17/02/16 16:39:28 INFO Utils: Successfully started service 'HTTP file server' on port 33583.
job-server[ERROR] 17/02/16 16:39:28 INFO DefaultSparkContextFactory$$anon$1: Added JAR /tmp/spark-jobserver/filedao/data/bqsdata-2017-02-16T16_39_10.082+08_00.jar at http://localhost:33583/jars/bqsdata-2017-02-16T16_39_10.082+08_00.jar with timestamp 1487234368819
job-server[ERROR] 17/02/16 16:39:28 INFO ContextURLClassLoader: Added URL file:/tmp/spark-jobserver/filedao/data/bqsdata-2017-02-16T16_39_10.082+08_00.jar to ContextURLClassLoader
job-server[ERROR] 17/02/16 16:39:28 INFO JarUtils$: Loading object com.bqs.risk.bigdata.graphx.ContactsGraphs$ using loader spark.jobserver.util.ContextURLClassLoader@1c53dc58
job-server[ERROR] 17/02/16 16:39:28 ERROR OneForOneStrategy: com.bqs.risk.bigdata.graphx.ContactsGraphs$ cannot be cast to spark.jobserver.SparkJobBase
job-server[ERROR] java.lang.ClassCastException: com.bqs.risk.bigdata.graphx.ContactsGraphs$ cannot be cast to spark.jobserver.SparkJobBase
job-server[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:231)
job-server[ERROR] 	at scala.util.control.Breaks.breakable(Breaks.scala:37)
job-server[ERROR] 	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:192)
job-server[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:144)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
job-server[ERROR] 	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
job-server[ERROR] 	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
job-server[ERROR] 	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
job-server[ERROR] 	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
job-server[ERROR] 	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
job-server[ERROR] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
job-server[ERROR] 	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
job-server[ERROR] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
job-server[ERROR] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
job-server[ERROR] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
job-server[ERROR] 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
job-server[ERROR] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
job-server[ERROR] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
job-server[ERROR] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
job-server[ERROR] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
job-server[ERROR] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
job-server[ERROR] 17/02/16 16:39:28 ERROR JobManagerActor: About to restart actor due to exception:
job-server[ERROR] java.lang.ClassCastException: com.bqs.risk.bigdata.graphx.ContactsGraphs$ cannot be cast to spark.jobserver.SparkJobBase
job-server[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:231)
job-server[ERROR] 	at scala.util.control.Breaks.breakable(Breaks.scala:37)
job-server[ERROR] 	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:192)
job-server[ERROR] 	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:144)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
job-server[ERROR] 	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
job-server[ERROR] 	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
job-server[ERROR] 	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
job-server[ERROR] 	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
job-server[ERROR] 	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
job-server[ERROR] 	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
job-server[ERROR] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
job-server[ERROR] 	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
job-server[ERROR] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
job-server[ERROR] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
job-server[ERROR] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
job-server[ERROR] 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
job-server[ERROR] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
job-server[ERROR] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
job-server[ERROR] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
job-server[ERROR] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
job-server[ERROR] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
job-server[ERROR] 17/02/16 16:39:28 INFO JobManagerActor: Shutting down SparkContext fe4f159d-com.bqs.risk.bigdata.graphx.ContactsGraphs
job-server[ERROR] 17/02/16 16:39:29 INFO SparkUI: Stopped Spark web UI at http://localhost:38015
job-server[ERROR] 17/02/16 16:39:29 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
job-server[ERROR] 17/02/16 16:39:29 INFO MemoryStore: MemoryStore cleared
job-server[ERROR] 17/02/16 16:39:29 INFO BlockManager: BlockManager stopped
job-server[ERROR] 17/02/16 16:39:29 INFO BlockManagerMaster: BlockManagerMaster stopped
job-server[ERROR] 17/02/16 16:39:29 INFO DefaultSparkContextFactory$$anon$1: Successfully stopped SparkContext
job-server[ERROR] 17/02/16 16:39:29 INFO JobManagerActor: Starting actor spark.jobserver.JobManagerActor
job-server[ERROR] 17/02/16 16:39:29 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
job-server[ERROR] 17/02/16 16:39:29 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
job-server[ERROR] 17/02/16 16:39:29 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
job-server[ERROR] 17/02/16 16:39:29 INFO RemoteActorRefProvider$RemotingTerminator: Remoting shut down.

**Comment by bronzels** [comment]
sorry, my fault, it is due to trait, extend, after trimmed to exactly like examples in source code, fixed

**Comment by velvia** [comment]
Are you running a matching version of SJS? That is also 0.6.2 and Scala 2.11?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
