### ISSUE TITLE
Multiple context creation fails because of timeout and despite failure context is created eventually 

### ISSUE THREAD

**Issue by vatsalmevada** [spark-jobserver/spark-jobserver#743]
In our use-case it is expected that multiple context creation queries can be submitted simultaneously.

In order to mimic the same when I tried creating multiple contexts in parallel using curl commands something like this:

```
curl -d "" http://<jobserver-url>/contexts/test_context &
curl -d "" http://<jobserver-url>/contexts/test_context1 &
curl -d "" http://<jobserver-url>/contexts/test_context2 &
curl -d "" http://<jobserver-url>/contexts/test_context3 &
curl -d "" http://<jobserver-url>/contexts/test_context4 &
curl -d "" http://<jobserver-url>/contexts/test_context5 &
curl -d "" http://<jobserver-url>/contexts/test_context6 &
```

And above service calls returns with the following message precisely after 40 seconds:

`The server was not able to produce a timely response to your request.`

_Also despite above-mentioned response, context is getting created eventually after few more seconds!_  Which doesn't look like normal behavior.

I tried setting timeout=100000 as GET argument and increasing/decreasing `context-creation-timeout` property, still it fails after 40 seconds. 

Is there any configuration which can allow me to adjust the timeout. 
Also, how can I make sure that the context won't be created if the context creation request fails due to timeout.

I have enabled `context-per-jvm` option. I am using `spark-2.0-preview` version. 

My config file is as follows:

```
spark {
  master = "spark://master:7077"
    submit = {
        deployMode : "cluster"
    }

  job-number-cpus = 4

  jobserver {
    port = 8090
    context-per-jvm = true
    context-creation-timeout = 30 s
    jobdao = spark.jobserver.io.JobSqlDAO

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    datadao {
      rootdir = /tmp/spark-jobserver/upload
    }

    sqldao {
      slick-driver = slick.driver.PostgresDriver
      jdbc-driver = org.postgresql.Driver
      rootdir = /tmp/spark-jobserver/sqldao/data

      jdbc {
        url = "jdbc:postgresql://postgre:5432/postgres"
        user = "postgres"
        password = "adept"
      }

      dbcp {
        enabled = true
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
    result-chunk-size = 1m
    short-timeout = 60 s	
  }
  
  context-settings {
    num-cpu-cores = 2           # Number of cores to allocate.  Required.
    memory-per-node = 512m         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

    passthrough {
      #es.nodes = "192.1.1.1"
    }
    spark.driver.allowMultipleContexts = true	
  }

}
logger.scala.slick.session=DEBUG
akka {
  remote.netty.tcp {
    # This controls the maximum message size, including job results, that can be sent
    # maximum-frame-size = 200 MiB
  }
}
spray.can.server {
  parsing.max-content-length = 300m
 verbose-error-logging = "on"
 verbose-error-messages = "on"
}
flyway.locations="db/postgresql/migration"

```

**Comment by noorul** [comment]
Can you provide the hardware profile of the machine where jobserver is running? I hope you know that each context spawns a new JVM with 2G driver memory.

**Comment by noorul** [comment]
@vatsalmevada See ^^

**Comment by vatsalmevada** [comment]
Machine hardware profile: RAM: 10 GB, No of CPU cores: 4

Yes, I am aware of the fact that driver program is running on the machine hosting job-server. I checked from the UI and it was showing 1G memory allocated for the driver program.  
I was able to reduce it to 512 MB by changing `JOBSERVER_MEMORY` property of the settings.sh file ( let me know if there is any other better way to update driver memory). 

I tried with 1GB and 512MB driver memory and I was able to reproduce the issue for 4-5 parallel jobs also. However irrespective of the driver memory, _my primary concern is that eventually contexts are getting created within few more seconds even after failure in context creation REST request._  This is making it difficult to programmatically manage context lifecycle.

Also the context creation request times out precisely after 40 seconds. Is it possible to configure this timeout?

**Comment by noorul** [comment]
Looks like a bug. Marked as bug

**Comment by manasdebashiskar** [comment]
Any status on this bug?

**Comment by bsikander** [comment]
Since jobserver doesn't support any async POST /context API, multiple POST /context requests can fail because internally the messages are queued up at the actor.
Jobserver cleans up the contexts which come up eventually in the latest release.
