### ISSUE TITLE
README for creating a scala/java jar to be uploaded

### ISSUE THREAD

**Issue by QuantumRich** [spark-jobserver/spark-jobserver#744]
Is there a README similar to the well detailed Python one ([link](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/python.md)) about how to write and package my own scala or java Spark job for this?

**Comment by noorul** [comment]
I created a guter8 template at spark-jobserver/spark-jobserver.g8. Is that what you are looking for?

**Comment by bsikander** [comment]
Closing. Docu can be found [here](https://github.com/spark-jobserver/spark-jobserver#create-a-job-server-project)
