### ISSUE TITLE
How to use Spark Session in SJS 2.0 version 

### ISSUE THREAD

**Issue by SenthilKumaravel** [spark-jobserver/spark-jobserver#752]
Hello All, I am using spark-job-server-2.0(preview) code to execute the existing PySpark project. We were using spark session in the existing code, not using spark context.I just want to know how to use spark session in spark-job-server to create the spark session object, currently creating spark context which is not required and throwing runtime error in the existing code.

**Comment by velvia** [comment]
Hi, ho are you invoking your existing PySpark code?

**Comment by noorul** [comment]
I don't think preview-2.0 branch support Spark Session

**Comment by steveSK** [comment]
I am maybe interested to implement SparkSession support, do you think we should create new SparkJob trait using SparkSession or I just should subtitute sparkContext with SparkSession

**Comment by velvia** [comment]
I think you can just have the default SparkJob trait implement SparkJobBase with a context type of SparkSession.  Basically SparkSession should be the default now going forward.
We can  have a context that supplies the old SparkContext for compatibility.

**Comment by hntd187** [comment]
The right way to do this would be to completely remove the idea of SparkContexts from it and have a central path through SparkSession since things like SqlContext and HiveContext no longer really exist, they want you to go entirely through SparkSession.

**Comment by yabinmeng** [comment]
What version do I expect to have Spark Session support?

**Comment by bsikander** [comment]
https://github.com/spark-jobserver/spark-jobserver/#new-sparkjob-api-with-spark-v21

**Comment by bsikander** [comment]
Jobserver has SparkSession support now. Closing.
