### ISSUE TITLE
SparkSQL return object

### ISSUE THREAD

**Issue by QuantumRich** [spark-jobserver/spark-jobserver#755]
Is there a reason SparkSQL jobs only return results without duration, jobID, etc.?

**Comment by velvia** [comment]
Sorry can you share more details?   What route did you run, what are you seeing etc.

**Comment by QuantumRich** [comment]
Sure. For example when I run:

`curl -d "sql = \"select * from addresses limit 10\"" '127.0.0.1:8090/jobs?appName=sql&classPath=spark.jobserver.SqlTestJob&context=sql-context&sync=true'
`

I only get the query results returned in the POST request.  Whereas if I ran any of the job-server-tests jobs like WordCount, I get timestamps and a start message.  And it would require me to use a GET request to fully retrieve the job.  

I am wondering why it's different since I'm writing a REST controller for this server and I would like to modularize things as much as possible.

**Comment by taoshi006** [comment]
can you share your whole job's code? i have the same question with you.

**Comment by noorul** [comment]
You are passing sync=true, which case only the result will be returned.
