### ISSUE TITLE
How to run a Spark application in a cluster?

### ISSUE THREAD

**Issue by yiu31802** [spark-jobserver/spark-jobserver#756]
Hello,

I would like to run my Spark application in a cluster consisting of 1 master and 2 slaves. Somehow, spark-job-server only tries to do the work with one master machine.

Following is what I did so far:

1) As a preparation (not sure if needed but), I constructed a basic cluster using

```{bash}
cd $SPARK_HOME
sbin/start-master.sh
sbin/start-slaves.sh # my conf/slaves file lists the two slave's IP
```

I have made sure that my simple Spark application uses all the nodes, by confirming it in localhost:8080.

2) Next step is to involve the spark-job-server. I modified the config file in spark-job-server like this to point to the master of the cluster:

```
master = "spark://10.159.12.72:7077"
```

3) Run the WordCount job by following the instruction. The job goes fine, but by checking the Spark Cluster GUI, no job was triggered as a cluster job.

I checked #720 but was not sure if my usecase is also within #720.

Thanks,

Junji

**Comment by noorul** [comment]
> 2) Next step is to involve the spark-job-server. I modified the config file in spark-job-server like this to point to the master of the cluster:
>
> ```
> master = "spark://10.159.12.72:7077"
> ```
>

Can you explain the following,
1. How did you deploy SJS?
2. Which version of SJS are you using?
3. How are you running SJS?

**Comment by yiu31802** [comment]
Sorry for missed the details.

1)
```
# The SJS and Spark master itself is located in the same machine.
cd <SJS>
./server_deploy.sh  # I only modified conf/myconf.conf for spark.master section.
cd <SJS workspace>/start_server.sh
```

2) `spark-2.0-preview` (Scala version is `2.11.8`, Spark version is `2.0.2`)

3) `start_server.sh`

**Comment by noorul** [comment]
If you look at the beginning of the spark jobserver log, you could see
the config it parsed. Can you check whether it has right master set?

**Comment by yiu31802** [comment]
Ah! Thank you so much. It is now resolved thanks to you.

It turned out that `start_server.sh` did not really start a new process, but some old process was still alive. As there was no error message in the console, I did not notice it. After properly killing the old process, and restarted it, now the new configuration was properly read and spark-job-server runs in a cluster.
