### ISSUE TITLE
spark-2.0-preview compilation fails

### ISSUE THREAD

**Issue by ASravanthi** [spark-jobserver/spark-jobserver#760]
Hi Team,

The commit 165d06a9215f4bdf74e75b5275f0f5521128ca4d, on spark-2.0-preview branch, the compilation fails( command sbt clean compile)

Error:
[error] /spark-jobserver/job-server-extras/src/main/java/spark/jobserver/JHiveTestLoaderJob.java:4: cannot find symbol
[error]   symbol:   class DataFrame
[error]   location: package org.apache.spark.sql
[error] import org.apache.spark.sql.DataFrame;
[error] /spark-jobserver/job-server-extras/src/main/java/spark/jobserver/JHiveTestJob.java:13:  java.lang.Object cannot be converted to org.apache.spark.sql.Row[]
[error]         return sc.sql(data.getString("sql")).collect();
[error] /spark-jobserver/job-server-extras/src/main/java/spark/jobserver/JHiveTestLoaderJob.java:25: cannot find symbol
[error]   symbol:   class DataFrame
[error]   location: class spark.jobserver.JHiveTestLoaderJob
[error]         final DataFrame addrRdd = sc.sql("SELECT * FROM `default`.`test_addresses`");
[error] /spark-jobserver/job-server-extras/src/main/java/spark/jobserver/JSqlTestJob.java:13: array required, but java.lang.Object found
[error]         Row row = sc.sql("select 1+1").take(1)[0];
[info] /spark-jobserver/job-server-extras/src/main/java/spark/jobserver/JHiveTestJob.java: Some input files use or override a deprecated API.
[info] /spark-jobserver/job-server-extras/src/main/java/spark/jobserver/JHiveTestJob.java: Recompile with -Xlint:deprecation for details.
[error] (job-server-extras/compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 113 s, completed 08-Mar-2017 12:21:00

**Comment by steveSK** [comment]
I added pull request which should fix the issue.

**Comment by Carl-Hee** [comment]
Thank you! It's works. In addition, have you met the issue after run job-server, the log report   
 Exception in thread "main" java.lang.NoClassDefFoundError: akka/actor/Actor

**Comment by raviteja-ms** [comment]
I'm facing the same problem. Please help

**Comment by hyitclj** [comment]
why I don's use it ? detail in https://github.com/spark-jobserver/spark-jobserver/issues/936

**Comment by bsikander** [comment]
Outdated. Closing.
