### ISSUE TITLE
 No configuration setting found for key 'spark.jobserver.driver-mode'

### ISSUE THREAD

**Issue by Carl-Hee** [spark-jobserver/spark-jobserver#761]
The version is spark-2.0-preview, and spark version is spark-2.0.0
When I use curl to run context, the log of jobserver is shown as follow:

 ERROR AkkaClusterSupervisorActor [] [] - About to restart actor due to exception:
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'spark.jobserver.driver-mode'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)

**Comment by z80sui** [comment]
@nikkiSproutling
@LeightonWong
Help,I have some error.

**Comment by LeightonWong** [comment]
@z80sui add spark.jobserver.driver-mode = client to your xxx.conf file

**Comment by Carl-Hee** [comment]
@LeightonWong  Thank you for your reply. I have tried it at first time, but still not work. I am wondering which part of the configuration should it be added,  context-settings part, or jobserver part?

**Comment by noorul** [comment]
@LeightonWong This should be fixed in the application.conf

**Comment by noorul** [comment]
@LeightonWong See my comment on your PR

**Comment by LeightonWong** [comment]
@z80sui You can add to any place, if you add it to jobserver part, you only need `driver-mode = client`, but if you add it to the outer part, for example outside `spark {xxx}`, you have to use the complete format `spark.jobserver.driver-mode = client`, you can read [typesafe config](https://github.com/typesafehub/config) for more information

**Comment by LeightonWong** [comment]
@noorul OK...should I make a new PR or the project members add it themselves.

**Comment by LeightonWong** [comment]
@noorul @z80sui submit a new pr to fix this. #764

**Comment by LeightonWong** [comment]
@Carl-Hee

**Comment by z80sui** [comment]
@LeightonWong OK,thank you

**Comment by Carl-Hee** [comment]
@LeightonWong Hi,  One more question. How to config the executor extra parameters?  like set  -XX:+UseParallelGC. I tried to pass it through curl when create context, but failed.

**Comment by nikkiSproutling** [comment]
I remember there is an env var called JAVA_OPTS used in server_start.sh
which can take more options to jvm.

**Comment by LeightonWong** [comment]
@Carl-Hee @nikkiSproutling Many way to do this. You can set `spark.executor.extraJavaOptions` in spark-defaults.conf when you are using spark alone, but if you are using job-server to create context, you can see the `manager_start.sh` not `server_start.sh` , the later is used in start job-server it self , not spark context, you can see `--conf "spark.executor.extraJavaOptions=$LOGGING_OPTS $JAVA_OPTS"`, this will override the default spark config defined in `spark-defaults.conf`, you can add your own config to $JAVA_OPTS or create your own ENV variable

**Comment by noorul** [comment]
This is fixed. Closing
