### ISSUE TITLE
architecture diagram？ who can provide jobserver's architecture diagram

### ISSUE THREAD

**Issue by taoshi006** [spark-jobserver/spark-jobserver#765]
who can provide jobserver's architecture diagram

**Comment by velvia** [comment]
There are no diagrams per se, but if you look in docs/ you will see several docs explaining the flow.

**Comment by amarouni** [comment]
@taoshi006 I have a simple diagram for the context-per-jvm case, it's not complete but can help you see the bigger picture : 

![ctx_sjs](https://cloud.githubusercontent.com/assets/10761082/24112874/30b11f68-0d9b-11e7-9cca-5c509278a842.jpg)

**Comment by velvia** [comment]
@amarouni that’s a good one.   Hmmm you interested in updating the docs?
