### ISSUE TITLE
Job Config data storage

### ISSUE THREAD

**Issue by jbuszkiewic-rms** [spark-jobserver/spark-jobserver#768]
We have been using Spark-Job-Server 0.6.2, and I have noticed that the post data *is not* saved in the `config.data` file when the job is submitted synchronously, but the same post data *is* saved in the `config.data` file when the job is submitted asynchronously.

Is this storage pattern a deliberate design decision or something else? I ask because we are attempting to read config data back and noticed that data was not present.

Thanks.

**Comment by bsikander** [comment]
Duplicate. Closing.
