### ISSUE TITLE
Spark JobServer results deleted on docker container restart

### ISSUE THREAD

**Issue by alvarovp27** [spark-jobserver/spark-jobserver#769]
Hi,
I deployed a Spark JobServer docker container in local mode. Everything works fine. My problem is that, when I invoke a job, it returns the results correctly, but if I restart the docker container, the job results are deleted. I can access to the job metadata by querying `/jobs/<job_id>`, but the result attribute doesn't appear, for instance:
`
{
  "duration": "1.33 secs",
  "classPath": "avp.examplesjs.HelloWorld",
  "startTime": "2017-02-03T16:58:15.930Z",
  "context": "ec677ee1-avp.examplesjs.HelloWorld",
  "status": "FINISHED",
  "jobId": "b45476bc-4754-42f0-9401-479d2c4a2523"
}
`

I'd like to know wether this behaviour is normal and if so, how could I configure the docker.conf in order to persist the jobserver results?

Thanks.

**Comment by velvia** [comment]
Hi Alvaro,

Yes this is expected.  When you restart the server, the results are not persisted.

**Comment by alvarovp27** [comment]
Hi, thanks for your asnwer.

And, is there some way to persist them? In my use case, I'm querying it from a web application, so in case the docker container fails and restarts, I'd need to make the job results accessible to the web application without needing to invoke again the jobs. I'd suggest to add this functionality to the JobServer since it would be so useful for these kind of use cases, since the only workaround that comes into my mind is to save the job results inside a MongoDB database inside the SparkJob, and query it by using a REST API to recover the jobs results instead of querying directly to the JobServer.

**Comment by amarouni** [comment]
@alvarovp27 IMHO the Jobserver shouldn't be concerned by any job result storage, it's just a API for running Spark jobs. As you mentioned you can write the results to whatever store you want from your Spark job. Another workaround, if you're running the server in a Docker container, would be to use Docker volumes but I don't recommend this for any prod environment.

**Comment by velvia** [comment]
@amarouni thanks!

**Comment by noorul** [comment]
I added a note in troubleshooting.md
