### ISSUE TITLE
Timeline for Spark Jobserver 0.7.0 Release

### ISSUE THREAD

**Issue by thoHeinze** [spark-jobserver/spark-jobserver#771]
We are currently using the Spark Jobserver 0.6.2 and see many updates in master branch which are quite interesting to us. Is there any timeline for the next release 0.7.0? We would prefer to us only official release (not simply the master) to be sure that everything works fine. Thank you!

**Comment by velvia** [comment]
We are trying to release 0.7.0 imminently…. just trying to finalize PRs.

**Comment by thoHeinze** [comment]
Very nice thanks!
