### ISSUE TITLE
Status of job - ERROR

### ISSUE THREAD

**Issue by kaushikranjan** [spark-jobserver/spark-jobserver#775]
In my jar file, in runJob, even if I add a runTimeException() .. JobServer shows status of Job as FINISHED.

For what exception will it show ERROR.

Example - if i fetch a dataframe from s3 and path is not valid, i throw runtime-exception. but job finishes with status-FINISHED. I want status to be ERROR

**Comment by noorul** [comment]
Which version are you using?

**Comment by kaushikranjan** [comment]
2.0 - preview on spark 2.1.0

**Comment by kaushikranjan** [comment]
def runJob() : = {
throw new Exception("wrong file path")
}

Output of job ...

status = FINISHED
result = "wrong file path"
....

why don't I get 
status = ERROR

**Comment by bsikander** [comment]
It is fixed now. In the latest release. It goes in ERROR state.
