### ISSUE TITLE
Error saving egg on mysql backend

### ISSUE THREAD

**Issue by loveyanbei** [spark-jobserver/spark-jobserver#778]
[2017-03-28 16:38:13,011] INFO  ternal.util.VersionPrinter [] [] - Flyway 3.2.1 by Boxfuse
[2017-03-28 16:38:13,177] INFO  dbsupport.DbSupportFactory [] [] - Database: jdbc:mysql://localhost:3306/spark_jobserver (MySQL 5.7)

I got this message on calling binaries API endpoint
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"BINARIES" ("APP_NAME","BINARY_TYPE","UPLOAD_TIME","BINARY")  values ('pyjob','E' at line 1"

jdbc:
libraryDependencies += "mysql" % "mysql-connector-java" % "6.0.6"

**Comment by noorul** [comment]
I think you might need a separate migration file for MySQL

See https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/resources/application.conf#L164

**Comment by loveyanbei** [comment]
@noorul I tried, jobserver won't start if I didn't set migration to mysql.
But I still got error on calling binaries API.

**Comment by noorul** [comment]
@loveyanbei Which version of SJS are you using?

**Comment by loveyanbei** [comment]
@noorul 2.0-preview branch

**Comment by jcguevara** [comment]
@loveyanbei , @noorul  Is there any update here? I'm trying to do the same and I get the following error:

`SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BYTEA              NOT NULL
)' at line 5
Location   : db/h2/migration/V0_7_0/V0_7_0__init_tables.sql (/value_iq/bin/spark/job-server/file:/value_iq/bin/spark/spark-2.1.1-bin-hadoop2.7/jars/spark-job-server.jar!/db/h2/migration/V0_7_0/V0_7_0__init_tables.sql)
Line       : 1
Statement  : CREATE TABLE JARS (
  JAR_ID       BIGINT             AUTO_INCREMENT NOT NULL PRIMARY KEY,
  APP_NAME     VARCHAR(255)       NOT NULL,
  UPLOAD_TIME  TIMESTAMP          NOT NULL,
  JAR          BYTEA              NOT NULL
)
`
The error is in the column `JAR` of type `BYTEA` . I'm using 2.0-preview too.

**Comment by noorul** [comment]
Can you try master branch? A lot changed there.

**Comment by derSascha** [comment]
Running h2 migration files against a mysql database does not work. Did you follow the mysql part in the [README](https://github.com/spark-jobserver/spark-jobserver#configuring-spark-jobserver-mysql-database-backend) and set the last line (`flyway.locations="db/mysql/migration"`) in your config?

**Comment by jcguevara** [comment]
@noorul thanks, I have now used the master branch and works fine. Did you know when the 0.8.0 will be released? Or how can I start using the Sparksession on my jobs?

**Comment by noorul** [comment]
No concrete date yet. I hope this will get out soon.
