### ISSUE TITLE
Thread & Memory leak

### ISSUE THREAD

**Issue by nbeag** [spark-jobserver/spark-jobserver#779]
Hi. We are encountering a significant thread and memory leak with the job server. We are on jobserver 0.6.2 and spark 1.6.1.

The Metaspace memory of the job server java process increases steadily with every job submitted, as does the amount of threads in the vm (i am monitoring with jvisualvm). Neither seem to ever have a corresponding reduction. I have witnessed it growing to over 2000 live and over 1500 daemon threads.
At the moment this is requiring us to restart the job server almost daily as we schedule many submits throughout the day and our allocated MaxMetaspaceSize of 1.5gb is quickly reached and the jobserver dies. On a related note: before we added a MaxMetaspaceSize, the job server was growing to consume all available memory on the server and the kernel oom killer was kicking in and killing other processes - to prevent this happening to others the max 'permgen' limit that the job server scripts are setting should really be changed to limit the max metaspace.

I am currently in the process of creating a docker-compose setup in a github project to reproduce the problem and will link to it when i have done so. I will include some screenshots of my profiling. 
Interestingly in our production environment the metaspace increases by around 7-12 MB with each submit, whereas in my docker env the increase is only in the KBs. It is still however an upward trend. 

I have tried both ad-hoc and manual context creation and both approaches seem to manifest the issue. My next point of investigation is to set jvm-per-context to true and see if it helps.

Anyone else seeing anything like this or have any ideas?

**Comment by LannyRipple** [comment]
We are on branch spark-2.0-preview and seeing behavior along these lines.  After some number of jobs have gone through the jobserver it starts complaining that it can't start native threads or just dies with OOM.

**Comment by velvia** [comment]
@nbeag thanks for trying to repro it, yes something reproducible would be great. 
Are these Scala, Java, or Python jobs?   
Would you be able to take a thread dump as well and send it here?  (or post on Gitter I guess)

thx

**Comment by nbeag** [comment]
@velvia they are Scala jobs. 

Here's a thread dump: 
[jobserver thread dump.txt](https://github.com/spark-jobserver/spark-jobserver/files/881385/jobserver.thread.dump.txt)

Also my docker-compose env to recreate the issue is here: https://github.com/nbeag/spark-jobserver-memorytests

**Comment by nbeag** [comment]
i've done some basic analysis of the threads from the thread dump and added a summary [here]( https://github.com/nbeag/spark-jobserver-memorytests/tree/master/thread-analysis).
It looks like jetty threads are the problem

**Comment by velvia** [comment]
@nbeag thanks for this excellent work.  So my quick take is:

These threads (mostly qtp, jetty) are created for each context’s web UI and other services.  The problem is that Spark does not clean them up because they assume that the process will die.   Solutions:

a) Try ivm-per-context, which should solve this problem
b) Try setting spark.ui.enabled to false.  This should at least get rid of one big user of threads, but maybe all that will happen is a slower leak.
c) Raise an issue with Databricks/Spark.   

-Evan

**Comment by nbeag** [comment]
i have turned on context-per-jvm and can confirm it solves the issue of the dramatic rise in thread count, and confines the increase in used Metaspace with each submit to a much smaller level (20-200KB increase). Still a leak, but a much smaller one.

**Comment by velvia** [comment]
Awesome.

Not sure where the leak in Meatspace comes from.

**Comment by kaushikranjan** [comment]
"I will include some screenshots of my profiling.
Interestingly in our production environment the metaspace increases by around 7-12 MB with each submit, whereas in my docker env the increase is only in the KBs."

When you say submit, are you creating context with each new Job or using the pre-created context to run all your jobs?
We are also using job-server in production. So, would like to know about this issue in detail.

**Comment by nbeag** [comment]
@kaushikranjan We create a new context for each job.
