### ISSUE TITLE
Supporting NamedObjects in SparkHiveJob

### ISSUE THREAD

**Issue by dpotluri** [spark-jobserver/spark-jobserver#780]
Hello, I am trying to build a Job external to the Spark Job Server and using the following libraries as dependencies of "spark.jobserver" % "job-server-api_2.10" % "0.6.2" % "provided",
"spark.jobserver" % "job-server-extras_2.10" % "0.6.2" % "provided"

I overlaoded HiveContextFactory to extend SparkContextFactoy to register a UDF while creating context factory.

So I now extend both SparkHiveJob and NamedObjectSupport and I see error : illegal inheritance; self-type .type does not conform to spark.jobserver.NamedObjectSupport's selftype spark.jobserver.NamedObjectSupport with spark.jobserver.SparkJob

Could I build a Spark Job external to Job Server?
Could i use both SparkHiveJob and NamedObjectSupport in the same job?

**Comment by jsnikhil** [comment]
This fix [#456](https://github.com/spark-jobserver/spark-jobserver/issues/456) should resolve the issue surrounding not being able to use SparkHiveJob and NamedObjectSupport in combination. However this was merged post 0.6.2 version of SJS.

Currently I am battling the same issue of needing to use the SparkSqlJob with NamedObjectSupport.

**Comment by valan4ik** [comment]
Jobserver was released several times since the issue was opened. Fix #456 is now included in the release.
Closing the issue, please reopen if the problem appears again.
