### ISSUE TITLE
Trouble importing anything from the `sql` package in `spark-2.0-preview` branch.

### ISSUE THREAD

**Issue by aa8y** [spark-jobserver/spark-jobserver#782]
So I am unable to import anything from the `org.apache.spark.sql` package in the `spark-2.0-preview` branch. Not sure if it's a local problem on my computer or if it's a problem with the code.

```
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions for evaluation. Or try :help.

scala> import org.apache.spark.sql.RowFactory
<console>:11: error: object RowFactory is not a member of package org.apache.spark.sql
       import org.apache.spark.sql.RowFactory
              ^

scala> import org.apache.spark.sql.Row
<console>:11: error: object Row is not a member of package org.apache.spark.sql
       import org.apache.spark.sql.Row
              ^

scala> import org.apache.spark.sql.Encoders
<console>:11: error: object Encoders is not a member of package org.apache.spark.sql
       import org.apache.spark.sql.Encoders
              ^

scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> RowFactory
<console>:15: error: not found: value RowFactory
       RowFactory
       ^

scala>
```

The underscore import works, but I am not really sure what it is really doing.

**Comment by velvia** [comment]
You appear to be using spark-shell?   I’m sorry but what does this have to do with spark job server?
What errors are you seeing when you submit jobs with SJS?

When you import with _ this imports everything from the scope.  What times means is that org.apache.spark.sql is indeed found.

**Comment by aa8y** [comment]
@velvia I am using `sbt console` not `spark-shell`. Hence the concern. Also while it looks like the underscore import works, it doesn't really since I cannot find any classes which are supposed to exist within the `sql` package.

**Comment by velvia** [comment]
I don't think you can currently use SBT console with job server.  The reason is that Spark is marked as a provided dependency. What do you need SBT console for that you cannot do better with spark shell?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
"We can do no great things, just small things with great love." -mother Teresa

**Comment by aa8y** [comment]
That makes sense. However, I wanted to use `sbt console` for demonstration of the actual problem. Let me try something else.

If I check out the `spark-2.0-preview` branch and make this change. This is the `git diff`.
```
diff --git a/job-server-api/src/main/scala/spark/jobserver/ContextLike.scala b/job-server-api/src/main/scala/spark/jobserver/ContextLike.scala
index 45a0f24..b20c789 100644
--- a/job-server-api/src/main/scala/spark/jobserver/ContextLike.scala
+++ b/job-server-api/src/main/scala/spark/jobserver/ContextLike.scala
@@ -1,6 +1,7 @@
 package spark.jobserver

 import org.apache.spark.SparkContext
+import org.apache.spark.sql.SparkSession

 /**
  * Represents a context based on SparkContext.  Examples include:
@@ -20,4 +21,4 @@ trait ContextLike {
    * stop method.
    */
   def stop()
-}
\ No newline at end of file
+}
```
and then run `sbt compile`, I get this error.
```
[error] $HOME/code/forks/spark-jobserver/job-server-api/src/main/scala/spark/jobserver/ContextLike.scala:4: object SparkSession is not a member of package org.apache.spark.sql
[error] import org.apache.spark.sql.SparkSession
[error]        ^
[error] one error found
[error] (job-server-api/compile:compileIncremental) Compilation failed
[error] Total time: 4 s, completed Apr 2, 2017 7:59:43 AM
```
But it just dawned to me that maybe it's because I was trying to use it in `job-server-api`. The import seems to work in `job-server-extras` because of the way `sbt` is set up. So I am closing this issue.
