### ISSUE TITLE
Concurrent access to the jars when cashing on the file system resulting in ClassNotFoundError

### ISSUE THREAD

**Issue by zromi18** [spark-jobserver/spark-jobserver#786]
When the SparkJob is run for the first time in two or more SparkContext at the same time in context-per-jvm mode, all the processes/jvms try to cache the same jar - literally the same file in the file system. The result of such a scenario is ClassNotFoundError, event thouth the original jar is there and in a good shape. I suggest either synchronization when cashing jars on the file system or using process/jvm specific files in the file system for jars, so there is no collision between processes/jvms.

**Comment by amarouni** [comment]
@zromi18 I had a similar issue so this might help, are you using the H2 file database ? If so I'd suggest using the H2 server database when working with the context-per-jvm mode.

**Comment by zromi18** [comment]
@amarouni Thank you for the advice, but that is not the case. I am using MySQL database and the nature of the problem is as I have described in the first comment.

**Comment by Meehau** [comment]
The fix for this issue was successfully merged ( https://github.com/spark-jobserver/spark-jobserver/pull/872 ). I think we can close this issue. @zromi18 - please close

**Comment by zromi18** [comment]
@Meehau great job. Thank you.
