### ISSUE TITLE
incompatible with spark-2.0.2?

### ISSUE THREAD

**Issue by Carl-Hee** [spark-jobserver/spark-jobserver#787]
The error log is shown like:

[2017-04-05 17:07:45,410] ERROR ions.codegen.CodeGenerator [] [akka://JobServer/user/jobManager-01-9fab-e6d5d13a8c67] - failed to comp
ile: org.codehaus.janino.JaninoRuntimeException: Code of method "()V" of class "org.apache.spark.sql.catalyst.expressions.GeneratedCla
ss$GeneratedIterator" grows beyond 64 KB
/* 001 */ public Object generate(Object[] references) {
/* 002 */   return new GeneratedIterator(references);
/* 003 */ }

spark-2.0.0 has a critical bug when using spark-sql, so I upgrade to 2.0.2. But the job failed to run.
I'm wondering if it is the version conflict?

**Comment by noorul** [comment]
@Carl-Hee Are you using spark-2.0-preview branch? The spark version on that is 2.1.0

**Comment by Carl-Hee** [comment]
@noorul  Yes, I am using spark-2.0-preview branch. But the REDDME shows the compatible version is spark-2.0?

**Comment by noorul** [comment]
Updated README.md. Closing
