### ISSUE TITLE
which version of spark should I use for spark job server v0.7.0?

### ISSUE THREAD

**Issue by chsjiang** [spark-jobserver/spark-jobserver#788]
I just saw a new tag release v0.7.0, I am wondering which version of spark it is compatible with.

Thanks,
Changsu Jiang

**Comment by chsjiang** [comment]
Ok. I got it in the notes:

Spark 2.0 support is added.

May I say this is a stable release?

Thank you very much!

**Comment by noorul** [comment]
You should be using spark 1.6.2

**Comment by chsjiang** [comment]
@noorul thanks
