### ISSUE TITLE
Documentation jars example is depreciated.

### ISSUE THREAD

**Issue by borissmidt** [spark-jobserver/spark-jobserver#792]
Dear,

I'm reading the documentation and the example of uploading a program uses the `/jars` command.
But this command is depreciated in favor of `/binaries` could you update the example so it uses the new command.

PS when i use the `/binaries` command i get the following error:
Unsupported binary type application/x-www-form-urlencoded% 

the documentation command 
```curl --data-binary @job-server-tests/target/scala-2.10/job-server-tests-$VER.jar localhost:8090/jars/test ```

**Comment by velvia** [comment]
Hi Boris, I think you need to pass in the correct MIME type.  If you are using curl, try —data-binary instead of -d

**Comment by borissmidt** [comment]
```
$ curl --data-binary @myjar-0.0.1-SNAPSHOT.jar localhost:8090/binaries/matcher
Unsupported binary type application/x-www-form-urlencoded%
```
i used the following command. But this issue is targeted more to the fact that the documentation is using a depreciated command instead of the command we should use.
