### ISSUE TITLE
WordCount example - jar upload is successful but can not start a job

### ISSUE THREAD

**Issue by iamnagesh** [spark-jobserver/spark-jobserver#793]
I'm following the [WordCountExample walk-through](https://github.com/spark-jobserver/spark-jobserver#wordcountexample-walk-through) and following is the execution:

```
F:\Soft\spark\Projects\spark-jobserver-master>curl --data-binary @job-server-tests/target/scala-2.10/job-server-tests_2.10-0.7.1-SNAPSHOT.jar localhost:8090/jars/test
{
  "status": "SUCCESS",
  "result": "Jar uploaded"
}
F:\Soft\spark\Projects\spark-jobserver-master>curl -d "input.string = a b c a b see" 'localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample'
curl: (6) Could not resolve host: 'localhost
'classPath' is not recognized as an internal or external command,
operable program or batch file.
```
The jar upload is working but when starting the job its throwing an error as shown above.

**Comment by thoHeinze** [comment]
You are working on Windows, right? This looks similar to the problem described in the PR https://github.com/spark-jobserver/spark-jobserver/pull/751 Please try to use double quotes for "localhost..."

**Comment by iamnagesh** [comment]
It works. Thanks!!!

**Comment by iamnagesh** [comment]
@thoHeinze, can I use a tool like Postman instead of these curl commands?
