### ISSUE TITLE
classPath spark.jobserver. not found

### ISSUE THREAD

**Issue by iamnagesh** [spark-jobserver/spark-jobserver#797]
I have added a new code file along with the existing example files and created a .jar. 

```
F:\Soft\spark\Projects\spark-jobserver-master_1\spark-jobserver-master>curl --data-binary @job-server-tests/target/scala-2.10/job-server-tests_2.10-0.7.1-SNAPSHOT.jar localhost:8090/jars/test
{
  "status": "SUCCESS",
  "result": "Jar uploaded"
}
F:\Soft\spark\Projects\spark-jobserver-master_1\spark-jobserver-master>curl -d "input.string = SamsungJ7Prime16GBGold" "localhost:8090/jobs?appName=test&classPath=spark.jobserver.ViewsRecommender"
{
  "status": "ERROR",
  "result": "classPath spark.jobserver.ViewsRecommender not found"
}
```
Though the above command fails, when I call another class from the same jar it runs successfully as shown below,
```
F:\Soft\spark\Projects\spark-jobserver-master_1\spark-jobserver-master>curl -d "input.string = a b c a b see" "localhost:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample"
{
  "duration": "Job not done yet",
  "classPath": "spark.jobserver.WordCountExample",
  "startTime": "2017-04-14T16:04:17.480+05:30",
  "context": "1ab9cf56-spark.jobserver.WordCountExample",
  "status": "STARTED",
  "jobId": "d177eefb-0642-442a-a650-9c0a07ad6400"
}
```
I have also attached the .jar file below
[job-server-tests_2.10-0.7.1-SNAPSHOT.zip](https://github.com/spark-jobserver/spark-jobserver/files/921973/job-server-tests_2.10-0.7.1-SNAPSHOT.zip)

**Comment by noorul** [comment]
Double check the contents of the jar and ensure that the class is there.

**Comment by noorul** [comment]
How are you compiling test package after adding new file?

**Comment by noorul** [comment]
Can you share a sample reproducible code?

**Comment by iamnagesh** [comment]
@noorul I'm trying to put up a sample code. I'll upload the zip in an hour or two. Thanks.

**Comment by iamnagesh** [comment]
@noorul 
[Execution_Steps.txt](https://github.com/spark-jobserver/spark-jobserver/files/932099/Execution_Steps.txt)
I have attached the project
[spark-jobserver-master (2).zip](https://github.com/spark-jobserver/spark-jobserver/files/932090/spark-jobserver-master.2.zip)

 and the execution steps that I'm following.

Also I don't get this error anymore but I'm facing issues with [this](https://github.com/spark-jobserver/spark-jobserver/issues/800)

**Comment by noorul** [comment]
I am closing this ticket as you are not getting this error anymore.
