### ISSUE TITLE
Integrate SJS-frontend with SJS

### ISSUE THREAD

**Issue by kaushikranjan** [spark-jobserver/spark-jobserver#798]
How do I integrate spark-jobserver-frontend with spark-jobserver?

I didn't find the documentation intuitive. Do I need to replace the contents of 
https://github.com/spark-jobserver/spark-jobserver/tree/master/job-server/src/main/resources/html
with the content of spark-jobserver-frontend?

**Comment by noorul** [comment]
I don't think spark-jobserver-frontend is production ready or tested well. @velvia  am I correct?

**Comment by velvia** [comment]
The frontend has not been integrated yet, but I believe is in use at that company that contributed it.

**Comment by bsikander** [comment]
Closing since spark-jobserver-frontend is not actively maintained at the moment.
