### ISSUE TITLE
Creating a streaming context on an existing spark context?

### ISSUE THREAD

**Issue by wangsir1988** [spark-jobserver/spark-jobserver#799]
As i know, right now, StreamingContextFactory create spark context internal. we can not reuse the spark context from a streaming context,  and we also can not inject an existing spark context into a streaming  context. Sometmies. we need this feature  to share rdds and states between spark jobs and streaming jobs in one context.

**Comment by thoHeinze** [comment]
Hi, is there any reason your are forced to use the StreamingContextFactory? You can also use the default ContextFactory and use SparkJob for both Batch Jobs and StreamingJobs. For the StreamingJob you just need to manually create a StreamingContext in your runJob method.

**Comment by velvia** [comment]
You are right, you could just create a streaming context yourself.    For streaming it doesn’t really matter.
The reason for the other contexts such as SQL to use the specific context factories is that for SQL for example you would want the metadata such as table definitions and any cached tables to survive from job to job if you are sharing the context amongst many jobs or using the jobs as  a query interface.

**Comment by wangsir1988** [comment]
@thoHeinze @velvia 
Thanks a lot,  i know what you means, that is , we can create and start a streaming context 
in a SparkJob's runJob function. but how can i stop the streaming without stopping the spark context 
if the SparkJob is running?

**Comment by thoHeinze** [comment]
@wangsir1988 Well, you can have only one streaming context inside your SparkContext anyhow (this holds true at least for Spark 1.6.1). This is a restriction of Spark, not of the Spark Jobserver. So if you stop it, you can't start any new streaming context. If it's just about stopping the initial streaming context, you have to build an own solution, afaik Spark Jobserver has no way to do it for you.
