### ISSUE TITLE
REST API to restart SJS

### ISSUE THREAD

**Issue by yiu31802** [spark-jobserver/spark-jobserver#803]
Due to my laziness instead of digging root causes, I often restart the SJS whenever it becomes unresponsive, often after multiple job requests or heavy sequential job requests.

I would like to have a REST API that restarts SJS, if it is technically possible. Otherwise, I would create a thin REST API layer that executes restart shell command....

**Comment by velvia** [comment]
Hmmm….. let me think.  I think this might be technically possible if you were running context-with-jvm=true.   The problem with running SparkContexts in-process with HTTP is that some SparkContexts are just difficult or impossible to restart, such as StreamingContexts.

**Comment by yiu31802** [comment]
Hello, I just implemented a quick-and-dirty SJS restart mechanism in javascript: https://www.npmjs.com/package/sjs-wrapper I actually use this package in my work cause our SJS server sometimes faces unexpected error or low performance, which can be resolved by restart.
