### ISSUE TITLE
Unable to run Java job 

### ISSUE THREAD

**Issue by kxiao** [spark-jobserver/spark-jobserver#807]
I am getting following errors when running Java jobs from the latest master code:
localhost:8090/jobs?appName=test&classPath=spark.jobserver.JavaHelloWorldJob
{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/context-supervisor/f5ea6c4d-spark.jobserver.JavaHelloWorldJob#-1670962549]] after [10000 ms]. Sender[null] sent message of type \"spark.jobserver.JobManagerActor$StartJob\".",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": [
      "akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)",
      "akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)",
      "scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)",
      "scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)",
      "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)",
      "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)",
      "akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)",
      "akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)",
      "akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)",
      "java.lang.Thread.run(Thread.java:745)"
    ]
  }
}
All Scala jobs run OK.
Would you please help to check what's the issue?

Thanks,

**Comment by hntd187** [comment]
Are you using the right context factory?

**Comment by kxiao** [comment]
I did not set anything for that.  Where should I set it? 
By the way, I am using sbt shell, restart to start the job server.

**Comment by jxchanghe** [comment]
First, you need first to create the context with JavaSparkContextFactory, like follow:
   **POST http://localhost:8090/contexts/java-context?context- factory=spark.jobserver.context.JavaSparkContextFactory**

Second, post the job under the context, like follow:
  **POST http://localhost:8090/jobs?appName=test&classPath=spark.jobserver.JavaHelloWorldJob&context=java-context**

**Comment by kxiao** [comment]
Thanks, It works now. Are there any documents about this, or other configurations and work flow ?

**Comment by velvia** [comment]
Please check the doc/ directory for a whole bunch of assorted docs.

**Comment by kxiao** [comment]
I don't see this in documents under /doc.
Thanks for all your help. I will close this.
