### ISSUE TITLE
JobInfoActor is retrieving job config in an unefficient way causing OutOfMemory error

### ISSUE THREAD

**Issue by zromi18** [spark-jobserver/spark-jobserver#819]
In case of GetJobConfig message JobInfoActor retrieves all the jobs' configs into Map first and then gets one config for the particular jobId from it. When there are many jobs executed in the past, then such an approach leads to OutOfMemory error.

**Comment by velvia** [comment]
Thanks, yes this should be fixed.

**Comment by zromi18** [comment]
@noorul @velvia My pull request that has solved the bug has been merged into the master branch. Can I just close the issue or does it require some kind of approval ?

**Comment by velvia** [comment]
@zromi18 you should be able to close it.  If not one of us can help you.
