### ISSUE TITLE
Unable to log debugging messages

### ISSUE THREAD

**Issue by curran** [spark-jobserver/spark-jobserver#82]
I'd like to output messages using `println` from a running job for debugging, but I'm not sure how to do this. I tried using `println` within a job, and was hoping to see the output in `job-server-local.log`, but it is not appearing there. Is there a different API that should be used for printing messages to the log? Thank you.

**Comment by velvia** [comment]
Hmm.... not sure why println isn't working, but you probably want to use
standard SLF4J logging.

-Evan

On Thu, Mar 5, 2015 at 12:01 PM, Curran Kelleher <notifications@github.com>
wrote:

> I'd like to output messages using println from a running job for
> debugging, but I'm not sure how to do this. I tried using println within
> a job, and was hoping to see the output in job-server-local.log, but it
> is not appearing there. Is there a different API that should be used for
> printing messages to the log? Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/82>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by zeitos** [comment]
Generally speaking it's not a great idea to use println for debugging messages... you want to use log4j (slf4j, logback) for that b/c you can set the log level and just print what you need.
Anyway: println sends logs to the StdOut so you'll see the logs on the terminal screen where you run jobserver.

If you really want to use println and send it to job-server-local.log you can do what's described here : http://stackoverflow.com/questions/1200175/log4j-redirect-stdout-to-dailyrollingfileappender

**Comment by curran** [comment]
Ok that sounds great, thank you for the information.
