### ISSUE TITLE
Spark Driver Memory

### ISSUE THREAD

**Issue by LeiSun-1101** [spark-jobserver/spark-jobserver#822]
When I use the spark job server to create a context, could I use some parameters to control the size of the memory of the driver in the job server? I use the spark job server 0.6.2.

**Comment by noorul** [comment]
As of now this cannot be done. But it will be a nice enhancement.

**Comment by thoHeinze** [comment]
Specifying a driver memory is possible after the change https://github.com/spark-jobserver/spark-jobserver/pull/982

**Comment by thoHeinze** [comment]
@bsikander: Please close this issue.
