### ISSUE TITLE
Starting a new job does not determine proxy user

### ISSUE THREAD

**Issue by zromi18** [spark-jobserver/spark-jobserver#827]
Starting a new job does not determine proxy user, that results in two issues:
- if context name is not provided in the request, the adHoc context is not created for the proxy user,
- if context name is provided and the context was created for the proxy user, then the context name in the request has to be prep-ended with the proxy user name and '~' character to be found, otherwise it is not found

**Comment by velvia** [comment]
Fix is merged now.
