### ISSUE TITLE
scala 2.11 what do you think?

### ISSUE THREAD

**Issue by zeitos** [spark-jobserver/spark-jobserver#84]
Here's my main issue: I need to have the disk encrypted at work and scala 2.10 seems to have some issues with long file names and encrypted FSs 

The main difference is that we need to update slick and sbt-scoverage

These are the changes that I tried:
https://github.com/zeitos/spark-jobserver/pull/1/files

**Comment by velvia** [comment]
I'm in support of having an option to compile for both 2.10 and 2.11.   Need some build work to support both, obviously.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by zeitos** [comment]
I just added a PR #85 for that

**Comment by velvia** [comment]
Since we're close to merging #85 I'm going to close this issue.
