### ISSUE TITLE
when packaging job server ( spark-2.0-preview branch) settings.sh not automatically copying to installation folder

### ISSUE THREAD

**Issue by SanthoshPrasad** [spark-jobserver/spark-jobserver#842]
when packaging job server using **bin/server_package.sh <environment>**  settings.sh file not automatically copying to installation folder.

**Comment by hyitclj** [comment]
why I don's use it ? detail in https://github.com/spark-jobserver/spark-jobserver/issues/936

**Comment by bsikander** [comment]
Closing as outdated.
