### ISSUE TITLE
commit dadd89a6 missing in v0.7.0 ?

### ISSUE THREAD

**Issue by msohn** [spark-jobserver/spark-jobserver#843]
I noticed that the following commit (last commit in v0.6.2) isn't contained in v0.7.0:

commit dadd89a69d8c3613d643de590ad8e0c87d8fda9b (tag: v0.6.2, origin/jobserver-0.6.2-spark-1.6.1)
Author: Evan Chan <velvia@gmail.com>
Date:   Thu Apr 28 00:04:28 2016 -0700

    Add missing manager_start.sh to docker file; make context-per-jvm default to false

Not sure if this is by intention or if you missed to include it in v0.7.0

**Comment by velvia** [comment]
Thanks, let me look into this

**Comment by noorul** [comment]
I see those two changes in v0.7.0.

**Comment by msohn** [comment]
but git says it's only contained in v0.6.2:

$ git clone https://github.com/spark-jobserver/spark-jobserver.git
Cloning into 'spark-jobserver'...
remote: Counting objects: 8632, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 8632 (delta 10), reused 21 (delta 4), pack-reused 8589
Receiving objects: 100% (8632/8632), 1.99 MiB | 639.00 KiB/s, done.
Resolving deltas: 100% (4373/4373), done.
$ cd spark-jobserver/
$ git tag --contains dadd89a6
v0.6.2
