### ISSUE TITLE
Spark Job Server Version

### ISSUE THREAD

**Issue by sunleialbert** [spark-jobserver/spark-jobserver#848]
Now my team needs to support the spark job server version 0.6 and spark job server version 0.7. I want to know if there exists some methods (eg. restful api) to know the version of the spark job server version.

**Comment by noorul** [comment]
As of now we don't have an API that will let you know which version of SJS is running on the server. But at compile time you know against which version are you compiling. For your artefacts you can have sjs version number as suffix.

**Comment by sunleialbert** [comment]
Thanks a lot.
