### ISSUE TITLE
SJS is not properly storing/using timestamp milliseconds in the binaries (JARs) storage system

### ISSUE THREAD

**Issue by Meehau** [spark-jobserver/spark-jobserver#857]
The storing of binaries (usually a JAR) properly includes a Upload Date timestamp with milliseconds (as the precision of up to 1 second may not be enough), but the underlying storage mechanism (ex. SqlDao) seems to round off these millisecond parts. Its also visible on the Spark Job Server UI /jars/binaries API - all the timestamps are rounded to the full seconds only.

**Comment by thoHeinze** [comment]
This issue has been fixed by https://github.com/spark-jobserver/spark-jobserver/pull/878

**Comment by thoHeinze** [comment]
@bsikander Can you please close the issue?
