### ISSUE TITLE
Public job server service (SaaS)

### ISSUE THREAD

**Issue by codemeow5** [spark-jobserver/spark-jobserver#865]
I'll plan to building a SaaS platform based on SJS. Anyone can submit job to our platform based on SJS API. But I found the files submitted by user (through /data apis) is placed in a unified directory.

So, my first step is to rewrite DataFileDAO. In order to save data files into different tenant directories. At the same time, I've found that DataFileDAO persistent metadata to [a separate binary file](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/scala/spark/jobserver/io/DataFileDAO.scala#L11). I plan to save the metadata into the [database backend](https://github.com/spark-jobserver/spark-jobserver#configuring-spark-jobserver-meta-data-database-backend).

I hope you can give me your opinion.

**Comment by hntd187** [comment]
So you're basically adding multi-tenant support? I think you're going to need to also add authentication or some mechanism similar on top of some routes in order to achieve this, which I believe is a lot more work than just implementing a file dao

**Comment by codemeow5** [comment]
@hntd187 This is only the first step. I think it would be better to decompose a task into several tiny task.

**Comment by velvia** [comment]
Hi Alexander,

Thanks, I like this idea.  The data API was only designed for local access, but I agree saving metadata to DB and allowing pluggable file DAO (such as to HDFS) would be improvements.

**Comment by codemeow5** [comment]
Hi, @velvia .What do you mean by "The data API was only designed for local access"?

**Comment by velvia** [comment]
Sorry I meant to say I think it was only designed for small files. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
"We can do no great things, just small things with great love." -mother Teresa
