### ISSUE TITLE
Is there is 64k constraint for post request 

### ISSUE THREAD

**Issue by ruoguluo** [spark-jobserver/spark-jobserver#867]
Hello,

I am using SJS 0.6.2.

In this method override def runJob(sqlContext: HiveContext, config: Config), I want to get data using:
val data = config.getString("data")

In my post request, data is in json format.  {"data":"a long string"}. I found that if the long string is bigger than 64K, it will cause exception. 

Does anyone meet such a situation?

**Comment by amarouni** [comment]
@ruoguluo This was fixed in #659 and this PR : https://github.com/spark-jobserver/spark-jobserver/pull/661
Take a look there, maybe you're not using the correct serializer.

**Comment by noorul** [comment]
@ruoguluo Is it working for you now?

**Comment by noorul** [comment]
Closing this. Please feel free to re-open if you are still facing this issue.
