### ISSUE TITLE
Performance SqlDAO in SJS 0.7

### ISSUE THREAD

**Issue by thoHeinze** [spark-jobserver/spark-jobserver#876]
Hi all, 

with the recent release 0.7 we were forced to switch from the FileDAO to SQLDAO. Since than we see major performance problems. We investigated already the root cause of these problems and are willing to contribute patches, but we like first to understand the current architecture a bit better. 

Our setup:
* we use Spark Jobserver with a H2 database running in server mode on the same VM and use context-per-jvm = true
* our Jobserver constantly runs 8 to 10 Spark jobs concurrently, which are updated frequently
* our users push jars larger than >30 MB and given that they don't always delete their jars afterwards we have several douzen up to hundreds of JARs existing on the jobserver; the H2 database will grow to several gigabyte of memory
* a simple "Select count(*) from BINARIES" will take 10 to 15 seconds for this setup
* most calls from the jobserver itself to the database fail due to the hard-coded timeouts inside the current code

Questions:
**BINARY vs. BLOB**: Currently you use BINARY as column type for storing the JAR inside H2. All BINARY data will be stored in Memory and is not thought for storing files. Why are you not using BLOB as recommended by H2 for storing files ? 
**Separate Metadata**: The BINARIES table is not only used for accessing the jars itself, but also for getting information about the jobs. Why don't you seperate the raw file content into a separate table and just have a hash inside the BINARIES table ?
**Streaming vs. loading data into ByteArray**: Is there any reason you always need to load the whole file into a ByteArray before transfering it? You could just use a streaming API for it.
**FileCacher**: What is the purpose of the FileCacher? In our setup with Jobserver and DB on the same host, it only results in a redundant storage of all jars. Imho this should be an optional feature, which is turned of by default (it only make sense if the DB runs on a separate host).

**Comment by msohn** [comment]
The H2 documentation says the following about the BINARY type [1]:

"Represents a byte array. For very long arrays, use BLOB. The maximum size is 2 GB, but **the whole object is kept in memory when using this data type**. The precision is a size constraint; only the actual data is persisted. For large text data BLOB or CLOB should be used."

I did some experiments and found that as soon as the total size of all binaries stored in the BINARIES table grows towards max heap size of the H2 process even simple SQL queries not explicitly selecting the BINARY column (e.g. "select BIN_ID from BINARIES") is slowing down heavily and finally crashes H2 probably due to an OOM.

After reading the H2 documentation on datatype BLOB [2] I tried to change the datatype of BINARIES.BINARY to datatype BLOB and adapted JobSQLDao accordingly. This fixed this issue. I started working on a corresponding flyway migration so I could create a pull request somewhen later this week if you agree on the direction of the fix.

[1] http://www.h2database.com/html/datatypes.html#binary_type
[2] http://www.h2database.com/html/datatypes.html#blob_type

**Comment by velvia** [comment]
@msohn thanks for this fix, looking forward to it.  It definitely sounds like the right direction.

**Comment by hntd187** [comment]
Wouldn't it be a better idea to just use a real database instead of H2 or am I missing something here?

**Comment by thoHeinze** [comment]
@hntd187 the way you design your schema is independent of the used database. The arguments of BINARY vs. BLOB are the same for Postgres ( see https://wiki.postgresql.org/wiki/BinaryFilesInDB). However, I have to admit that we only tested H2.

**Comment by Meehau** [comment]
Hello all,

We're experiencing similar issues, and just wanted to add that it happens that I'm also currently working on it - on the "**Separate Metadata**" part so far, that @thoHeinze mentioned (we came to the same conclusion). The tables should be definietely split into two parts, I agree. Going to submit a pull request on Thursday.

As for the other points - yes, we also agree that a **Streaming** option may be more efficient. Will look into that later too. I think its definitely doable. 

**FileCacher** - I've recently worked on this (see #786) and, again, I think its possible to make it optional.

**Comment by msohn** [comment]
Using column type Blob instead of byte array is also better for Postgres and Mysql. Databases manage blobs separate from other data which improves efficiency of database caches, improves performance and reduces memory consumption.

**Comment by hntd187** [comment]
Well right I'm not saying that anything in regards to the scheme is wrong or unnecessary but h2 is meant to be a quick up and running feature not a production level feature. All I'm asking is wouldnt switching to a real DB on a real server allievoate a lot of this without a code change?

**Comment by thoHeinze** [comment]
@hntd187 Well, obviously postgres or mysql will provide you more stability etc. But like @msohn and I already pointed out, BINARY will also be a problem for them. So the simple question is: Do you want to reserve enough memory to load all jars in memory of the backend database? We are not happy to have a database with 16 GB RAM memory or similar, also in productive use cases.

**Comment by velvia** [comment]
@htnd187 it seems to me this change benefits all databases, not just H2, so I think we should just proceed with it.  It seems using a BLOB type is a better approach (though I suppose you can argue that an incremental type where we store part of the jar is even better).

**Comment by hntd187** [comment]
@velvia oh no I don't wish to imply I'm not on board with the changes, I absolutely am. Please don't think I don't agree with what people are suggesting, I'm just  trying to understand how much the problem would change if you switched to something like PSql from H2

**Comment by velvia** [comment]
@htnd187 got it.  
Ultimately the bigger issue with H2 is that unless you use the locking mode, it just doesn’t work with the multi-JVM / context-per-JVM model.

**Comment by thoHeinze** [comment]
@hntd187 I will run a small test scenario with a postgres db and let you know afterwards, no problem.

**Comment by hntd187** [comment]
@thoHeinze It's not a huge deal, I was more just curious, if it's even a slight hassle don't bother, either way the change would be a great thing to have

**Comment by noorul** [comment]
Closing this.

**Comment by thoHeinze** [comment]
@noorul Can we please leave this issue open as meta issue.  Many parts of the problem have not been adressed. We actually waited for https://github.com/spark-jobserver/spark-jobserver/pull/886 to be merged before continuing here.

**Comment by thoHeinze** [comment]
Most of the points discussed in this issue have been solved: 
* use BLOB type for JAR Content by PR https://github.com/spark-jobserver/spark-jobserver/pull/881
* move binary content into separate by PR table https://github.com/spark-jobserver/spark-jobserver/pull/932
* prevent saving the same JAR multiple times by PR https://github.com/spark-jobserver/spark-jobserver/pull/960
* make caching optional feature by PR https://github.com/spark-jobserver/spark-jobserver/pull/950

Thanks everyone for contributing and reviewing!

**Comment by velvia** [comment]
Thank you too!
