### ISSUE TITLE
Spark Streaming context 

### ISSUE THREAD

**Issue by tarekabouzeid** [spark-jobserver/spark-jobserver#88]
i am trying to do the word count example on flume stream, so i tried to modify the already existing wordcount example code , compilation successfully done on sbt , but when i try to run the jar on job server using hue interface , it gives out an error and the job server is shutdown 

object WordCountExample extends SparkJob {
  def main(args: Array[String]) {
    val sc = new SparkContext("spark://bdvm01.ejada.com:7077", "WordCountExample")
    
    val config = ConfigFactory.parseString("")
    val results = runJob(sc, config)
    println("Result is " + results)
  }

  override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
    Try(config.getString("host"))
      .map(x => SparkJobValid)
      .getOrElse(SparkJobInvalid("No host/port config params"))
  }
  override def runJob(sc: SparkContext, config: Config): Any = {
    val batchInterval = Milliseconds(2000)
    val ssc = new StreamingContext(sc, batchInterval)
    val stream = FlumeUtils.createStream(ssc, config.getString("host"), config.getString("port").toInt)
    val body = stream.map(e => new String(e.event.getBody.array))
    val counts = body.flatMap(line => line.toLowerCase.replaceAll("[^a-zA-Z0-9\\s]", "").split("\\s+"))
                 .map(word => (word, 1))
                 .reduceByKey(_ + _)

    counts.saveAsTextFiles("/usr/local/output/output")

    ssc.start()
    ssc.awaitTermination()
    
  }
}

and that's the error : 

> job-server[ERROR] Uncaught error from thread [JobServer-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[JobServer]
job-server[ERROR] java.lang.NoClassDefFoundError: org/apache/spark/streaming/Milliseconds$
job-server[ERROR]       at spark.jobserver.WordCountExample$.runJob(WordCountExample.scala:38)
job-server[ERROR]       at spark.jobserver.WordCountExample$.runJob(WordCountExample.scala:23)
job-server[ERROR]       at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:228)
job-server[ERROR]       at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
job-server[ERROR]       at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
job-server[ERROR]       at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
job-server[ERROR]       at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
job-server[ERROR]       at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
job-server[ERROR]       at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
job-server[ERROR]       at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
job-server[ERROR]       at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
job-server[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.spark.streaming.Milliseconds$
job-server[ERROR]       at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
job-server[ERROR]       at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
job-server[ERROR]       at java.security.AccessController.doPrivileged(Native Method)
job-server[ERROR]       at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
job-server[ERROR]       at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
job-server[ERROR]       at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
job-server[ERROR]       ... 11 more
job-server ... finished with exit code 255

so does that mean that job server doesn't support streaming yet ?

**Comment by duncanfinney** [comment]
` java.lang.NoClassDefFoundError: org/apache/spark/streaming/Milliseconds$`

It sounds like you are building the jar against an different version of spark or java than what is on the server.

**Comment by velvia** [comment]
Agreed, check your classpath and versions.

On Mon, Mar 16, 2015 at 9:08 AM, Duncan Finney <notifications@github.com>
wrote:

> java.lang.NoClassDefFoundError: org/apache/spark/streaming/Milliseconds$
>
> It sounds like you are building the jar against an different version of
> spark or java than what is on the server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/88#issuecomment-81764708>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by tarekabouzeid** [comment]
thank you for your responses guys , i found that i must add some jars to the class path of the job server , as my code requires some extra dependency jars , but i don't know where to add these dependency jars to the job server i checked some issues with dependency jars but still don't know where to add them  , can you tell me where to add the dependency jars if you please ?  also i wonder if i have a running streaming job in the job server , is it possible to stop the job from the job server ?

**Comment by duncanfinney** [comment]
You should make a "fat jar" to deploy your code. Or takes all your jars and puts them into one big jar. It's a pretty common thing in java development. Namespaced files get matching folder structures so you can put a ton of jars together without file collisions. 

Check out sbt-assembly if you're using SBT. 

http://github.com/SBT/sbt-assembly

**Comment by peterklipfel** [comment]
Note that this can have issues with submitting to the spark jobserver. I found it preferable to use the `packages` flag with the docker container than to mess with the configs
