### ISSUE TITLE
How to create 2 rdds in a single spark sql job ?

### ISSUE THREAD

**Issue by AnshPrusty** [spark-jobserver/spark-jobserver#885]
Below is my code.
override def runJob(sc:SQLContext, jobConfig: Config): Any = {
   import sc.implicits._
   val df1 = sc.read.format("jdbc")
    	.option("url", "jdbc:postgresql://<ip>:5432/<dbname>")
    	.option("driver", "org.postgresql.Driver")
    	.option("dbtable", "table1_name")
    	.option("user", "postgres")
    	.option("password", "<password>")
    	.load()
   val tb1 = df1.registerTempTable("table1")
   val df2 = sc.read.format("jdbc")
    	.option("url", "jdbc:postgresql://<ip>:5432/<dbname>")
    	.option("driver", "org.postgresql.Driver")
    	.option("dbtable", "table2_name")
    	.option("user", "postgres")
    	.option("password", "<password>")
    	.load()
    val tb2 = df2.registerTempTable("table2")
    sc.sql(jobConfig.getString("sql")).collect()
}
when I pass" sql =select count(*) from table1" in a post request it works but for table2 is shows 'table or view not found'
I think RDDS are not getting created...
Then how to create 2 RDDS from 2 different tables in a single job?
If that is not possible how to share rdds between jobs?

**Comment by Majea** [comment]
val tb2 = df1.registerTempTable("table2")
should be 
val tb2 = df2.registerTempTable("table2")
maybe?

**Comment by AnshPrusty** [comment]
Thanks for your replay @Majea but its val tb2 = df2.registerTempTable("table2") actually

**Comment by velvia** [comment]
Hmm, I don’t see anything wrong with your code (other than what @Majea pointed out).  All you normally need to do is registerTempTable and the SQLContext carries over its context between jobs (assuming the other job is also assigned to the same SQL context).   Have you tried listing the tables available?  This is possible with some APIs of SQLContext.

**Comment by AnshPrusty** [comment]
hi @velvia I have done it but when I add one more rdd to that same class and again rerun it using a new app name the 3rd rdd shows table or view not found
while using a new class to create 3 rdds works perfectly...
can you tell me is there any log file for jobs? I know there is a log file for job server(job-server-local.log)But when I put a println to it a job it does reflect in that job-server-local.log. I don't know where is the jobs log.Thank you

**Comment by velvia** [comment]
If you use context-with-jvm=true, then there are separate log files under the directory for each process/context.  If you don’t, then all logs get sent to the main job-server(-local).log

**Comment by AnshPrusty** [comment]
Below is the code to create multiple rdds in a spark job
override def runJob(sc:SQLContext, jobConfig: Config): Any = {
    import sc.implicits._
    val tables = jobConfig.getStringList("tablenames").toList
    for ( table <- tables ) {
         val df = sc.read.format("jdbc")
		    	.option("url", "jdbc:postgresql://<ip>:5432/<database>")
		    	.option("driver", "org.postgresql.Driver")
		    	.option("dbtable", table)
		    	.option("user", "postgres")
		    	.option("password", "password")
		    	.load()
		 val ab = df.registerTempTable(table)
      }
     sc.sql("show tables").collect()
}
override def validate(sc:SQLContext, jobConfig: Config): SparkJobValidation = SparkJobValid





In the url send parameter as below
string urlParameters  = "\"tablenames\":[\"table1\",\"table2\"]";

You will find the job result = ["[,table1,true]","[,table2,true]"]
That means RDD has been created for both the tables.
If any of them is false check your database connection.

Thanks @Majea and @velvia
