### ISSUE TITLE
spark jobserver corrupts international characters in json response

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#887]
I noticed that international characters returned in json were coming through corrupted (appeared as question marks inside of diamonds). I'm not sure, but I think this line in spark/jobserver/ChunkEncodingActor.scala
 HttpResponse(entity = HttpEntity(MediaTypes.`application/json`), ...
needs to be 
 HttpResponse(entity = HttpEntity(MediaTypes.`application/json`.withCharset(HttpCharsets.`UTF-8`), ...
instead

**Comment by velvia** [comment]
Thanks @barrybecker4

**Comment by barrybecker4** [comment]
My apologies. This does not seem to be a job-server issue at all. The problem was on our end.
We were writing files with
new BufferedWriter(new FileWriter(filename))
but should have been using
new BufferedWriter(new OutputStreamWriter(new FileOutputStream(filename), "UTF8"))
Not a jobserver issue. Closing.
