### ISSUE TITLE
Hi, dear guys, is there some way to call set of SparkConf in new version of spark-jobserver? 

### ISSUE THREAD

**Issue by qihuagao** [spark-jobserver/spark-jobserver#889]
I intend to use:
 set("spark.kryo.registrator", "com.inneractive.fortknox.kafka.AggregationKryoRegistrator")

Thanks a lot!

**Comment by hntd187** [comment]
Do you mean inside a job? You can get the current context conf from the `SparkContext` and you can get the `SparkContext` from the `SparkSession`, or are you trying to configure it ahead of time? The documentation has all the steps on how to setup contexts and their configuration ahead of time.

**Comment by qihuagao** [comment]
Thanks for quick resp. Yes, its inside a job. 
For the time being, I just used uploading jar of job. So does this meaning I can only load the jar with job server, make them start together?
