### ISSUE TITLE
java.lang.NoClassDefFoundError - org.apache.spark.sql.types.DataType

### ISSUE THREAD

**Issue by liweys** [spark-jobserver/spark-jobserver#890]
The app _ex1_ was uploaded successfully. 
_ex1_ works fine with spark-submit. 

Failed to start job _ex1_  (see below), but _WordCountExample_ works fine.
**The missing class can be found in spark-2.1.1\jars\spark-catalyst_2.11-2.1.1.jar.**

Cmd 

> curl -d "" "host:8090/jobs?appName=ex1&classPath=demo.spark.Stitcher2"

Error stack:

> "cause": "org.apache.spark.sql.types.DataType",
>  "stack": ["java.net.URLClassLoader.findClass(URLClassLoader.java:381)"
>  "java.lang.ClassLoader.loadClass(ClassLoader.java:424)"
>  "java.lang.ClassLoader.loadClass(ClassLoader.java:357)"
>  "java.lang.Class.getDeclaredFields0(Native Method)"
>  "java.lang.Class.privateGetDeclaredFields(Class.java:2583)"
>  "java.lang.Class.getField0(Class.java:2975)"
>  "java.lang.Class.getField(Class.java:1701)"
>  "spark.jobserver.JarUtils$.loadObject(JarUtils.scala:61)"
>  "spark.jobserver.JarUtils$.loadClassOrObject(JarUtils.scala:37)"
>  "spark.jobserver.JobCache$$anonfun$getSparkJob$1.apply(JobCache.scala:33)"
>  "spark.jobserver.JobCache$$anonfun$getSparkJob$1.apply(JobCache.scala:29)"
>  "spark.jobserver.util.LRUCache.get(LRUCache.scala:47)"
>  "spark.jobserver.JobCache.getSparkJob(JobCache.scala:29)"
>  "spark.jobserver.JobManagerActor$$anonfun$startJobInternal$1.apply$mcV$sp(JobManagerActor.scala:143)"
>  "scala.util.control.Breaks.breakable(Breaks.scala:37)"
>  "spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:131)"
>  "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:120)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)"
>  "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)"
>  "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)"
>  "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)"
>  "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)"
>  "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)"
>  "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:20)"
>  "akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)"
>  "akka.actor.ActorCell.invoke(ActorCell.scala:456)"
>  "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)"
>  "akka.dispatch.Mailbox.run(Mailbox.scala:219)"
>  "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)"
>  "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)"
>  "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)"
>  "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)"
>  "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"]
> 
>     "causingClass": "java.lang.ClassNotFoundException"
>

**Comment by thoHeinze** [comment]
What kind of context did you use ? Catalyst is part of the Spark SQL part, you need to use maybe a SQL Context:  https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/contexts.md
