### ISSUE TITLE
Worker cannot connect back to driver: Connection refused

### ISSUE THREAD

**Issue by rabejens** [spark-jobserver/spark-jobserver#891]
I set up a small Spark environment on two machines. One runs a master and a worker, and the other one runs a worker only. I can use this cluster using the Spark Shell like:

```
spark-shell --master spark://mymaster.example.internal:7077
```

I can run computations in there that get distributed to the nodes correctly, so everything runs fine.

However, I am having trouble when using the spark-jobserver.

First try was to start the Docker container (with the environment variable `SPARK_MASTER` pointing to the correct master URL). When the job was started, the worker it was pushed to complained that it couldn't connect back to `172.18.x.y:nnnn`. This was clear because this was the internal IP address of the Docker container the jobserver ran in.

So, I ran the jobserver container again with `--network host` so it attached itself to the host network. However, starting the job led to a `Connection refused` again, this time saying it couldn't connect to 172.30.10.10:nnnn. 172.30.10.10 is the IP address of the host I want to run the jobserver on and it IS reachable from both worker and master nodes (The Spark instances run in Docker containers too, but they are also attached to the host network).

Digging deeper, I tried to start a Docker container which just has a JVM and Spark inside, ran it with `--network host` too and launched a Spark job from inside. This worked.

What might I be missing?

**Comment by rabejens** [comment]
I investigated some more. I am now at home but I rebuilt the setup with two VMs. I installed Spark on the bare metal and use the jobserver in Docker and this works.

**Comment by velvia** [comment]
Hm interesting.  

I’m wondering what folks would consider the ideal docker setup.   Having Spark be either bare metal or be in a separate VM/container is kind of nice from a separation of concerns thing; it means you can use any one of many standard Spark containers and redeploy only SJS.   But it seems to me the networking would be even harder to setup, but here you are saying it is not.

**Comment by rabejens** [comment]
It turned out to be a much simpler problem: I just checked the error again and it refused to connect to port 7337 which led me to the solution: I set up the jobserver to start jobs with dynamic allocation and forgot to start the shuffle server. *head -> table*
