### ISSUE TITLE
Exceptions in jobs are not serialized properly

### ISSUE THREAD

**Issue by krcz** [spark-jobserver/spark-jobserver#901]
In REST response of jobs with ERROR status there is information about the exception. On creating jobs it contains proper error class and stack trace. When listing jobs (or specific job) though error class always contains `java.lang.Throwable` and stack trace points to `JobSqlDAO` `getJobInfos` function, the place where error is deserialized. It is caused by the fact that only the exception message is persisted.

It makes debugging jobs run on Spark Job Server much harder or even impossible.

**Comment by krcz** [comment]
We need fixing this for our project. I have already started work on the issue, but as we want the fix to be merged, I'm consulting it now.

I see possible solutions:

### 1. Just serialize Throwable using standard Java serialization
Pros:
* all Throwable data is retained in an unchanged form
Cons:
* serialization / deseriazization overhead
* binary blobs in database

### 2. Store error class and printed stack trace as new text fields in database
Pros:
* simple
* most information about stack trace is retained, as text, including information about exceptions the main exception causes (other exceptions placed in cause field
* doesn't require migration other than creating new column in db
Cons:
* currently stack trace in REST API is exposed as JSON list of strings; here it would have to be changed to string, probably

### 3. Store JSON representation of exception, containing error message, class and stack trace
Pros:
the same as in option 1 + readable data in DB
Cons:
* requires much code to support

I will be grateful if you reply quickly, as I would like to implement that soon. My recommendation is option 2.

**Comment by zromi18** [comment]
Hi Krcz,

I vote for option 2. I do not think that lots of implementations depend on a stack trace represented as an array of strings. Even though I would not sacrifice good design over backwards compatibility to not so good interface.

Regards,
Roman Zarzecki

**Comment by krcz** [comment]
@noorul @marcoboi @velvia @hntd187 
Can you take a look at this, please?

**Comment by bsikander** [comment]
Fixed.
