### ISSUE TITLE
Jobserver does not work with Mesos client mode

### ISSUE THREAD

**Issue by yuchaoran2011** [spark-jobserver/spark-jobserver#904]
The configuration guide provided in https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/mesos.md unfortunately is not enough. A few more things need to be done in order for jobs submitted through Jobserver to be correctly launched as Mesos tasks. The main ones required are
1. Spark needs to be built with the appropriate Mesos version. Current Spark build command in build.sbt does not contain -Pmesos flag. In fact, Mesosphere already provdes publicly available Mesos-ready Spark builds.
2. spark.mesos.executor.docker.image needs to be set for the Jobserver to launch Spark tasks in the Mesos cluster.
3. spark.mesos.executor.home needs to be set for the same reason.
4. "proxy-user root" needs to be present as a spark-submit option

Changes I've made to test out this feature in our team are available at: https://github.com/spark-jobserver/spark-jobserver/compare/master...yuchaoran2011:lightbend2.1
It also includes a fix that makes Jobserver easier to use e.g. instead of randomly assigning a port for Spark UI, fix it!

I'm considering making a PR to fix this issue. But I would like to gather some input from project committers and users of Jobserver on Mesos. Thanks!

**Comment by thoHeinze** [comment]
@yuchaoran2011 It does not make sense to hard-code the port of the Spark driver UI. What if you have more than one job on the same host running in parallel ? It is the default behaviour of Spark to choose a random port, the jobserver behaves totally consistent here. If you want to have a specific port you can alway override "spark.ui.port" during the context creation.

**Comment by noorul** [comment]
Please feel free to create PRs. I am not sure whether anyone from @spark-jobserver/committers is using mesos.

**Comment by bsikander** [comment]
Unfortunately, PR was not submitted and no progress was made on the issue.
The master branch has moved ahead and this fix is hard to merge in.

Regarding fixing the Spark UI port, in my opinion, only works for scenarios where we have a single driver.
