### ISSUE TITLE
Context's Json should not be passed as Java argument when starting Context

### ISSUE THREAD

**Issue by marcoboi** [spark-jobserver/spark-jobserver#915]
A Json representing the context's settings is passed as argument to the {{spark-submit}} command that starts the JobManager.
Json encoding does not comply with Java parameter encoding requirements. Therefore, the spark-submit command (which ultimately relies on the java command) will not be able to parse the Json string correctly.
For instance, Json strings can contain white spaces, which are interpreted as parameter separators by Java.
As there is no way to guarantee the Json will have the form of a valid Java parameter, passing Json strings as Java parameters should be avoided altogether.

See also: https://stackoverflow.com/questions/23958338/how-to-stop-java-from-separating-json-string-passed-as-a-command-line-argument-i

I temporarily fixed the issue by reverting to the old system where the context string was dumped to a file and read in by the JobManager.

https://github.com/spark-jobserver/spark-jobserver/blob/eaebce3f1d32dbdbe61ee5b7b9bb2121bde85f7e/job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala#L232

**Comment by thoHeinze** [comment]
@marcoboi Storing the parameters into a file is also no option imho. The change was introduced by @LeightonWong to support the Spark cluster mode, where the driver is running on a Spark worker node and not on the same host like the SJS. As cluster mode is a very important feature for making the jobserver really H/A, we should find another solution.

**Comment by velvia** [comment]
Hmmm…. perhaps we should consider passing the context settings asynchronously after the JobManager starts.

**Comment by LeightonWong** [comment]
Pass the context settings asynchronously as a akka message after JobManager starts is great, for both the Job server settings and custom spark context settings. Now the Job server settings is stored in ${JobServerHome}/xxx.conf file, when using cluster mode, I have to copy this file to all the worker node, and also send the custom context content as a json string enclose with single quota. I did not modify this part of code because this modify will change the main JobManager start process so I only commit the cluster mode part, but it is really not so convenient.
Another solution is to support remote protocol like hdfs/http, to fetch the config settings from single remote address.

**Comment by velvia** [comment]
Yes, an alternative solution is to pass HTTP endpoint (perhaps pointing back to main job server), though this seems like unnecessary overhead since there is Akka already.  HDFS should be fine though not every installation of Spark has HDFS (eg, Datastax Enterprise, and other edge cases).

**Comment by marcoboi** [comment]
@thoHeinze, I forgot to mention that I store the file locally in _my current setup_, where I run on a Local instance of Spark. I understand that will not work in a cluster setup. 
I was just suggesting a temporary patch for those who might have been in the same situation.

**Comment by marcoboi** [comment]
Passing the context settings after the JobManager has started seems to me the way to go.
Ideally, I would say we should let Akka do the communication, instead of creating a custom REST end point.

**Comment by velvia** [comment]
Totally agree.

**Comment by liweys** [comment]
`java` works fine with args with blanks etc. There is no problem to pass json string as an arg, just make sure the string is really **passed**. If you split the string yourself, that's not java's problem (in your case your shell splitted the string, not `java`).

**Comment by derSascha** [comment]
PR #927 implements the akka version. The job manager connects to the akka cluster and than transfers the context config via akka. Only the cluster address and actor name is added as arguments. No local `context.conf` file or JSON arguments anymore.
