### ISSUE TITLE
manager_start's process cannot run synchronously

### ISSUE THREAD

**Issue by marcoboi** [spark-jobserver/spark-jobserver#917]
While the process that executes {{manager_start}} is locked for synchronous execution at line 248, the script execute the spark-submit command as a forked process. 
That means that the only synchronous part of the script (and the only part that can really fail) is the part _before_ the spark-submit command.
Forking the process also implies that any output produced by spark-submit is sent to {{null}}, so there is no way any error to the application's logs.

Since there is no way of running the spark-submit command synchronously _and_ wait for the return code: 
* the script process should be run in an asynchronous process 
* spark-submit should not be executed in a forked process but in the main process
* output generated by spark-submit should be logged in the main application

https://github.com/spark-jobserver/spark-jobserver/blob/eaebce3f1d32dbdbe61ee5b7b9bb2121bde85f7e/job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala#L247

**Comment by thoHeinze** [comment]
I personally don't get why the Spark Jobserver writes here some custom code to achieve this. There is a standard solution offered by Spark: the SparkLauncher (see https://spark.apache.org/docs/2.2.0/api/java/index.html?org/apache/spark/launcher/package-summary.html) @velvia: Is there any reason why we don't use the SparkLauncher?

**Comment by velvia** [comment]
I believe we considered it at one point but don’t remember why we don’t.  
As long as SparkLauncher offers the same variety of launch options and we can launch the JobManager process in a similar way, it’s probably fine.

However there are other PRs now that tries to fix the current iteration so let us consider the approaches.

**Comment by marcoboi** [comment]
@thoHeinze's suggestion is worth considering:
* would be easier to maintain (maintaining a shell script in line with Scala code is a pain - I've been doing that)
* would support Unix and Windows in one shot (currently, there is no Windows manager_submit)

@velvia, could you point out some of the hurdles you came across when considering that option?

**Comment by velvia** [comment]
My memory is really bad…. I blame having 3 kids.  :-p

@hntd187 @noorul @fotero do you guys remember how the design discussions went around the context-per-ivm / separate process?  I sort of remember someone implemented the script-based approach and we ran with it.

There are also some old PRs for context-per-ivm that one can dig through.

**Comment by thoHeinze** [comment]
@velvia: I just went through the history and found two related PR's: https://github.com/spark-jobserver/spark-jobserver/pull/120 and https://github.com/spark-jobserver/spark-jobserver/pull/345 Both have a lot of comments, but I didn't see anything related to the SparkLauncher.

**Comment by marcoboi** [comment]
Thanks @velvia , I had plans to work on the manager_start script to improve it. When I get to that, I'll have a look if we can do away with it in and use the Launcher instead.

**Comment by noorul** [comment]
@marcoboi Please go ahead and improve it.

**Comment by marcoboi** [comment]
hey @noorul , fixes for 916 and 917 are in https://github.com/spark-jobserver/spark-jobserver/pull/918

**Comment by bsikander** [comment]
SparkLauncher has replaced manager_start in the new release. Closing.
