### ISSUE TITLE
JsonFormat from runjob

### ISSUE THREAD

**Issue by SivaKaviyappa** [spark-jobserver/spark-jobserver#926]
I am not sure if this is an issue may be some body can give me an pointer on how to achieve this. I will be much obliged.
 I am using spray json api. 
case class Response(jobCompleted:String,detailedMessage:String)
Type jobOutput=String
override def runJob(sc: HiveContext, runtime: JobEnvironment, data: 
JobData): JobOutput = {
  val generateResponse= new GenerateResponse(data,sc)
  val response=generateResponse.generateResponse()
  response.pettyPrint
}
I would like my response to be a json like this,
" result":{
     "jobCompleted":true,
    "detailedMessage":"all good"
   }  
how ever I am getting it like this
```
result:{ {"{\"jobCompleted\":\"true\",\"detailedMessage.."}.

``

Now I tried to set it response.toJson and I got an AST
"result": [{
    "jobCompleted": ["true"],
    "detailedMessage": ["all good"]
  }],

Thanks,
Siva

**Comment by velvia** [comment]
Siva,

What are you trying to do overall?   So you have a Scala program that is using HTTP to talk to JobServer, is that right?

Evan Chan
velvia@gmail.com
----
“Never doubt that a small group of thoughtful, committed citizens can change the world.” —M. Mead

**Comment by SivaKaviyappa** [comment]
Nothing complicated.Yes that's correct.

**Comment by SivaKaviyappa** [comment]
This is not an issue. I am new  and I finally figured that this is achieved by returning the values as Map[String,JsValue].
