### ISSUE TITLE
Does not return result for Type Map[String,Any]

### ISSUE THREAD

**Issue by SivaKaviyappa** [spark-jobserver/spark-jobserver#929]
Hello - Is there a way around this?

object SampleSJS extends App with SparkHiveJob  {

  type JobData = String
  type JobOutput = collection.Map[String,Any]

  def ccToMap(cc: AnyRef) =
    (Map[String, Any]() /: cc.getClass.getDeclaredFields) {
      (a, f) =>
        f.setAccessible(true)
        a + (f.getName -> f.get(cc))
    }

  override  def runJob(sc: HiveContext, runtime: JobEnvironment, data: JobData): JobOutput ={
      val xlst=List("one","two")
      val ylst=List("three","four")
      val subresult1=SubResult(xlst)
      val subresult2=SubResult(ylst)
      val subResultlist=List(subresult1,subresult2)
      val response=Response("xxxx","yyy",subResultlist)
      val responseMap=ccToMap(response)
  
     val result=responseMap.map{ case (k, v) => k.toString -> v }

            result
    
   }
case class Response(param1:String,param2:String,param3:List[SubResult])

case class SubResult(lst:List[String])

{
  "duration": "0.027 secs",
  "classPath": "com.SampleSJS",
  "startTime": "2017-09-19T01:20:51.138-04:00",
  "context": "cntxt1",
  "status": "FINISHED",
  "jobId": "d58d3edb-0cb0-462f-8185-b0c97a5e1967"
}

**Comment by noorul** [comment]
You can convert your Scala object into JSON string and return it.
