### ISSUE TITLE
Not receiving result node for long answers 

### ISSUE THREAD

**Issue by aminalavian** [spark-jobserver/spark-jobserver#930]
Hi ,

I started job server with "server.start" without any problems. when job has a short result job server works fine and we have result node but when we ask the job server for a long result, job server replies with the "status": "FINISHED" message without the result node. I think maybe the problem is the cache of the job server, it means the job server can not store the long result and we should change some configuration file for increasing the cache !so I am googling a lot but until now I could not find any answer .

This is my    .conf

spark {
  
  master = "local[4]"
  

  
  job-number-cpus = 2

  jobserver {
    port = 8090

    context-per-jvm = true

   
    jobdao = spark.jobserver.io.JobSqlDAO

    filedao {
      rootdir = /tmp/spark-jobserver/filedao/data
    }

    datadao {
      
      rootdir = /tmp/spark-jobserver/upload
    }

    sqldao {
   
      slick-driver = slick.driver.H2Driver

     
      jdbc-driver = org.h2.Driver

     
      rootdir = /tmp/spark-jobserver/sqldao/data

     
      jdbc {
        url = "jdbc:h2:file:/tmp/spark-jobserver/sqldao/data/h2-db;AUTO_SERVER=TRUE"
        user = ""
        password = ""
      }

    
      dbcp {
        enabled = false
        maxactive = 20
        maxidle = 10
        initialsize = 10
      }
    }
    
    result-chunk-size = 1m
  }

 
  context-settings {
    num-cpu-cores = 3G           # Number of cores to allocate.  Required.
    memory-per-node = 1G         # Executor memory per node, -Xmx style eg 512m, #1G, etc.

   
    passthrough {
  
    }
  }

  
}

akka {
  remote.netty.tcp {
     maximum-frame-size = 1000 MiB
  }
}
   

Thanks in advance
S.A.Alavian

**Comment by noorul** [comment]
@aminalavian By long result what do you mean? Is it of type long? Can you provide an example?

**Comment by Vinay-KY** [comment]
It can be you need to set following config
 # Number of job results to keep per JobResultActor/context
    job-result-cache-size = 5000

Refer to troubleshooting page - https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/troubleshooting.md

**Comment by aminalavian** [comment]
@Vinay-KY  Thanks for your reply, I checked what you said with more than 5000 cache results but still not working

**Comment by aminalavian** [comment]
@noorul  thanks for your feedback,I think I can't say my point correctly,what I mean is that the volume of the data in the result is large,the problem is not about the type long,

**Comment by noorul** [comment]
@aminalavian Can you quantify volume here? Are you returning json? If so what is the size?

**Comment by aminalavian** [comment]
I attached the sample of results node when we increase the results node after that I just get:" status : finished" from SJS in the localhost:8090 without results node. although I think SJS store the results node in the H2 database but maybe it just can't show us in the GUI.


[New Text Document.txt](https://github.com/spark-jobserver/spark-jobserver/files/1336073/New.Text.Document.txt)

**Comment by noorul** [comment]
@aminalavian SJS stores the result in cache. If you restart SJS then it will be lost.

**Comment by aminalavian** [comment]
Dear @noorul  I know what you talk about.If I restart SJS after that we lose all results, but for the results that I attached to the last comment every thing works fine but when those results increased SJS just showed status : finished, It means SJS can't store the results, if you have any idea about the cache of the SJS except this parameter in the *.conf "job-result-cache-size = 5000" please let me know. because I checked that parameter but nothing goes well .

**Comment by aminalavian** [comment]
Hi again! Until now I checked with "context-per-jvm=true" in ".conf" but when I change the value from "true" to "false" with the same job I lost the log per job and run many job at the same time but the result node is OK it means I can get big volume of the results. what happens exactly? why when you run a job and the volume of the data in the result is big, only the parameter  "context-per-jvm=false" in the ".conf" works fine?

**Comment by velvia** [comment]
How big is your result?    When context-per-jvm=true, the context is run in a separate JVM and the results have to be transmitted over the wire, which is slower and has lower defaults for size.   Those can be tuned of course.

However I think in general bigger results should really be written to say HDFS and what should be returned is a path to the directory/file etc.

**Comment by aminalavian** [comment]
Dear @velvia  thanks a lot for your replay, about your first paragraph that you mentioned the defaults size, how can we change it? how can we tune the parameter in the ".conf" in order to manage the results size ?

**Comment by aminalavian** [comment]
Hi again :) , Now SJS works with Yarn correctly but Yarn needs some tuning to progress job as soon as possible, but still with "context-per-jvm=true" I can't get big volume of the results. for this situation I need an alternative plan, do you know any applications like SJS with RESTful interface for submitting and managing Apache Spark jobs, jars, and job contexts except "Livy"?
Note: @velvia I am still waiting for your advise about your first paragraph that you mentioned the defaults size, how can we change it? how can we tune the parameter in the ".conf" in order to manage the results size ?

**Comment by velvia** [comment]
So just look under application.conf and you will see various tuning parameters:

akka.remote.netty.tcp.maximum-frame-size, send-buffer-size, receive-buffer-size

spray.can.server.parsing.max-context-length


Evan Chan
velvia@gmail.com
----
“Never doubt that a small group of thoughtful, committed citizens can change the world.” —M. Mead

**Comment by aminalavian** [comment]
Thanks @velvia for your reply, as I mentioned I run SJS with "context-per-jvm=true"on the .conf file and I started SJS with server_start.sh script,on the SJS page at github.com they explain for running SJS on the cluster mode we should configure the .conf file and some other configurations file, after I configured all of them every thing works fine but now for the big volume of the results problem I increased value of the "akka.remote.netty.tcp.maximum-frame-size" and the "job-result-cache-size" parameters but still I have problem and when I set the "context-per-jvm=false" on the .conf file the big volume of the results problem is solved and my question exactly is this : why SJS just can get the big volume of the results from Spark when I set "context-per-jvm=false" on the .conf file ?

**Comment by velvia** [comment]
Well the reason is that when everything is in the same JVM there is no need to serialize and send over a huge amount of data.  
Do check the other configs that I sent in my previous response, the spray response size might have something to do also.

In general however, I believe for big results say > 30MB, I really think that it is better to save it to say HDFS or S3 and just return the output path instead of the whole results.  It will be faster and you get other advantages like persistence.

**Comment by aminalavian** [comment]
I wanted to appreciate everyone's time and comments regarding this issue .

For big results I want to use the last solution by @velvia  which seems more suitable . 


Best Regards
S.A.Alavian
