### ISSUE TITLE
Question on troubleshooting guide

### ISSUE THREAD

**Issue by Vinay-KY** [spark-jobserver/spark-jobserver#931]
The troubleshooting guide under section - ["Job with status finished has no result"](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/troubleshooting.md#job-with-status-finished-has-no-result) says following

> The job finished right now and results are in transfer.

**What does above mean?** 

and if it happens then - 

- will querying _jobs/job_id_ url again would give the results if these are cached as well?

- Can adding or tweaking any other setting will avoid this happening?

**Comment by noorul** [comment]
Which version of SJS and Spark are you using?

**Comment by Vinay-KY** [comment]
Spark is 2.10 and SJS the latest release available since Mar 31

**Comment by noorul** [comment]
Can you confirm which version of SJS?

**Comment by Vinay-KY** [comment]
0.7.0

**Comment by noorul** [comment]
It looks like 0.7.0 does not support spark 2.x 

See https://github.com/spark-jobserver/spark-jobserver#version-information

**Comment by derSascha** [comment]
@Vinay-KY 
> The job finished right now and results are in transfer.
This means the transfer between the akka actors. It could take some milliseconds to do this with huge results. There is no tweek/setting to fix this... Just query it again some time later.

**Comment by Vinay-KY** [comment]
Sorry, my bad, I just checked again and it is indeed 0.8.0

**Comment by noorul** [comment]
Can you provide more information about the job that you are running? Did you try test jobs that come with the project?

**Comment by noorul** [comment]
Fixed in #934
