### ISSUE TITLE
Fail to set spark.rpc.message.maxSize in jobserver, how to set?

### ISSUE THREAD

**Issue by moveforever** [spark-jobserver/spark-jobserver#938]
Whether to set spark.rpc.message.maxSize=512 when creating context in jobserver, it fail to run task.
```
Error is org.apache.spark.SparkException: Job aborted due to stage failure: Serialized task 35:4 was 250906987 bytes, which exceeds max allowed: spark.rpc.message.maxSize (134217728 bytes). Consider increasing spark.rpc.message.maxSize or using broadcast variables for large values.
```

**Comment by velvia** [comment]
You should be able to set this in your job config.   See
https://github.com/spark-jobserver/spark-jobserver#context-configuration <https://github.com/spark-jobserver/spark-jobserver#context-configuration>

**Comment by bsikander** [comment]
You can also set it through `launcher.spark.rpc.message.maxSize`. Closing.
