### ISSUE TITLE
SprkSubmit running after deletion of Context

### ISSUE THREAD

**Issue by dashrathc** [spark-jobserver/spark-jobserver#942]
**Used Spark version**
1.6.0

**Used Spark Job Server version**
0.6.2-KNIME_cdh-5.9

**Deployed mode**
client on YARN

In a long run like after 24 hours, spark jobserver deletes the context but "sparksubmit" process keeps running. "context-per-jvm=true" is enabled. So the process which is started by manager-start.sh script keeps running even though context is stopped.

Could anyone please share any resolution about above behavior?

Thanks

**Comment by velvia** [comment]
We have a rash of PRs to merge soon.  I’m hoping you can try in a few days and hopefully the problem will get solved.

**Comment by hyitclj** [comment]
why I don's use it ? detail in https://github.com/spark-jobserver/spark-jobserver/issues/936

**Comment by bsikander** [comment]
This problem is fixed now. Closing.
