### ISSUE TITLE
Question about runJob API and NamedRDD

### ISSUE THREAD

**Issue by zhutongxue** [spark-jobserver/spark-jobserver#952]
Hi,
As we all know, in Spark ,the DAG is lazy execution. The RDDs are computed only when some action is triggered.  
So, if I want only create a namedRDD in a spark job through job server, how to implement the runjob api? If  I must invoke a RDD action api?

Thanks in advance!

**Comment by velvia** [comment]
Ni hao,

Do you mind explaining in more detail?  Yes RDDs are lazy in their execution.  However at some point you force the RDD to be computed, and at that point is a good time to use the namedRDD to update/create.

**Comment by zhutongxue** [comment]
@velvia 
Hi，
Thanks you for your reply! 
Assume there is a defined Spark Job， which only creates a NamedRDD by RDD Transformation operation in the RunJob method. If I submit the Spark job through Job server, Will the job be executed in the spark cluster？
In other words， Do I have to invoke a RDD action API to compute RDD in the Runjob method？
Thanks！

**Comment by velvia** [comment]
Hi, yes, you need to invoke an RDD action API.  It is just like a regular spark application, you still need some action API on the RDD in order to cause computation to take effect.

**Comment by zhutongxue** [comment]
@velvia 
Hi,
Here is the code piece from  https://stackoverflow.com/questions/35662412/persisting-sharing-a-rdd-in-spark-job-server. The runJob method defined in the code does not invoke rdd/dataframe action function. But it seems to work !
![image](https://user-images.githubusercontent.com/3257543/32529219-3e1193fc-c472-11e7-935e-2c74bb9a1be8.png)
