### ISSUE TITLE
How to build the docker image?

### ISSUE THREAD

**Issue by minafarid** [spark-jobserver/spark-jobserver#966]
Can someone point out how to build the docker image with version 0.8-SNAPSHOT that supports Spark v 2.2.0?
The docker hub has old images.

Thank you

**Comment by zafercavdar** [comment]
The version of the source code is 0.8.0-SNAPSHOT. You can clone the repo and run `docker build -t app/jobserver .`

**Comment by minafarid** [comment]
thanks.
