### ISSUE TITLE
How to get the latest version of jobserver

### ISSUE THREAD

**Issue by spark-empty** [spark-jobserver/spark-jobserver#973]
I want to get a 0.8.0-SNAPSHOT and spark-2.0-preview version of the table, how do I do？？？

**Comment by velvia** [comment]
The current head of Master is already at those versions, just follow the README to compile and deploy.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
"We can do no great things, just small things with great love." -mother Teresa

**Comment by spark-empty** [comment]
I compiled the master version via the git clone https://github.com/spark-jobserver/spark-jobserver.git command, but I did not get a new version of the job interface using SparkSession in the project source code

**Comment by spark-empty** [comment]
![default](https://user-images.githubusercontent.com/32859230/33061176-0b8d4df4-ced6-11e7-85dd-5009a82af284.png)
I set the Scala version of the config / local.sh file, set the 2.11.8, but in the compilation process or 2.10, I hope you can help me, thank you

**Comment by bsikander** [comment]
By any chance, does your environment variables contain `SCALA_VERSION`? What is the value of `echo $SCALA_VERSION`?

**Comment by spark-empty** [comment]
Thanks for your reply, I'm pretty sure my scala version is 2.11. I used the Git -clone command to get the latest project directly on Linux, but I checked the source and did not explain the newsparkjob interface mentioned in the documentation.
Thank you, looking forward to your reply! ! !

**Comment by noorul** [comment]
@spark-empty Do you still face this issue?

**Comment by spark-empty** [comment]
Thank you, I have solved this problem, but there is still no good solution to the hive problem, can be achieved through the configuration file to open or close the hiveContext
