### ISSUE TITLE
Support ad-hoc context with Java API

### ISSUE THREAD

**Issue by liweys** [spark-jobserver/spark-jobserver#978]
**Used Spark Job Server version**
master

**Actual (wrong) behavior**
Java API must be used against persistent context.

**Expected behavior**
Be able to create ad-hoc context with Java API.

**Comment by hntd187** [comment]
Again, this is not a bug. This is intended by both us and Spark Developers. As I mentioned before, if at some point Spark merges their SparkContext and JavaSparkContext we will do the same. In the mean time, there is no reason to do this and it's not wrong behavior.

**Comment by liweys** [comment]
"Actual (wrong) behavior" comes from the template ...
