### ISSUE TITLE
Web UI is not showing context details on YARN client mode

### ISSUE THREAD

**Issue by dashrathc** [spark-jobserver/spark-jobserver#985]
**Used Spark version**
2.2.0

**Used Spark Job Server version**
0.8.0

**Deployed mode**
YARN client

**Actual (wrong) behavior**
Web UI does not show context name and other details even though context is successfully initialized. Get request on https://localhost:8091/contexts/test-context returns 500 response code and Akk time out exception as response. 
When master is changed to "local[*]" and context-per-jvm=false then it's working fine.

Could anyone please help me out to resolve this issue ASAP?

**Comment by addisonj** [comment]
I just ran into this, it looks like AkkaClusterContextSupervisor isn't handling the message.

Patch here that I think *should* work: https://github.com/instructure/spark-jobserver/commit/2607d98ee5877bc7831c930395d2c3ec5db3cd1e

Will submit a PR when I get some time to test it

**Comment by dashrathc** [comment]
Thanks @addisonj  for your response.

I have updated AkkaClusterSupervisorActor.scala accordingly and also added following
 `implicit val timeout: Timeout = Timeout(5 seconds)` 
to be able to compile it successfully.
It's working fine now.
