### ISSUE TITLE
Unnecessary exception wrapping in the jobs

### ISSUE THREAD

**Issue by LMnet** [spark-jobserver/spark-jobserver#989]
**Used Spark version**

2.2.0

**Used Spark Job Server version**

0.7.0, but issue is relevant to 0.8.0 too

**Deployed mode**

Spark Standalone

**Actual (wrong) behavior**

After #408 pull request all exceptions are wrapped in the `RuntimeException`. What is the reason for this? I don't see any issue with the original (before PR) behavior. But with the new behavior, I have to parse the exception's message to get the original error class. And the `errorClass` field of the result became absolutely useless because it's always `java.lang.RuntimeException`.

**Steps to reproduce**

Throw any exception from the job.

**Comment by LMnet** [comment]
@ishassan @velvia can you give some comments about this?

**Comment by bsikander** [comment]
The author fixed the issue in a PR. Closing it.
