### ISSUE TITLE
configure spark job server standalone cluster mode.

### ISSUE THREAD

**Issue by babukalamgi** [spark-jobserver/spark-jobserver#992]
**spark 2.0.0**

**0.8.1-SNAPSHOT**

**Deployed mode**
(Spark Standalone)

I want to submit the job from spark job server to spark cluster.
for this, I need configure spark job server help me out, please.

Thanks in advance.

**Comment by bsikander** [comment]
This feature is implemented in the current release. Please try. Thanks.
