### ISSUE TITLE
I do not want to use Hive

### ISSUE THREAD

**Issue by spark-empty** [spark-jobserver/spark-jobserver#994]
How can I modify the configuration of the hivesurpport opened in the code below?
Looking forward to your reply，Thank you!!!!
![_20171228190500](https://user-images.githubusercontent.com/32859230/34409065-59d329cc-ec02-11e7-98ac-89a76b259a40.png)

**Comment by hntd187** [comment]
This won't stop you from ignoring hive, it just enables the functionality for hive serdes, udfs and metastore _if you were to use them_, but also if you do not it can be safely ignored.

**Comment by velvia** [comment]
Hmmm. Not sure. What version/distribution of Spark are you using? It's almost like the version of Hive included is not right or not matching.

**Comment by acrozes** [comment]
Used Spark version: Spark 2.2.0
Used Spark Job Server version: 0.8.0
spark-jobserver in "Development mode"
Spark Standalone Cluster: 1 master, 1 worker, spark-shell is fine (spark-shell.cmd --master spark://192.168.36.1:7077)
```
$ jps
13908 JobServer
18500 sbt-launch.jar
18564 Worker
18596 Master
2536 Program
7064 Jps
11628 SparkSubmit
```
When I comment this line, all is fine.
Must I add something in the build.sbt file ?

**Comment by hntd187** [comment]
Right, you still _need_ hive regardless of if you want to use it or not. Spark uses it's catalog internally for a lot of things. So you are not including the hive dependency for this to work. Just include it and all will be fine.
