### ISSUE TITLE
unable to submit job to specific queue when using cluster deployment

### ISSUE THREAD

**Issue by dennischin** [spark-jobserver/spark-jobserver#999]
**Used Spark version**
2.2.0

**Used Spark Job Server version**
0.8.0 and 0.8.1 built from git

**Deployed mode**
cluster

**Actual (wrong) behavior**
Create a context specifying spark-yarn-queue. Create a new job specifying context.  The new job always goes to default queue.

**Steps to reproduce**
Setup job server to use cluster deploy mode. Create a context specifying spark-yarn-queue. Create a new job specifying context.  The new job always goes to default queue.
--- note that if i use client deploy mode, the new job does go into the specified queue.

**Comment by dverlan** [comment]
@dennischin did you get this solved? 

I am hitting similar issue while trying to create a context - it goes to the `default` queue despite me passing the queue in post request: `curl -X POST "$EMR_MASTER_IP:8090/contexts/test?spark.dynamicAllocation.enabled=true&spark.yarn.queue=XXX"`

Few logs:

`/var/log/spark-jobserver/spark-job-server.log`
> [2019-06-06 16:01:44,521] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting context with actor name jobManager-742196eb-ca4b-4cd1-a1b3-af3a85fdc4a5
> [2019-06-06 16:01:44,521] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Created working directory /mnt/var/log/spark-jobserver/jobserver-test5442331660160864724 for context test
> [2019-06-06 16:01:44,561] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - Initializing spark launcher
> [2019-06-06 16:01:44,562] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - Adding custom arguments to launcher
> [2019-06-06 16:01:44,564] INFO  spark-launcher [] [akka://JobServer/user/context-supervisor] - Start launcher application
> [2019-06-06 16:01:44,586] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Scheduling a time out message for forked JVM
> [2019-06-06 16:02:14,606] WARN  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Context forked JVM failed to initialize for actor jobManager-742196eb-ca4b-4cd1-a1b3-af3a85fdc4a5


`/var/log/spark-jobserver/jobserver-test8754386651126545099/spark-job-server.out`
> 2019-06-06T15:59:44,210 [main] WARN  org.apache.spark.deploy.yarn.Client - Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
> Exception in thread "main" org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1559542738729_0170 to YARN : Application application_1559542738729_0170 submitted by user hadoop to unknown queue: default
>         at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:276)
>         at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:174)
>         at org.apache.spark.deploy.yarn.Client.run(Client.scala:1152)
>         at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1520)
>         at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
>         at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
>         at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
>         at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
>         at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by bsikander** [comment]
umm, try the following
```
curl -X POST "$EMR_MASTER_IP:8090/contexts/test?launcher.spark.dynamicAllocation.enabled=true&launcher.spark.yarn.queue=XXX
```

**Comment by dverlan** [comment]
This helped, thank you @bsikander !
Do you know if this is documented anywhere? i.e. usage of `launcher.` prefix

**Comment by bsikander** [comment]
@dverlan It is not documented directly and it should be documented.
You can read some details [here](https://github.com/spark-jobserver/spark-jobserver/blob/489b45af233406a318eadf99b7c0479b4ac9729c/job-server/src/main/resources/application.conf#L201) and [here](https://github.com/spark-jobserver/spark-jobserver/pull/982). Would you like to contribute?

In last release, we replaced spark-submit with SparkLauncher. This change now allows dynamically attaching any spark configuration to the driver process by using `launcher.` prefix.

Closing the ticket, if you need more help just reopen.
